RevenueCat/purchases-android

- .circleci/config.yml
- examples/CustomEntitlementComputationSample/gradle/libs.versions.toml
- examples/MagicWeather/gradle/libs.versions.toml
- examples/MagicWeatherCompose/gradle/libs.versions.toml
- fastlane/Fastfile
- fastlane/README.md
Our sample apps are usually pretty behind to the latest version of the SDK. This PR adds them to the automation mechanisms so the version of the SDK is auto-updated.
> Auto-update sample apps SDK versions

- gradle/libs.versions.toml
- purchases/src/main/kotlin/com/revenuecat/purchases/common/logUtils.kt
Originally I tried to update to newer versions, but that breaks compatibility with kotlin 1.6. I was able to update to 1.7.21 without breaking a sample app using kotlin 1.6.20 without issues.
> Update Kotlin from 1.6.21 to 1.7.21

- purchases/src/main/kotlin/com/revenuecat/purchases/PurchaseParams.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/Constants.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/CustomerInfoFactory.kt
- purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesTest.kt
This is a possible approach to some issues we've had with developers passing the wrong productId to the purchase methods on upgrades/downgrades. We expect them to pass the productId, but some are passing the `productId:basePlanId` form.
This PR supports both forms, by just picking the `productId` when given in the incorrect form.
> Support receiving productId with basePlanId in upgrades/downgrades

- api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
- api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesCommonAPI.kt
- examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/main/MainViewModel.kt
- examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OfferingFragment.kt
- examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OverviewViewModel.kt
- purchases/src/androidTestCustomEntitlementComputation/kotlin/com/revenuecat/purchases/PurchasesIntegrationTest.kt
- purchases/src/androidTestDefaults/kotlin/com/revenuecat/purchases/trustedentitlements/TrustedEntitlementsInformationalModeIntegrationTest.kt
- purchases/src/defaults/kotlin/com/revenuecat/purchases/Purchases.kt
- purchases/src/defaults/kotlin/com/revenuecat/purchases/coroutinesExtensions.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/CoroutinesExtensionsCommon.kt
- purchases/src/test/java/com/revenuecat/purchases/PurchasesCoroutinesCommonTest.kt
- purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesCoroutinesTest.kt
Make coroutine APIs stable. This is removing the `@ExperimentalPreviewRevenueCatPurchasesAPI` annotations from the new coroutine APIs.
> Make coroutines APIs stable

- base-application.gradle
- examples/MagicWeather/app/build.gradle
- library.gradle
It's not necessary to specify the `buildToolsVersion` anymore. That will be determined by the AGP plugin. This removes some old references we had to that. https://developer.android.com/tools/releases/build-tools
> Remove unnecessary buildToolsVersion config

- feature/amazon/build.gradle
- library.gradle
- purchases/build.gradle
This reverts the changes in #1169, and additionally makes some changes so we only apply the maven publish plugin when using the `defaults` flavor in non-purchases modules. This should avoid having to have extra flavors in those modules and having them support the `customEntitlementComputation` flavor.
This was becoming a bit of a problem as I was working in the debug view #1075. Since some of the functions I'm using aren't in the `customEntitlementComputation` flavor. I could have split the debug view library by flavor to make it compatible, but that seems like unnecessary work.
> Remove customEntitlementComputation flavor for non-purchases modules

- api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/PurchasesDebugViewAPI.kt
- debugview/src/debug/kotlin/com/revenuecat/purchases/debugview/ContextExtensions.kt
- debugview/src/debug/kotlin/com/revenuecat/purchases/debugview/DebugRevenueCatViewModel.kt
- debugview/src/debug/kotlin/com/revenuecat/purchases/debugview/InternalDebugRevenueCatBottomSheet.kt
- debugview/src/debug/kotlin/com/revenuecat/purchases/debugview/InternalDebugRevenueCatScreen.kt
- debugview/src/debug/kotlin/com/revenuecat/purchases/debugview/models/InternalDebugRevenueCatScreenViewModel.kt
- debugview/src/debug/kotlin/com/revenuecat/purchases/debugview/models/InternalDebugRevenueCatScreenViewModelFactory.kt
- debugview/src/debug/kotlin/com/revenuecat/purchases/debugview/models/SettingScreenState.kt
- debugview/src/debug/kotlin/com/revenuecat/purchases/debugview/models/SettingState.kt
- debugview/src/debug/kotlin/com/revenuecat/purchases/debugview/settings/SettingGroup.kt
- debugview/src/debug/kotlin/com/revenuecat/purchases/debugview/settings/SettingOffering.kt
- debugview/src/debug/kotlin/com/revenuecat/purchases/debugview/settings/SettingText.kt
- debugview/src/main/kotlin/com/revenuecat/purchases/debugview/DebugRevenueCatBottomSheet.kt
- debugview/src/main/kotlin/com/revenuecat/purchases/debugview/DebugRevenueCatScreen.kt
- debugview/src/release/kotlin/com/revenuecat/purchases/debugview/InternalDebugRevenueCatBottomSheet.kt
- debugview/src/release/kotlin/com/revenuecat/purchases/debugview/InternalDebugRevenueCatScreen.kt
- examples/MagicWeatherCompose/app/src/main/java/com/revenuecat/sample/main/MainScreen.kt
This PR adds the offerings section to the debug menu and allows to purchase packages, products and subscription options for those offerings.
https://github.com/RevenueCat/purchases-android/assets/808417/6431e038-b4ca-446e-a83c-990960d71831
> Debug view: Add offerings section and purchasing capabilities

- purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
We are getting reports of this exception
```
Exception java.util.NoSuchElementException:
at java.util.AbstractQueue.remove (AbstractQueue.java:117)
at com.revenuecat.purchases.google.BillingWrapper.executePendingRequests$lambda-2$lambda-1$lambda-0 (BillingWrapper.kt:101)
at com.revenuecat.purchases.google.BillingWrapper.executePendingRequests (BillingWrapper.kt:101)
at com.revenuecat.purchases.google.BillingWrapper.onBillingSetupFinished$lambda-25 (BillingWrapper.kt:672)
at <private>
```
In this piece of code
```
private fun executePendingRequests() {
synchronized(this@BillingWrapper) {
while (billingClient?.isReady == true && !serviceRequests.isEmpty()) {
serviceRequests.remove().let { mainHandler.post { it(null) } }
}
}
}
```
I can't think of a way that's possible since the access to …
> Fix NoSuchElementException by using poll when accessing serviceRequests

- examples/MagicWeatherCompose/settings.gradle
- fastlane/Fastfile
- ui/debugview/build.gradle
- ui/debugview/gradle.properties
This sets up the project to be able to deploy the `defaultsRelease` variant as `purchases-debug-view-noop` package and `defaultsDebug` variant as `purchases-debug-view`
Hold until #1187 and #1191 are merged.
> Debug view: Support deploying both noop and debug version of `debugview` package

- purchases/src/main/kotlin/com/revenuecat/purchases/utils/JSONArrayExtensions.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/utils/JSONObjectExtensions.kt
- purchases/src/test/java/com/revenuecat/purchases/OfferingsTest.kt
- purchases/src/test/java/com/revenuecat/purchases/utils/JSONArrayExtensionsTest.kt
- purchases/src/test/java/com/revenuecat/purchases/utils/JSONObjectExtensionsTest.kt
Fixes [DENG-494](https://linear.app/revenuecat/issue/DENG-494/offering-metadata-not-being-set-properly-with-nested-information)
Metadata not fully expanding on native Android and hybrids.
- Added `.toMap(deep=true)` within `JSONObject.toMap()` to keep expanding nested objects
- Added `.toMap(deep=true)` within `JSONArray.toList()` to keep expanding nested objects
- More and deeper nested tests for `JSONObject`, `JSONArray`, and offering
> DENG-494: Fix offering metadata not fulling expanding

- .circleci/config.yml
- examples/MagicWeather/app/proguard-rules.pro
- examples/purchase-tester/proguard-rules.pro
- feature/amazon/consumer-rules.pro
- integration-tests/proguard-rules.pro
- purchases/consumer-rules.pro
This PR relaxes the rules in our `consumer-rules.pro` files. This allows to obfuscate and minify more code from our SDK. Note that this means that stack traces will be obfuscated moving forward and will need the mapping file in order to deobfuscate.
> Relax consumer rules to allow for better minifying and obfuscation

- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesConfiguration.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/FileHelper.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsFileHelper.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizer.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsTracker.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/utils/AndroidVersionUtils.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/utils/DataListener.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/utils/FileExtensions.kt
- purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
- purchases/src/test/java/com/revenuecat/purchases/PurchasesCommonTest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/FileHelperTest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsFileHelperTest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizerFunctionalTest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizerTest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerTest.kt
This PR is the first part of a possible approach to avoid loading huge files in memory in diagnostics at once. Basically, in here we change to reading the file per lines instead of reading everything in one go.
- Diagnostics will be Android 24+ only.
- An important change in behavior is that, instead of using the number of events in the diagnostics file to set a limit, we use the file size. So if on SDK configuration we detect that it's reached X size, we would clear the whole file and start over. 
- When we reach the file size limit, we remove the whole file, instead of just the oldest events.
- We remove the properties from the `MAX_EVENTS_STORED_LIMIT_REACHED` event since they don't make sense with the new approach. (This will require backend changes)
- Now we will have a limit to the …
> Optimize diagnostics file management

- purchases/src/main/kotlin/com/revenuecat/purchases/amazon/AmazonBackend.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/Backend.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/BackendHelper.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/offerings/OfferingsManager.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/strings/NetworkStrings.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesPoster.kt
- purchases/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/offerings/OfferingsManagerTest.kt
We discovered that the SDK might take a while to respond to offerings/customer info operations if they are started before any `Activity` has had the chance to start. This is because the SDK considers the app to be in the background, and we have some optimizations in place where we add some jittering to backend requests performed in the background
The approach in this PR is to make it so:
- If a request without a jitter delay is started after a request with jitter (but before it's completed), we move the callbacks to use the response from the request without jittering.
- If a request with jittering is started after a request without jitter (but before it's completed), we will not add the request with jitter but just reuse the existing request without jittering.
Note that with this …
> Optimize SDK initialization when requests executed before any activity starts

- examples/MagicWeatherCompose/app/build.gradle
- examples/MagicWeatherCompose/gradle/libs.versions.toml
- examples/MagicWeatherCompose/settings.gradle
This changes magic weather compose to use the real debug view dependencies instead of pointing to the local version by default.
> Use real debug view dependencies in magic weather compose

- purchases/src/main/kotlin/com/revenuecat/purchases/common/offerings/OfferingsCache.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/offerings/OfferingsManager.kt
- purchases/src/test/java/com/revenuecat/purchases/common/offerings/OfferingsManagerTest.kt
Unifies caching offerings and updating the offerings cache timestamp to simplify things, as suggested in https://github.com/RevenueCat/purchases-android/pull/1204#discussion_r1303095501
> Unify caching offerings and updating update timestamp

- api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
- api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesCommonAPI.kt
- purchases/src/customEntitlementComputation/kotlin/com/revenuecat/purchases/Purchases.kt
- purchases/src/defaults/kotlin/com/revenuecat/purchases/listenerConversions.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/ListenerConversionsCommon.kt
Adds `restorePurchases` functionality to the `customEntitlementComputation` package.
> CustomEntitlementComputation: Add `restorePurchases`

- purchases/src/main/kotlin/com/revenuecat/purchases/PostPendingTransactionsHelper.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/PostReceiptHelper.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/PostReceiptInitiationSource.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/PostTransactionWithProductDetailsHelper.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/SyncPurchasesHelper.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/Backend.kt
- purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
- purchases/src/test/java/com/revenuecat/purchases/PostPendingTransactionsHelperTest.kt
- purchases/src/test/java/com/revenuecat/purchases/PostReceiptHelperTest.kt
- purchases/src/test/java/com/revenuecat/purchases/PostReceiptInitiationSourceTest.kt
- purchases/src/test/java/com/revenuecat/purchases/PostTransactionWithProductDetailsHelperTest.kt
- purchases/src/test/java/com/revenuecat/purchases/PurchasesCommonTest.kt
- purchases/src/test/java/com/revenuecat/purchases/SyncPurchasesHelperTest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
- purchases/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesBackendTests.kt
- purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesCoroutinesTest.kt
- purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesTest.kt
This PR adds a new `initiation_source` field to the post receipt body that indicates where the receipt was originated from. This is already done in iOS.
> Send `initiation_source` in post receipt requests

- purchases/src/main/kotlin/com/revenuecat/purchases/PostPendingTransactionsHelper.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/PostReceiptInitiationSource.kt
- purchases/src/test/java/com/revenuecat/purchases/PostPendingTransactionsHelperTest.kt
- purchases/src/test/java/com/revenuecat/purchases/PostReceiptInitiationSourceTest.kt
We talked about renaming `queue` initiation source, which is more of an iOS term, to `unsynced_active_purchases` to match more what we do in android.
> Rename `queue` initiation source to `unsynced_active_purchases`

- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/PaywallColor.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/PaywallData.kt
Just adds the PaywallData class and its classes. Followup PRs will parse them and add them to the Offerings class
> Add PaywallData and its classes

- gradle/libs.versions.toml
- purchases/build.gradle
Adds kotlinx serialization dependency
> Adds kotlinx serialization

- purchases/src/main/kotlin/com/revenuecat/purchases/Offering.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/OfferingParser.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/PaywallColor.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/PaywallData.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/URLSerializer.kt
- ui/debugview/src/main/kotlin/com/revenuecat/purchases/ui/debugview/models/TestModels.kt
Tests will go in a followup PR
> Serializes PaywallData

- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/paywall/PaywallScreenViewModel.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallViewModel.kt
We can and should be using coroutines to interact with the main SDK. This updates the paywall tester app and the `revenuecatui ` sdk to use the coroutine versions of the SDK methods.
> Paywalls: Use coroutines to interact with SDK

- purchases/src/main/kotlin/com/revenuecat/purchases/common/OfferingParser.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/PaywallData.kt
- Set `ignoreUnknownKeys` to `true`, so there are no exceptions if new fields are added
- Removed `default_locale` since it's deprecated
- Added `revision` https://github.com/RevenueCat/purchases-ios/pull/3155/files
> Add revision and remove default_locale

- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/PaywallData.kt
Counterpart of https://github.com/RevenueCat/purchases-ios/blob/paywalls/Sources/Paywalls/PaywallData.swift#L139
Tested passing `Locale("en")` and `Locale.US`
Tests will come in future PR where I add tests for PaywallData
> Add configForLocale to PaywallData 

- purchases/src/main/kotlin/com/revenuecat/purchases/common/offerings/OfferingsManager.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/strings/OfferingStrings.kt
I noticed we had a very misleading log `Offerings updated from network.`. It seemed to indicate that that offerings had finished updating but it actually indicated that offerings started to be updated from network. I changed it to `Start Offerings update from network.` and also changed the location of the log so it happens in all places where offerings are actually fetched from network.
> Improve offerings start log

- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/offerings/OfferingsFactory.kt
- purchases/src/test/java/com/revenuecat/purchases/PurchasesConfigurationTest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/offerings/OfferingsFactoryTest.kt
This should be fixed in other places too, but for now, I am just fixing it in OfferingsParser
> Fix OfferingsParser exceptions being swallowed

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/InternalPaywallView.kt
This just adds a couple of text views as a PoC of setting a paywall in the dashboard and seeing the data in the UI.
> Paywalls: Use paywall data in paywall

- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/PaywallColor.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/ContextExtensions.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/InternalPaywallView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/OfferingToStateMapper.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallDataExtensions.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallViewModel.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallViewModelFactory.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallViewState.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/UIConstant.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/template2/Template2.kt
- ui/revenuecatui/src/main/res/values/strings.xml
Mostly a bunch of cleanup and improving the UI in this PR.
- Start using colors for texts and buttons.
- Start using device locale
- Move code to extensions for reusability
- Move paywall view UI to `Template2`. First template we're working on
- Improve Template2 to look closer to actual UI.
- Extract conversion from `Offering` to `PaywallViewState` for easier testing and reusability
- Make sure visibility of elements is correct.
> Paywalls: Add initial Template2 UI and using colors and texts in paywall

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/InternalPaywallView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/RemoteImage.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModel.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModelFactory.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewState.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/ContextExtensions.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/PaywallDataExtensions.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/Logger.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/OfferingToStateMapper.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template2.kt
This PR reorganizes the the new RevenueCatUI module files. The packages are:
- `composables`: For generic composables used in multiple UI locations
- `helpers`: Generic helpers
- `extensions`: Extensions for existing classes
- `data`: Data used to drive the UI and view model
> Paywalls: Organize files into packages

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/PaywallBackground.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/ModifierExtensions.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/PaywallDataExtensions.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template2.kt
This creates a generic `PaywallBackground` that can be used in any template.
- Created `Modifier.conditional`
- Changed `PaywallData.getUrlStringFromImage` to return `String?` (images are optional)
- Added `PaywallBackground` to `Template2`
> `Paywalls`: created `PaywallBackground`

- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/paywall/PaywallScreen.kt
- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/paywall/PaywallScreenState.kt
- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/paywall/PaywallScreenViewModel.kt
Hooked up restoring listeners and displayed messages in a dialog
> Show dialog messages when restoring

- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/paywall/PaywallScreen.kt
- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/paywall/PaywallScreenState.kt
- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/paywall/PaywallScreenViewModel.kt
Displays an AlertDialog after purchase is successful or if it errors out
> Show dialog after completed or error purchasing

- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/PaywallData.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModel.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/TestData.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template2.kt
This allows us to create previews for each template so we can easily iterate on them.
> `Paywalls`: new `TestData` to store fake paywalls

- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/main/appinfo/AppInfoScreen.kt
- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/main/appinfo/AppInfoScreenViewModel.kt
This improves PaywallTester so we can logIn/logOut and display the debug menu from the app.
> PaywallTester: Improve AppInfo screen to allow LogIn/LogOut and display debug menu

- purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/strings/BillingStrings.kt
- purchases/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
Hopefully this fix the following stacktrace on Samsung devices
```
Fatal Exception: java.lang.IllegalStateException: Too many bind requests(999+) for service Intent { act=com.android.vending.billing.InAppBillingService.BIND pkg=com.android.vending cmp=com.android.vending/com.google.android.finsky.billing.iab.InAppBillingService (has extras) }
at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:2115)
at android.app.ContextImpl.bindService(ContextImpl.java:2024)
at android.content.ContextWrapper.bindService(ContextWrapper.java:870)
at com.android.billingclient.api.BillingClientImpl.launchBillingFlow(com.android.billingclient:billing@@5.1.0:52)
at com.revenuecat.purchases.google.BillingWrapper.startConnection(BillingWrapper.kt:122)
at …
```
> Catch IllegalStateException and forward StoreProblemError

- api-tester/src/main/java/com/revenuecat/apitester/java/PeriodAPI.java
- api-tester/src/main/java/com/revenuecat/apitester/java/PricingPhaseAPI.java
- api-tester/src/main/java/com/revenuecat/apitester/kotlin/PeriodAPI.kt
- api-tester/src/main/java/com/revenuecat/apitester/kotlin/PricingPhaseAPI.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/models/Period.kt
- purchases/src/test/java/com/revenuecat/purchases/models/PeriodTest.kt
To help with the variables work needed for paywalls, this adds a helper function `valueInMonths` for the `Period` class. This will be used to calculate the price per month.
> Add `valueInMonths` helper to `Period` class

- ui/revenuecatui/build.gradle
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/InternalPaywallView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModel.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModelFactory.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/TestData.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/PackageConfigurationFactory.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/ProcessedLocalizedConfiguration.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/TemplateConfigurationFactory.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableDataProvider.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableProcessor.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/OfferingToStateMapper.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableDataProviderTest.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableProcessorTest.kt
This adds an initial implementation for processing paywall strings variables.
Considering some of the variables require access to the context/resources (like to get application name or to access some string resources), we have to keep a reference to the application context in the viewModel, which is not ideal...
The alternative discussed was to delay processing the strings (including locales and variables) until the last moment and use the activity context, but that seems to make a more complex architecture.
> Paywalls: Add variable processing to paywall strings

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/InternalPaywallView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModel.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModelFactory.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/TestData.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableDataProvider.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/AndroidApplicationContext.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableDataProviderTest.kt
Follow up to #1251. This allows us to create a fake `ViewModel` for previews and snapshots.
> `Paywalls`: extracted `ApplicationContext` interface and `MockViewModel`

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/TestData.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableDataProvider.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/AndroidApplicationContext.kt
- ui/revenuecatui/src/main/res/values/strings.xml
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/TemplateConfigurationFactoryTest.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableProcessorTest.kt
This PR adds support for the `sub_period` variable. In order to do that, some refactors were made to make sure we could test the result.
> Paywalls: Add support for `sub_period` variable

- examples/paywall-tester/build.gradle
- ui/revenuecatui/build.gradle
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/TestData.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableDataProvider.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableProcessor.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/PeriodExtensions.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/TemplateConfigurationFactoryTest.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableProcessorTest.kt
This PR adds support for the `price_per_period` variable in the paywalls. The period is calculated using a `MeasureFormat` which is only available in Android API 24+ so we've increased the min sdk version for now.
> Paywalls: Implement `price_per_period` variable support

- .idea/codeStyles/Project.xml
This is enforced by `Detekt`, so it helps if the IDE defaults to it.
> `Code style`: enabled `ALLOW_TRAILING_COMMA`

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/TestData.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableDataProvider.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableProcessor.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/TemplateConfigurationFactoryTest.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableProcessorTest.kt
Adds support for `sub_offer_duration` variable in paywalls. Makes sure we use the same intro offer than with `sub_offer_price` in case there are multiple (currently we only display one)
> Paywalls: Add support for `sub_offer_duration` variable in paywalls

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/InternalPaywallView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/Footer.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModel.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModelFactory.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/TestData.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/OfferingToStateMapper.kt
It was hardcoded to `FULL_SCREEN`, but we'll need to be able to override it.
> `Paywalls`: `InternalPaywallView` now takes a `PaywallViewMode` parameter

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/InternalPaywallView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModel.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/TestData.kt
I noticed the locale changes weren't working as expected. It changed the system driven locales but not our computed strings. This was because the code that was meant to update the state upon locale changes was wrong. We were using `remember` to store the last locales, but that doesn't survive configuration changes like the view model does. So I moved the logic to the view model.
> Paywalls: Fix state update upon locale changes

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/InternalPaywallView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModel.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModelFactory.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableDataProvider.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/PaywallDataExtensions.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/HelperFunctions.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template2.kt
A bit hacky but this way we can see the preview of the default data
> Add preview for default data

- api-tester/src/main/java/com/revenuecat/apitester/java/InAppMessageTypeAPI.java
- api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesCommonAPI.java
- api-tester/src/main/java/com/revenuecat/apitester/kotlin/InAppMesageTypeAPI.kt
- api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesCommonAPI.kt
- purchases/src/customEntitlementComputation/kotlin/com/revenuecat/purchases/Purchases.kt
- purchases/src/defaults/kotlin/com/revenuecat/purchases/Purchases.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesConfiguration.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/amazon/AmazonBilling.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/AppConfig.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/BillingAbstract.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/models/InAppMessageType.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/strings/BillingStrings.kt
- purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
- purchases/src/test/java/com/revenuecat/purchases/PurchasesConfigurationTest.kt
- purchases/src/test/java/com/revenuecat/purchases/PurchasesLifecycleTest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/AppConfigTest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/BaseHTTPClientTest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerTest.kt
- purchases/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
- purchases/src/testDefaults/kotlin/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt
Followup to #1290.
This improves the API to future-proof them in case Google adds new in-app message types in the future. This is not a breaking change since the previous APIs haven't been released yet.
> Future-proof in-app message APIs in case new types are added

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/PackageConfigurationFactory.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/TemplateConfigurationFactory.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/errors/PackageConfigurationError.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/OfferingToStateMapper.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/TemplateConfigurationFactoryTest.kt
We had a `require` in `createPackageConfiguration` that would throw if the selected package in the template configuration is not available. I changed the error handling with using `Result`
> Better handling of packages not found for id error

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/IntroEligibilityStateView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/ModifierExtensions.kt
This is equivalent to https://github.com/RevenueCat/purchases-ios/blob/main/RevenueCatUI/Views/IntroEligibilityStateView.swift.
It allows us to display different text depending on:
- Whether there is a special `_with_intro_offer` version of the text
- Has eligible offers
This will be used when displaying `call_to_action` and `offer_details`. And later on we can expand this to support multiple phases.
> `Paywalls`: Intro Eligibility dependent composable

- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/PaywallData.kt
- purchases/src/test/java/com/revenuecat/purchases/paywalls/PaywallDataTest.kt
- purchases/src/test/resources/paywalldata-sample1.json
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/ProcessedLocalizedConfiguration.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/TemplateConfigurationFactoryTest.kt
Adds parsing of `call_to_action_with_multiple_intro_offers` and `offer_details_with_multiple_intro_offers` to paywall data. Also adds those fields to the processed localization fields. This will be used with products that have multiple offers (free trial + discount)
> Paywalls: Add multiple offers fields to the paywall response and processing

- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/main/offerings/OfferingsScreen.kt
- gradle/libs.versions.toml
- ui/revenuecatui/build.gradle
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/InternalPaywallView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallDialog.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallDialogOptions.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallViewListener.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallViewOptions.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/WindowHelper.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template1.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template2.kt
This adds a new composable `PaywallDialog` that can be used to display the paywall as a dialog. It also modifies paywall tester to provide options on how we want to display the paywall from the offerings tab.
> Paywalls: Add API to display paywall as a composable dialog

- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/PackageExtensionsTest.kt
This adds some tests to a bit of logic added in #1301 to calculate the intro eligibility.
> Paywalls: Add some tests to intro eligibility calculation

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/PackageConfigurationFactory.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/TemplateConfigurationFactory.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/OfferingToStateMapper.kt
There shouldn't be any behavior change, but this refactor makes it more clear what happens when none of the configured packages are available.
> Refactor checking for available packages when creating package configuration

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/testdata/templates/Template1TestData.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/testdata/templates/Template2TestData.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/testdata/templates/Template3TestData.kt
We were passing `PaywallTemplate` enum `name` instead of `id` when building `TestData`
> Fix template test data

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/InternalPaywallView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/LoadingPaywallView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/testdata/TestData.kt
This uses `PaywallData.default` (from #1261) to be able to display a loading view just like in iOS.
> `Paywalls`: created `LoadingPaywallView`

- gradle/libs.versions.toml
- ui/revenuecatui/build.gradle
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/LoadingPaywallView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/Footer.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/IconImage.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/Placeholder.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/PurchaseButton.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/placeholder.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template2.kt
This uses https://github.com/google/accompanist/blob/main/placeholder/. It's deprecated but might come to Compose itself in the future. This is just a temporary loading screen, we can decide whether to keep it, implement it in another way, or remove it in the future.
> `Paywalls`: implemented `LoadingPaywallView` with `placeholder`

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/IntroEligibilityStateView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template1.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template3.kt
Also added the missing offer details to template 3:
> `Paywalls`: use `IntroEligibilityStateView`

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/InternalPaywallView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallFooter.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallViewMode.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallViewOptions.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/UIConstant.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/IconImage.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/PaywallBackground.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModel.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModelFactory.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewState.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/PaywallDataExtensions.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template1.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template2.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template3.kt
This provides a new `PaywallFooter` composable in the API that allows to display a minified paywall UI overlaying the user's custom paywall.
> Paywalls: Add PaywallFooter composable to present a minified paywall UI that allows for custom paywalls

- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/main/offerings/OfferingsScreen.kt
> `PaywallsTester`: added template name to offerings list

- gradle/libs.versions.toml
- ui/revenuecatui/build.gradle
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/IntroEligibilityStateView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/Markdown.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/PurchaseButton.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/testdata/templates/Template1TestData.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/testdata/templates/Template2TestData.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/testdata/templates/Template3TestData.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template1.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template2.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template3.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/TemplateConfigurationFactoryTest.kt
This uses https://github.com/commonmark/commonmark-java for parsing, and the rendering implementation is derived from https://github.com/ErikHellman/MarkdownComposer/blob/master/app/src/main/java/se/hellsoft/markdowncomposer/MarkdownComposer.kt with a lot changes to be able to use `Markdown()` in the same way we use `Text()`, therefore being able to replace our usages everywhere.
> `Paywalls`: Markdown support

- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/main/MainScreen.kt
- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/main/offerings/OfferingsScreen.kt
- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/paywall/PaywallScreen.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/Markdown.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/PaywallIcon.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template2.kt
Make sure we use material3 all accross the paywall tester app and the revenuecatui library. Also some linter fixes in `Markdown`
> Fix material theme references to use Material3 versions

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/IntroEligibilityStateView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/PurchaseButton.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/PackageExtensions.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template1.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template2.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template3.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/PackageExtensionsTest.kt
Added support for multiple intro offers to IntroEligibilityStateView
> Add support for multiple intro offers in IntroEligibilityStateView

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModel.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/errors/PaywallValidationError.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/OfferingToStateMapper.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/strings/PaywallValidationErrorStrings.kt
We can't really detect debug builds like we do in iOS, so this PR just adds some debug logs for validation errors that create the default template.
> Log errors when displaying default paywall

- purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/strings/BillingStrings.kt
- purchases/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
This is a possible approach to deal with #1288 
Seems like Google may be calling the `onBillingServiceDisconnected` callback multiple times consecutively. In those cases we are scheduling retries in the future for each of those calls which adds some overheard to that bug in Google's side. In order to minimize that overhead, this PR suggests having only a maximum of 1 retry scheduled, which should reduce the overhead a lot.
> Optimize billing client connection retries

- ui/revenuecatui/gradle.properties
Adding a `gradle.properties` file to the `ui:revenuecatui` module to specify the name of the dependency. With this, developers will need to add the dependency like: `implementation "com.revenuecat.purchases:purchases-ui:VERSION_NUMBER"`
> Add revenuecatui gradle.properties to specify name of dependency

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallDialog.kt
I noticed this while looking at the paywall dialog. We shouldn't be exposing the `DialogScaffold`
> Paywalls: Make DialogScaffold private

- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/PaywallColor.kt
- purchases/src/test/java/com/revenuecat/purchases/paywalls/PaywallColorTest.kt
Turns out it already did, so I just wrote some tests.
> `Paywalls`: `PaywallColor` supports RGBA

- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/SamplePaywalls.kt
There was a bug when loading a different template after dismissing a paywall. The offering would not change and would always load the first offering loaded
It took me a bit to realize what's going on, but we have this piece of code in the InternalPaywallView
```
@Composable
private fun getPaywallViewModel(
options: PaywallViewOptions,
): PaywallViewModel {
val applicationContext = LocalContext.current.applicationContext
return viewModel<PaywallViewModelImpl>(
// We need to pass the key in order to create different view models for different offerings when
// trying to load different paywalls for the same view model store owner.
key = options.offeringSelection.offeringIdentifier,
factory = PaywallViewModelFactory(
applicationContext.toAndroidContext(),
options,
MaterialTheme.colorScheme, …
```
> Fix loading another template in Paywalls screen

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallDialog.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallDialogOptions.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallActivityLauncher.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/HelperFunctions.kt
This mimics the equivalent API in `PaywallDialogOptions` (and like in iOS).
> `Paywalls`: new `PaywallActivityLauncher.launchIfNeeded` methods

- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/main/offerings/OfferingsScreen.kt
- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/main/paywalls/PaywallsScreen.kt
- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/paywall/PaywallScreen.kt
- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/paywall/PaywallScreenViewModel.kt
- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/paywallfooter/PaywallFooterScreen.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/InternalPaywall.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/LoadingPaywall.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/Paywall.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallDialog.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallDialogOptions.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallFooter.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallListener.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallMode.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallOptions.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallActivity.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/Footer.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/PurchaseButton.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallState.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModel.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModelFactory.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/TemplateConfiguration.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/TemplateConfigurationFactory.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/testdata/TestData.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/Animations.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/PaywallDataExtensions.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/OfferingToStateMapper.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template1.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template2.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template3.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/TemplateConfigurationFactoryTest.kt
This renames a few elements of our public API:
- `PaywallView` to `Paywall`
- `PaywallViewOptions` to `PaywallOptions`
- `PaywallViewListener` to `PaywallListener`
And internal names:
- `InternalPaywallView` to `InternalPaywall`
- `PaywallViewState` to `PaywallState`
- `LoadingPaywallView` to `LoadingPaywall`
- `PaywallViewMode` to `PaywallMode`
- Some other private composables.
> Paywalls: Rename `PaywallView` to `Paywall`

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/InternalPaywall.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallDialogOptions.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallOptions.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallActivity.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallActivityArgs.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallActivityLauncher.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/IntroEligibilityStateView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/TypographyExtensions.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/fonts/FontProvider.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/fonts/FontResourceProvider.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/fonts/PaywallTheme.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/fonts/TypographyType.kt
This adds a way for devs to give us a `FontProvider`, which will be used to override the font family in our views when a font family is provided. If it's not provided, the current material3 theme's font will be used.
> Paywalls: Support custom fonts through FontProvider

- gradle/libs.versions.toml
- ui/revenuecatui/build.gradle
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallActivity.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallActivityArgs.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallActivityLauncher.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/fonts/CustomFontProvider.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/fonts/CustomParcelizableFontProvider.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/fonts/FontProvider.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/fonts/FontStyleParceler.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/fonts/FontWeightParceler.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/fonts/GoogleFontProvider.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/fonts/ParcelizableFontProvider.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/fonts/PaywallFont.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/fonts/PaywallFontFamily.kt
Followup to #1328 
This PR adds support for Google fonts when launching the paywall as an activity and modifies the API to better support both these and bundled fonts and font families with multiple fonts.
> Paywalls: Support Google fonts and font families with multiple fonts

- purchases/consumer-rules.pro
After adding kotlin serialization in the paywalls branch, looks like the integration tests started failing to compile with the error:
```
R8: Missing class java.lang.ClassValue (referenced from: void kotlinx.serialization.internal.ClassValueCache$initClassValue$1.<init>(kotlinx.serialization.internal.ClassValueCache) and 3 other contexts)
```
In order to fix this issue, we are adding a `dontwarn` instruction to the proguard rules of the library temporarily so it can compile. 
After investigating why this is needed, I noticed https://github.com/Kotlin/kotlinx.serialization/blob/ba38b7099e502c16efd30386d18174e3a7aefb3a/rules/common.pro#L32 and https://github.com/Kotlin/kotlinx.serialization/issues/2119. But I believe this shouldn't be needed from those comments... However, I believe it …
> Paywalls: Fix proguard rules kotlinx serialization

- api-tester/src/defaults/java/com/revenuecat/apitester/java/PurchasesAPI.java
- api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
- purchases/src/defaults/kotlin/com/revenuecat/purchases/Purchases.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/subscriberattributes/SpecialSubscriberAttributes.kt
- purchases/src/testDefaults/kotlin/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt
OneSignal is migrating to a new User Centric API (v11.0). Adding a new reserved attribute to provide the new OneSignal User Id.
* Added $onesignalUserId reserved attribute with setter methods
> Add purchases.setOnesignalUserID

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template1.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template2.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template3.kt
The template previews were broken after some recent changes to the VM that made it so the state didn't change to the loaded state in the view model after some operations happened in the SDK, which wasn't available. This just uses a mock view model for the templates moving forward.
> Paywalls: Fix paywall compose previews

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/LoadingPaywall.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/Footer.kt
Added alpha and corner radius to the placeholder items. Also changed how `Footer` is implemented to only make the `Text` a placeholder.
> `Paywalls`: improve `LoadingPaywall`

- api-tester/src/main/java/com/revenuecat/apitester/java/StoreProductAPI.java
- api-tester/src/main/java/com/revenuecat/apitester/kotlin/StoreProductAPI.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/models/PricingPhase.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/models/StoreProduct.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/utils/PriceExtensions.kt
- purchases/src/test/java/com/revenuecat/purchases/google/StoreProductTest.kt
- purchases/src/test/java/com/revenuecat/purchases/utils/PriceExtensionsTest.kt
This is a counterpart to the existing `formattedPricePerMonth`. It becomes the canonical implementation returning a `Price` instead.
This will be used for Paywalls to calculate discounts between packages.
> Add `StoreProduct.pricePerMonth`

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/LoadingPaywall.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModel.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/PackageConfigurationFactory.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/TemplateConfigurationFactory.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/testdata/TestData.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/testdata/templates/Template2TestData.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/OfferingToStateMapper.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModelTest.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/TemplateConfigurationFactoryTest.kt
- ui/revenuecatui/src/test/resources/default_template.json
This uses the existing `TemplateConfiguration.PackageInfo.currentlySubscribed` to prevent users from subscribing to a lifetime subscription they already own.
Better consumable support will come in the future.
> `Paywalls`: improve handling of lifetime/custom packages

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/OfferDetails.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template1.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template2.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template3.kt
Followup to #1365. This adds the offer details to the template 2 when in condensed form. 
https://github.com/RevenueCat/purchases-android/assets/808417/567fa149-f026-4957-ba1c-28b5db88aec0
> Paywalls: Add offer details in template 2 when in condensed form

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template3.kt
Template 3 did not support footer presentation.
> Paywalls: Support footer in template 3

- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/main/paywalls/PaywallsScreen.kt
- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/paywallfooter/PaywallFooterScreen.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/InternalPaywall.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template3.kt
Now that footer is supported in all templates, this enables them in the paywalls tab of purchase tester.
> Paywalls: Enable footer modes in paywall tester paywalls tab

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/AdaptiveComposable.kt
This fixes the performance issue where it was constantly laying out, consuming about 10% CPU non-stop.
With this change, after the initial layout, CPU usage is 0% on a paywall.
> `Paywalls`: optimize `AdaptiveComposable`

- purchases/build.gradle
- purchases/consumer-rules.pro
- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/offerings/OfferingsManager.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/PaywallData.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/utils/CoilImageDownloader.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/utils/OfferingImagePreDownloader.kt
- purchases/src/test/java/com/revenuecat/purchases/common/offerings/OfferingsManagerTest.kt
- purchases/src/test/java/com/revenuecat/purchases/utils/OfferingImagePreDownloaderTest.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/RemoteImage.kt
We want to predownload images from offerings early in the app's lifetime so they are ready when the paywalls are displayed. This PR checks if the paywall sdk is part of the path and if so, and there is a `current` paywall, we download the images.
> Paywalls: Predownload offering images if paywalls sdk exists

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/BlurTransformation.kt
This accomplishes 2 things:
- Optimizes blurring algorithm by only blurring a smaller version of the image
- Fixes the blur not having a large enough radius (because of the `25` limit by `RenderScript`
> `Paywalls`: optimize backwards compatible blurring

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/PaywallBackground.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/RemoteImage.kt
When displaying the default template and using `Image` we weren't using the `transformation` for backwards compatible blurring.
This adds a new `LocalImage` that reuses the same code as `RemoteImage` to be able to render images from a resource using Coil, which also has the benefit of asynchronous loading, caching, etc.
> `Paywalls`: fix backwards-compatible blurring of default paywall background

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/InternalPaywall.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template1.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template2.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template3.kt
> `Paywalls`: fixed incorrect background on footer

- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/paywall/PaywallScreenViewModel.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/InternalPaywall.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/LoadingPaywall.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModel.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/testdata/TestData.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModelTest.kt
> `Paywalls`: display purchase/restore errors

- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/SamplePaywalls.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/LoadingPaywall.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/Footer.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/Markdown.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModel.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/testdata/TestData.kt
> `Paywalls`: use `LocalUriHandler` for opening links

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/PaywallBackground.kt
> `Paywalls`: increase `PaywallBackground` blur radius to match iOS

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/AdaptiveComposable.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/Footer.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/IntroEligibilityStateView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/PurchaseButton.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template2.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template3.kt
- `PurchaseButton` is now accessible and will only read the relevant text
- `Footer` is fully accessible and will read the largest text even if it's not displayed
- `Template2` provides context on what package is selected
- `Template3` combines feature elements into a single accessibility element
https://github.com/RevenueCat/purchases-android/assets/685609/77bae51f-0f52-4c57-b642-62aefa3fc8b7
> `Paywalls`: fixed accessibility across templates

- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/main/offerings/OfferingsScreen.kt
- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/main/paywalls/PaywallsScreen.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallDialog.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallDialogOptions.kt
`PaywallDialog` works by presenting paywalls automatically based on a provided condition. Because of this, it should also know how to dismiss itself. I changed it to implement this automatically, but also provide a way to optionally pass a block for it.
Also updated the docs to reflect the new APIs: https://github.com/RevenueCat/revenuecat-docs/pull/450
> `Paywalls`: `PaywallDialogOptions` no longer requires `dismissRequest`

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallDialog.kt
@aboedo noticed that when navigating to the Template 2 full screen from the Paywalls tab, going back, then navigating again was not working. 
@tonidero took a very quick look and seems that we are not calling the PaywallDialog onDismiss callback when going back, so the PaywallsScreen thinks that there is still a paywall displaying so it doesn't work.
I added the missing call to the `dismissRequest` callback
> Fix navigation after closing paywall in Paywalls screen

- purchases/src/main/kotlin/com/revenuecat/purchases/common/OfferingParser.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/EmptyStringToNullSerializer.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/PaywallData.kt
- purchases/src/test/java/com/revenuecat/purchases/paywalls/PaywallDataTest.kt
- purchases/src/test/resources/paywalldata-empty-images.json
Equivalent to https://github.com/RevenueCat/purchases-ios/pull/3195
This fixes issues with paywalls in the backend sending `""` as images and the SDK trying to render an empty image and taking space:
> `Paywalls`: decode empty images as `null`

- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/PaywallData.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/URLSerializer.kt
- purchases/src/test/java/com/revenuecat/purchases/paywalls/PaywallDataTest.kt
- purchases/src/test/resources/paywalldata-empty-images.json
Note that this is only for the optional URLs, `assetBaseURL` is still required, but I'll handle errors there in a separate PR.
> `Paywalls`: ignore URL deserialization errors

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallDialog.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallDialogOptions.kt
We call `paywallDialogOptions.dismissRequest?.invoke()` inside `toPaywallOptions` so since we were passing 
```
val dismissRequest = {
paywallDialogOptions.dismissRequest?.invoke()
shouldDisplayDialog = false
}
```
the `paywallDialogOptions.dismissRequest?.invoke()` piece was getting called twice when calling `paywallDialogOptions.toPaywallOptions(dismissRequest)`
> Fix onDismiss getting called twice in PaywallDialogs

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/InternalPaywall.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/LoadingPaywall.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallDialogOptions.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallFooter.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallOptions.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallActivity.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallActivityArgs.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallActivityLauncher.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/CloseButton.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallState.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModel.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/testdata/TestData.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/OfferingToStateMapper.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallOptionsTest.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModelTest.kt
This adds a close button to the paywall that can be displayed when using the `Paywall` composable, the `PaywallDialog` or the `PaywallActivityLauncher`.
> Paywalls: Add close button option

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallMode.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/PaywallBackground.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallState.kt
Unless it needs to be blur, to match iOS behavior.
Thanks to @lburdock for finding this discrepancy!
> `Paywalls`: footer view should not render background image

- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/PaywallData.kt
- purchases/src/test/java/com/revenuecat/purchases/paywalls/PaywallDataTest.kt
- purchases/src/test/resources/paywalldata-sample1.json
Equivalent to https://github.com/RevenueCat/purchases-ios/pull/2818
`IntroEligibilityStateView` relies on strings being `null` to determine what string is available, therefore we need to make sure we don't have empty strings in `PaywallData`.
> `Paywalls`: convert empty strings to `null`

- purchases/src/main/kotlin/com/revenuecat/purchases/common/OfferingParser.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/PaywallData.kt
- purchases/src/test/java/com/revenuecat/purchases/common/offerings/OfferingsFactoryTest.kt
- purchases/src/test/java/com/revenuecat/purchases/paywalls/PaywallDataTest.kt
- purchases/src/test/resources/paywalldata-sample1.json
This also adds coverage for `PaywallData` deserialization inside of `Offering`
> `Paywalls`: `PaywallData` errors shouldn't make `Offering`s fail to decode

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/ConsistentPackageContentView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/PurchaseButton.kt
In some cases, the purchase button text doesn't change when selecting different packages. However, we were still animating the text resulting in a small flash in the purchase button when changing the selected package.
This makes it so, if the purchase button text doesn't change between all the packages, we don't animate it.
> Paywalls: Fix purchase button text flashing when changing selected package

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/PurchaseButton.kt
See #1411.
This fixes inconsistent touch behavior when tapping on it.
> `Paywalls`: disallow Markdown links in `PurchaseButton`

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallDialog.kt
I've been testing the paywall dialog in tablets. I noticed it mostly looks fine on landscape, but not so great on portrait. So I added a max height to the dialog so it was not so stretched
|-------|-------|
| ![image](https://github.com/RevenueCat/purchases-android/assets/808417/c727ebb9-e95e-4a42-ad64-e20d5b3e8e5f) | ![image](https://github.com/RevenueCat/purchases-android/assets/808417/4ce4fc19-f0f5-46d8-b469-45753f13cb76) |
| ![image](https://github.com/RevenueCat/purchases-android/assets/808417/9bf6999e-e2c3-4ada-82cf-2a07e35aef41) | ![image](https://github.com/RevenueCat/purchases-android/assets/808417/9bf6999e-e2c3-4ada-82cf-2a07e35aef41) |
| | ![image](https://github.com/RevenueCat/purchases-android/assets/808417/a7cd68c4-b9c2-48b8-a597-4cfea39cff7a) |
| | …
> Paywalls: Improve PaywallDialog look on tablets

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallDialog.kt
Followup to #1419 
I was playing with this value and in a slightly more wide tablet, it would use the full height... So I want to decrease this max aspect ratio a bit to avoid those tablets from having the full height of the screen.
> Paywalls: Decrease max aspect ratio for tablets to have a max height

- purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/google/errors.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/strings/BillingStrings.kt
- purchases/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
We recently started getting reports of app performance issues when retrying to reconnect to Billing Client after a disconnection. See https://github.com/RevenueCat/purchases-android/issues/1288 
There's a related issue opened in Google's sample repository https://github.com/android/play-billing-samples/issues/636
It looks like after changing language in the system settings, the BillingClient will never connect again until the Play Store is opened or their caches are cleared. The way it behaves is when trying to connect, it will instantly call `onBillingServiceDisconnected` then call `onBillingSetupFinished` with a `BILLING_UNAVAILABLE`.
In our current code, we would retry to reconnect with a backoff on `onBillingServiceDisconnected`, which should be fine, because we would just back off an …
> Improvements on BillingWrapper retrying mechanism 

- api-tester/src/main/java/com/revenuecat/apitester/java/StoreProductAPI.java
- api-tester/src/main/java/com/revenuecat/apitester/kotlin/StoreProductAPI.kt
- gradle/libs.versions.toml
- purchases/build.gradle
- purchases/src/main/kotlin/com/revenuecat/purchases/models/Period.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/models/StoreProduct.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/utils/PriceExtensions.kt
- purchases/src/test/java/com/revenuecat/purchases/utils/PriceExtensionsPricePerMonthTest.kt
- purchases/src/test/java/com/revenuecat/purchases/utils/PriceExtensionsPricePerPeriodTest.kt
- purchases/src/test/java/com/revenuecat/purchases/utils/PriceExtensionsPricePerWeekTest.kt
- purchases/src/test/java/com/revenuecat/purchases/utils/PriceExtensionsPricePerYearTest.kt
This brings parity with `purchases-ios` and will be used for a new paywalls variable.
> `StoreProduct`: new `pricePerWeek` and `pricePerYear`

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableDataProvider.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableProcessor.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableProcessorTest.kt
Depends on #1426.
Equivalent to https://github.com/RevenueCat/purchases-ios/pull/3355.
> `Paywalls`: new `{{ sub_price_per_week }}` variable

- api-tester/src/main/java/com/revenuecat/apitester/java/OfferingAPI.java
- api-tester/src/main/java/com/revenuecat/apitester/kotlin/OfferingAPI.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/Offering.kt
We were missing the constructors in the API tester so we didn't realize that we removed the previous constructor with no `PaywallData`.
This was caught by PHC: https://github.com/RevenueCat/purchases-hybrid-common/pull/544
> `Offering`: restore constructor with no `PaywallData`

- api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/revenuecatui/PaywallTrackingAPI.kt
- purchases/src/defaults/kotlin/com/revenuecat/purchases/Purchases.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/PaywallData.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/events/PaywallEvent.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/events/PaywallEventsFileHelper.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/events/PaywallEventsManager.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/events/PaywallStoredEvent.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/utils/serializers/DateSerializer.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/utils/serializers/URLSerializer.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/utils/serializers/UUIDSerializer.kt
- purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
- purchases/src/test/java/com/revenuecat/purchases/paywalls/events/PaywallEventSerializationTests.kt
- purchases/src/test/java/com/revenuecat/purchases/paywalls/events/PaywallEventsManagerTest.kt
- purchases/src/testDefaults/kotlin/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt
This adds support for storing paywall events into disk. In followup PRs, we will send these events to our servers for analytics and use these events to indicate whether a purchase came from our paywalls.
> Paywalls: Store paywall events on disk and API (1)

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallDialog.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/IntSizeExtensions.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/HelperFunctions.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template1.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template5.kt
This modifies templates 1 and 5 so the top images don't use the full height of the screen when using devices in horizontal. This is not a problem when presenting as a dialog, since the width is limited, but if using the composables directly, it might be problematic.
> Improve fullscreen templates in landscape orientation

- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/BillingAbstract.kt
- purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
- purchases/src/test/java/com/revenuecat/purchases/amazon/AmazonBillingTest.kt
- purchases/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
I removed a side effect on setting `purchasesUpdatedListener`. I don't think we should be starting/ending the connection there and we should do it independently
> Remove side effect from setting purchasesUpdatedListener

- api-tester/src/defaults/java/com/revenuecat/apitester/java/revenuecatui/PaywallActivityLauncherAPI.java
- api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/revenuecatui/PaywallActivityLauncherAPI.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallActivityLauncher.kt
- Remove duplicated `registerForActivityResult` call
- Allow using any instance, like `AppCompatActivity`
> `PaywallActivityLauncher`: new constructor for a generic `ActivityResultCaller`

- purchases/src/main/kotlin/com/revenuecat/purchases/common/Backend.kt
These logs were added in https://github.com/RevenueCat/purchases-android/pull/1204. These logs might happen primarily if the developer calls getCustomerInfo/getOfferings before any activity has started. In those situations, we have to handle it so the request does not wait for the whole jitter.
There is nothing much the developer can do about this and it's not actually an error, so lowering the log level from warning to debug for these.
Fixes https://github.com/RevenueCat/react-native-purchases/issues/757
> Lower request jitter log level from warning to debug

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/RemoteImage.kt
Without this, the error we were logging didn't have any information:
> RevenueCatUI E Error loading image from 'https://assets.pawwalls.com/....jpg[':](https://assets.pawwalls.com/....jpg':) coil.request.ErrorResult@2678e133
> `Paywalls`: improve error log when images fail to load

- purchases/src/main/kotlin/com/revenuecat/purchases/common/AppConfig.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/Backend.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/networking/Endpoint.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/networking/RCHTTPStatusCodes.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/events/PaywallBackendEvent.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/events/PaywallEventRequest.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/events/PaywallStoredEvent.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/utils/JsonElementExtensions.kt
- purchases/src/test/java/com/revenuecat/purchases/backend_integration_tests/BaseBackendIntegrationTest.kt
- purchases/src/test/java/com/revenuecat/purchases/backend_integration_tests/ProductionBackendIntegrationTest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/backend/BackendPaywallEventTest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/backend/BackendTest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/networking/EndpointTest.kt
- purchases/src/test/java/com/revenuecat/purchases/paywalls/events/PaywallEventRequestSerializationTest.kt
- purchases/src/test/java/com/revenuecat/purchases/utils/JsonElementExtensionsTest.kt
This follows up on #1436. 
Here we are adding the code to send paywall events to our servers. This is not connected with the work done in #1436 yet. That will be done in followup PRs.
> Paywalls: Support sending paywall events to servers (2)

- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/events/PaywallEventsManager.kt
- purchases/src/test/java/com/revenuecat/purchases/paywalls/events/PaywallEventsManagerTest.kt
This adds the code to the `PaywallEventsManager` class to actually send the events to the backend and clear them locally once finished.
> Paywalls: Add paywall events flush logic and tests (3)

- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/events/PaywallEventsManager.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/utils/EventsFileHelper.kt
- purchases/src/test/java/com/revenuecat/purchases/paywalls/events/PaywallEventsManagerTest.kt
Makes sure we handle errors in each event line correctly and that we clear errors from the file correctly.
> Paywall events: Handle errors parsing specific paywall event lines

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/InternalPaywall.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/LoadingPaywall.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallDialog.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallState.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModel.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModelFactory.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PurchasesType.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/testdata/TestData.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/OfferingToStateMapper.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModelTest.kt
This PR adds tracking of the `paywall_impression`, `paywall_close` and `paywall_cancel` events to the paywalls.
> Paywalls: Track paywall events

- purchases/src/main/kotlin/com/revenuecat/purchases/PostReceiptHelper.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/Backend.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/PaywallPresentedCache.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/events/PaywallEvent.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/events/PaywallPostReceiptData.kt
- purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
- purchases/src/test/java/com/revenuecat/purchases/PostReceiptHelperTest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/backend/BackendTest.kt
- purchases/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesBackendTests.kt
- purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesTest.kt
- purchases/src/testDefaults/kotlin/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt
This sends the paywall data during the post receipt requests to make sure we attribute purchases to paywalls. We do this by caching the paywall events as needed.
> Paywall events: Send paywall data with post receipt requests

- .circleci/config.yml
We were using an old version of the revenuecat circleci orb. [One of the fixes](https://github.com/RevenueCat/sdks-circleci-orb/pull/7) was to set git config globally, which would fix the issues recording snapshots in: https://app.circleci.com/pipelines/github/RevenueCat/purchases-android/8733/workflows/98ffd3bc-7365-4364-b64a-ebfe948f330f/jobs/31537
> Update circleci orb to latest version

- purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/strings/OfferingStrings.kt
- purchases/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
We are getting this exception:
```
Exception java.lang.IllegalStateException:
at kotlin.coroutines.SafeContinuation.resumeWith (SafeContinuationJvm.kt:44)
at <private>
at com.revenuecat.purchases.CustomerInfoHelper$getCustomerInfoFetchOnly$1$1.invoke (CustomerInfoHelper.kt:107)
at com.revenuecat.purchases.CustomerInfoHelper$getCustomerInfoFetchOnly$1$1.invoke (CustomerInfoHelper.kt:107)
at com.revenuecat.purchases.CustomerInfoHelper.dispatch$lambda$0 (CustomerInfoHelper.kt:197)
at android.os.Handler.handleCallback (Handler.java:942)
at android.os.Handler.dispatchMessage (Handler.java:99)
at android.os.Looper.loopOnce (Looper.java:240)
at android.os.Looper.loop (Looper.java:351)
at android.app.ActivityThread.main (ActivityThread.java:8381)
at java.lang.reflect.Method.invoke
at …
```
> Prevents queryPurchases from being called twice

- purchases/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
`queryPurchasesAsync` is called twice in the function, so 4 would come from calls to `onQueryPurchasesResponse` and 1 for the `onSuccess`
> Fix flaky test in BillingWrapperTest

- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/amazon/AmazonBilling.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/amazon/AmazonStrings.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/BillingAbstract.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/google/usecase/GetBillingConfigUseCase.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/strings/BillingStrings.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/strings/OfferingStrings.kt
- purchases/src/test/java/com/revenuecat/purchases/PurchasesCommonTest.kt
- purchases/src/test/java/com/revenuecat/purchases/amazon/AmazonBillingTest.kt
- purchases/src/test/java/com/revenuecat/purchases/google/usecase/GetBillingConfigUseCaseTest.kt
- purchases/src/test/java/com/revenuecat/purchases/utils/MockHandlerFactory.kt
This PR adds a new method to the `BillingAbstract` to obtain the country code of the store, now that it's been added in Google's BC 6.1.0.
In this PR, we only log the country as soon as we connect but we plan to send this data to the backend in future PRs.
> Add method to get storefront for Google and Amazon stores

- purchases/src/main/kotlin/com/revenuecat/purchases/amazon/AmazonBilling.kt
- purchases/src/test/java/com/revenuecat/purchases/amazon/AmazonBillingTest.kt
We were not calling the BillingAbstract `stateListener` after it was connected. This adds a call to make sure we call it and keep the same behavior as on Google. Currently, we were just syncing pending purchases in Google, which shouldn't matter much if we do it there for Amazon since we're also doing on app foreground.
> Use state listener in Amazon store

- ui/revenuecatui/src/main/res/values-tr/strings.xml
Turkish translation was wrong, I fixed `purchases-ios`' translation before. Fixing `purchases-android` now to have the same translation. (https://github.com/RevenueCat/purchases-ios/blob/main/RevenueCatUI/Resources/tr.lproj/Localizable.strings)
I updated `privacy`, `restore`, `restore_purchases`, `terms`, `lifetime` and `continue_cta`'s translations.
> `Paywalls`: Fix Turkish translation

- purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/google/usecase/QueryPurchaseHistoryUseCase.kt
- purchases/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
- purchases/src/test/java/com/revenuecat/purchases/google/usecase/QueryProductDetailsUseCaseTest.kt
- purchases/src/test/java/com/revenuecat/purchases/google/usecase/QueryPurchaseHistoryUseCaseTest.kt
Counterpart of https://github.com/RevenueCat/purchases-android/pull/1444 for `queryPurchaseHistoryAsync`
> Add retries to queryPurchaseHistoryAsync

- purchases/src/test/java/com/revenuecat/purchases/google/usecase/BaseBillingUseCaseTest.kt
- purchases/src/test/java/com/revenuecat/purchases/google/usecase/GetBillingConfigUseCaseTest.kt
- purchases/src/test/java/com/revenuecat/purchases/google/usecase/QueryProductDetailsUseCaseTest.kt
- purchases/src/test/java/com/revenuecat/purchases/google/usecase/QueryPurchaseHistoryUseCaseTest.kt
As suggested in https://github.com/RevenueCat/purchases-android/pull/1448#pullrequestreview-1736243570
I created a BaseBillingUseCaseTest to remove some duplicated stuff in the UseCase tests
> Create a BaseBillingUseCaseTest

- purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizer.kt
We were checking the diagnostics file size in the main thread which was causing a disk read violation. This moves that operation to the diagnostics thread
> Check diagnostics file size in background thread

- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizer.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/networking/ETagManager.kt
- purchases/src/test/java/com/revenuecat/purchases/backend_integration_tests/BaseBackendIntegrationTest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizerFunctionalTest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizerTest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/networking/ETagManagerTest.kt
We detected some `DiskReadViolation` caused by initilizing shared preferences. This should have a very low impact on initialization time, but might be good to delay that so it's not caused until actually needed. We currently have 3 shared preferences files, 2 of them are only used later on and can be initialized later.
> Initialize shared preferences lazily

- purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/google/usecase/AcknowledgePurchaseUseCase.kt
- purchases/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
- purchases/src/test/java/com/revenuecat/purchases/google/usecase/AcknowledgePurchaseUseCaseTest.kt
Creates a `AcknowledgePurchaseUseCase`. Similar to https://github.com/RevenueCat/purchases-android/pull/1487
> Add AcknowledgePurchaseUseCase

- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/Dispatcher.kt
- purchases/src/test/java/com/revenuecat/purchases/utils/SyncDispatcher.kt
We were creating threads every time we added a task to the executor service. This shouldn't be a problem if tasks ended early and not too many tasks were in the queue, but it's not very efficient. This is another implementation to propagate exceptions to the main thread so they can be thrown and not swallowed when they happen on the thread pool.
> Avoid creating threads when dispatching tasks

- Gemfile
- Gemfile.lock
- fastlane/Fastfile
- Fixed missing dependency
- Fixed passing wrong parameter to CircleCI (`Unexpected argument(s): record-revenuecatui-snapshots`)
- Fixed duplicated `create_snapshots_repo_pr` https://app.circleci.com/pipelines/github/RevenueCat/purchases-android/9068/workflows/743d2c2b-7063-4cca-861b-cef31d0e7b48/jobs/33675
> Fixes on generate_snapshots_RCUI lane

- api-tester/src/defaults/java/com/revenuecat/apitester/java/revenuecatui/PaywallResultAPI.java
- api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/revenuecatui/PaywallResultAPI.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallActivity.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallActivityArgs.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallActivityLauncher.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallResult.kt
Users could potentially restore their purchases and get entitlements granted but the paywall activity was not dismissing. This will add that functionality in the case where users use the `requiredEntitlementIdentifier` parameter to launch the activity.
This adds a new `PaywallResult` value, `Restored`. This will be returned if the last action the user performed was a restore.
> Paywalls: Auto-close paywall activity if restore grants required entitlement identifier

- ui/revenuecatui/src/main/AndroidManifest.xml
- ui/revenuecatui/src/main/res/values/themes.xml
Remove `PaywallActivity`'s theme in order to pickup the application's theme if set.
> Paywalls: Remove `PaywallActivity` theme to pickup application's theme by default

- api-tester/src/defaults/java/com/revenuecat/apitester/java/revenuecatui/PaywallFooterViewAPI.java
- api-tester/src/defaults/java/com/revenuecat/apitester/java/revenuecatui/PaywallViewAPI.java
- api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/revenuecatui/PaywallAPI.kt
- api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/revenuecatui/PaywallFooterViewAPI.kt
- api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/revenuecatui/PaywallViewAPI.kt
- api-tester/src/defaults/res/layout/paywall_footer_view_api.xml
- api-tester/src/defaults/res/layout/paywall_view_api.xml
- examples/paywall-tester/build.gradle
- examples/paywall-tester/src/main/AndroidManifest.xml
- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/Constants.kt
- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/MainActivity.kt
- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/PaywallFooterViewActivity.kt
- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/PaywallViewActivity.kt
- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/main/offerings/OfferingsScreen.kt
- examples/paywall-tester/src/main/res/font-v26/lobster_two.xml
- examples/paywall-tester/src/main/res/font/lobster_two.xml
- examples/paywall-tester/src/main/res/layout/activity_paywall_footer_view.xml
- examples/paywall-tester/src/main/res/layout/activity_paywall_view.xml
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallFooter.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/fragment/PaywallFooterView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/views/PaywallFooterView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/views/PaywallView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/views/PaywallViewAttributesReader.kt
- ui/revenuecatui/src/main/res/values/paywall_view_attrs.xml
This adds a new view `PaywallFooterView` which acts as a wrapper for the `PaywallFooter` composable. It has some limitations:
- Condensed form not supported
- Need to set most of the attributes on the construction of the view.
This view will be used in the hybrids in order to support footer view.
> Paywalls: Add `PaywallFooterView`

- ui/revenuecatui/build.gradle
Add the `revenuecatui` module to generated documentation. We already had a multi-module setup, so it was straightforward to add it.
> Add revenuecatui docs to reference docs

- ui/revenuecatui/src/main/res/values-zh-rHK/strings.xml
- ui/revenuecatui/src/main/res/values-zh-rTW/strings.xml
Android equivalent to https://github.com/RevenueCat/purchases-ios/pull/3489/
I noticed that we don't have a separate file for Chinese Simplified on Android? Is this intentional?
> Paywalls: improve Chinese localization

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallActivity.kt
After #1511, in flutter/rn, we might display the action bar in the paywall when being presented as an activity depending on the theme.
This change makes sure we hide the action bar independently of the theme.
> Hide action bar from paywall activity

- .circleci/config.yml
I noticed it's possible to deploy without waiting for all tests to pass. It's probably an edge case but it's possible we merge something into `main` that breaks unit tests then start a release from that broken commit.
I added a new hold job to force the release in case we actually don't want to wait for tests to pass. The name is pretty clear `force-release-without-waiting-for-tests` so I think people will understand that it's skipping tests.
> Wait for tests to pass when deploying

- api-tester/src/defaults/java/com/revenuecat/apitester/java/revenuecatui/PaywallActivityLauncherAPI.java
- api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/revenuecatui/PaywallActivityLauncherAPI.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallActivityLauncher.kt
We need a version of `launchIfNeeded` that accepts a `offeringIdentifier` for `purchases-hybrid-common` to be able to call the function from `PaywallFragment`
> Add `launchIfNeeded` with `offeringIdentifier`

- ui/revenuecatui/src/main/res/values-zh-rCN/strings.xml
Added Chinese from mainland China. 
Notes: 
- I_have_no_idea_what_im_doing.gif
- There isn't an exact equivalent to iOS's zh_Hans in Android Studio, it allows you to set `zh_CN` and `zh_SG`. ChatGPT suggested adding those two as the equivalent. I added only one, under the assumption that zh_SG would automatically pick up zh_CN just like what happens in different variations of Spanish or English. 
- I added the entries that we have on iOS for Chinese Simplified, updating format where needed.
> Paywalls: add Chinese from mainland China

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallListener.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModel.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModelTest.kt
Cancelling the purchase modal shouldn't display an error dialog.
This is a very confusing experience, especially because that error wouldn't be localized.
> `Paywalls`: `PurchaseCancelledError` sends `onPurchaseCancelled` instead of an error

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template2.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template5.kt
This was making https://github.com/RevenueCat/react-native-purchases/pull/799/files#diff-8eaf252c074773fc7f002e444b255a9c2c60b23a2c75448799b85abb2f509bf9R20 crash when measuring the size giving this error:
I removed the scroll in Footer mode because it's not needed
> Remove scroll in Template 2 and 5 in Footer mode

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallActivity.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallResult.kt
In the `PaywallActivityLauncher` result, we were only reporting errors happening during purchasing, but not when an error happened during restores. 
This PR fixes that so we also report restore errors as long as that's the last operation that happened before closing the paywall.
> Report restore errors when using PaywallActivityLauncher

- api-tester/src/defaults/java/com/revenuecat/apitester/java/revenuecatui/PaywallActivityLauncherAPI.java
- api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/revenuecatui/PaywallActivityLauncherAPI.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallActivityLauncher.kt
In the hybrid SDKs, we want to return a result from the `presentPaywall`/`presentPaywallIfNeeded` methods with the result of the paywall. However, we can't do that easily since `presentPaywallIfNeeded` might not present the paywall at all, and there was no way to know whether the paywall was displayed in that case until now.
This adds a new parameter to the `launchIfNeeded` methods that receive a `requiredEntitlementIdentifier` that will indicate whether the paywall was displayed. Note that this isn't added to the `launchIfNeeded` method that received a block of code, since the client should know in that case whether the paywall was displayed or not, depending on the result of that callback.
> PaywallActivityLauncher: Add callback indicating whether the paywall was displayed when presented conditionally to an entitlement identifier

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallDialog.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/WindowHelper.kt
As I was testing #1551, I noticed that the dialog size wasn't correct. The width of the device sometimes was `MEDIUM` on a phone, causing it to present the dialog in a narrowed version. After more testing, I noticed that it was always one of the dimensions that were not `COMPACT` on my emulator, so I decided to check both. If one of the dimensions is `COMPACT`, we would present the dialog as full screen.
| Before  | After |
| ------------- | ------------- |
| ![image](https://github.com/RevenueCat/purchases-android/assets/808417/de5900ca-f0cc-48d1-8e32-64ea58819a7c) |  ![image](https://github.com/RevenueCat/purchases-android/assets/808417/c3a987a8-37b2-444c-81cc-4e8a16a98b44) |
> Fix paywall dialog composable sizing issues

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModel.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModelTest.kt
Equivalent to https://github.com/RevenueCat/purchases-ios/pull/3577
I've also added test coverage for errors in `PaywallViewModel`.
> `Paywalls`: improve error display

- gradle/libs.versions.toml
We bumped the ad library version in #1550. However, that version of the library adds the `AD_ID` permission, forcing our customers to have it as well, which is not intended. This reverts that bump but keeps the null pointer exception handling.
> Revert google ads library bump to remove `AD_ID` permission

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template5.kt
See also https://github.com/RevenueCat/purchases-ios/pull/3589
> `Paywalls`: improve template 5 layout for long product names

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/WindowHelper.kt
This is an attempt on dealing with #1566. We haven't been able to repro, but we can use the underlying activity from the context given by `LocalContext.current` in order to properly calculate the window size.
> Use activity instead of context to calculate window size

- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableProcessorTest.kt
This seemed to have been a bad merge from #1569.
> `VariableProcessor`: fix tests

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallState.kt
I'm currently debugging an issue with a developer, and realized that we have no way of knowing if the paywall goes into this state other than the error dialog being displayed.
This logs an error as well to make it easier to debug.
Example:
```
RevenueCatUI com.revenuecat.paywall_tester        E  Paywall transitioned to error state: Error 10: Error performing request.
```
> `Paywalls`: log error when creating `PaywallState.Error`

- purchases/src/main/kotlin/com/revenuecat/purchases/common/OfferingParser.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/offerings/OfferingsFactory.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/strings/OfferingStrings.kt
While debugging an issue, I realized that the SDK never prints anything after fetching products.
This should provide more visibility on the `Offerings` initialization.
> `OfferingsFactory`: debug logs when creating `Offerings`

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/views/PaywallFooterView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/views/PaywallView.kt
This will make it so calling the setOfferingId method after the initial layout updates the state causing a recomposition of the paywall.
> Paywall views: Support updating options state after initial layout

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/views/PaywallFooterView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/views/PaywallView.kt
We were missing calling `onPurchaseCancelled` when creating an internal PaywallListener
> Add missing forwarding to `PaywallListener.onPurchaseCancelled`

- api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/revenuecatui/PaywallFooterViewAPI.kt
- api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/revenuecatui/PaywallViewAPI.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/views/PaywallFooterView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/views/PaywallView.kt
External contribution from #1588 
- It's not possible for us to change the font family in react-native-purchase.
- My hope was to expose this font provider methods for the RN Bridge so that we can at least set custom font family.
- Exposing fontProviders for PaywallFooterView and PaywallView.
- theme composition local provider should update this autmoatically.
Need to add something like this on the React Native side.
If user did link the font via
```xml
<font-family xmlns:app="http://schemas.android.com/apk/res/android">
<font app:fontStyle="normal" android:fontWeight="200" android:font="@font/montserrat" />
</font-family>
```
```kotlin
ReactFontManager.getInstance().addCustomFont(this, "Montserrat", R.font.montserrat);
```
We could just bring the font family 
```kotlin
@ReactProp(name= …
```
> [EXTERNAL] Exposing fontprovider setter in `PaywallView` and `PaywallFooterView` by @Jjastiny

- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
- purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesTest.kt
`DEFERRED` is not currently supported in the latest SDK release, but on 6.9.5, the latest version it's supported on, the `DEFERRED` purchase might not work if the developer gives as an old product id in the format `productId:basePlanId`. Reason for it is that for deferred purchases, we used the given old product id as the key of the callback, which doesn't match the one returned once the purchase is completed, so the purchase is successful, but the value is never returned.
This applies a patch so we make sure to use only the `productId` as the `oldProductIdentifier` even if the developer gives us the other format (which can be obtained from several places in our SDK). This will be release as a hotfix and we will make hotfixes of the hybrids as well
> Fix `DEFERRED` purchases when passing old product id in invalid format

- CHANGELOG.md
This brings the release notes for #1595 (6.9.6) to `main`
> Update CHANGELOG with 6.9.6 release notes

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableDataProvider.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableProcessor.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/PeriodExtensions.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableProcessorTest.kt
Android equivalent of https://github.com/RevenueCat/purchases-ios/pull/3629
- `price_per_period_full`
- `total_price_and_per_month_full`
- `sub_period_length`
- `sub_period_abbreviated`
> `Paywalls`:  add 4 new variables

- api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/revenuecatui/PaywallFooterViewAPI.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/views/PaywallFooterView.kt
https://github.com/RevenueCat/purchases-android/pull/1589  made `PaywallFooterView` an `AbstractComposeView`, which broke React Native's implementation because we override `onMeasure` which is final in `AbstractComposeView`
> Revert making PaywallFooterView an AbstractComposeView

- purchases/src/main/kotlin/com/revenuecat/purchases/common/OfferingParser.kt
We have a customer having a silent crash here. I am changing it to catch everything to get more insights
> Catch Exception instead of only IllegalArgumentException when decoding paywallData

- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/PaywallData.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/utils/LocaleExtensions.kt
- purchases/src/test/java/com/revenuecat/purchases/paywalls/PaywallDataTest.kt
- purchases/src/test/java/com/revenuecat/purchases/utils/LocaleExtensionsTest.kt
Test coverage to ensure that Android isn't affected by https://github.com/RevenueCat/purchases-ios/pull/3633.
I've also extracted `getDefaultLocales` and  `localizedConfiguration(List<Locale>)` so we can test those.
> `Paywalls`: add test coverage for locales with different region

- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/events/PaywallEvent.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/events/PaywallPostReceiptData.kt
- purchases/src/test/java/com/revenuecat/purchases/common/backend/BackendTest.kt
The API is expecting the `revision` key instead of `paywall_revision` for paywall data in POST receipt. The backend has a fix to support both but changing this for consistency between SDKs.
- Renamed `paywall_revision` to `revision` in `PaywallPostReceiptData`
- Added `offering_id` to `PaywallPostReceiptData`
> Fix paywall POST receipt data for paywall revision

- purchases/consumer-rules.pro
- Added rules for version 1.4.1 https://github.com/Kotlin/kotlinx.serialization/blob/v1.4.1/README.md#android which are now included in the latest versions of kotlin serialization but starting from 1.5.0. We are still in 1.4.1 for kotlin compatibility reasons
- Added rules that fix issues when targetting Android SDK 34 and compiling with < 34 (like using version 33). There's been a breaking change in Android 14 (they added ClassValue) and copying what the [behavior changes website mentions](https://developer.android.com/about/versions/14/behavior-changes-14#core-libraries):
> The problem originates with a Kotlin library that changes runtime behaviour based on whether Class.forName("java.lang.ClassValue") returns a class or not. If your app was developed against an older version of the …
> Fix serialization proguard rules

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/InternalPaywall.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallDialog.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModel.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModelFactory.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModelTest.kt
When using `PaywallDialog` composable, if the user restored and matched the `requiredEntitlementIdentifier` or condition to display the paywall given by the developer, we were not dismissing the paywall automatically.
This fixes that, and auto-dismisses the paywall after a successful restore if it matches the given condition by the developer.
> Paywalls: Call `PaywallDialog` dismiss handler after successful restore if needed

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/LoadingPaywall.kt
Still trying to figure out repro steps for #1611 since we disable touches during the loading screen... However, I noticed we can probably just ignore all taps here which should avoid the crash entirely as well. Will fix #1611
> Paywalls: No-op on all view model methods in the Loading paywall screen

- api-tester/src/main/java/com/revenuecat/apitester/java/OfferingsAPI.java
- api-tester/src/main/java/com/revenuecat/apitester/java/PresentedOfferingContextAPI.java
- api-tester/src/main/java/com/revenuecat/apitester/java/StoreProductAPI.java
- api-tester/src/main/java/com/revenuecat/apitester/kotlin/OfferingsAPI.kt
- api-tester/src/main/java/com/revenuecat/apitester/kotlin/PresentedOfferingContextAPI.kt
- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/Constants.kt
- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/PaywallTesterApp.kt
- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/AppScreen.kt
- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/main/MainScreen.kt
- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/main/offerings/OfferingsScreen.kt
- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/paywall/PaywallScreenViewModel.kt
- examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OverviewFragment.kt
- examples/purchase-tester/src/main/res/layout/fragment_overview.xml
- examples/purchase-tester/src/main/res/values/strings.xml
- purchases/src/main/kotlin/com/revenuecat/purchases/Offerings.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/PresentedOfferingContext.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/Backend.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/OfferingParser.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/strings/OfferingStrings.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/utils/JSONArrayExtensions.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/utils/JSONObjectExtensions.kt
- purchases/src/test/java/com/revenuecat/purchases/OfferingsTest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/backend/BackendTest.kt
- purchases/src/test/java/com/revenuecat/purchases/utils/productStubs.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModelTest.kt
New function to get `Offering` by a placement identifier
New `getCurrentOfferingForPlacement(placementId: String): Offering?` method on `Offerings`
- Added demo button for this in paywalls example app
- Added demo button for this in purchase tester app
```kotlin
// Example usage
offerings.getCurrentOfferingForPlacement("onboarding")?.let {
showPaywall(it)
}
```
1. Returns an `Offering` if the placement identifier has a value
2. Checks if the placement identifier key exists in the `placements` dictionary
- If the key exists (and value is `null`)
1. Returns `null` if the placement identifier key exists in the dictionary but has a `null` value (this is intentional by the developer to NOT have an `Offering` for this placement identifier)
- If the key doesn't exist
1. Return the `Offering` for …
> Add `getCurrentOffering(forPlacement: String)` to `Offerings`

- api-tester/src/main/java/com/revenuecat/apitester/java/PresentedOfferingContextAPI.java
- api-tester/src/main/java/com/revenuecat/apitester/java/StoreProductAPI.java
- api-tester/src/main/java/com/revenuecat/apitester/kotlin/PresentedOfferingContextAPI.kt
- api-tester/src/main/java/com/revenuecat/apitester/kotlin/StoreProductAPI.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/Offerings.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/PresentedOfferingContext.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/Backend.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/OfferingParser.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/strings/OfferingStrings.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/utils/JSONObjectExtensions.kt
- purchases/src/test/java/com/revenuecat/purchases/OfferingsTest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/backend/BackendTest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/offerings/OfferingsFactoryTest.kt
- purchases/src/test/java/com/revenuecat/purchases/utils/productStubs.kt
Get more context with targeting information 
- Parse targeting information into `Offerings`
- Add targeting context into `Offerings.current`
- Add targeting context into `getCurrentOffering(forPlacement: String)`
- Post targeting context in post receipts
> Add targeting to `PresentedOfferingContext`

- purchases/src/main/kotlin/com/revenuecat/purchases/PostTransactionWithProductDetailsHelper.kt
We were never posting prices for Amazon purchases, because when we try to find the purchased product, we where using the `subscriptionOptions` property, which is always null for Amazon
This fix is a bit hacky right now, but we need to ship it quickly
> Fix amazon zero price

- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/PaywallColor.kt
There's a small typo in the docs of `PaywallColor`. `#RRGGBBAA` should have been `#AARRGGBB`, according to the docs of the underlying API being used ([`Color.parseColor()`](https://developer.android.com/reference/android/graphics/Color#parseColor(java.lang.String))). 
Regarding `purchases-ios`, `parseColor` in `PaywallColor.swift` does seem to follow the RRGGBBAA pattern, so the documentation is correct there. I couldn't find this API in the hybrids.  
Resolves #1643 
The documentation is aligned with the documentation of the underlying API.
> Fixes a typo in PaywallColor.

- api-tester/src/defaults/java/com/revenuecat/apitester/java/revenuecatui/PaywallColorAPI.java
- api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/revenuecatui/PaywallColorAPI.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/PaywallColor.kt
- purchases/src/test/java/com/revenuecat/purchases/paywalls/PaywallColorTest.kt
We were parsing RGBA paywall colors as ARGB. This isn't a problem right now since we currently don't support alpha colors in paywalls, but in case we do in the future, we need to match iOS, which uses RGBA.
> Correctly support RGBA colors

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/UIConstant.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template5.kt
If there's no header image in template 5, the close button overlaps the title
Adds some space if there's no header image:
> Add space to title in Template 5

- .circleci/config.yml
The version we are using is deprecated
https://discuss.circleci.com/t/android-image-deprecations-and-eol-for-2024/50180/15
> Update android executor to a non-deprecated tag

- purchases/src/main/kotlin/com/revenuecat/purchases/common/OfferingParser.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/strings/OfferingStrings.kt
This removes an error log which was happening even in normal situations. The response from the backend may have a `placements` key with only a fallback, but no `offering_ids_by_placement`, which was logging it as an error, which it wasn't
> Remove confusing placements error log

- ui/revenuecatui/src/main/res/values-no/strings.xml
Correct word but wrong context
`Restaurere` to `Gjenopprett`
> `Paywalls`: Update Norwegian "restore" localization

- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsHelper.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizer.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsTracker.kt
- purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
- purchases/src/test/java/com/revenuecat/purchases/PurchasesCommonTest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizerTest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerFunctionalTest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerTest.kt
We were clearing the diagnostics file during SDK configuration if we detected the file to be too big. We could make this clearing happen during tracking of events. Advantages of this:
- We make sure the file never gets too big 
- We don't miss extra events if we need to clear the file
This shouldn't be a problem performance-wise since we are doing all this in a background thread + checking the file size is pretty quick.
> Make clearing diagnostics file happen during tracking

- purchases/src/main/kotlin/com/revenuecat/purchases/PostReceiptHelper.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/amazon/AmazonBilling.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/Backend.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/BillingAbstract.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/networking/PostReceiptResponse.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/strings/PurchaseStrings.kt
- purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
- purchases/src/test/java/com/revenuecat/purchases/PostReceiptHelperTest.kt
- purchases/src/test/java/com/revenuecat/purchases/amazon/AmazonBillingTest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/backend/BackendTest.kt
- purchases/src/test/java/com/revenuecat/purchases/google/usecase/AcknowledgePurchaseUseCaseTest.kt
- purchases/src/test/java/com/revenuecat/purchases/google/usecase/ConsumePurchaseUseCaseTest.kt
- purchases/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesBackendTests.kt
- purchases/src/test/java/com/revenuecat/purchases/utils/Responses.kt
This brings support to non-consumables in android. The backend will let us know whether we need to consume a product after posting it or not.
> Support non consumable products

- purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
- purchases/src/test/java/com/revenuecat/purchases/google/usecase/AcknowledgePurchaseUseCaseTest.kt
After #1697 , we stopped consuming non-consumables if the backend indicates to not consume them. Non-consumables still need to be acknowledged, otherwise they get refunded, this PR fixes that.
For reference, https://developer.android.com/google/play/billing/integrate#non-consumable-products
> Fix non-consumables not getting acknowledged

- examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OfferingCardAdapter.kt
- examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OverviewFragment.kt
I've run into some issues with purchase tester for a while where the offerings were not updated after changing screens or purchasing. This simplifies the reloading so it loads always. There might be more performant options, but considering this is a test app, I didn't want to dedicate too much time to it.
> Fix purchase tester offerings not reloading

- .circleci/config.yml
This was causing the release PRs to never turn green completely
Also, it breaks "Rerun from fails" in CircleCI since there's a approval job, which causes the workflow to never fail completely if another job fails.
> Remove `force-release-without-waiting-for-tests` job

- examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/ConfigureFragment.kt
Enabling trusted entitlement seems like a more sensible default for our test app.
> Set INFORMATIONAL trusted entitlements mode as the default in the purchase tester app

- api-tester/src/defaults/java/com/revenuecat/apitester/java/DeprecatedPurchasesAPI.java
- api-tester/src/defaults/java/com/revenuecat/apitester/java/PurchasesAPI.java
- api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/DeprecatedPurchasesAPI.kt
- api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
- api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAreCompletedByAPI.java
- api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesCommonAPI.java
- api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAreCompletedByAPI.kt
- api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesCommonAPI.kt
- examples/MagicWeather/app/src/main/java/com/revenuecat/sample/MainApplication.kt
- examples/MagicWeatherCompose/app/src/main/java/com/revenuecat/sample/MainApplication.kt
- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/MainApplication.kt
- examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/ConfigureFragment.kt
- examples/purchase-tester/src/main/res/layout/fragment_configure.xml
- examples/purchase-tester/src/main/res/values/strings.xml
- purchases/src/defaults/kotlin/com/revenuecat/purchases/Purchases.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesAreCompletedBy.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesConfiguration.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/amazon/AmazonStrings.kt
- purchases/src/test/java/com/revenuecat/purchases/PurchasesConfigurationTest.kt
- purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesConfigureTest.kt
- purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesTest.kt
- Adds `PurchasesAreCompletedBy` enum.
- Adds `PurchasesConfiguration.Builder.purchasesAreCompletedBy()`
- Deprecates `PurchasesConfiguration.Builder.observerMode()`, with a nice `ReplaceWith` action.
- Adds `Purchases.syncAmazonPurchase()`.
- Deprecates `Purchases.syncObserverModeAmazonPurchase`, with a nice `ReplaceWith` action.
- Deprecates `Purchases.finishTransactions`, with an okay `ReplaceWith` action.
- Adds API tests for `PurchasesAreCompletedBy`.
- Adds API tests for `purchasesAreCompletedBy()`.
- PaywallsTester, PurchaseTester and the MagicWeather samples use `purchasesAreCompletedBy()` instead of `observerMode()`.
- Adds some unit tests for `purchasesAreCompletedBy()`.
This PR does not remove all internal mentions of the terms "observer mode" and "finish transactions" from the …
> Deprecate observerMode in favor of purchasesAreCompletedBy

- api-tester/src/main/java/com/revenuecat/apitester/java/InstallmentsInfoAPI.java
- api-tester/src/main/java/com/revenuecat/apitester/java/SubscriptionOptionAPI.java
- api-tester/src/main/java/com/revenuecat/apitester/kotlin/InstallmentsInfoAPI.kt
- api-tester/src/main/java/com/revenuecat/apitester/kotlin/SubscriptionOptionAPI.kt
- examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/SubscriptionOptionExtensions.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/google/subscriptionOptionConversions.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/models/GoogleInstallmentsInfo.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/models/GoogleSubscriptionOption.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/models/InstallmentsInfo.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/models/SubscriptionOption.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/models/TestStoreProduct.kt
- purchases/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
- purchases/src/test/java/com/revenuecat/purchases/utils/billingClientStubs.kt
- purchases/src/test/java/com/revenuecat/purchases/utils/productStubs.kt
- ui/debugview/src/main/kotlin/com/revenuecat/purchases/ui/debugview/models/TestModels.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/PackageExtensionsTest.kt
This exposes the info for installment plans so developers can use it. The new API looks like:
- New `InstallmentsInfo` interface with `commitmentPaymentsCount` and `subsequentCommitmentPaymentsCount` fields.
- New `GoogleInstallmentsInfo` data class implementing previous interface.
- New method in `SubscriptionOption`/`GoogleSubscriptionOption` exposing the installments info.
> Expose `InstallmentsInfo` in `SubscriptionOption`

- purchases/src/main/kotlin/com/revenuecat/purchases/common/subscriberattributes/SpecialSubscriberAttributes.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/google/attribution/GoogleDeviceIdentifiersFetcher.kt
- purchases/src/test/java/com/revenuecat/purchases/google/attribution/GoogleDeviceIdentifiersFetcherTests.kt
- purchases/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesManagerTests.kt
Cherry-picked the squashed commit from https://github.com/RevenueCat/purchases-android/pull/1725, but targeting `main` this time.
> Stops collecting the ANDROID_ID.

- api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesCommonAPI.java
- api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesCommonAPI.kt
- purchases/src/customEntitlementComputation/kotlin/com/revenuecat/purchases/Purchases.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/BillingFactory.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesConfiguration.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
- purchases/src/test/java/com/revenuecat/purchases/BillingFactoryTest.kt
- purchases/src/test/java/com/revenuecat/purchases/PurchasesConfigurationTest.kt
- purchases/src/test/java/com/revenuecat/purchases/amazon/BillingFactoryAmazonTest.kt
- purchases/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
PR to support pending prepaid purchase as a new feature added in BC7. This will be enabled by default but can be disabled through an option in `PurchasesConfiguration`: `pendingTransactionsForPrepaidPlansEnabled `.
> Support pending prepaid purchases

- gradle/libs.versions.toml
- ui/revenuecatui/build.gradle
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/Footer.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/UriHandlerExtensions.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/FooterLinksNoBrowserTest.kt
- Adds `UriHandler.openUriOrElse()`, inspired by the stdlib's `Map.getOrElse()`.
- Uses `openUriOrElse()` in the `Footer` to log a warning if there's no browser installed.
- Adds `FooterLinksNoBrowserTest`.
Closes #1723
> Fixes crash if no browser is installed

- examples/MagicWeatherCompose/gradle/libs.versions.toml
Build was failing because the compose compiler we use in MagicWeatherCompose is incompatible with 1.7.21. Upgraded to 1.8.22 to match the rest of the projects
> Bump kotlin to 1.8 in MagicWeatherCompose

- purchases/src/main/kotlin/com/revenuecat/purchases/common/durationExtensions.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/google/usecase/BillingClientUseCase.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/strings/BillingStrings.kt
- purchases/src/test/java/com/revenuecat/purchases/google/usecase/AcknowledgePurchaseUseCaseTest.kt
- purchases/src/test/java/com/revenuecat/purchases/google/usecase/ConsumePurchaseUseCaseTest.kt
- purchases/src/test/java/com/revenuecat/purchases/google/usecase/QueryProductDetailsUseCaseTest.kt
- purchases/src/test/java/com/revenuecat/purchases/google/usecase/QueryPurchaseHistoryUseCaseTest.kt
- purchases/src/test/java/com/revenuecat/purchases/google/usecase/QueryPurchasesByTypeUseCaseTest.kt
- purchases/src/test/java/com/revenuecat/purchases/google/usecase/QueryPurchasesUseCaseTest.kt
We detected this error could happen consistently when acknowledging pending prepaid purchases after payment is performed when the app is closed. This adds some retries to this error, but much smaller than the one that we have when the app is in background (15min vs 4 seconds).
> Add retries upon Google's SERVICE_UNAVAILABLE error when app in foreground

- purchases/src/main/kotlin/com/revenuecat/purchases/common/AppConfig.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/utils.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/PaywallData.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/utils/LocaleExtensions.kt
- purchases/src/test/java/com/revenuecat/purchases/common/AppConfigTest.kt
With version 8.0.0 and BC7, we bumped the min sdk to 21 (since it was required by BC7). This removes some checks we had for versions lower than that which shouldn't happen anymore.
> Remove unneeded Android Lollipop version checks

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/Footer.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/testdata/TestData.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template1.kt
See https://github.com/RevenueCat/purchases-flutter/issues/1078
There is no bottom margin if there is no button present in the footer. This adds a small padding there.
| Before  |  After  |
|---|---|
| ![image](https://github.com/RevenueCat/purchases-android/assets/808417/7e9a9eee-df8f-4c2a-8827-50c5dad3eb4e) | ![image](https://github.com/RevenueCat/purchases-android/assets/808417/d7d04776-348e-4d12-a281-c41ab0fc0c36) |
> Paywalls: Add bottom padding when there are no buttons in footer

- .circleci/config.yml
- Updates both Android executors to 2024.04.1. 
- This drops support for API 27 (compared to 2023.11.1), see [CircleCI docs](https://circleci.com/developer/images/image/cimg/android).  
- Updates the Android orb to 2.5.0. 
- Updates the RC orb to 3.0.0.
> SDK-3482 Updates various orbs and images

- api-tester/src/main/java/com/revenuecat/apitester/java/PeriodAPI.java
- api-tester/src/main/java/com/revenuecat/apitester/kotlin/PeriodAPI.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/models/Period.kt
- purchases/src/test/java/com/revenuecat/purchases/models/PeriodTest.kt
This will fix #1753
In cases where the period we get from the store is in the format ISO8601-2, that is, has multiple units, our current parsing code wouldn't parse it correctly. I changed to use the smaller unit sent from the store and convert it to that unit.
> Support ISO8601-2 period durations

- purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/google/usecase/AcknowledgePurchaseUseCase.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/google/usecase/ConsumePurchaseUseCase.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/strings/PurchaseStrings.kt
- purchases/src/test/java/com/revenuecat/purchases/google/usecase/AcknowledgePurchaseUseCaseTest.kt
- purchases/src/test/java/com/revenuecat/purchases/google/usecase/ConsumePurchaseUseCaseTest.kt
Cleans up logs when acknowledging or consuming and getting an `ITEM_NOT_OWNED`. Also removed some duplication of the logs
-------
Before:
After:
> Makes `ITEM_NOT_OWNED` message more clear when restoring and acknowledging/consuming

- fastlane/Fastfile
Now we have an active token in production that won't expire, so we can require an active entitlement for integration tests. We just need to update some ENVs in CI. This is just a cleanup
> Update test lane to require active entitlements

- purchases/src/androidTest/kotlin/com/revenuecat/purchases/BasePurchasesIntegrationTest.kt
- purchases/src/androidTestDefaults/kotlin/com/revenuecat/purchases/offlineentitlements/OfflineEntitlementsWithInitialRequestsCompletedIntegrationTest.kt
We had a test that verifies that a token gets recognized and entitlements given if the user is offline, then they recover, but that test wasn't working correctly, since the token we used didn't grant any entitlements (was an expired token).
After changing to a proper token, this test started failing because the token was already assigned to a different user and we were posting it with initiation source `unsynced_active_purchases`, which doesn't transfer active purchases, so the entitlement was never granted. In order to properly test that case, we would need a new token every time we run the tests which we currently can't have, since testing with Google Play is bad :(. 
For now, I've changed the test to cover recovery after a restore, which does work as expected. Happy to provide more …
> Change android integration test to cover more testable use case

- api-tester/src/main/java/com/revenuecat/apitester/java/GoogleReplacementModeAPI.java
- api-tester/src/main/java/com/revenuecat/apitester/kotlin/GoogleReplacementModeAPI.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/Backend.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/models/GoogleReplacementMode.kt
Deferred replacement mode was removed in V7 of the SDK. This brings it back.
> Add `DEFERRED` replacement mode

- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
- purchases/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
Another followup to #1751 and #1764 
When making `DEFERRED` purchases, Google returns the result using the old product id. We need to cache all the context information using the old product id so we can attribute it correctly.
> Use correct product context with `DEFERRED` purchases

- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesConfiguration.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
- purchases/src/test/java/com/revenuecat/purchases/PurchasesConfigurationTest.kt
- purchases/src/test/java/com/revenuecat/purchases/PurchasesFactoryTest.kt
I noticed that trusted entitlements may fail if passing an API key with extra whitespaces. This is because it's part of the data we are verifying and the backend uses the trimmed version so there is a mismatch. This trims the API key we use in the SDK, so it matches what the backend uses in those cases. Any real API key shouldn't contain any whitespaces so I think it should be fine but lmk what you think
> Use trimmed API key

- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/caching/DeviceCache.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/offlineentitlements/OfflineEntitlementsManager.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/identity/IdentityManager.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/subscriberattributes/caching/SubscriberAttributesCache.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/subscriberattributes/caching/SubscriberAttributesMigrationExtensions.kt
- purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
- purchases/src/test/java/com/revenuecat/purchases/identity/IdentityManagerTests.kt
- purchases/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesDeviceCacheTests.kt
- purchases/src/testDefaults/kotlin/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt
This PR addresses a significant number of ANRs (Application Not Responding errors) reported, such as in issue #1629.
The method `IdentityManager.configure` is currently running on the main thread and accessing `SharedPreferences`. Accessing `SharedPreferences` can be costly, especially if the XML file storing the preferences is large. This cost is particularly high during the initial accesses, as the XML file needs to be read and parsed, which can block the main thread and lead to ANRs.
**Custom Dispatcher**: This PR introduces a custom dispatcher to the `IdentityManager`, allowing configure to run on a background thread. By moving this operation off the main thread, we avoid blocking it with the potentially expensive SharedPreferences access.
**Main Thread Optimization**: The remaining …
> Attempt to fix ANRs by moving some tasks during configure to background

- examples/CustomEntitlementComputationSample/gradle/wrapper/gradle-wrapper.properties
- examples/MagicWeather/gradle/wrapper/gradle-wrapper.properties
- examples/MagicWeatherCompose/gradle/wrapper/gradle-wrapper.properties
- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
As the title says. 
Gradle was at 8.0 and needed to at least be 8.1. for maven.publish 0.28.0, so I updated to the latest.
There was no requirement to update AGP, but from experience it is good to keep that somewhat in sync with Gradle, so went with the latest here too.
> Updates Gradle (8.9), AGP (8.5.1) and maven.publish (0.28.0)

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/RemoteImage.kt
We were seeing some flickering in the paywall images when the activity was paused/started. This seems to have been caused because the loader was recreated every time. The loader only actually uses a reference to the application context, so we can just change it to avoid that recreation and store a reference to the image loader.
> [Paywalls] Fix `RemoteImage` flicker on activity changes

- .circleci/config.yml
- api-tester/src/main/java/com/revenuecat/apitester/java/PricingPhaseAPI.java
- api-tester/src/main/java/com/revenuecat/apitester/kotlin/PricingPhaseAPI.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/models/PricingPhase.kt
- purchases/src/test/java/com/revenuecat/purchases/common/models/ParameterizedPricingPhaseTest.kt
As the title says. 
**Context:**
- https://github.com/RevenueCat/purchases-hybrid-common/pull/621#discussion_r1689767219
- https://github.com/RevenueCat/purchases-android/pull/1255
> Adds pricePerPeriod functions to PricingPhase

- .gitignore
- .idea/detekt.xml
As the title says. The [Detekt IntelliJ plugin](https://plugins.jetbrains.com/plugin/10761-detekt) requires some manual setup. If every team member has to do that individually, there's a higher chance of discrepancies and errors.
> Adds the Detekt IntelliJ plugin settings to version control.

- .idea/detekt.xml
As the title says. Previously discussed here: https://github.com/RevenueCat/purchases-android/pull/1796#discussion_r1695021333
> Adds the baseline file to the Detekt IntelliJ plugin settings.

- .circleci/config.yml
This will make it so we publish paywall tester for internal testing on each SDK release
> Publish paywall tester on each release

- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/Constants.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/PaywallData.kt
- purchases/src/test/java/com/revenuecat/purchases/paywalls/PaywallDataTest.kt
- purchases/src/test/resources/paywalldata-default-locale-with-missing_current_locale.json
Support new `default_locale` property in paywall data
If localization for preferred language isn't found, use the default locale before falling back to the first locale.
https://github.com/user-attachments/assets/fae5bfb1-d22b-4d69-a944-ff3311c47ee5
> [Paywalls] Add default locale

- fastlane/Fastfile
This changes the device running the nightly load shedder integration tests to a Pixel 7 to hopefully improve the flakyness
> [V5] Change device running nightly integration tests

- fastlane/Fastfile
This changes the device running the nightly load shedder integration tests to a Pixel 7 to hopefully improve the flakyness
> [V4] Change device running nightly integration tests

- build.gradle
- config/detekt/detekt-baseline.xml
- gradle/libs.versions.toml
Compose has many footguns that are easy to forget. (Think state restoration, remembering, modifier parameters, viewmodel forwarding.) It's unrealistic to expect everyone to always remember all of these. These Detekt rules help to avoid these issues a lot, in my experience. Static checks also ease the pressure on code reviews to spot these issues.  
You can find a description of the rules [here](https://mrmans0n.github.io/compose-rules/rules/). They were originally developed at [Twitter](https://github.com/twitter/compose-rules) (1.0), and are currently maintained by [the engineer who started the project](https://x.com/mrmans0n/status/1507390768796909571). Slack is maintaining [the Lint version](https://slackhq.github.io/compose-lints/) of these same rules. 
**Note:** the Detekt IntelliJ …
> Adds Detekt rules for Compose. Updates detekt to 1.23.6.

- purchases/src/main/kotlin/com/revenuecat/purchases/common/HTTPClient.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsTracker.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/errors.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/networking/HTTPResult.kt
- purchases/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerTest.kt
This adds a new property to the `http_request_performed` diagnostics event including information of any backend provided error codes if any.
> [Diagnostics] Send backend_error_code in http request failures if available

- .circleci/config.yml
- build.gradle
- fastlane/Fastfile
- fastlane/README.md
- gradle/libs.versions.toml
- test-apps/testpurchasesuiandroidcompatibility/build.gradle.kts
Adds Emerge snapshots to purchases UI, as RevenueCat has expressed interest and we figured we'd make the process easier 😄 .
Adds the basic integration necessary for getting up and running with Emerge snapshots:
- Adds the Emerge gradle plugin to the `testpurchasesuiandroidcompatibility` module.
- Worth noting that Emerge requires the plugin to be set on an `application` module vs a library module. @tonidero had mentioned that the Previews we want to snapshot are in `:ui:revenuecatui`. Given that this application module depends directly on the `:ui:revenuecatui` module and snapshots use a debug variant, all code should be present from that module, giving Emerge all `@Previews` automatically.
- Adds what I believe is the necessary fastlane/CircleCI setup to invoke snapshots, but my …
> Add Emerge snapshot testing

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/PackageConfigurationFactory.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/MultiTierTemplateConfigurationFactoryTest.kt
There's an equivalent iOS fix here: https://github.com/RevenueCat/purchases-ios/pull/4243.
If a Template 7 Paywall is configured to use packages for which the products are not available, it crashes in `PackageConfigurationFactory.kt`, line 142. 
The SDK prints these logs: 
```
Tier Standard has no available products and will be removed from the paywall.
Tier Premium has no available products and will be removed from the paywall.
``` 
After that, no tiers are left anymore, but this case isn't considered.
<details>
<summary>Stack trace</summary>
```java
FATAL EXCEPTION: main (Ask Gemini)
Process: com.revenuecat.purchases_sample, PID: 19505
java.util.NoSuchElementException: List is empty.
at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:214)
at …
```
> Fixes a Paywall Template 7 crash when none of the tiers have any available products.

- .circleci/config.yml
- build.gradle
- fastlane/Fastfile
- fastlane/README.md
- gradle/libs.versions.toml
- test-apps/testpurchasesuiandroidcompatibility/build.gradle.kts
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallFooter.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/Markdown.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/PaywallDataExtensions.kt
Adds Emerge snapshots to purchases UI, as RevenueCat has expressed interest and we figured we'd make the process easier 😄 .
Adds the basic integration necessary for getting up and running with Emerge snapshots:
- Adds the Emerge gradle plugin to the `testpurchasesuiandroidcompatibility` module.
- Worth noting that Emerge requires the plugin to be set on an `application` module vs a library module. @tonidero had mentioned that the Previews we want to snapshot are in `:ui:revenuecatui`. Given that this application module depends directly on the `:ui:revenuecatui` module and snapshots use a debug variant, all code should be present from that module, giving Emerge all `@Previews` automatically.
- Adds what I believe is the necessary fastlane/CircleCI setup to invoke snapshots, but my …
> [EXTERNAL] Add Emerge snapshot testing (#1785) by @rbro112

- api-tester/src/defaults/java/com/revenuecat/apitester/java/PurchasesAPI.java
- api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
- purchases/src/defaults/kotlin/com/revenuecat/purchases/Purchases.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/subscriberattributes/SpecialSubscriberAttributes.kt
- purchases/src/testDefaults/kotlin/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt
This adds a new API `setKochavaDeviceId` that allows to set the kochava device ID required for the Kochava integration. 
Keeping on hold until backend support is added
> Add `$kochavaDeviceId` attribution convencience method

- test-apps/testpurchasesuiandroidcompatibility/build.gradle.kts
Attempts to wire up Emerge gradle plugin configuration for getting snapshot diffs on PRs as a follow up from https://github.com/RevenueCat/purchases-android/pull/1831. Emerge diffs using Git information (sha/base sha), so we just need to set the baseSha to the proper `main` branch sha the PR is based off. 
Wires up two notable config items from Emerge plugin to enable diffing:
- `baseSha` for finding the proper base build to diff against. Emerge sets this implicitly from Git info (when `baseSha` is not explicitly set), which I believe should work here since CircleCI is doing a standard checkout. 
- I couldn't find a base sha variable in https://circleci.com/docs/variables/, but I believe our implicit setting should handle.
- The gradle plugin code that sets this is …
> [EXTERNAL] Wireup Emerge gradle plugin config for PR snapshot diffs

- test-apps/testpurchasesuiandroidcompatibility/build.gradle.kts
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/PaywallIcon.kt
Attempts to wire up Emerge gradle plugin configuration for getting snapshot diffs on PRs as a follow up from
https://github.com/RevenueCat/purchases-android/pull/1831. Emerge diffs using Git information (sha/base sha), so we just need to set the baseSha to the proper `main` branch sha the PR is based off.
Wires up two notable config items from Emerge plugin to enable diffing:
- `baseSha` for finding the proper base build to diff against. Emerge sets this implicitly from Git info (when `baseSha` is not explicitly set), which I believe should work here since CircleCI is doing a standard checkout.
- I couldn't find a base sha variable in https://circleci.com/docs/variables/, but I believe our implicit setting should handle.
- The gradle plugin code that sets this is …
> [EXTERNAL] Wireup Emerge gradle plugin config for PR snapshot diffs (#1841) by @rbro112

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallActivityLauncher.kt
We got a couple reports of a similar issue:
- https://github.com/RevenueCat/purchases-android/issues/1842
- https://community.revenuecat.com/sdks-51/crash-in-kotlin-4999
Seems that those happened mostly on android TV. While I haven't been able to reproduce normally, I was able to reproduce (with the same stacktrace) by adding an artificial delay between the obtention of the customer info and presenting the paywall when `requiredEntitlementIdentifier` is shown and killing the activity.
This is a possible approach to fixing this.
> Fix crash if activity finished while calculating presentation logic

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModel.kt
This was a regression in #1777, and was reported in #1849 
We weren't marking as an action in progress when performing purchases.
> Fix interaction not disabled during purchases

- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableProcessorTest.kt
As the title says. When investigating an issue I wanted to eliminate the possibility that our SDK is somehow processing these incorrectly. Turns out it isn't. Can't hurt to add these tests to avoid regressions I think?
> Adds some more test cases validating {{ total_price_and_per_month }} for quarterly packages. 

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/InternalPaywall.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallOptions.kt
This is an approach to fix DENG-955
If trying to display multiple paywalls at the same time, all paywalls would currently share the same view model. This caused that all of them would be exactly the same, which was not great for some use cases. This adds a key to the view model injection using the paywall options view model hash code. This means we will have one view model for each combination of paywall options parameters.
> Fix multiple paywalls display issues

- config/detekt/detekt.yml
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/SubscriptionDetailsView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/SubscriptionInformation.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/icons/CalendarMonth.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/icons/CurrencyExchange.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/icons/UniversalCurrencyAlt.kt
- A new `SubscriptionDetailsView` ☝️, modelled after the iOS namesake. (The black border is Android Studio's preview UI.)
- Slightly tweaked the `TopLevelPropertyNaming` Detekt rule to allow CamelCase constants, following the Compose guidelines. I modified [Detekt's recommendation](https://detekt.dev/docs/introduction/compose#toplevelpropertynaming-for-compose) to also allow SCREAMING_SNAKE_CASE, as we use that in other parts.
- Any logic to display the new `SubscriptionDetailsView`.
I was thinking we can update the design as we go, when we have a better idea of what this is going to look like, but let me know what you think!
> [CustomerCenter] Adds SubscriptionDetailsView

- api-tester/src/defaults/java/com/revenuecat/apitester/java/PurchasesAPI.java
- api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
- purchases/src/defaults/kotlin/com/revenuecat/purchases/Purchases.kt
- purchases/src/defaults/kotlin/com/revenuecat/purchases/coroutinesExtensions.kt
- purchases/src/defaults/kotlin/com/revenuecat/purchases/listenerConversions.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/Backend.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/HTTPClient.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/LocaleProvider.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/networking/Endpoint.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/customercenter/CustomerCenterConfigData.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/customercenter/ScreenMapSerializer.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/interfaces/GetCustomerCenterConfigCallback.kt
- purchases/src/test/java/com/revenuecat/purchases/backend_integration_tests/ProductionBackendIntegrationTest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/backend/BackendGetCustomerCenterConfigTest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/backend/BackendPaywallEventTest.kt
- purchases/src/test/java/com/revenuecat/purchases/customercenter/CustomerCenterConfigDataTest.kt
- purchases/src/test/resources/get_customer_center_config_success.json
- purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesTest.kt
- Adds networking layer and models to `RevenueCat` to support the new CustomerCenter.
- Adds a new `X-Preferred-Locales` header.
- Adds a new `Purchases.getCustomerCenterConfigData` method to access the data from `RevenueCatUI`
> [CustomerCenter] Add networking layer and models

- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/main/appinfo/AppInfoScreen.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/CustomerCenter.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/InternalCustomerCenter.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/CustomerCenterState.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/CustomerCenterViewModel.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/CustomerCenterViewModelFactory.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PurchasesType.kt
This adds an initial composable and view model with some previews so we can start iterating over the customer center. 
New composable using it as a bottom sheet and using it from paywall tester will come in follow up PRs.
Nothing exposed in this PR yet.
> [CustomerCenter] Create `CustomerCenter` composable and view model with some initial UI

- purchases/src/main/kotlin/com/revenuecat/purchases/customercenter/CustomerCenterConfigData.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/customercenter/HelpPathsSerializer.kt
- purchases/src/test/java/com/revenuecat/purchases/customercenter/CustomerCenterConfigDataTest.kt
While testing one thing I noticed we were not handling unknown help path types. This basically caused the whole screen to not be deserialized, since we catch deserialization issues at that level, but we can do better than that and just not deserialize the unknown path type.
> [CustomerCenter] Fix help path deserializing when unknown type

- api-tester/src/defaults/java/com/revenuecat/apitester/java/PurchasesAPI.java
- api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
- purchases/src/defaults/kotlin/com/revenuecat/purchases/Purchases.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/DangerousSettings.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesConfiguration.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/strings/ConfigureStrings.kt
- purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
- purchases/src/test/java/com/revenuecat/purchases/PurchasesConfigurationTest.kt
- purchases/src/test/java/com/revenuecat/purchases/PurchasesFactoryTest.kt
- purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesConfigureTest.kt
- purchases/src/testDefaults/kotlin/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallActivity.kt
In here we store the latest known state for `Purchases` so we can reconfigure when displaying the `PaywallActivity` and the SDK is not configured. This may happen if the app is killed while displaying the `PaywallActivity`, the developer is not configuring in the application but on an activity and the user returns through the app through the recent apps menu.
Additionally, it includes the changes from #1866 so we avoid reconfiguring the SDK if the configuration parameters are the same.
> Save SDK configuration on paywall activity so it can reconfigure automatically

- purchases/src/androidTest/kotlin/com/revenuecat/purchases/purchasesExtensions.kt
- purchases/src/customEntitlementComputation/kotlin/com/revenuecat/purchases/Purchases.kt
- purchases/src/defaults/kotlin/com/revenuecat/purchases/Purchases.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/AppConfig.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/HTTPClient.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/utils/IsDebugBuildProvider.kt
- purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
- purchases/src/test/java/com/revenuecat/purchases/PurchasesCanMakePaymentsTest.kt
- purchases/src/test/java/com/revenuecat/purchases/PurchasesFactoryTest.kt
- purchases/src/test/java/com/revenuecat/purchases/PurchasesLifecycleTest.kt
- purchases/src/test/java/com/revenuecat/purchases/backend_integration_tests/BaseBackendIntegrationTest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/AppConfigTest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/BaseHTTPClientTest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerTest.kt
- purchases/src/test/java/com/revenuecat/purchases/utils/IsDebugBuildProviderTest.kt
- purchases/src/testDefaults/kotlin/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt
As the title says. Quite a few changed files. Here's what's new: 
- `AppConfig` has a new `isDebugBuild` property.
- `HTTPClient` reads this property and sets the `X-Is-Debug-Build` header accordingly.
- `PurchasesFactory` uses the new `IsDebugBuildProvider` to determine the `isDebugBuild` property when it creates the `AppConfig`. 
- `AppConfigTest` is adjusted.
- There's a new `HTTPClientTest` case. 
- `IsDebugBuildProviderTest` was added.
iOS implementation: https://github.com/RevenueCat/purchases-ios/pull/4364
> Adds X-Is-Debug-Build header

- purchases/consumer-rules.pro
As the title says. This rule will normally have no effect as we don't declare the `org.json:json` dependency, but some apps do (transitively). In that scenario, this rule avoids `NoSuchMethodError`s and `NoSuchFieldError`s. 
**Note:** I gave this the `pr:fix` label, as it will fix the issue reported in [this Zendesk ticket](https://revenuecat.zendesk.com/agent/tickets/47240). Let me know if you think we should give it another label instead.
> Keeps the org.json package.

- purchases/src/main/kotlin/com/revenuecat/purchases/common/Dispatcher.kt
**Note:** this PR is intended as more of a discussion starter, which is why it's a draft.
We sometimes come across issues where the SDK seems to hang. This is annoying to investigate, as no error is logged (nor does it crash). See e.g.:
- https://github.com/RevenueCat/react-native-purchases/issues/1088
- [Zendesk: My paywall on android does not load when the app is not in debuggable mode](https://revenuecat.zendesk.com/agent/tickets/47240)
I found one cause of hanging while investigating the second issue. Errors can be swallowed by the `Dispatcher`, as it only rethrows `Exception`s. However, not all errors are `Exception`s. An example of an error which is a `Throwable` but not an `Exception` is a [`NoSuchMethodError`](https://developer.android.com/reference/java/lang/NoSuchMethodError). …
> Dispatcher catches and rethrows Throwable instead of Exception to avoid swallowing errors

- api-tester/src/defaults/java/com/revenuecat/apitester/java/PurchasesAPI.java
- api-tester/src/defaults/java/com/revenuecat/apitester/java/RedeemWebPurchaseListenerAPI.java
- api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/IntentExtensionsAPI.kt
- api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
- api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/RedeemWebPurchaseListenerAPI.kt
- examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/MainActivity.kt
- examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OverviewFragment.kt
- purchases/src/defaults/kotlin/com/revenuecat/purchases/IntentExtensions.kt
- purchases/src/defaults/kotlin/com/revenuecat/purchases/Purchases.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/WebPurchaseRedemption.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/Backend.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/errors.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/networking/RCHTTPStatusCodes.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/deeplinks/DeepLinkParser.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/deeplinks/WebPurchaseRedemptionHelper.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/errors.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/interfaces/RedeemWebPurchaseListener.kt
- purchases/src/test/java/com/revenuecat/purchases/common/backend/BackendRedeemWebPurchaseTest.kt
- purchases/src/test/java/com/revenuecat/purchases/deeplinks/WebPurchaseRedemptionHelperTest.kt
- purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesTest.kt
This adds some new result types to a web purchase redemption:
- InvalidToken
- AlreadyRedeemed
- Expired. This one includes additional information like the obfuscated email where a new token was/will be sent and whether that email was sent.
This falls behind the experimental APIs introduced in #1889 
Additionally, this renames `parseAsDeepLink` to `parseAsWebPurchaseRedemption` and removes the `DeepLink` type. This is a breaking change, but should be ok since the API is marked as experimental and not usable still by any customers.
> Add extra error cases for web purchases redemptions

- purchases/src/main/kotlin/com/revenuecat/purchases/google/attribution/GoogleDeviceIdentifiersFetcher.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/strings/AttributionStrings.kt
Reported in https://github.com/RevenueCat/purchases-android/issues/1913
Looks like https://github.com/RevenueCat/purchases-android/commit/84874c940d3e2f60c87455db36760a36fb9dc704 surfaced this issue and might be the cause for many hangs in React Native
> Catch `NoSuchMethodError` on Ads library

- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/ButtonComponent.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/ImageComponent.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/PackageComponent.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/PurchaseButtonComponent.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/StackComponent.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/StickyFooterComponent.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/TextComponent.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/common/Background.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/common/ComponentOverrides.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/common/ComponentsConfig.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/common/Localization.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/common/PaywallComponentsData.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Border.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/ColorInfo.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/CornerRadiuses.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Dimension.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/ImageUrls.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/MaskShape.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Padding.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Shadow.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Shape.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Size.kt
Adds `@JvmSynthetic` to all public and internal Paywall Components fields to minimize the Java API. (Kotlin's `internal` visibility becomes `public` in Java.)
> [Paywalls V2] Minimizes Java API

- purchases/src/main/kotlin/com/revenuecat/purchases/common/FileHelper.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizer.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/events/PaywallEventsManager.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/utils/EventsFileHelper.kt
- purchases/src/test/java/com/revenuecat/purchases/common/FileHelperTest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsFileHelperTest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizerTest.kt
`Stream` is a Java 8 API, which needs [desugaring](https://developer.android.com/studio/write/java8-support) to function correctly across devices and API levels. This can lead to crashes such as https://github.com/RevenueCat/purchases-flutter/issues/1213, which is only surfacing now because we fixed error-swallowing in https://github.com/RevenueCat/purchases-android/pull/1894.
Fortunately, Kotlin's `Sequence` is a near drop-in replacement for `Stream`. This PR implements that replacement.
> Uses `Sequence` instead of `Stream` to avoid errors due to unavailable Java 8 APIs

- .circleci/config.yml
- purchases/src/androidTest/kotlin/com/revenuecat/purchases/BasePurchasesIntegrationTest.kt
Integration tests have been failing pretty frequently. From some tests, it seems that verifying the purchase token in the backend after a while takes a bit longer, which makes it frequently go over the timeout limit of 5s set for purchasing. This increases the timeout so it has time to finish the purchase on those situations.
> Increase integration test timeout

- api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/IntentExtensionsAPI.kt
- examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/MainActivity.kt
- examples/web-purchase-redemption-sample/src/main/java/com/revenuecat/webpurchaseredemptionsample/MainActivity.kt
- purchases/src/defaults/kotlin/com/revenuecat/purchases/IntentExtensions.kt
- purchases/src/defaults/kotlin/com/revenuecat/purchases/Purchases.kt
This modifies the `Intent.parseAsWebPurchaseRedemption()` method to `Intent.asWebPurchaseRedemption()` following the naming of the API in the iOS SDK, so we consolidate them. This is a breaking change but this is an experimental API not open to developers yet so it should be safe.
> Modify intent extension API to parse redemption links to mimick iOS

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/text/TextComponentView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/IntroEligibilityStateView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/Markdown.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template1.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template2.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template3.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template4.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template5.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template7.kt
This adds support for Markdown inside the text component of paywalls V2. Here you can see the text component previews before (top) and after (bottom)
> [Paywalls V2] Add support for markdown in text component

- purchases/src/androidTestDefaults/kotlin/com/revenuecat/purchases/PurchasesIntegrationTest.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/networking/RCHTTPStatusCodes.kt
This adds a couple tests verifying that the RC servers can be reached and that an unknown host returns an unknown host error as expected. This is an attempt to debug some flakyness we're experiencing in our integration tests in Firebase test labs.
> Add reachability tests to integration tests

- api-tester/src/defaults/java/com/revenuecat/apitester/java/RedeemWebPurchaseListenerAPI.java
- api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/RedeemWebPurchaseListenerAPI.kt
- examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OverviewFragment.kt
- examples/web-purchase-redemption-sample/src/main/java/com/revenuecat/webpurchaseredemptionsample/Content.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/Backend.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/errors.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/interfaces/RedeemWebPurchaseListener.kt
- purchases/src/test/java/com/revenuecat/purchases/common/backend/BackendRedeemWebPurchaseTest.kt
- purchases/src/test/java/com/revenuecat/purchases/deeplinks/WebPurchaseRedemptionHelperTest.kt
We decided to rename this redemption result value to better represent the meaning of the result. Note that the API is marked as experimental and the feature is still not enabled in our backend, so it should be ok to rename it.
> WebPurchaseRedemption: Rename `AlreadyRedeemed` result to `PurchaseBelongsToOtherUser`

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/image/ImageComponentView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/ktx/ThemeImageUrls.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/modifier/Overlay.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/modifier/Size.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/StackComponentView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/ImageComponentStyle.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/RemoteImage.kt
This adds a new component `ImageComponentView` and the corresponding `ImageComponentStyle`. It doesn't include transformations from `ImageComponent` to `ImageComponentStyle`.
- Placeholder to image loading:
https://github.com/user-attachments/assets/ae010171-2ae4-4d82-b84c-68fa9015d2bd
- Previews
> [Paywalls V2] Adds `ImageComponentView`

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/OfferingToStateMapper.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallDataValidationTest.kt
There was validation that was preventing image from being optional in multi-tier paywall
- Remove error from being throw when no multi-tier paywall image and do a warning log instead
> Fix multi-tier template to allow optional header image

- api-tester/src/defaults/java/com/revenuecat/apitester/java/PurchasesAPI.java
- api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
- purchases/src/defaults/kotlin/com/revenuecat/purchases/Purchases.kt
- purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesTest.kt
In order to support the hybrids, getting the url from an intent might not always be easy. This adds an overload to the parsing method so we can obtain the `WebPurchaseRedemption` object from a string URL.
> Add web redemption parse method for strings to support hybrids

- purchases/src/defaults/kotlin/com/revenuecat/purchases/Purchases.kt
Followup to #1972, this makes sure we handle issues when parsing URLs if any. It should normally not happen though, but better to be defensive.
> Parse web redemption link strings more defensively

- purchases/src/main/kotlin/com/revenuecat/purchases/Offering.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/OfferingParser.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/LoadingPaywall.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModel.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/testdata/TestData.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/OfferingToStateMapper.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/PaywallValidationResult.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/LegacyPaywallDataValidationTest.kt
- Adds `PaywallComponentsData` to `Offering`.
- `OfferingParser` parses `paywall_components` into `PaywallComponentsData`.
- `PaywallViewModel` emits `PaywallState.Loaded.Components` if it encounters an `Offering` with `PaywallComponentsData`
- `PaywallValidationResult` is a `sealed interface` now.
- Renames a few existing functions to indicate they handle the "legacy" `PaywallData`.
- Renames `PaywallDataValidationTest` to `LegacyPaywallDataValidationTest`.
> [Paywalls V2] Adds `PaywallComponentsData` to `Offering`

- purchases/src/main/kotlin/com/revenuecat/purchases/common/errors.kt
Currently these error codes would display in the API as "UnknownBackendError". This performs some better processing of these error codes.
> [WEB-1757] Handle new backend error codes that may show in the redemption endpoint

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/PaywallAction.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/button/ButtonComponentView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/ButtonComponentStyle.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/button/ButtonComponentViewTests.kt
This PR does 2 things:
- Makes `ButtonComponentStyle`'s `actionHandler` a suspendable function, and disables the button clickability until previous taps have finished processing.
- Adds `PurchasePackage` to the available `PaywallAction` sealed interface.
> [PaywallsV2] Improve `ButtonComponentView` to handle disabling the button and add `PurchasePackage` action

- purchases/build.gradle
- purchases/src/main/kotlin/com/revenuecat/purchases/common/OfferingParser.kt
Since the iOS closed beta is coming up, I thought it'd be good to be extra careful about parsing the `paywall_components` JSON, as more people will soon have the ability to create those via the dashboard.
To enable, add the following line to your `local.properties` file in the root of the repo:
```properties
revenuecat.flag.paywallComponents=true
```
To disable, set it to false, or remove the line entirely.
> [Paywalls V2] Adds a `FLAG_PAYWALL_COMPONENTS` build flag

- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/ButtonComponent.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/ComponentView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/LoadedPaywallComponents.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stickyfooter/StickyFooterComponentView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/StickyFooterComponentStyle.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/StyleFactory.kt
This PR adds `StickyFooterComponentView` to our components
> [Paywalls V2] Add `StickyFooterComponentView`

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/LoadedPaywallComponents.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/ButtonComponentStyle.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/StyleFactory.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/StackComponentViewTests.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/StyleFactoryTests.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/text/TextComponentViewTests.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/text/TextComponentViewWindowTests.kt
Adds support for the `PurchaseButtonComponent`, which maps to a normal `ButtonComponentView` for now. We also pass action and actionhandler from the style factory, which might also change once we move more logic to the VM.
> [Paywalls V2] Add `PurchaseButtonComponent` support

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/image/ImageComponentView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/RemoteImage.kt
This has 2 main changes:
- Adds one more preview for `ImageComponentView` that verifies how it looks when the dimension size is `Fit` (which translates to the image size) but the parent is smaller than the image.
- Adds one more parameter to `RemoteImage` and `LocalImage` that allows to set an optional preview resource drawable.
> [Paywalls V2] Add more image component previews to test parent being smaller than image size

- purchases/src/androidTest/kotlin/com/revenuecat/purchases/ErrorsTest.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/errors.kt
> Make `PurchasesError` `java.io.Serializable`

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/image/ImageComponentState.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/image/ImageComponentView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/modifier/AspectRatio.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/RemoteImage.kt
The current mechanisms to show remote images in Compose Previews did not allow us to specify the size of the remote image. The replacement image was a solid color or a vector drawable, both of which resize uniformly to the view they're displayed in. However, in the real world, Paywalls V2 will receive images with a fixed size. We needed a way to preview resizing and scaling behavior with these kinds of images.
This PR adds a new `previewImageLoader` parameter, which can be used to return whatever kind of image we want. This is then used in `ImageComponentView` previews to check its behavior for images with a fixed size. It's slightly hacky, but the upside is that it will only run in the preview environment. The alternative approach involves updating to Coil 3 …
> [Paywalls V2] Improves image previews

- purchases/src/main/kotlin/com/revenuecat/purchases/errors.kt
Addressing #2037
This makes it so the message is not part of the serialization, since it's not needed
> Convert error message property into computed property

- purchases/src/main/kotlin/com/revenuecat/purchases/CustomerInfo.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/EntitlementInfo.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/SubscriptionInfo.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/CustomerInfoFactory.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/EntitlementInfoFactories.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/responses/SubscriptionInfoResponse.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/utils/EntitlementInfoHelper.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/utils/serializers/ISO8601DateSerializer.kt
- purchases/src/test/java/com/revenuecat/purchases/EntitlementInfoHelperTest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/CustomerInfoTest.kt
- purchases/src/test/java/com/revenuecat/purchases/utils/Responses.kt
We had more information we were not exposing in the CustomerInfo JSON
This PR adds `CustomerInfo.subscriptionsByProductIdentifier` which has some useful information for devs that don't use the entitlements system
https://github.com/RevenueCat/purchases-ios/pull/4508
> Add `subscriptionsByProductIdentifier` to `CustomerInfo`

- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/CornerRadiuses.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/button/ButtonComponentView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/StackComponentState.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/StackComponentView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/StackComponentStyle.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/StyleFactory.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/button/ButtonComponentViewTests.kt
Follow-up to #2009 
This PR adds the `edgeToEdge` top/bottom style for badges.
> [Paywalls V2] Add `Badge`'s `edgeToEdge` `Top`/`Bottom` alignment style layout

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/StackComponentView.kt
Followup to #2009 and #2039.
This adds support for `nested` style badges.
As discussed over Slack, the nested badges won't move the content of the stack, and just be placed on top.
> [Paywalls V2] Add `Badge`'s `nested` style layout

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/image/ImageComponentView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/ktx/Shape.kt
As the title says. Implementation is the same as [the dashboard](https://github.com/RevenueCat/revenuecat-app/blob/main/src/concepts/projects/paywall-builder/components/previewer/components/image.tsx#L88-L115), except it uses a relative offset (0.2 x height) instead of a fixed one (27 px).
> [Paywalls V2] Implements `Convex` and `Concave` image masks

- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/common/ComponentOverrides.kt
- purchases/src/test/java/com/revenuecat/purchases/paywalls/components/common/ComponentOverridesTests.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/PresentedPartial.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/image/ImageComponentState.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/StackComponentState.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/text/TextComponentState.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/text/TextComponentView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallState.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/assertions/assertPixelColorEquals.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/BuildPresentedPartialTests.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/ToPresentedOverridesTests.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/StackComponentViewTests.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/text/TextComponentViewTests.kt
Intro offer eligibility was not properly hooked up yet to the override system, and it was using the iOS concept of at most being eligible for a single offer. This PR ensures the offer eligibility follows the Android model of potentially being eligible for multiple offers, and hooks it up to the override system. 
A bunch of the added lines are tests.
> [Paywalls V2] Handles intro offer eligibility overrides

- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/MaskShape.kt
- purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/MaskShapeTests.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/image/ImageComponentView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/ktx/Shape.kt
`Circle` is the new `Pill`. See https://github.com/RevenueCat/purchases-ios/pull/4674#discussion_r1917238488 for context.
> [Paywalls V2] Removes `MaskShape.Pill` in favor of `MaskShape.Circle`.

- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/identity/IdentityManager.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/strings/IdentityStrings.kt
- purchases/src/test/java/com/revenuecat/purchases/identity/IdentityManagerTests.kt
Until now, when devs enabled Trusted Entitlements, we would clear the cached `CustomerInfo` and customers would need to refetch the latest value from the server, which could potentially cause delays and/or losing access temporarily.
With this PR, we won't be clearing the cached CustomerInfo anymore. Instead, we would return the cached customer info, which will have a `VerificationResult` of `NOT_REQUESTED`.
> [Trusted Entitlements] Do not clear CustomerInfo upon enabling Trusted Entitlements

- purchases/src/main/kotlin/com/revenuecat/purchases/EntitlementVerificationMode.kt
- purchases/src/test/java/com/revenuecat/purchases/PurchasesConfigurationTest.kt
This enables Trusted Entitlements by default. Behavior won't change for devs not check the verification result, but this will make it much easier to use in the future, as all SDK versions have it enabled.
This should be merged after #2049.
> [Trusted Entitlements] Enable `Trusted Entitlements` by default

- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/PaywallComponent.kt
- purchases/src/test/java/com/revenuecat/purchases/paywalls/components/FallbackComponentTests.kt
As the title says. Adds a custom serializer that looks for a `fallback` key if the `type` is unknown. 
This is the Android equivalent of https://github.com/RevenueCat/purchases-ios/pull/4621.
> [Paywalls V2] Adds support for fallback components

- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/CornerRadiuses.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/MaskShape.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Shape.kt
- purchases/src/test/java/com/revenuecat/purchases/paywalls/components/ImageComponentTests.kt
- purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/CornerRadiusesTests.kt
- purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/MaskShapeTests.kt
- purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/ShapeTests.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/LoadedPaywallComponents.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/button/ButtonComponentView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/ktx/Shape.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/StackComponentView.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/button/ButtonComponentViewTests.kt
This adds the remaining `edgeToEdge` style layouts for the badge, including leading and trailing
> [Paywalls V2] Add `edgeToEdge` badge trailing/leading style layout

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/image/ImageComponentView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/StackComponentView.kt
- In Overlay style badges, the badge will now be placed in the middle of the border if any.
- In Nested style badges, we fix an issue where the border width wasn't added as padding, so the border was drawn on top of the stack content. This also means the badge is now placed inside the border.
> [Paywalls V2] Badge: Handle main stack border width correctly in overlay and nested badge styles

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/StackComponentView.kt
This changes the `edgeToEdge` top and bottom badge extend to the whole parent stack
> [Paywalls V2] Make `edgeToEdge` top/bottom badge extend to entire stack background

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/views/ManageSubscriptionsView.kt
As the title says. These are just some suggestions. Feel free to ignore.
- Uses `TextButton`s instead of primary `Button`s, and places them on a `Surface`. (The latter is more of an artistic choice haha.)
- Uses the `titleLarge` style for the screen title, following the [guidelines](https://m3.material.io/styles/typography/applying-type#e9e0cea3-10cb-405d-98a9-cf6a90758967). 
- Updates spacing. 
- Removes the shadow from the top card, as elevation is not often shown with shadows in Material 3. 
|-------|------|
|  ![image](https://github.com/user-attachments/assets/a58d6f6e-0503-432f-b454-55a725f4f547)  | ![image](https://github.com/user-attachments/assets/77f9c8b0-fb61-4f33-9480-8a38555a1255) |
> Some Material 3 updates to the `ManageSubscriptionsView`

- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/MainActivity.kt
While debugging some theming issues in PaywallsTester, I noticed that the entire app composable is wrapped in a `Surface`.  This turned out not to be the cause of the issue, but it made my spidey sense tingle, as `Surface` overrides the `LocalContentColor` of its children. To avoid potential issues, and confusion / red-herring-chasing in the future, I figured we can change this to a `Box` with a `.background()`.
> `PaywallTesterApp` is no longer wrapped in a `Surface`

- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/MainActivity.kt
- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/main/offerings/OfferingsScreen.kt
- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/theme/Theme.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/customercenter/CustomerCenterConfigData.kt
- purchases/src/test/java/com/revenuecat/purchases/common/backend/BackendGetCustomerCenterConfigTest.kt
- purchases/src/test/resources/get_customer_center_config_success.json
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/InternalCustomerCenter.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/SubscriptionDetailsView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/actions/CustomerCenterAction.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/CustomerCenterConfigTestData.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/PurchaseInformation.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/viewmodel/CustomerCenterViewModel.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/views/ManageSubscriptionsView.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/PurchaseInformationTest.kt
If the active purchase is not from Google, we just display a button for Managing subscriptions and another one for contacting support. Although this should probably be configurable from the dashboard, this is the same we do in iOS atm.
> Add support to manage non-Google purchases in Customer Center

- purchases/src/test/java/com/revenuecat/purchases/paywalls/PaywallColorTest.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/InternalCustomerCenter.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/CustomerCenterConfigDataExtensions.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/views/ManageSubscriptionsView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/views/PromotionalOfferView.kt
For this configuration:
This is how it's built:
| Light | Dark |
|--------|--------|
| <img width="428" alt="Screenshot 2025-01-30 at 19 47 34" src="https://github.com/user-attachments/assets/71f2f780-0c7c-44e4-9b5b-bbc2d86774d9" /> | <img width="427" alt="Screenshot 2025-01-30 at 19 41 27" src="https://github.com/user-attachments/assets/2181e950-dd55-476f-aafe-35d20fe102bc" /> |
| <img width="427" alt="Screenshot 2025-01-30 at 19 47 02" src="https://github.com/user-attachments/assets/8a65403c-ed81-40b1-8d48-7e9ec77ee790" /> | <img width="431" alt="Screenshot 2025-01-30 at 19 46 19" src="https://github.com/user-attachments/assets/752e0651-c2b0-431e-b1d5-7bc393b56db9" /> |
| <img width="423" alt="Screenshot 2025-01-30 at 19 48 01" …
> Customer Center use remote appearance config

- examples/web-purchase-redemption-sample/src/main/java/com/revenuecat/webpurchaseredemptionsample/Constants.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/EntitlementInfo.kt
- purchases/src/test/java/com/revenuecat/purchases/common/backend/BackendRedeemWebPurchaseTest.kt
RevenueCat Billing product is being renamed to Web Billing
- Rename "RevenueCat Billing"/"RC Billing" to "Web Billing" in a couple of places. 
- Store enum remains unchanged
> Rename to Web Billing

- examples/purchase-tester/src/main/res/layout/row_view.xml
As the title says. It can be seen in CI on `main` [here](https://app.circleci.com/pipelines/github/RevenueCat/purchases-android/13468/workflows/24e8614e-be03-41fa-9bc7-58d670905a91/jobs/62094). 
>warning: ERROR: View field header collides with a variable or import file://examples/purchase-tester/src/main/res/layout/row_view.xml Line:19
> Fixes "View field header collides with a variable" data binding error in PurchaseTester

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/InternalCustomerCenter.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/CustomerCenterState.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/viewmodel/CustomerCenterViewModel.kt
Touching the `X` navigation button in the promotional offer closes the whole Customer Center, this PR modifies that behavior and adds a way to override what the X does. In the case of the promotional offer, it should call `dismissPromotionalOffer` which effectively calls the main action that the user triggered (like Cancel Purchase)
Also fixes another bug related to promotional offers, when the promo offer can't be loaded, it wasn't triggering the main path either, it was not doing anything.
> Fixes `X` in promo offer not dismissing the promo

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/properties/FontSpec.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/text/TextComponentView.kt
Remove `cursive` as a generic font to match with what is possible with other platforms (iOS)
(Above)
> [Paywalls V2] Remove cursive as a generic font

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/InternalCustomerCenter.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/dialogs/RestorePurchasesDialog.kt
Hide the contact support button if the email is not set in CustomerCenter
> fix: Hide contact support if there's no email

- purchases/src/main/kotlin/com/revenuecat/purchases/common/events/BackendStoredEvent.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/events/EventsManager.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/customercenter/events/CustomerCenterSurveyOptionChosenEvent.kt
- purchases/src/test/java/com/revenuecat/purchases/common/events/EventsManagerTest.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/viewmodel/CustomerCenterViewModel.kt
This is a follow-up of https://github.com/RevenueCat/purchases-android/pull/2124
- Address typo
- Address wrong documentation
> fix: Address typo and wrong doc for CustomerCenter events

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/StackComponentView.kt
A number of components clip their contents so they don't go out of bounds of the component itself. This is a problem for the `StackComponent` since sometimes we want shadows of children or other elements to extend beyond the bounds of the stack itself. An example of this, is with overlaid badges.
This PR removes the clipping of the stack component itself except when there is a Leading/Trailing EdgeToEdge badge or Nested badge, in which we actually need to clip.
| ---- | ---- |
| ![image](https://github.com/user-attachments/assets/dbc1aa52-4c18-47de-bb67-6366531d4aae) | ![image](https://github.com/user-attachments/assets/c128a9a3-4480-4846-8033-f083fcd352ca) |
| <img width="303" alt="image" src="https://github.com/user-attachments/assets/87d952fc-4857-4d4a-857a-b78bdda564 …
> [Paywalls V2] Fix stack clipping issues

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/InternalCustomerCenter.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/views/PromotionalOfferScreen.kt
The OutlineButton does not offer a way of customizing it.
This PR replaces OutlineButton with TextButton, and uses localization instead of a hardcoded string.
> fix: Use TextButton instead of outline for Promotionals

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/image/ImageComponentView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/modifier/Border.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/modifier/Shadow.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/properties/BackgroundStyle.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/properties/ColorStyle.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/text/TextComponentView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/timeline/TimelineComponentView.kt
This PR does 2 things:
- Ensures the angle is consistent, even if the area is not square.
- Ensures the interpretation of the angle is consistent with CSS' [`linear-gradient`](https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/linear-gradient). It's not a 100% 1 to 1, but it's close I think. 
| CSS | purchases-android |
|-----|--------------------|
| ![image](https://github.com/user-attachments/assets/cfb40af1-c64b-4c68-a790-24e49503cea2) | ![image](https://github.com/user-attachments/assets/1b497849-bb43-4069-a29c-41f567b4ae02) |
| ![image](https://github.com/user-attachments/assets/3e3e008a-d3cc-438f-8de1-5e89c9e9c119) | ![image](https://github.com/user-attachments/assets/d37c33f4-3093-4581-8657-84a1d2ab9f60) |
| ![image](https://github.com/user-attachments/assets/65a18385-2100-4c …
> [Paywalls V2] Makes linear gradients consistent with CSS

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/StackComponentView.kt
Fixes an issue with sizing of stacks that have nested badges. The padding wasn't applied in the correct place
| ----- | ----- |
| <img width="353" alt="image" src="https://github.com/user-attachments/assets/5d6f42fa-5ddb-4701-9e4b-c9a6bb8500fe" /> | <img width="354" alt="image" src="https://github.com/user-attachments/assets/3f2b85b7-3f31-4286-98f3-6a6bfc57fe14" /> |
> [Paywalls V2] Fix issue with sizing of stacks with nested badges

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/CustomerCenterUIConstants.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/CustomerCenterConfigTestData.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/views/ManageSubscriptionsView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/views/PromotionalOfferScreen.kt
| Before | After | 
|--------|-----|
| <img width="617" alt="Screenshot 2025-02-12 at 14 43 37" src="https://github.com/user-attachments/assets/12a8407c-dcba-4cd7-a101-c7d32e9a1c5c" /> | ![image](https://github.com/user-attachments/assets/9a75f998-169a-4b48-973b-fa1a800b8556) |
This pull request includes several updates to the `CustomerCenterUIConstants`, `CustomerCenterConfigTestData`, and `ManageSubscriptionsView` files to improve UI consistency and update text for better clarity.
* Added a new padding value `PaddingLarge` and updated the padding for `ContentUnavailableViewPaddingTopDescription` to use `PaddingLarge` instead of `PaddingMedium`. (`[[1]](diffhunk://#diff-be840fca768a3e52732a6f0037def19ef22eb16112e1d11ce52ec9cf8112fbb0R15)`, …
> Updates on no active purchases screen

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/CustomerCenter.kt
Removed the `@JvmSynthetic`, `@ExperimentalPreviewRevenueCatUIPurchasesAPI`, `@SuppressWarnings("PreviewPublic")`, and `@InternalRevenueCatAPI` annotations to make the CustomerCenter public
> Make `CustomerCenter` public

- api-tester/build.gradle
- api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/revenuecatui/PaywallColorAPI.kt
- feature/amazon/build.gradle
- purchases/build.gradle
- ui/debugview/build.gradle
- ui/revenuecatui/build.gradle
As the title says. This makes Android Studio recognize this as the default too, which should reduce errors caused by mismatched variants. (For instance, previews in `revenuecatui` break if its selected variant doesn't match `purchases`.)
> Explicitly sets the `defaults` flavor as the default.

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/StackComponentState.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/StackComponentView.kt
This was a though one. The cause of this is twofold:
1. `Column` and `Row` don't draw anything without children. Fixed by checking for this case and using a `Box` instead.
2. A `margin` would eat away the available space, making the divider invisible even with problem 1 fixed. This is fixed by adjusting the `size` for the `margin`. 
Fixes [MON-917](https://linear.app/revenuecat/issue/MON-917).
> [Paywalls V2] Fixes empty stacks not showing up.

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/pkg/PackageComponentView.kt
This has the desired effect of not being able to "select" a singular package on a paywall, without having to traverse the tree. It also avoids [the potentially confusing case of trying to reselect an already selected package](https://revenuecat.slack.com/archives/C07H5S8CFL3/p1739371997220059).
> [Paywalls V2] Disables the click handler for the selected package

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/StackComponentView.kt
We were not applying the main stack's margin to the `Overlaid` badges. This means that the badges could look like they were outside the main stack. I think it makes sense that we apply the main stack margins to the badge as well.
> [Paywalls V2] Apply stack margins to overlay badges

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/properties/BackgroundStyle.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/RemoteImage.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/CoilImageLoader.kt
This is an attempt to fix an issue where some icon images where failing to load. Our theory is that the ImageLoader was getting deallocated, since it seemed the connection was getting closed. I haven't been able to reproduce though, so not sure if this will fix it. A couple things to consider:
- We are only using a single ImageLoader when fetching the images, we are still using multiple image loaders to predownload the images. Plan to address this later
- I noticed for images when cache is disabled, we're not setting the loader which in effect, would fallback to the "default" image loader. We might want to fix that at some point as well.
> [Paywalls V2] Refactor to use a single ImageLoader singleton in RevenueCatUI

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/StackComponentView.kt
As the title says. This caused the items to be spaced further apart than desired.
> [Paywalls V2] Fixes the top system bar padding being applied to all children in a vertical container

- purchases/src/main/kotlin/com/revenuecat/purchases/common/Backend.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/CustomerInfoFactory.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/JsonHelper.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/JsonProvider.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/events/EventsRequest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/backend/BackendPaywallEventTest.kt
- purchases/src/test/java/com/revenuecat/purchases/paywalls/events/PaywallEventsRequestSerializationTest.kt
As promised to @tonidero and @JayShortway, here's a `JsonHelper` that unifies Json use.
This PR introduces `JsonProvider`, and a `defaultJson`. 
> Sadly, `classDiscriminator` cannot be dynamic so we need one per discriminator (paywalls will need one)
> chore: Unify Json encoding with JsonHelper

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/StackComponentView.kt
With distribution `SPACE_AROUND` or `SPACE_EVENLY` we were still adding some spacers to the sides with `weight(1f)` even if some children had size `Fill`. This makes it so we don't add any of those when any children has `Fix` in the main axis of the stack.
> [Paywalls V2] Fix wrong spacers in Stack when some children are Fill

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/viewmodel/CustomerCenterViewModel.kt
We were not returning the updated state when loading the promotional offer, so it was effectively never been set in the state
> Fix promotional offer not being displayed

- .circleci/config.yml
- examples/paywall-tester/build.gradle
We had minification disabled in paywall tester, which allowed us to miss the issue fixed in #2176. This enables it so CI picks up future issues with our UI module, which aren't caught by purchase tester. It also adds a job to be run as part of the tests building the paywall tester app.
> Enable paywall tester minification

- purchases/src/main/kotlin/com/revenuecat/purchases/common/events/BackendStoredEvent.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/events/EventsManager.kt
- purchases/src/test/java/com/revenuecat/purchases/common/events/EventsManagerTest.kt
This PR enables customer center tracking. We missed it because the tests were only checking for paywalls, but now the modified test checks for both.
> fix: Track customer center events

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/InternalCustomerCenter.kt
This PR is a follow-up of https://github.com/RevenueCat/purchases-android/pull/2168
To properly tackle the regression, we're now adding a preview to make sure we don't miss this in the future
> chore: Introduce preview for no active subscriptions

- .circleci/config.yml
We have a bunch of workflows that check if the `pipeline.trigger_source` is **not** `scheduled_pipeline`. These will all be triggered when triggering workflows from the API, however, which is not what we want. This PR adds an additional check to make sure that the `action` is `default`. 
We've added a CI workflow that updates the Paywalls v2 template previews in [#2192](https://github.com/RevenueCat/purchases-android/pull/2192), which will be triggered from khepri. We don't want to trigger all the other workflows together with that.
> Avoids triggering "unscheduled" workflows when triggering workflows via the CircleCI API

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/button/ButtonComponentView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/properties/ColorStyle.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/StackComponentView.kt
This is the Android equivalent of https://github.com/RevenueCat/purchases-ios/pull/4787. 
This adds a progress indicator to the `ButtonComponentView`. It calculates the indicator color in the same way as we do on iOS. I created a new `GradientBrush` intermediate type that allows for reading the gradient colors after the brush has been constructed. This is used to determine the progress indicator color when the `StackComponentView` has a gradient background.
I didn't want to add the logic to  `StackComponentView`, as that one is big enough already, and my first attempt at doing so resulted in multiple layout issues. Also, ideally it is unaware of the progress indicator. Perhaps in the future, we can add a slot API to `StackComponentView`, but we're not there yet.
> [Paywalls V2] Adds progress indicator to buttons

- purchases/src/main/kotlin/com/revenuecat/purchases/common/events/BackendEvent.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/events/BackendStoredEvent.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/customercenter/events/CustomerCenterSurveyOptionChosenEvent.kt
- purchases/src/test/java/com/revenuecat/purchases/backend_integration_tests/ProductionBackendEventsTest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/events/EventsManagerTest.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/viewmodel/CustomerCenterViewModel.kt
This is the counterpart of https://github.com/RevenueCat/purchases-ios/pull/4837
`survey_option_title_key` is ignored in the backend, so there's no need to have it here. 
This PR removes it and adds a test that verifies backwards compatibility with stored events. However, I think we should move to an implementation similar to iOS, where the StoredEvents contains an already encoded version of the event. That would remove any need to test backwards compatibility.
> chore: Delete key from customer center survey event

- ui/revenuecatui/src/debug/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/TemplatePreviews.kt
`PaywallComponentsTemplate_Preview` has been identified as a problematic preview that crashes the Emerge emulator. Apparently we're running into this emulator crash: https://issuetracker.google.com/issues/398784711. 
I'm ignoring it to keep our shipping velocity up. I will explore rendering them outside of Emerge and then uploading them as an alternative next.
> [Paywalls V2] Ignores template previews for now.

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/Logger.kt
Our [docs](https://www.revenuecat.com/docs/test-and-launch/debugging#custom-log-handling) mention that all logs are prefixed with `[Purchases]`, but this was not actually the case. [This caused logs being missed](https://community.revenuecat.com/general-questions-7/basicc-paywall-showing-not-the-designed-v2-paywall-5979?postid=20528#post20528).
>All logs from the SDK are prepended with “[Purchases]“, you can use this string as a filter in your log output to clearly see the logs that are from Purchases.
> Logs from RevenueCatUI are now tagged with `[Purchases]` too.

- config/detekt/detekt.yml
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/iconcomponent/IconComponentView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/image/ImageComponentView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/timeline/TimelineComponentView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/RemoteImage.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/HelperFunctions.kt
This replaces the `previewImageLoader` parameter in `RemoteImage` with a `LocalPreviewImageLoader` `CompositionLocal`. This is similar to [how previews are handled in Coil 3](https://coil-kt.github.io/coil/compose/#previews).
This will be very helpful in rendering images in our template previews. Without this change, we would have to propagate the `previewImageLoader` parameter through the entire component tree, adding it to every `ComponentView`. This change avoids that, because we can just wrap our previewed composable in `ProvidePreviewImageLoader()`.
> Adds a `LocalPreviewImageLoader` `CompositionLocal`.

- api-tester/src/main/java/com/revenuecat/apitester/java/OfferingAPI.java
- api-tester/src/main/java/com/revenuecat/apitester/kotlin/OfferingAPI.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/Offering.kt
- purchases/src/test/java/com/revenuecat/purchases/OfferingsTest.kt
Checking whether an `Offering` has a paywall is not possible now that there's also v2 paywalls. Added the same property in iOS (see RevenueCat/purchases-ios/pull/4847)
This PR adds the `hasPaywall` property to `Offering` to allow knowing whether an `Offering` has a paywall or not.
> Add `hasPaywall` property to `Offering`

- .circleci/config.yml
- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ConfigurePurchasesUseCase.kt
- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/Constants.kt
- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/MainApplication.kt
- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/main/appinfo/AppInfoScreen.kt
- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/main/appinfo/AppInfoScreenViewModel.kt
This adds the ability to switch between 2 projects (API keys) to PaywallsTester. 
To be able to effectively test new paywall templates on Android. See [MON-970](https://linear.app/revenuecat/issue/MON-970) for more context and details.
I wanted to do this in the most pragmatic way possible without it being hacky, since we might be building other ways of previewing paywalls in the near future. Since the goal is to switch between 2 specific projects, I chose to support exactly that. Other options would have been to allow logging in with your account like RC Mobile, or adding your own API key in a text field, but that would have meant adding persistence. Let me know if you disagree or have other ideas! 🙏 
- `Constants.kt` now has `GOOGLE_API_KEY_A` and `GOOGLE_API_KEY_B`. The app uses `A` by …
> Adds support for switching between 2 API keys to PaywallsTester

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/CustomerCenter.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/CustomerCenterActivity.kt
Dark mode colors were not correctly applied in React Native. We needed to set the correct theme and also set the correct `LocalContentColor` based on the theme to the whole `InternalCustomerCenter` otherwise composables would default to black.
> Fix `CustomerCenterActivity` colors on dark mode

- integration-tests/proguard-rules.pro
- purchases/src/defaults/kotlin/com/revenuecat/purchases/Purchases.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/properties/BackgroundStyle.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/RemoteImage.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/PurchasesExtensions.kt
We don't want to have a dependency on our API in the Coil library, which can cause issues with some mocking libraries this hides the dependency.
> fix: Remove API dependency with Coil

- purchases/src/main/kotlin/com/revenuecat/purchases/common/HTTPClient.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/common/Localization.kt
- purchases/src/test/java/com/revenuecat/purchases/common/BaseHTTPClientTest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/FakeLocaleProvider.kt
- purchases/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
- purchases/src/test/java/com/revenuecat/purchases/paywalls/components/common/LocaleIdTests.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallState.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallStateLoadedComponentsLocaleTests.kt
A paywall with a non-default locale containing only a language would fall back to the default locale, even if the device prefers the non-default one.
This has 2 causes:
- The SDK didn't properly match against locales without a region, such as `ja`. The device would have `ja-JP` configured, and it would not pick `ja` from the paywall configuration. 
- The `X-Preferred-Locales` header was sent with locales containing dashes, but khepri expects underscores. This meant that the SDK never received any non-default locales. 
Respectively:
- The SDK now checks the "language only" variant of the locale as well.
- The SDK sends the `X-Preferred-Locales` header with underscores.
> [Paywalls V2] Fixes locales without region and `X-Preferred-Locales`

- purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/common/Localization.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallState.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/OfferingToStateMapper.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallComponentDataValidationTests.kt
This was reported here: https://github.com/RevenueCat/react-native-purchases/issues/1178#issuecomment-2710805526.
Some paywalls would fail to render due to missing variable localizations: 
>All variable localizations for locale 'de_DE' are missing.
This was caused by the fact that the network response would sometimes contain inconsistent locale ids in `components_localizations` (`de_DE`) and `ui_config.localizations` (`de`). The Android SDK would pick `de_DE` and would be unable to find the variable localizations in `ui_config.localizations`. 
This is fixed by having the SDK also check the "language only" locale id if the "full" locale id is not found.
> [Paywalls V2] Handles potential locale id inconsistency between strings and variables

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/text/TextComponentView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/Markdown.kt
Reported in the [Community](https://community.revenuecat.com/sdks-51/paywall-for-compose-multiplatform-different-text-colors-in-emulator-than-paywall-editor-text-field-to-enter-discount-code-6008). 
The text color on the paywall was influenced by the text color in the Material 3 theme.
Our annotated text in the markdown component did not properly set the color.
> [Paywalls V2] Avoids the theme from influencing the text color

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/modifier/Background.kt
There was an issue where the background painter could actually paint outside the composable itself. This fixes that by making clipping happen before painting.
| --- | --- |
| ![image](https://github.com/user-attachments/assets/3fd0bc09-94d6-4c3d-bae8-1e526f439882) | ![image](https://github.com/user-attachments/assets/60a9e2aa-8346-4b08-9896-822e84ee0cf2) |
> Fix background painting outside composable

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/HorizontalStack.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/StackComponentView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/VerticalStack.kt
This PR adds `HorizontalStack` and `VerticalStack`, which are used by `StackComponentView`. They handle the item arrangement logic, adding spacers where needed. There should be no change in functionality. Just moving stuff around.
`StackComponentView.kt` is a huge file. Moving self-contained pieces of logic out of there improves maintainability.
> [Paywalls V2] Reorganizes stack arrangement logic

- gradle.properties
Likely the result of this Gradle bug: https://github.com/gradle/gradle/issues/19750
Please thumbs up that linked bug and share with everyone!
I saw this PR https://github.com/RevenueCat/purchases-android/pull/2121 and thought I could help :)
> Set metaspace size to avoid "Daemon disappeared" failures

- gradle.properties
Likely the result of this Gradle bug:
https://github.com/gradle/gradle/issues/19750
Please thumbs up that linked bug and share with everyone!
I saw this PR https://github.com/RevenueCat/purchases-android/pull/2121 and thought I could help :)
by @runningcode in #2237
> [EXTERNAL] Set metaspace size to avoid "Daemon disappeared" failures (#2237) contributed by @runningcode

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/errors/PaywallValidationError.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/strings/PaywallValidationErrorStrings.kt
I figured this error message could better describe what the actual issue is, and how to resolve it. This hopefully reduces tickets of [people running into it](https://community.revenuecat.com/sdks-51/paywall-v2-not-being-shown-on-android-5972?postid=20850#post20850).
> [Paywalls V2] Tweaks the `MissingPackage` error message.

- api-tester/src/customEntitlementComputation/kotlin/com/revenuecat/apitester/java/PurchasesAPI.java
- api-tester/src/customEntitlementComputation/kotlin/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
- purchases/src/customEntitlementComputation/kotlin/com/revenuecat/purchases/Purchases.kt
- purchases/src/customEntitlementComputation/kotlin/com/revenuecat/purchases/PurchasesConfigurationForCustomEntitlementsComputationMode.kt
Allows for more configuration in customEntitlementComputation mode. Supersedes https://github.com/RevenueCat/purchases-android/pull/2243.
> Allows configuring `showInAppMessagesAutomatically` and `pendingTransactionsForPrepaidPlansEnabled` in customEntitlementComputation mode

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template3.kt
Landscape in Paywalls v1 Template 3 looked squished or overflowing off the edge
Force 0.5 weight on each of the columns in landscape mode
|--------|--------|
| ![Screenshot 2025-03-18 at 6 36 06 AM](https://github.com/user-attachments/assets/bb59deb4-f7e1-4f78-887f-0a31d0559ce0) | ![Screenshot 2025-03-18 at 6 41 39 AM](https://github.com/user-attachments/assets/f1d76fe8-ecc8-4985-844d-4b4d2015efcd) |
> Fix landscape mode in Paywalls v1 Template 3

- purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsEntry.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsTracker.kt
- purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsEntryTest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsFileHelperTest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerFunctionalTest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerTest.kt
This adds some new properties to diagnostics so we're able to better track events and what happens within the same session.
It also adds a small refactor to `DiagnosticsTracker` track events to avoid repetition to pass the app session id.
> [Diagnostics] Add `id` and `app_session_id` to events

- api-tester/src/defaults/java/com/revenuecat/apitester/java/PurchasesAPI.java
- api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/main/appinfo/AppInfoScreen.kt
- purchases/src/main/java/com/revenuecat/purchases/customercenter/CustomerCenterManagementOption.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/customercenter/CustomerCenterListener.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/viewmodel/CustomerCenterViewModel.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/CustomerCenterViewModelTests.kt
Equivalent of https://github.com/RevenueCat/purchases-ios/pull/4872/files adding a listener that gets triggered as soon as an option is selected
> Add `onManagementOptionSelected` to `CustomerCenterListener`

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/LocalizedTextPartial.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/properties/FontSpec.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/StyleFactory.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/Result.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallComponentDataValidationTests.kt
A customer reported their paywall failed to render with the following validation error in the logs: 
> Aliased font ‘’ does not exist.
The real cause seems to be on the dashboard, as their paywall was able to be published without any Font family selected: 
While this is ideally fixed on the dashboard, this PR introduces a behavior change in the SDK that will treat this situation as "no font selected". The SDK now ignores blank font aliases. This is a bit more defensive and less strict, but still valid behavior imo.
> [Paywalls V2] Ignores missing font alias if it's blank.

- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsFileHelper.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizer.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsTracker.kt
- purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizerTest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerTest.kt
With all the new events we've been adding, we can potentially reach the file size limit much more easily, specially considering we only sync once per app open. This changes the logic, so we also sync if, after tracking an event, the file reaches a lower file size than the maximum. This should help us receiving events more frequently and avoid losing those events.
> [Diagnostics] Sync diagnostics if file reaches lower limit

- fastlane/Fastfile
I'm sure I tested this, but when running from `main` I got a "[No such file or directory](https://app.circleci.com/pipelines/github/RevenueCat/purchases-android/14671/workflows/77041cdb-1dd9-467e-9cbb-d94e4bc2a3fa/jobs/72243)" error. This PR recreates the output dir after branch switching, and that seems to fix it.
> [Paywalls V2] Fixes the update-paywall-templates job

- examples/MagicWeather/app/build.gradle.kts
- examples/purchase-tester/build.gradle
- gradle/libs.versions.toml
- integration-tests/build.gradle
- purchases/build.gradle
Starting from [Kotlin 1.4](https://kotlinlang.org/docs/reference/whatsnew14.html#dependency-on-the-standard-library-added-by-default), the dependency on the standard library added by default via `kotlin-android (org.jetbrains.kotlin.android) plugin`, so we can remove them:
> You no longer need to declare a dependency on the stdlib library in any Kotlin Gradle project, including a multiplatform one. The dependency is added by default. 
>
> The automatically added standard library will be the same version of the Kotlin Gradle plugin, since they have the same versioning.
>
> For platform-specific source sets, the corresponding platform-specific variant of the library is used, while a common standard library is added to the rest. The Kotlin Gradle plugin will select the appropriate JVM …
> Remove redundant kotlin stdlib dependencies

- .circleci/config.yml
- test-apps/testpurchasesuiandroidcompatibility/build.gradle.kts
GitHub's merge queue feature runs CI on intermediate branches with names looking like this: 
> gh-readonly-queue/main/pr-2305-de127b96b159da7def5cef15f51af329369eac92
Such a CI run is not a "PR" run, which means that the `CIRCLE_PULL_REQUEST` environment variable is not set. Fortunately we can extract the PR number from the branch name, which is implemented in this PR.
> Attempts to have Emerge Snapshots handle merge queue branches.

- gradle/libs.versions.toml
Clean up the `libs.versions.toml` file for consistency and improve readability.
- Versions have nothing changed.
- re-ordered versions & dependencies alphabetically.
- Hard-coded versions are moved to be referenced.
The result:
```toml
[versions]
agp = "8.8.0"
activityCompose = "1.9.3"
adsIdentifier = "17.0.1"
amazon = "3.0.5"
androidxCore = "1.8.0"
androidxNavigation = "2.5.3"
annotation = "1.3.0"
appcompat = "1.4.1"
assertJ = "3.22.0"
browser = "1.8.0"
billing = "7.1.1"
composeBom = "2024.09.00"
coil = "2.4.0"
coreTesting = "2.0.0"
commonmark = "0.21.0"
constraintlayout = "1.1.0"
coroutines = "1.6.4"
datastorePreference = "1.0.0"
dependencyGraph = "0.9"
detekt = "1.23.6"
detektRulesCompose = "0.4.10"
dokka = "1.8.10"
emergeGradlePlugin = "4.2.0"
emergeSnapshots = "1.3.0"
espresso = …
```
> Clean up libs.versions.toml

- .circleci/config.yml
- fastlane/Fastfile
The `update-paywall-preview-resources-submodule` job did not actually initialize and checkout the submodule, which means changes were never detected. This PR fixes that.
> [Paywalls v2] Fixes `update-paywall-preview-resources-submodule` CI job

- ui/revenuecatui/src/testDebug/kotlin/com/revenuecat/purchases/ui/revenuecatui/snapshottests/PaywallComponentsTemplatePreviewRecorder.kt
`PaywallComponentsTemplatePreviewRecorder` uses a dedicated main Dispatcher, which in turn is used by Coil to call our preview ImageLoader. Without this dedicated main Dispatcher, recording the screenshots hangs after the first template. 
We've been getting [some failures](https://app.circleci.com/pipelines/github/RevenueCat/purchases-android/14987/workflows/2f1f1294-8839-4918-8dd6-c2085ed2a74b/jobs/74784/tests) related to concurrently setting and resetting the main Dispatcher in CI though:
>Dispatchers.Main is used concurrently with setting it 
This isn't happening locally for me, but maybe CI runs the individual test cases (templates) of the parameterized test (slightly) in parallel?
In this PR we only set and reset the main Dispatcher once for all of …
> [Paywalls v2] Improves `PaywallComponentsTemplatePreviewRecorder` stability

- ui/revenuecatui/src/debug/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/TemplatePreviews.kt
Since we now have a few templates with date variables, we should use a fixed date to avoid seeing changed snapshots daily.
> [Paywalls v2] Uses a fixed date for template previews to avoid daily changes.

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/ktx/Localization.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallStateLoadedComponentsLocaleTests.kt
We were still not always properly localizing the paywall when the region doesn't match between the device and the paywall configuration.
This is caused by the fact that in this scenario we use a LocaleId containing only the language and script, without the region. If we then try to find this LocaleId in the paywall's localizations map, we can't find any, because the localizations map contains a region.
We use the matched locale ID as it exists in the paywall config, instead of a permutation.
> [Paywalls V2] Improves fuzzy matching locale when the region doesn't match

- config/detekt/detekt.yml
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/timeline/TimelineComponentView.kt
1. The timeline would stretch vertically when its width is set to `Fit`.
2. The text would not be outlined properly when the text width is set to `Fit`.
| Bug 1 | Bug 2 |
|------|-------|
| ![image](https://github.com/user-attachments/assets/513f5a7a-00da-4a75-a848-024386991748) | ![image](https://github.com/user-attachments/assets/c93506f2-d3c6-437f-9fa2-9b64e568b44a) |
1. Fixed by setting the right `Dimension`.
2. Fixed by setting a `horizontalBias` of `0f`.
- Adds a bunch of Paywalls
- Some quality of life improvements (imo) to detekt.
> [Paywalls v2] Fixes timeline layout when width is Fit

- api-tester/src/defaults/java/com/revenuecat/apitester/java/PurchasesAPI.java
- api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
- purchases/src/defaults/kotlin/com/revenuecat/purchases/Purchases.kt
- purchases/src/defaults/kotlin/com/revenuecat/purchases/coroutinesExtensions.kt
- purchases/src/defaults/kotlin/com/revenuecat/purchases/listenerConversions.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/interfaces/GetStorefrontCallback.kt
- purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesTest.kt
We already had a `Purchases.storefrontCountryCode` property. This basically was null until the storefront property was returned. 
This PR adds some new APIs to obtain the `storefrontCountryCode` asynchronously, which is the real nature of this data
> Add async storefront country code apis

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/SubscriptionDetailsView.kt
The subscription name is truncated by the Customer Center. 
For example "Monthly long subscription name" looks like:
Made it max 2 lines and added elipsis
> Product name truncation issue in Customer Center on Android

- .circleci/config.yml
Super quick follow-up to #2370. Otherwise this typo will live forever 😅
> Fixes a typo: matalava -> metalava.

- purchases/src/main/kotlin/com/revenuecat/purchases/common/responses/SubscriptionInfoResponse.kt
This resolves a JSON parsing issue for the subscriptions where properties that are marked optional e.g. `String?` did not have an initial value and thus if they were not present in the decoded JSON string it would instead produce a deserialisation error like so:
```
04-24 14:39:41.911 12055 12055 E [Purchases] - ERROR: Error deserializing subscription information. The input is not a SubscriptionInfo
04-24 14:39:41.911 12055 12055 E [Purchases] - ERROR: kotlinx.serialization.MissingFieldException: Field 'product_plan_identifier' is required for type with serial name 'com.revenuecat.purchases.common.responses.SubscriptionInfoResponse', but it was missing at path: $
04-24 14:39:41.911 12055 12055 E [Purchases] - ERROR: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSeriali …
```
> [EXTERNAL] fix: Optional property deserialisation error (#2376) by @thomas-coldwell

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/image/ImageComponentState.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/image/ImageComponentView.kt
Adding a margin to a single side of an image component with Fixed size constraints would result in the image being cropped as it would treat it as padding.
Adjusts the size and aspect ratio modifiers of the outer `Box`, to ensure it grows enough to account for the margin.
> [Paywalls v2] Avoid image cropping when combining single-sided margin with Fixed size constraint

- scripts/pre-commit.sh
- Adds closing quotes to the `echo` message parameter (this was breaking)
- Adds quotes around the OUTPUT variable (not breaking but a shellcheck warning)
> Fixes pre-commit script

- gradle/libs.versions.toml
It looks like this change https://github.com/RevenueCat/purchases-android/pull/2318/files#diff-697f70cdd88ba88fe77eebda60c7e143f6ad1286bca75017421e93ad84fb87dfR59 downgraded the version of `androidx.constraintlayout` to `1.1.0`
I am suspicious it could be causing https://github.com/RevenueCat/react-native-purchases/issues/1266
> Fix downgrade of constraint layout version

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/InternalPaywall.kt
Since we're ensuring the effect runs after a successful recomposition, it's ideal for triggering side-effects that rely on the final, stable state of the UI. This approach makes running such operations safer during the recomposition phase.
> Use SideEffect for refreshing vm states inside InternalPaywall

- purchases/src/main/kotlin/com/revenuecat/purchases/common/offerings/OfferingsCache.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/offerings/OfferingsManager.kt
- purchases/src/test/java/com/revenuecat/purchases/common/FakeLocaleProvider.kt
- purchases/src/test/java/com/revenuecat/purchases/common/offerings/OfferingsCacheTest.kt
- purchases/src/test/java/com/revenuecat/purchases/common/offerings/OfferingsManagerTest.kt
The `OfferingsCache` would return cached Offerings (including products with localized descriptions) even if the locale has changes since caching. This prevents developers from showing the correct description in this scenario. 
`OfferingsCache` now remembers the locales at time of caching, and verifies they are unchanged when checking for staleness. Developers will receive up-to-date Offerings (including products with correctly-localized descriptions) when they call `getOfferings()` after the locale has changed.
> `getOfferings()` returns fresh Offerings and Products when the locale has changed

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/StyleFactory.kt
The bottom sheet should have window insets applied, to avoid clashing with system bars. This will only apply to its content. The background will still draw behind the system bar.
> [Paywalls] Ensures bottom window insets are applied to the sheet.

- .run/apiCheck.run.xml
- .run/apiDump.run.xml
- scripts/pre-commit.sh
I've just made Metalava a required CI check. This PR makes 2 updates for added Metalava convenience: 
- It is no longer ran as a pre-commit hook. This was a bit slow, and we don't update the public API surface that often, while every commit had to wait for this check.
- 2 Android Studio Run Configurations are added:
- `apiDump` generates new public API definition files.
- `apiCheck` checks whether the current public API still corresponds to the current definition files. This is also what the CI check does.
> Some Metalava updates

- fastlane/Fastfile
Our latest Paywall template has a space in its Offering ID. This [broke](https://app.circleci.com/pipelines/github/RevenueCat/purchases-android/15641/workflows/5f607155-90a3-4791-8fc7-f4de0bfe00c6/jobs/80605) recording of screenshots. This PR should fix that.
> Support spaces in template IDs when recording Paywall screenshots

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/modifier/Border.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/tabs/TabControlToggleView.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/Switch.kt
Our schema allows the Tabs component's Toggle button to receive gradient colors, but the SDK did not support that. 
This PR implements gradient support in the underlying `Switch` component, by duplicating the Material 3 implementation and swapping the `background()` and `border()` modifiers with our own (which already supported gradients). No other changes have been made.
> [Paywalls] Tab toggle supports gradient colors

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/viewmodel/CustomerCenterViewModel.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PurchasesType.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/CustomerCenterViewModelTests.kt
There's an issue when loading promotional offers for target products that miss a base plan
For example this configuration is valid if the product is old and configured without base plans in the dashboard:
The SDK will fail to load the promotional becasue it looks for the `product.id`, which in that case would look like `annual_freetrial:p1y`. On the other hand `product.googleProduct?.productId` has only the product id `annual_freetrial` so we should be looking for that instead if we can't find a promotional matching the base plan.
There was also another issue when loading the target product, since we were picking the first one returned, which is not ideal. For example, if the product "subscription" had "monthly" and "annual" base plans. And the target product was just "subscription", …
> Issue when loading promotional offers when products are missing base plans

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/PurchaseInformation.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/viewmodel/CustomerCenterViewModel.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/CustomerCenterViewModelTests.kt
- ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/PurchaseInformationTest.kt
We should be using the managementURL of the displayed subcription not the CustomerInfo one. We needed #2468 for this
> Use subscription's managementURL instead of CustomerInfo's in Customer Center

- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/main/offerings/OfferingsScreen.kt
- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/paywall/PaywallScreen.kt
- examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/paywallfooter/PaywallFooterScreen.kt
- ui/debugview/src/debug/kotlin/com/revenuecat/purchases/ui/debugview/InternalDebugRevenueCatScreen.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/InternalPaywall.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/InternalCustomerCenter.kt
Use `collectAsStateWithLifecycle` instead of `collectAsState` in Compose.
`collectAsState` is not lifecycle-aware and operates independently of Android's lifecycle system. This means it continues to collect data from the `Flow` even when the UI is no longer visible, potentially leading to unnecessary background work and performance issues.
On the other hand, `collectAsStateWithLifecycle` is a safer and more lifecycle-conscious alternative. It automatically suspends collection when the composable leaves the active lifecycle state (e.g., when the UI is not in the foreground), helping you avoid wasted resources and keeping your UI logic tightly aligned with the Android lifecycle.
Key advantages of `collectAsStateWithLifecycle`:
- It respects the `Lifecycle` of the host activity or fragment. …
> Use collectAsStateWithLifecycle instead of collectAsState in Compose

- .circleci/config.yml
- fastlane/Fastfile
- purchases/src/androidTest/kotlin/com/revenuecat/purchases/BasePurchasesIntegrationTest.kt
- purchases/src/androidTest/kotlin/com/revenuecat/purchases/Constants.kt
- purchases/src/androidTestDefaults/kotlin/com/revenuecat/purchases/PurchasesIntegrationTest.kt
We were running virtual currency integration tests both with and without the load shedder. However, the load shedder doesn't currently support virtual currencies, so these tests were failing when run for the load shedder integration test app. This PR updates the integration tests so that the virtual currency integration tests don't run for the load shedder integration tests app.
We are able to accomplish this by:
- When we're running integration tests through the integration tests app, fastlane sets the `IS_RUNNING_LOAD_SHEDDER_INTEGRATION_TESTS` string to `true` in `Constants.kt`.
- There's a new function `BasePurchasesIntegrationTest.isRunningLoadShedderIntegrationTests`, that tests can use to determine if they're running in the load shedder integration test app.
I manually forced the …
> Dont run VC tests on load shedder integration tests

- api-tester/src/main/java/com/revenuecat/apitester/java/VirtualCurrenciesAPI.java
- api-tester/src/main/java/com/revenuecat/apitester/java/VirtualCurrencyAPI.java
- api-tester/src/main/java/com/revenuecat/apitester/kotlin/VirtualCurrenciesAPI.kt
- api-tester/src/main/java/com/revenuecat/apitester/kotlin/VirtualCurrencyAPI.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/InternalRevenueCatAPI.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/virtualcurrencies/VirtualCurrencies.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/virtualcurrencies/VirtualCurrency.kt
This PR exposes the `VirtualCurrency` and `VirtualCurrencies` constructors publicly behind the `@InternalRevenueCatAPI` annotation. This will help us in a few scenarios when we need to instantiate VC objects outside of `purchases-android`, including in the mapper tests in PHC.
We considered a few other approaches before deciding to use `@InternalRevenueCatAPI`:
- Making the constructor public without an annotation. This works, but isn't ideal for a few reasons:
- Adding new properties would be a breaking change unless we used the `@JvmOverloads` annotation. Even then, we would need to provide a default value, and that won't always be easy (e.g. when we add VC icons, these will likely not be optionals)
- Parsing the VC objects from JSON in the PHC mapper tests. This would work but feels a …
> Expose Virtual Currency Constructors with @InternalRevenueCatAPI

- api-tester/src/main/java/com/revenuecat/apitester/java/TestStoreProductAPI.java
- purchases/src/main/kotlin/com/revenuecat/purchases/models/TestStoreProduct.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/teststore/TestStoreProductConverter.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/teststore/TestStorePurchasingData.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/utils/PriceExtensions.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/utils/PriceFactory.kt
- purchases/src/test/java/com/revenuecat/purchases/teststore/TestStoreProductConverterTest.kt
- purchases/src/test/java/com/revenuecat/purchases/utils/PriceFactoryTest.kt
This is another step in preparation to support the new TestStore. This adds the logic to transform WebBilling products into `TestStoreProduct`. These will be used for purchasing when using a test api key.
The logic here is currently unused, but will be used in follow-up PRs
> Convert WebBilling products into TestStoreProducts

- api-tester/src/defaults/java/com/revenuecat/apitester/java/PurchasesAPI.java
- api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
- api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesCommonAPI.java
- api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesCommonAPI.kt
- purchases/api-defauts.txt
- purchases/api-entitlement.txt
- purchases/src/customEntitlementComputation/kotlin/com/revenuecat/purchases/Purchases.kt
- purchases/src/defaults/kotlin/com/revenuecat/purchases/coroutinesExtensions.kt
- purchases/src/defaults/kotlin/com/revenuecat/purchases/listenerConversions.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/CoroutinesExtensionsCommon.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/ListenerConversionsCommon.kt
- ui/revenuecatui/api.txt
While CEC already had the `storefrontCountryCode`, this also adds the APIs `getStorefrontCountryCode` and `awaitStorefrontCountryCode` to the CEC flavor.
> Expose getStorefront APIs in CustomEntitlementComputation flavor

- CHANGELOG.md
Some users have been facing issues on the V9 migration when using anonymous accounts and haven't configured their one time products correctly in the RevenueCat dashboard. This adds a warning to the changelog in an effort to make this issue a bit more visible before upgrading
> Add warning on V9 CHANGELOG

- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/SharedPreferencesManager.kt
- purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizer.kt
- purchases/src/test/java/com/revenuecat/purchases/common/SharedPreferencesManagerTest.kt
We were storing data in the default shared preferences file, which could potentially be used by the app developer. That's a bad practice and it's more difficult to do some things with. This PR changes to a separate shared preferences file and adds a migration, so we migrate all RC data from the previous shared preferences file to the new one. We won't delete the data from the previous shared preferences file, but that will remain unused.
> Migrate RC SharedPreferences data to a separate file

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallDialog.kt
There is an issue in our current version of compose that causes the Dialog composable to extend beyond the screen size in Android 35+ devices: https://issuetracker.google.com/issues/246909281. This was fixed in a newer version of Compose, however, that introduces a breaking change by forcing apps to compile against Android 35.
This PR introduces a workaround by applying some bottom padding that consists on the status bar + navigation bars sizes as bottom padding. It also makes the PaywallDialog go Edge to Edge on Android 35+, which is the default starting on that version. The current fix has been tested on Android <35 and >35 and also when the client app uses a higher version of compsoe with the fix.
| Issue in Android 35+ | Android < 35 | Android >= 35 with older compose version | …
> Fix PaywallDialog going over screen size on Android 35+

- purchases/src/main/kotlin/com/revenuecat/purchases/CoroutinesExtensionsCommon.kt
Documentation about the `Purchases.awaitPurchase` coroutine extension was misleading.
Fixes a typo on documentation where the wrong class is mentioned.
Fixed the typo by linking the correct class (`PurchasesError`) embedded in the `PurchasesTransactionException` thrown in case of errors.
> docs: fixed a typo on documentation about `Purchases.awaitPurchase`

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/InternalCustomerCenter.kt
- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/viewmodel/CustomerCenterViewModel.kt
Fixes https://github.com/RevenueCat/purchases-android/pull/2588#issuecomment-3149306146
A new lint issue that starts happening when upgrading to AGP 8.13.0
Also wrapped the `refreshStateIfColorsChanged` in a LaunchedEffect keyed by the inputs, so it only runs when the theme actually changes.
> Fix CoroutineCreationDuringComposition lint error on AGP 8.13.0

- ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallActivityLauncher.kt
Required for https://github.com/RevenueCat/purchases-unity/pull/649
> Expose `launch` and `launchIfNeeded` to Java

- examples/CustomEntitlementComputationSample/app/build.gradle.kts
- examples/MagicWeatherCompose/app/build.gradle.kts
Revert kotlinCompilerExtensionVersion for MagicWeatherCompose and CustomEntitlementComputationSample since they use Kotlin 1.9.x. Thanks for finding this out, @JayShortway 👍 #2691
> Revert kotlinCompilerExtensionVersion for MagicWeatherCompose and CustomEntitlementComputationSample

- purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
We believe this scenario can deadlock:
- `Purchases.logOut()` , acquires `IdentityManager` lock
- Calls `subscriberAttributesManager.synchronizeSubscriberAttributesForAllUsers()` which does some stuff and actually has a `waitUntilIdle()`. It may need `PurchasesOrchestrator` lock for the operations to complete, but it might be held by the next step (`onAppForegrounded`)
- `onAppForegrounded` calls `allowSharingPlayStoreAccount` , acquires `PurchasesOrchestrator` lock
- it tries to call `identityManager.currentUserIsAnonymous()` but `IdentityManager` is locked
- at the same time `onBillingSetupFinished` and calls `PurchasesOrchestrator.getAllowSharingPlayStoreAccount` , which is locked on `PurchasesOrchestrator`
So basically, both `PurchasesOrchestrator` and `IdentityManager` get locked and …
> Fix deadlock in `allowSharingPlayStoreAccount`
