RevenueCat/purchases-android

build.gradle
purchases/src/main/java/com/revenuecat/purchases/Purchases.java
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.java

If a product is missing, it will just be null, and won't prevent the rest of entitlements from being sent.

[FINAL] Entitlements Don't Fail if Missing a Product

---

purchases/src/main/java/com/revenuecat/purchases/BillingWrapper.java
purchases/src/test/java/com/revenuecat/purchases/BillingWrapperTest.java

In some cases, the `BillingClient` will respond with an OK but have a null purchases object. This creates an odd situation where we can error with code OK.
This detects that case and switches the code to ERROR.

[FINAL] Fix Error Edge Case

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
purchases/src/main/java/com/revenuecat/purchases/Purchases.java
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.java

When closing an `RCPurchases` object, close everything out.

[FINAL] Unsubscribe From Lifecycle Methods

---

purchases/src/main/java/com/revenuecat/purchases/BillingWrapper.java
purchases/src/main/java/com/revenuecat/purchases/Purchases.kt
purchases/src/test/java/com/revenuecat/purchases/BillingWrapperTest.java

I noticed sometimes skudetails is null and I traced it down to google sending null when calling querySkuDetailsAsync. Since Kotlin crashes hard since skudetails is not marked as ?, I make sure we send an empty list of sku details instead of null.

Makes skuDetails empty when Google sends a null list when calling querySkuDetailsAsync

---

purchases/src/main/java/com/revenuecat/purchases/DeviceCache.kt
purchases/src/main/java/com/revenuecat/purchases/Purchases.kt
purchases/src/test/java/com/revenuecat/purchases/DeviceCacheTest.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

This Pull Request removes the automatic call to `restorePurchasesForPlayStoreAccount()` that gets triggered when setting a listener.
It also makes sure when calling `identify` and `reset` force a reset of the caches, which will eventually trigger a call to PurchaserUpdatedListener if any

Removes automatic restore of purchases and makes sure identify and reset force an update of caches

---

purchases-sample/src/main/java/com/revenuecat/purchases_sample/MainActivity.java
purchases-sample/src/main/java/com/revenuecat/purchases_sample/MainApplication.kt
purchases/src/main/java/com/revenuecat/purchases/Purchases.kt

Since `defaultInstance` doesn't actually creates an instance if there's no instance, I decided to rename it to sharedInstance. Note it's also nullable now.

Renames defaultInstance to sharedInstance

---

purchases/src/main/java/com/revenuecat/purchases/Dispatcher.java
purchases/src/test/java/com/revenuecat/purchases/DispatcherTest.java

onCompletion of the AsyncCall, we were calling the callback in the same background thread as the Runnable. I dispatched the callback call to the main thread as we do in the iOS SDK

Fixes threading problem

---

purchases/src/main/kotlin/com/revenuecat/purchases/DeviceCache.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/test/java/com/revenuecat/purchases/DeviceCacheTest.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

Looking at https://docs.revenuecat.com/discuss/5c479f9f9c2c64013f2836a2 
> I've been using the auto generated ID, what's the best way to retroactively add the UID to the account without having them to restore transactions?
The solution is:
>You can use the .createAlias method to attach your User ID to the purchase history of a previous randomly generated App User ID. After you get your account UID you can check to see if it equals the current App User Id for the Purchases instance - if not, call .createAlias.
To make things easier, I added this check in the code so that users that are calling `createAlias` are not triggering useless backend calls.

Makes sure we don't create alias or identify over the same app user id

---

purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

There was a bug when purchaseCallbacks had more than one callback, we were changing the size while iterating which causes a crash. I also added synchronized blocks around accesses to purchase callbacks.

Fixes ConcurrentModificationException and protects purchaseCallbacks syncronization

---

purchases/src/main/java/com/revenuecat/purchases/interfaces/MakePurchaseListener.java
purchases/src/main/java/com/revenuecat/purchases/interfaces/PurchaseCompletedListener.java
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/listenerConversions.kt

Related to https://github.com/RevenueCat/purchases-android/pull/56 and https://github.com/RevenueCat/purchases-android/issues/55
Note this breaks API for kotlin since function overloading by just changing a parameter function is not available in Kotlin, or in other words, I can't overload makePurchaseWith.

Return Purchase object when making purchase

---

purchases/src/main/kotlin/com/revenuecat/purchases/BillingWrapper.kt
purchases/src/test/java/com/revenuecat/purchases/BillingWrapperTest.kt

After this https://docs.revenuecat.com/discuss/5c9069317c710300447d2d7b and https://docs.revenuecat.com/discuss/5c9068a88e78ef00bf13be8f I looked deeper into the BillingWrapper code and realized there were some possible race conditions:
- Setting `purchasesUpdatedListener` to `null` (happens on `Purchases.sharedInstance.close()`) will call `endConnection`, which will set `clientConnected` to false.
- If `onBillingSetupFinished` gets called after this call to `endConnection`, `clientConnected` will be set to `true` and execute the pending requests, which most of them fail because the `BillingClient` and the `purchasesUpdatedListener` are `null`
If someone calls configure twice (which can certainly happen if it's being called in an Activity), the first instance gets closed.
Apart from that, …

Fixes Race Conditions on BillingWrapper

---

purchases/src/main/kotlin/com/revenuecat/purchases/BillingWrapper.kt
purchases/src/main/kotlin/com/revenuecat/purchases/HTTPClient.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/test/java/com/revenuecat/purchases/BackendTest.kt

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
at org.json.JSONTokener.nextValue(JSONTokener.java:94)
at org.json.JSONObject.(JSONObject.java:156)
at org.json.JSONObject.(JSONObject.java:173)
at com.revenuecat.purchases.HTTPClient.performRequest(HTTPClient.java:113)
at com.revenuecat.purchases.HTTPClient.performRequest(HTTPClient.java:83)
at com.revenuecat.purchases.Backend$getPurchaserInfo$call$1.call(Backend.java:52)
at com.revenuecat.purchases.Dispatcher$AsyncCall.run(Dispatcher.java:25)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at …
```

Fixes multiple crashes

---

purchases/src/main/java/com/revenuecat/purchases/util/AdvertisingIdClient.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Backend.kt
purchases/src/main/kotlin/com/revenuecat/purchases/BillingWrapper.kt
purchases/src/main/kotlin/com/revenuecat/purchases/DeviceCache.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/errors.kt
purchases/src/test/java/com/revenuecat/purchases/BackendTest.kt
purchases/src/test/java/com/revenuecat/purchases/DispatcherTest.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

Main changes are:
- Automatically adds `rc_gps_adid`. 
- Keeps track of posted attribution data by caching in shared preferences a combination of adid_networkuserid per attribution network and app user Id. If latest attribution data for a network was sent for the same ad id and network user ID, skip posting the attribution data.
- Makes `addAttributionData` a static method. If the Purchases instance is not initialized, cache the attribution data and post it once it's initialized. Deprecates the old `addAttributionData` instance methods

Better Attribution Data

---

purchases/src/main/kotlin/com/revenuecat/purchases/Dispatcher.kt
purchases/src/main/kotlin/com/revenuecat/purchases/errors.kt
purchases/src/test/java/com/revenuecat/purchases/DispatcherTest.kt

Some OEMs and roms allow users to change permissions granted for apps at runtime. This can result in SecurityExceptions where the app does not have the internet permission when making a network request.
This PR simply catches the exception in `Dispatcher` and then converts it into a `PurchasesError` with (`PurchasesErrorCode.InsufficientPermissionsError`). I thought this was simpler and more effcient then having to check for the permission before each request.
Testing:
* Added a new test in `DispatcherTest`.
* Reproduced the crash by removing the internet permission + permission check in the init method, verified that this fixes it and propagates the correct error.

Handle missing INTERNET permissions when making network requests.

---

purchases/src/main/kotlin/com/revenuecat/purchases/BillingWrapper.kt
purchases/src/test/java/com/revenuecat/purchases/BillingWrapperTest.kt

This is oddly nullable (as far as I can tell, it's nowhere in the documentation). This adds a null check, if i'ts null we'll just build the map off an empty list.
I added a unit test to cover this, but was not able to manually reproduce (maybe it depends on the state the device is in? or whatever version of Google Play Services the device running?)

Handle null purchase lists in BillingWrapper#queryPurchases.

---

purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

Should fix https://github.com/RevenueCat/purchases-android/issues/80
We forgot to check if the executorService is shutdown before executing when performing `updatePendingPurchaseQueue`

Checks if executor is shutdown when calling updatePendingPurchaseQueue

---

purchases/build.gradle
purchases/src/main/kotlin/com/revenuecat/purchases/BillingWrapper.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchaseWrapper.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/errors.kt
purchases/src/main/kotlin/com/revenuecat/purchases/testUtils.kt
purchases/src/test/java/com/revenuecat/purchases/BillingWrapperTest.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

- Updated BillingClient library to version 2.0.3
- `BillingClient.BillingResponse` has been replaced with `BillingClient.BillingResponseCode`.
- BillingClient calls return now a `BillingResult`. This class contains a `debugMessage` and an error code.
- Added a `BillingResult.toHumanReadableDescription()` that prints both the `debugMessage` and the response code.
- Calling for `BillingWrapper.queryPurchaseHistoryAsync` now returns a `List<PurchaseHistoryRecord>`
- `BillingWrapper.consumeAsync` requires a `ConsumeParams` instead of a token.
- `PurchaseWrapper` has been updated to hold either a `Purchase` or a `PurchaseHistoryRecord`.
- Non consumable purchases need to be acknowledged
- Pending purchases need to be enabled in order to instantiate the BillingClient
- Entitlements shouldn't be …

Updates to BillingClient 2.0.3

---

purchases/src/main/kotlin/com/revenuecat/purchases/BillingWrapper.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchaseType.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchaseWrapper.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/errors.kt
purchases/src/test/java/com/revenuecat/purchases/BillingWrapperTest.kt
purchases/src/test/java/com/revenuecat/purchases/DeviceCacheTest.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

The key changes this PR introduces are:
- Added our own `PurchaseType` enum to not have a null purchaseType and to avoid having to deal with Strings
- If `onPurchasesUpdated` gets hit with a new purchase and the type of the purchase is unknown, we will try to get the type of the purchase by calling `queryPurchases` which is synchronous. We normally get the product type using `productTypes`, a Map whose values get set when making a purchase. When making a purchase for a subscription `productA` we will set the `productTypes[productA]` to be `SUBS`. It is possible the `onPurchasesUpdated` method gets hit with a purchase of a product that hasn't been recently purchased (like when a pending transaction succeeds and the app is open). It is also possible that `queryPurchases` fails for whatever …

Fixes Pending purchases

---

purchases/src/main/kotlin/com/revenuecat/purchases/BillingWrapper.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchaseHistoryRecordWrapper.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchaseWrapper.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/test/java/com/revenuecat/purchases/BillingWrapperTest.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

Choosing `PurchaseWrapper` to wrap both `Purchase` and `PurchaseHistoryRecord` wasn't a good idea. When posting the token to the backend, we were checking if the state of the purchase was `PURCHASED`. The problem is that for restores and syncing of purchases, the Purchase in the PurchaseWrapper is null and therefore, the status is unknown.
I refactored the code to not reuse the PurchaseWrapper and to make more clear what is happening in each of the cases. 
The unit tests didn't find this because they were wrong. They were creating PurchaseWrappers with Purchases inside, and mocking a PURCHASED purchase.

Fixes purchases not being posted on restores and syncpurchases

---

purchases/build.gradle
purchases/src/main/kotlin/com/revenuecat/purchases/AppLifecycleHandler.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

This PR avoids fetching the purchaser info or the entitlements as soon as the SDK is initialized and defers it to whenever the app is foregrounded. This would prevent us from updating the caches in cases when the Application object is created but the app is in the background (like whenever there is a push notification or any broadcast service that wakes the app up).

Adds lifecycle observer and defers updating the caches until the app is foregrounded

---

purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

https://trello.com/c/BUfBUMAe/433-fix-appsflyer-sdk-compatibility
Appsflyer released a new version of their SDK and made some changes that affect us a little bit. The main change is that they renamed their callback and it now returns a map object that contains all the conversion data keys. Previously it had returned only parameters that had a value.
We need to make a change, since Appsflyer now returns a Map<String, Object> but the addAttribution method expects a Map<String, String>.

Fixes incompatibility with latest AppsFlyer SDK

---

purchases/src/main/java/com/revenuecat/purchases/util/AdvertisingIdClient.kt

Fixes https://github.com/RevenueCat/purchases-android/issues/98
We were calling `unbindService` even if the result of `bindService` is false. When I added this file to the project I converted the one we have in Unity https://github.com/RevenueCat/purchases-unity/blob/master/Android/purchasesunity/src/main/java/com/revenuecat/purchasesunity/AdvertisingIdClient.java to Kotlin. I realized the try/catch statement was inside the sucessful bindService. Extracting the if check should fix the problem and would make both Java and Kotlin implementations match.

fixes unbindservice being called even if bindservice is false

---

purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/listenerConversions.kt

The documentation on the `restorePurchases` was wrong. I copied over the one in the iOS SDK

Restore purchases doc updates

---

purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt

I was doing final manual testing when I encountered a regression introduced in the clear cached purchaser info PR.
`deviceCache.clearOfferingsCacheTimestamp()` wasn't being called when getting the SkuDetails fails while trying to construct the Offerings object

[FINAL] makes cache stale after an error fetching skudetails

---

purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

Should fix #114 . 
It's possible the SKUDetails cannot be retrieved. We should not assume that we can fetch all SKUDetails associated with a purchase.

Fixes NoSuchElementException

---

purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/caching/DeviceCache.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesDeviceCacheTests.kt
purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt

Based on #118 
Adds the public methods to set attributes and automatic synchronization of attributes when the app goes to foreground/background

[Final] Subscriber Attributes Part 4 (Public API and automatic synchronization)

---

purchases-sample/src/main/java/com/revenuecat/sample/fasdf.java
purchases/src/main/kotlin/com/revenuecat/purchases/Backend.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/attributes/SubscriberAttributesManager.kt
purchases/src/main/kotlin/com/revenuecat/purchases/errors.kt
purchases/src/test/java/com/revenuecat/purchases/BackendTest.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesBackendTests.kt
purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesManagerTests.kt
purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt
purchases/src/test/java/com/revenuecat/purchases/responses.kt
purchases/src/test/resources/responses/attribute_errors_post_receipt_response.json

- Adds attributes as a parameter to the post receipt call.
- Logs attribute errors

[FINAL] Subscriber Attributes Part 5 Sync before posting receipts

---

purchases/src/main/java/com/revenuecat/purchases/util/AdvertisingIdClient.kt

Another try to fix https://github.com/RevenueCat/purchases-android/issues/98
What I think it's happening is that since bindService is running in a separate thread (and probably running stuff on the main thread) `unbindService` could get called before the `bindService` finishes doing its things and crash
I also realized the completion blocks were running before `unbindService` and in a different thread but that should be fine since this is internal anyway

[FINAL] Makes sure unbindService runs in the main thread when getting AdvertisingIDInfo

---

CHANGELOG.md
RELEASING.md
gradle.properties
purchases/build.gradle
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt

- Another fix for NoSuchElementException when retrieving Advertising ID #124
- Added Subscriber Attributes, which allow developers to store additional, structured information 
for a user in RevenueCat. More info: https://docs.revenuecat.com/docs/user-attributes

Version 3.1.0

---

purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt

Invalidating the cache is simultaneously an advanced technique and attractive to beginners who might think they need to invalidate the cache on every app launch, so I added a link to our docs that explains how to work with the cache in normal circumstances. 
https://github.com/RevenueCat/purchases-ios/pull/223
N/A

Update invalidatePurchaserInfoCache docs

---

purchases/src/main/kotlin/com/revenuecat/purchases/Backend.kt
purchases/src/main/kotlin/com/revenuecat/purchases/HTTPClient.kt
purchases/src/test/java/com/revenuecat/purchases/BackendTest.kt
purchases/src/test/java/com/revenuecat/purchases/HTTPClientTest.kt
purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesBackendTests.kt

https://stackoverflow.com/a/12155874
We are calling JSONObject(body) and body is Map<String, Map> so in Android < 19 we send this:
"attributes":"{$displayName={value=cesar, updated_at_ms=1589043738052}}"}
In Android >=19 we send it correctly:
{"attributes": {"$displayName": {"value": null, "updated_at_ms": 1589042480440}}}

Fix subscriber attributes JSON for old Android devices

---

.circleci/config.yml

Before moving to git flow, we would release SNAPSHOT releases when merging onto master. We should now release SNAPSHOT releases when merging to develop.

Deploy SNAPSHOTS when merging to develop

---

purchases/build.gradle
purchases/src/main/kotlin/com/revenuecat/purchases/EntitlementInfo.kt
purchases/src/main/kotlin/com/revenuecat/purchases/EntitlementInfos.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchaserInfo.kt
purchases/src/main/kotlin/com/revenuecat/purchases/utils.kt

Some classes were still implementing `Parcelable` by hand, but we are already using `@Parcelize` to avoid boilerplate. I migrated all the classes to `Parcelize`

Migrates some classes to use Parcelize

---

purchases-sample-java/src/main/java/com/revenuecat/purchases/purchases_sample_java/CatsActivity.java
purchases-sample-java/src/main/res/layout/activity_cats.xml
purchases-sample/src/main/java/com/revenuecat/sample/CatsActivity.kt
purchases-sample/src/main/res/layout/activity_cats.xml
purchases/src/main/kotlin/com/revenuecat/purchases/Factories.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchaserInfo.kt
purchases/src/test/java/com/revenuecat/purchases/PurchaserInfoTest.kt
purchases/src/test/resources/responses/valid_empty_purchaser_response.json
purchases/src/test/resources/responses/valid_full_purchaser_response.json

The backend returns a `management_url` in the Purchaser Info response. The logic behind it is:
- Use the user's active subscription store to determine the correct link to send.
- Users may have multiple, in that case we can fall back to the platform header.
This URL can be opened in Android apps like so:
```
try {
startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse(purchaserInfo.getManagementURL())));
} catch (ActivityNotFoundException exception) {
exception.printStackTrace();
}
```

Adds management URL to Purchaser Info

---

purchases/build.gradle
purchases/src/main/kotlin/com/revenuecat/purchases/AppConfig.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Backend.kt
purchases/src/main/kotlin/com/revenuecat/purchases/HTTPClient.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/utils.kt
purchases/src/test/java/com/revenuecat/purchases/AppConfigTest.kt
purchases/src/test/java/com/revenuecat/purchases/HTTPClientTest.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt

Some apps have additional security requirements (specifically kids apps) that require them to proxy all traffic from their parties through their own servers.
Right now, apps can override the hostname in the SDK to their proxy URL, but they need to remember to do this every time they upgrade SDK versions.
We should make an "official way" of setting a proxy URL that will persist for the user between SDK updates.
Add a static property that is called proxyURL
Log whenever someone calls configure with a configured proxyURL.

Adds proxy URL static property

---

CHANGELOG.md
gradle.properties
purchases/build.gradle
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt

- Added `proxyKey`, useful for kids category apps, so that they can set up a proxy to send requests through. **Do not use this** unless you've talked to RevenueCat support about it. 
https://github.com/RevenueCat/purchases-android/pull/152
- Added `managementURL` to purchaserInfo. This provides an easy way for apps to create Manage Subscription buttons that will correctly redirect users to the corresponding subscription management page on all platforms. 
https://github.com/RevenueCat/purchases-android/pull/151
- Extra fields sent to the post receipt endpoint: `normal_duration`, `intro_duration` and `trial_duration`. These will feed into the LTV model for more accurate LTV values. 
https://github.com/RevenueCat/purchases-android/pull/148
- Fixed a bug where if the `context` passed to the …

Bump 3.2.0

---

purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

This change https://github.com/RevenueCat/purchases-android/pull/152/files#diff-c2f78fa2df4dd98b44def5ad956966c6R8 changed the constructor of AppConfig to accept `observerMode` instead of `finishTransactions`, but we never changed what we send to the constructor, so no transactions were being consumed/acknowledged

Fixes finishTransactions regression

---

CHANGELOG.md

Copy of #155, but includes bug fix PRs that happened afterwards
- Added `proxyKey`, useful for kids category apps, so that they can set up a proxy to send requests through. **Do not use this** unless you've talked to RevenueCat support about it. 
https://github.com/RevenueCat/purchases-android/pull/152
https://github.com/RevenueCat/purchases-android/pull/157
- Added `managementURL` to purchaserInfo. This provides an easy way for apps to create Manage Subscription buttons that will correctly redirect users to the corresponding subscription management page on all platforms. 
https://github.com/RevenueCat/purchases-android/pull/151
- Extra fields sent to the post receipt endpoint: `normal_duration`, `intro_duration` and `trial_duration`. These will feed into the LTV model for more accurate …

release: 3.2.0

---

purchases/src/main/kotlin/com/revenuecat/purchases/Factories.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchaserInfo.kt
purchases/src/main/kotlin/com/revenuecat/purchases/utils.kt
purchases/src/test/java/com/revenuecat/purchases/PurchaserInfoTest.kt
purchases/src/test/resources/responses/valid_full_purchaser_response.json

Added parsing of `original_purchase_date` in `subscriber` to purchaserInfo

add original_purchase_date

---

purchases/build.gradle
purchases/src/main/kotlin/com/revenuecat/purchases/BillingWrapper.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/ReplaceSkuInfo.kt
purchases/src/main/kotlin/com/revenuecat/purchases/UpgradeOrDowngradeInfo.kt
purchases/src/main/kotlin/com/revenuecat/purchases/utils.kt
purchases/src/test/java/com/revenuecat/purchases/BillingWrapperTest.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

Main changes are:
- `setOldSku(oldSku)` replaced with `setOldSku(oldSku, purchaseToken)`
- `setAccountId` replaced with `setObfuscatedAccountId`.

BillingClient update to 3.0.0

---

CHANGELOG.md
RELEASING.md
gradle.properties
purchases/build.gradle
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt

- Added mParticle as one of the attribution options  
https://github.com/RevenueCat/purchases-android/pull/163
- Added original_purchase_date to JSON response
https://github.com/RevenueCat/purchases-android/pull/164
- Updated BillingClient to 3.0.0
https://github.com/RevenueCat/purchases-android/pull/166
- Moved the SKUDetails inside the ProductInfo that's passed to the Backend class when posting tokens
https://github.com/RevenueCat/purchases-android/pull/167

Release 3.3.0

---

purchases/src/main/kotlin/com/revenuecat/purchases/Dispatcher.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt

We got a report of this stacktrace:
```
Fatal Exception: java.util.concurrent.RejectedExecutionException: Task com.revenuecat.purchases.Purchases$updatePendingPurchaseQueue$1@43f3b0f rejected from java.util.concurrent.ThreadPoolExecutor@f84e79c[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 0] 
at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2078) 
at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:843) 
at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1384) 
at com.revenuecat.purchases.Purchases.updatePendingPurchaseQueue$purchases_release(Purchases.kt:1180) 
at com.revenuecat.purchases.Purchases$1.onConnected(Purchases.kt:134) 
at …
```

Synchronizes accesses to executorService

---

common/src/main/java/com/revenuecat/purchases/common/BillingWrapper.kt

https://issuetracker.google.com/issues/155005449
Turns out that upgrades/downgrades only work if the obfuscatedAccountId is the same as the original purchase. I have commented it out for now until it's fixed, since it's an optional parameter (https://developer.android.com/reference/com/android/billingclient/api/BillingFlowParams.Builder?hl=id#setobfuscatedaccountid). I can remove it if necessary. I am not sure they will ever fix it.
Reported in https://github.com/RevenueCat/purchases-flutter/issues/93

Removes setObfuscatedAccountId from the parameters. Should fix upgrades/downgrades

---

.buildscripts/jacoco.gradle
.circleci/config.yml
CHANGELOG.md
gradle.properties
purchases/build.gradle
purchases/src/main/kotlin/com/revenuecat/purchases/Backend.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesBackendTests.kt

- Addresses an issue where subscriber attributes might not sync correctly if subscriber info for the user hadn't been synced before the subscriber attributes sync was performed.

Fixes 404 marking attributes as synced

---

.circleci/config.yml

Looks like deploys are broken because we are not installing fastlane when running the deploy jobs : https://app.circleci.com/pipelines/github/RevenueCat/purchases-android/891/workflows/db1371ed-70f6-4ae3-a525-d79ef98cbd73/jobs/2123

Fixes deploys: installs fastlane

---

CHANGELOG.md
RELEASING.md
common/src/main/java/com/revenuecat/purchases/common/Config.kt
gradle.properties
library.gradle

- Deprecated `addAttribution` in favor of `setAdjustId`, `setAppsflyerId`, `setFbAnonymousId`, `setMparticleId`.
- Added support for OneSignal via `setOnesignalId`
https://github.com/RevenueCat/purchases-android/pull/184
- Fixed a RejectedExecutionException due to un-synchronized accesses to the ExecutorService 
https://github.com/RevenueCat/purchases-android/pull/179
- Fixed downgrades/upgrades https://github.com/RevenueCat/purchases-flutter/issues/93
https://github.com/RevenueCat/purchases-android/pull/179

Version 3.5.0

---

common/src/main/java/com/revenuecat/purchases/common/caching/DeviceCache.kt
common/src/test/java/com/revenuecat/purchases/common/DeviceCacheTest.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

Fixes an issue where after calling `invalidatePurchaserInfoCache` and then `purchaserInfoWithCompletion`, the invalidated cached version of purchaserInfo would be returned first, and only the delegate would get the updated version. 
This is fixed by entirely removing the cached version from storage, so that the SDK forcibly only returns a new version, if communication with the backend succeeds. 
iOS counterpart: https://github.com/RevenueCat/purchases-ios/pull/333

InvalidePurchaserInfoCaches fix

---

feature/subscriber-attributes/src/main/java/com/revenuecat/purchases/subscriberattributes/AttributionFetcher.kt
feature/subscriber-attributes/src/test/java/com/revenuecat/purchases/subscriberattributes/AttributionFetcherTests.kt

Should prevent crashing if there is a timeout https://github.com/RevenueCat/purchases-android/issues/193

Catch TimeoutException when calling getAdvertisingIdInfo

---

CHANGELOG.md
common/src/main/java/com/revenuecat/purchases/common/Config.kt
gradle.properties
library.gradle

- Fixes an issue where after calling invalidatePurchaserInfoCache and then purchaserInfoWithCompletion, the invalidated 
cached version of purchaserInfo would be returned first, and only the delegate would get the updated version.
https://github.com/RevenueCat/purchases-android/pull/189
- Catch TimeoutException when calling getAdvertisingIdInfo
https://github.com/RevenueCat/purchases-android/pull/194

Version 3.5.1

---

feature/subscriber-attributes/src/main/java/com/revenuecat/purchases/subscriberattributes/AttributionFetcher.kt
feature/subscriber-attributes/src/test/java/com/revenuecat/purchases/subscriberattributes/AttributionFetcherTests.kt

https://github.com/RevenueCat/purchases-android/pull/194 added a catch for `TimeoutException`. It turns out, what's being thrown in this report https://github.com/RevenueCat/purchases-android/issues/193 is actually a `IOException` with a `TimeoutException` inside.
This PR adds another catch, just in case `TimeoutException` gets thrown in some cases.

Catch IOException when getAdvertisingIdInfo

---

utils/src/main/java/com/revenuecat/purchases/utils/JSONObjectExtensions.kt

I am not sure why this would break, but we are getting reports of someone having an exception that says:
"JSONObject["management_url"] is not a string"
I have tried for long and haven't been able to reproduce it, but I noticed that we changed this in https://github.com/RevenueCat/purchases-android/pull/164
They are actually reporting errors when upgrading flutter from 1.2.1. which uses Android 3.2.0 to 1.3.1 which uses 3.5.0. The change was released on https://github.com/RevenueCat/purchases-android/releases/tag/3.3.0

Management url json fix

---

fastlane/Fastfile

There is an issue with dokka https://app.circleci.com/pipelines/github/RevenueCat/purchases-android/1004/workflows/a34a96ce-0206-44b8-b990-f054a04e824c/jobs/2523
The fix is to run `build` before running dokka -> https://github.com/Kotlin/dokka/issues/777

fixes dokka

---

purchases/src/main/AndroidManifest.xml

BillingClient includes the BILLING permission directly, we don't need to request it from our side https://github.com/RevenueCat/purchases-android/issues/210
I don't think this will change anything but hopefully the warning they see in that issue will go away

Removes BILLING permission from AndroidManifest

---

CHANGELOG.md
common/src/main/java/com/revenuecat/purchases/common/Config.kt
gradle.properties
library.gradle
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt

- Removes Billing permission from AndroidManifest since it's added by the BillingClient
https://github.com/RevenueCat/purchases-android/pull/211
- Fixes Deferred downgrades. The Purchase object in the completion block of `purchaseProduct` and `purchasePackage` is now nullable when changing products.
https://github.com/RevenueCat/purchases-android/pull/200

Version 4.0.0

---

common/src/main/java/com/revenuecat/purchases/common/errors.kt

This happens when a user changes ID but stays on the same device,
and tries to purchase a subscription again.  This maps to unknown
error, with ITEM_ALREADY_OWNED string in details.
Thank you for contributing to Purchases. Before pressing the "Create Pull Request" button, please provide the following:

Map ITEM_ALREADY_OWNED error from BillingClient

---

common/src/main/java/com/revenuecat/purchases/common/errors.kt
common/src/test/java/com/revenuecat/purchases/common/BillingResponseCodeTest.kt

It's not the first time this https://github.com/RevenueCat/purchases-android/pull/220 happens.
This PR adds tests that would fail if there are new `BillingResponseCodes`. Since `BillingResponseCode` is not an enum, we have to add an `else` to the `when` statement we use, and therefore, we don't get notified when there's a new code. 
I also changed the implementation of `getBillingResponseCodeName` so that's dynamic and we don't have to manually type the name of the codes. I added tests for it.

Adds tests to make sure we handle all BillingResponseCodes

---

utils/src/main/resources/mockito-extensions/org.mockito.plugins.MockMaker

This file was unnecessary and I believe it was causing issues to people using version 1.x.x of the mockito SDK. Should be safe to remove because this module doesn't even have tests. It's originally intended to be able to mock final classes in Kotlin.
We originally had it in the `test` folder https://github.com/RevenueCat/purchases-android/blob/3.4.1/purchases/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker and somehow it ended up in the main folder when doing the modularization.

Removes mock-maker-inline

---

.circleci/config.yml

The deploy jobs were not running on tags because the `assemble-sample-app` job wasn't running in tags. I cleaned up the workflows a little bit:
- Moved the deploys to its own workflow
- Removed the requirement to do the deploy after the `assemble-sample-app`. That is going to be run in the develop branch anyhow

Fixes deploy CI job

---

common/src/main/java/com/revenuecat/purchases/common/Dispatcher.kt
common/src/test/java/com/revenuecat/purchases/common/DispatcherTest.kt

I realized exceptions that happen in the threads started to not show up when we changed the ExecutorService. 
We used to have a similar issue because we were using `submit` instead of `execute`. `submit` returns a `Future`, which contains the Exception. 
In `ScheduledExecutorService`, `schedule` acts like `submit`, returning a `Future`. I found out that calling `execute` is actually calling `schedule` with a 0 delay, so calling `execute` is the same as calling `submit` in `ScheduledExecutorService`.
Tried different solutions, like overriding `afterExecute` (I found it in this blogpost https://aozturk.medium.com/how-to-handle-uncaught-exceptions-in-java-abf819347906) but it only works for `execute` in a regular `ExecutorService`. Looking at the documentation …

Fixes exceptions swallowed by ExecutorService

---

build.gradle
common/build.gradle
library.gradle
public/build.gradle
purchases/build.gradle
test-utils/build.gradle

Looks like the changes don't affect us:
```
Version 3.0.2 of the Google Play Billing Library and Kotlin extension are now available.
Bug fixes
Fixed a bug in the Kotlin extension where the coroutine fails with error "Already resumed".
Fixed unresolved references when the Kotlin extension is used with the kotlinx.coroutines library version 1.4+.
```
https://developer.android.com/google/play/billing/release-notes

Updates BillingClient to 3.0.2

---

build.gradle
purchases/build.gradle
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt

Should fix https://github.com/RevenueCat/purchases-android/issues/240 and https://github.com/RevenueCat/react-native-purchases/issues/184
The newer version of the `lifecycle` library forces `addObserver` and `removeObserver` to be called from the Main thread

Update lifecycle version and calls addObserver and removeObserver from Main thread

---

public/build.gradle
public/src/androidTest/java/com/revenuecat/purchases/PackageTest.kt
public/src/main/java/com/revenuecat/purchases/parceler/SkuDetailsParceler.kt

The billing library from google is obfuscated and the mOriginalJson
field cannot be accessed.
This leads to the following crash on saving any instance of Package as a Parcelable:
```
E/ThreadGroup: CRASH IN main!
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
Caused by: java.lang.NoSuchFieldException: No field mOriginalJson in class Lcom/android/billingclient/api/SkuDetails; (declaration of 'com.android.billingclient.api.SkuDetails' appears in …
```

Fix SkuDetailsParceler

---

CHANGELOG.md
common/src/main/java/com/revenuecat/purchases/common/Config.kt
gradle.properties
library.gradle

- Fixes JSONObjectParceler, SkuDetailsParceler and adds unit tests for other Parcelable classes.
https://github.com/RevenueCat/purchases-android/pull/249
https://github.com/RevenueCat/purchases-android/pull/253
https://github.com/RevenueCat/purchases-android/pull/254
- Changes cache refresh period on background to 25 hours.
https://github.com/RevenueCat/purchases-android/pull/255

Prepares for version 4.0.3

---

common/src/main/java/com/revenuecat/purchases/common/Factories.kt
common/src/test/java/com/revenuecat/purchases/common/EntitlementInfosTests.kt

Right now consumables and promotionals return willRenew as true. We should update so that:
1. Consumables always return willRenew as false
1. Promotionals always return willRenew as false
1. Subscriptions return willRenew as true if they don't have unsubscribe detected or billing issues.

Updates willRenew logic

---

common/src/main/java/com/revenuecat/purchases/common/Backend.kt
common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
purchases/src/main/kotlin/com/revenuecat/purchases/listenerConversions.kt

Fixes a couple of bugs with identity v3: 
- `logInWith` wasn't internal, but it's not meant to be public yet
- the endpoint url was updated from `login` to `identify`
- added `logOutWith` method

Fix: identity v3 bugs

---

common/src/main/java/com/revenuecat/purchases/common/caching/DeviceCache.kt

This PR catches "cannot cast String to Set" exceptions. This will alleviate crashes from this [issue](https://github.com/RevenueCat/purchases-flutter/issues/24) that I and other Flutter devs have encountered. This issue occurs after utilizing a forked version of the flutter SharedPreferences package, which unfortunately corrupts StringSet preferences. Rather than crashing when querying the token cache, this will simply return an empty set.

Catch exceptions when getting stringSet from sharedPreferences

---

common/src/main/java/com/revenuecat/purchases/common/Backend.kt
common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt

Android equivalent of https://github.com/RevenueCat/purchases-ios/pull/484
Updates the location of the old appUserID in `/identify` calls: 
| :-: | :-: |
| included in the URL | included in the POST body as `app_user_id` |

Identity v3: update appUserID location in /identify

---

Gemfile.lock

Deploys are failing because there's a version of a gem missing 
https://app.circleci.com/pipelines/github/RevenueCat/purchases-android/1519/workflows/ca471bd9-506d-4ddc-a70c-29c09aa79217/jobs/3918
It got pulled from the servers. This PR updates the lock file, which actually reverts to use `declarative-option-0.1.0`

updated gemfile.lock to fix deploys

---

feature/amazon/build.gradle

I realized I forgot to commit this changes when merging Amazon. This PR basically adds downloading the Amazon dependency automatically when trying to build the `amazon` module. This won't release the .jar as part of our .aar.

Downloads amazon jar automatically when building

---

common/src/main/java/com/revenuecat/purchases/common/caching/DeviceCache.kt
common/src/test/java/com/revenuecat/purchases/common/DeviceCacheTest.kt
config/detekt/detekt-baseline.xml

We got this stacktrace:
```
Caused by: java.lang.NullPointerException: 
at com.revenuecat.purchases.common.caching.DeviceCache.findKeysThatStartWith (DeviceCache.kt:325) 
at com.revenuecat.purchases.subscriberattributes.caching.SubscriberAttributesMigrationExtensionsKt.getAllLegacyStoredSubscriberAttributes (SubscriberAttributesMigrationExtensions.kt:40) 
at com.revenuecat.purchases.subscriberattributes.caching.SubscriberAttributesMigrationExtensionsKt.migrateSubscriberAttributesIfNeeded (SubscriberAttributesMigrationExtensions.kt:7) 
at com.revenuecat.purchases.subscriberattributes.caching.SubscriberAttributesCache.cleanUpSubscriberAttributeCache (SubscriberAttributesCache.kt:77) 
at com.revenuecat.purchases.identity.IdentityManager.configure (IdentityManager.kt:30) 
at …
```

Catches NullPointerException on DeviceCache.findKeysThatStartWith

---

CHANGELOG.latest.md
RELEASING.md
fastlane/Fastfile

- Cleaned up the RELEASING.md document. I removed the Manual process stuff, like in the iOS releasing document. Removed references to releasing script.
- Automatically add the version number when attaching the changelog

Release process updates

---

RELEASING.md

We realized we don't have this documented anywhere, so I added some instructions on how we did the hotfix release this morning.

Explains how to release hotfixes in RELEASING.md

---

.circleci/config.yml
library.gradle

Looks like when we added modularization we broke the test results storage in CircleCI. In a multi module project, the test results are stored in `module_name/build/test-results/` so I aded a step that should copy all test results into a single folder.

Adds test results consolidation step

---

feature/google/src/main/java/com/revenuecat/purchases/google/BillingWrapper.kt
feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt

- Add back in the `setObfuscatedAccountId` call only for non-upgrade/downgrade purchases
- See Zendesk ticket containing customer request here: https://revenuecat.zendesk.com/agent/tickets/8987

Set obfuscatedAccountID for non upgrade/downgrade purchase

---

common/src/main/java/com/revenuecat/purchases/common/errors.kt
public/src/main/java/com/revenuecat/purchases/errors.kt

InvalidPackageName was being mapped to StoreProblemError, which is misleading to the user. 
* created a new ConfigurationError type and mapped InvalidPackageName to it
* changed BackendInvalidPlatform to map to ConfigurationError as well
* changed any Apple-specific errors to map to UnexpectedBackendResponseError, since we shouldn't receive those from an Android app
[iOS PR](https://github.com/RevenueCat/purchases-ios/pull/494)

Update InvalidPackageNameError mapping

---

public/src/main/java/com/revenuecat/purchases/PurchaserInfo.kt

The `ReplaceWith` hint for the deprecated `purchasedNonSubscriptionSkus` property was invalid: `nonSubscriptionTransactions` is not a Set, so in order to return a set of identifiers it's necessary to properly transform the `List<Transaction>` into the expected `Set<String>`.

Updated ReplaceWith annotation

---

feature/google/src/main/java/com/revenuecat/purchases/google/BillingWrapper.kt
feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
strings/src/main/java/com/revenuecat/purchases/strings/OfferingStrings.kt

Addresses this ticket: https://spectrum.chat/revenuecat/general/android-crash-sku-must-be-set~7faa56e8-2ec4-4c8d-b37a-2d525c41d8f6?authed=true
BillingClient throws an exception if an empty string sku is passed to querySkuDetailsAsync
* filter out empty skus from the list
* don't bother querying if list is empty 
* unit tests
Also pulled in a unit test fix from the 4.1.0 release -- pulling sha256() out of the verify block

Empty SKU list bug

---

.circleci/config.yml
RELEASING.md
build.gradle
fastlane/Fastfile
gradle/wrapper/gradle-wrapper.properties

Updates the `gradle-maven-publish-plugin` to make use of new `closeAndReleaseRepository` task.
Created a new `upload-and-close-release` job in CircleCI that calls the `closeAndReleaseRepository` task, and renamed the old `deploy` task to `upload-release` to be more specific and consistent.
Not sure if there's really a use case for the old upload-only task, but I wanted to keep it around for testing purposes. I call it from the CircleCI `deploy` workflow for now, but will update that to run `upload-and-close-release` once we've tested the other works as expected.

Update release plugin

---

build.gradle
config/detekt/detekt-baseline.xml
examples/MagicWeather/build.gradle
examples/purchase-tester/build.gradle

JCenter has been sunset https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
The alternative is to add `mavenCentral` instead of jCenter's bintray (https://onesignal.com/blog/android-migrate-jcenter-to-maven-central/). The version of the detekt we were running had a dependency only available in Bintray, so I also updated it to the most recent version which has a dependency available in mavenCentral

Replace jcenter repository with mavenCentral

---

fastlane/Fastfile
fastlane/README.md

I added a function to tag with latest the HEAD after a GitHub release is created from Fastlane. @aboedo brought a good point to indicate that that release might not always be the latest. This PR adds checks to make sure the release is actually the latest. 
In order to do that I checkout the latest branch and check the version and compare.
This made me realize that the CHANGELOG.latest.md will always be attached to the top of CHANGELOG.md, which would not be true for all releases (i.e. hotfixes). But we can solve that in another moment.

More checks when tagging with latest

---

purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt

if you call `sharedInstance` but you haven't configured the SDK yet, the app will crash. 
However, the docs suggested that you'd get a `null` value for `sharedInstance`. This PR updates the docs to reflect the current behavior.

clarify usage of `sharedInstance`

---

common/src/main/java/com/revenuecat/purchases/common/networking/ETagManager.kt
common/src/test/java/com/revenuecat/purchases/common/networking/ETagManagerTest.kt

I realized there's an issue with ETags so this PR disables them.
We use request date to determine if an entitlement is active, which means that we basically check if the entitlement is active at the moment the request is made to determine if we should grant the entitlement. This prevents users from losing access if there's no connectivity. 
The fact that the backend doesn't take into account the request date in order to calculate the hash used for the ETags means that it's possible the SDK keeps using an old cached request with a very old request date, and that we don't mark the entitlements as not active. For example:
- A request is retrieved on 05-26-2021 using ETags. We store the response and we associate it with that ETag. At this moment, the entitlement is active, with an expiration …

Disable ETags

---

fastlane/Fastfile

There were issues when creating the pull request with the bump to next version so I explicitely added some "optional" parameters to the lane and now it's working fine.
The tagging of the latest release was also broken, it was missing an early exit and had some issues switching back to the current branch.

Fix prepare_next_version lane and tagging latest tag

---

public/src/main/java/com/revenuecat/purchases/Offering.kt

addresses https://github.com/RevenueCat/purchases-android/issues/332
The method `getPackage` could throw `NoSuchElementException`, but this behavior wasn't documented. 
I added the `@Throws` annotation.

add `@Throws` to `getPackage`

---

purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/listenerConversions.kt

Makes `logIn` and `logOut` public, deprecates identity v2 methods.

identity V3: public facing changes

---

CHANGELOG.md

Updated release notes for 4.3.0 since it wasn't mentioning an update to the Android Billing Library, from 3.0.2 to 4.0.0.
Relevant commit:
https://github.com/RevenueCat/purchases-android/commit/f6554bbf7376c3fd492f0bc67183a9f35889ae78

Updated 4.3.0 changelog

---

feature/subscriber-attributes/src/main/java/com/revenuecat/purchases/subscriberattributes/AttributionDataMigrator.kt
feature/subscriber-attributes/src/test/java/com/revenuecat/purchases/subscriberattributes/AttributionDataMigratorTests.kt

Super tiny fixes to fix a couple things that I noticed while developing the same feature for iOS.
- First of all I noticed that we were giving preference to the MParticleID instead of the network ID. It should be the other way around.
- There was a duplicated JSON key in one of the JSONs used for testing.
- We didn't have tests for MParticle 🤕

Small fixes on attribution data conversion to subscriber attributes

---

common/src/main/java/com/revenuecat/purchases/common/Backend.kt
common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
strings/src/main/java/com/revenuecat/purchases/strings/NetworkStrings.kt

We are getting some customers calling alias or identify too often. Sometimes with the same parameters. 
Something I have noticed while trying to replicate the issue with this code:
```kotlin
for (i in 1..10) {
if (newUserId != Purchases.sharedInstance.appUserID) {
Purchases.sharedInstance.loginWith {
// Do other stuff
}
}
}
```
Is that most of the times the code will enter in the `if` clause. The reason is that we only update the appUserID when the API call has come back with a result, so the check would most of the times evaluate to the same.
In this PR, I have added the same caching mechanism we currently have for other API calls. It prevents the same calls being executed at the same time with the same parameters. This should prevent apps from hitting our servers with `/alias` and …

Adds callback cache identity

---

common/src/main/java/com/revenuecat/purchases/common/Backend.kt
common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt

I broke the error treatment for unsuccessful `/identify` calls in this PR https://github.com/RevenueCat/purchases-android/pull/358
I was calling `onError` instead of the `onErrorHandler`. I added some tests since we didn't have any tests that could catch this.

Fix onError of unsuccessful /identify calls

---

CHANGELOG.latest.md
CHANGELOG.md
common/src/main/java/com/revenuecat/purchases/common/Config.kt
gradle.properties
library.gradle

- Makes improvements to prevent multiple HTTP requests with the same parameters to `/identify` and `/alias`. 
https://github.com/RevenueCat/purchases-android/pull/358
https://github.com/RevenueCat/purchases-android/pull/359

Prepares release 4.3.2

---

build.gradle
examples/purchase-tester/build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties
integration-tests/build.gradle
library.gradle

Updated to the latest stable version of the Android Gradle plugin 7.0.2 and the build tools version to 3.0.3
Changes introduced by AGP 7 are outlined here https://android-developers.googleblog.com/2020/12/announcing-android-gradle-plugin.html
One of the main changes is that now we require JDK 11. In order to install it, the best way is to use sdkman. Instructions on that are here https://github.com/RevenueCat/purchases-android/blob/e2e4df2db2612d015a41db710e2a2afccd396c19/CONTRIBUTING.md#environment-setup

Update to Android Gradle plugin 7.0.2 and buildToolsVersion 3.0.3

---

library.gradle

This updates robolectric and all of our other out-of-date testing dependencies
Robolectric was the forcing mechanism -- our tests wouldn't build because the version of robolectric that we were on referenced a deprecated maven URL.

Update test dependencies

---

CHANGELOG.latest.md
CHANGELOG.md
common/src/main/java/com/revenuecat/purchases/common/Config.kt
common/src/main/java/com/revenuecat/purchases/common/subscriberattributes/SpecialSubscriberAttributes.kt
gradle.properties
library.gradle
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt

- Added support for Airship integration via `setAirshipChannelID`

Release: 4.4.0

---

purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

Fixes [sc-11021]
Adds an `Purchases.isConfigured` to check if setup has been called.
Should be helpful for folks wanting to prevent https://github.com/RevenueCat/purchases-android/issues/377 when race conditions occur.

Add isConfigured

---

CHANGELOG.latest.md
CHANGELOG.md
common/src/main/java/com/revenuecat/purchases/common/Config.kt
gradle.properties
library.gradle

- Added `isConfigured` to be able to check if there is an instance of Purchases already configured
https://github.com/RevenueCat/purchases-android/pull/378

Version 4.5.0

---

CHANGELOG.latest.md
CHANGELOG.md
common/src/main/java/com/revenuecat/purchases/common/Config.kt
gradle.properties
library.gradle

- Added `EntitlementInfo.ownershipType`, which can be used to determine whether an entitlement was granted by a direct purchase or shared through a family member.
https://github.com/RevenueCat/purchases-android/pull/382
- Added a log warning when `configure` is called with an empty string as `appUserID`, to make it clear that the user will be considered an anonymous user.
https://github.com/RevenueCat/purchases-android/pull/384

release: 4.6.0

---

feature/amazon/src/main/AndroidManifest.xml

Fixes https://github.com/RevenueCat/purchases-android/issues/397
Builds targeting sdk 31 were failing due to missing the "exported" attribute on the amazon ResponseReceiver. Confirmed this via PurchaseTester
See [Behavior Changes](https://developer.android.com/about/versions/12/behavior-changes-12#exported) for more info
Will also hotfix coming for a new amazon alpha...

Add exported tag to receiver to fix builds targeting sdk 31

---

feature/amazon/src/main/AndroidManifest.xml

Same as https://github.com/RevenueCat/purchases-android/pull/402, but based off the latest alpha release tag, `5.0.0-amazon.alpha.3`, in order to make a "hotfix alpha".
Would love input on versioning, though. `5.0.0-amazon.alpha.4` feels like a "major alpha", in which case we might as well release off the `amazon-release` branch. Which I suppose is an option. It has a fair amount of changes, but since these are alphas anyway, maybe a hotfix is overkill?
`5.0.1-amazon.alpha.3` would take precedence over `5.0.0` based on [semver](https://semver.org/#spec-item-11)
I think the best option, if we do a hotfix, is `5.0.0-amazon.alpha.3.0.1` ("A larger set of pre-release fields has a higher precedence than a smaller set, if all of the preceding identifiers are equal.")
Thoughts?

Hotfix: Add exported property to ResponseReceiver

---

feature/amazon/src/main/AndroidManifest.xml

Didn't realize yesterday that this Receiver was in 4.6.0. Even though the receiver isn't "active" since amazon isn't enabled, it'll still cause a build error. 
This will be for a 4.6.1 hotfix.

Add exported attribute to manifest

---

feature/amazon/src/main/AndroidManifest.xml

I was testing this in the amazon-release branch, and in the latest alpha, and fetching products doesn't work unless exported is true.

Changes exported of the Amazon receiver to true

---

.run/All tests.run.xml
.run/Common tests.run.xml

I've added these 2 for now:
But it would be nice to add more, maybe excluding `features` which seem to be slower tests (some of them take several seconds?)
I'll update our [internal docs](https://www.notion.so/revenuecat/Running-Tests-9433d87cd7b94517bc490544202a28d3) when this is merged.

Added run configurations for tests

---

public/src/main/java/com/revenuecat/purchases/CustomerInfo.kt

`jsonObject` was not including in `equals`.
Looks like `JSONObject#equals` doesn't do a recursive equality check, and I think removing it from `hashCode` makes more sense, since the parsed content is already part of it.

Fixed `CustomerInfo#hashCode` not matching `CustomerInfo#equals`

---

common/src/main/java/com/revenuecat/purchases/common/CustomerInfoFactories.kt
strings/src/main/java/com/revenuecat/purchases/strings/OfferingStrings.kt

Depends on #425.
Fixes [sc-11030]. This is equivalent to https://github.com/RevenueCat/purchases-ios/pull/879.
I've also verified that the behavior now matches all the changes in https://github.com/RevenueCat/purchases-ios/pull/879.

`createOfferings`: added log when there are no packages

---

feature/google/src/main/java/com/revenuecat/purchases/google/BillingWrapper.kt
feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
strings/src/main/java/com/revenuecat/purchases/strings/BillingStrings.kt

Fixes [sc-11657]
Related issues:
https://github.com/RevenueCat/purchases-android/issues/381
[community post](https://community.revenuecat.com/sdks-51/react-native-android-app-crash-after-purchase-1016?postid=3155#post3155)
BillingClient expects that the Activity passed into `launchBillingFlow` has a non-null intent. The fix is to detect a null intent and pass a new one in.
I'm unsure whether setting an empty intent could have unwanted side effects...maybe we want to only log here.

Fix null intent crash

---

feature/amazon/src/main/java/com/revenuecat/purchases/amazon/AmazonStrings.kt
feature/amazon/src/main/java/com/revenuecat/purchases/amazon/storeProductConversions.kt
feature/amazon/src/test/java/com/revenuecat/purchases/amazon/PriceExtractorTest.kt
public/src/main/java/com/revenuecat/purchases/models/StoreProduct.kt

We had a report of a weird case:
```
Product{identifier: subscription.amazon.monthly, description: Get Access to everything, title: Full Access, price: 0.0, priceString: US$ 7.99, currencyCode: INR, introductoryPrice: null}
```
With the previous code, that didn't make much sense for multiple reasons. First of all, we get the `currencyCode` straight from the Marketplace:
```
Currency.getInstance(Locale("EN", marketplace)
```
That means that if `currencyCode` is `INR`, marketplace has to be `IN`. That is an obvious inconsistency with what Amazon is sending for `priceString`, which is in `USD`. Amazon always sends the priceString in the currency of the marketplace, so it doesn't make sense to get  `US$ 7.99`. I've also never seen it formatted with a space, which is also strange. 
In any …

Revamp price and currency code extraction for Amazon products

---

purchases/src/main/java/com/revenuecat/purchases/interfaces/GetSkusResponseListener.kt

`skus` does not contain nullable `SkuDetails`. This broke when converting from Java to Kotlin.

Fix GetSkusResponseListener nullability

---

fastlane/Fastfile

Android equivalent of https://github.com/RevenueCat/purchases-ios/pull/1164
Ensures that pre-release builds are marked correctly in GH.

fix: pre-release builds not marked correctly in GH

---

api-tester/build.gradle
build.gradle
library.gradle

We were uploading the api-tester module to sonatype because the publishing plugin was being applied via `library.gradle`

Prevents uploading api-tester to maven

---

feature/google/src/main/java/com/revenuecat/purchases/google/purchaseExtensions.kt

I noticed we are logging about more than one sku being returned when there's only one. Looks like the length check was off by 1.

Fix length check for logging multi-line subs

---

purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

[sc-12368]
isBillingSupported & isFeatureSupported have been deprecated for ~8 months, so this upcoming major feels like a good time to fully remove them.
I repurposed a couple of their tests for canMakePayments to use.

Remove isBillingSupported and isFeatureSupported

---

api-tester/build.gradle
base-application.gradle
examples/MagicWeather/app/build.gradle
examples/purchase-tester-java/build.gradle
examples/purchase-tester/build.gradle
integration-tests/build.gradle

Created a `base-application.gradle` to remove duplicated configuration in the applications we have in the repository.
Suggested by @NachoSoto in https://github.com/RevenueCat/purchases-android/pull/445#discussion_r785022898

Creates a base-application.gradle 

---

examples/MagicWeather/app/build.gradle

In this PR https://github.com/RevenueCat/purchases-android/pull/448 I added a `base-application.gradle` to use as base for all Apps inside the repo. It turns out I broke MagicWeather since MagicWeather is its own project and `rootProject.projectDir` is the root of MagicWeather and not the root of the repository.
I am not sure if it's possible to reference to `base-application.gradle` (maybe using a `../../` path), but I actually thing that since we want MagicWeather to be an isolated sample app, we shouldn't reference anything relatively.

Revert magicweather base-application.gradle changes

---

examples/MagicWeather/app/build.gradle

Updated dependency version to 5.0.0-rc1

Update magicweather dependency to 5.0.0-rc1

---

examples/MagicWeather/app/src/main/java/com/revenuecat/sample/MainApplication.kt
examples/MagicWeather/app/src/main/java/com/revenuecat/sample/data/SampleWeatherData.kt
examples/MagicWeather/app/src/main/java/com/revenuecat/sample/ui/paywall/PaywallFragment.kt
examples/MagicWeather/app/src/main/java/com/revenuecat/sample/ui/user/UserFragment.kt
examples/MagicWeather/app/src/main/java/com/revenuecat/sample/ui/weather/WeatherFragment.kt

I got too excited with updating MagicWeather to 5.0.0-rc1 that I didn't check if it compiled lol
This PR fixes compilation and removes deprecated functions

Update MagicWeather part 2

---

fastlane/Fastfile

We were pointing to the wrong variable when determining if a release is pre-release

Fix is_prerelease

---

purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt

Uses a rev.cat link for the customer info cache docs.

Update doc link to use rev.cat

---

examples/MagicWeather/app/build.gradle
examples/MagicWeather/app/src/main/java/com/revenuecat/sample/MainApplication.kt
examples/MagicWeather/app/src/main/java/com/revenuecat/sample/data/Constants.kt

Update our MagicWeather app to follow best practices for Amazon as outlined in our [docs](https://docs.revenuecat.com/docs/configuring-sdk#initialization)

Add Amazon + example configuration to MagicWeather

---

examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/Constants.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/LoginFragment.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/MainApplication.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OverviewFragment.kt
examples/purchase-tester/src/main/res/layout/fragment_login.xml

[sc-12862]
Fixes the "continue as random user" button in purchase tester -- previously we'd get an error for logging out from anonymous user.
Also:
* pulled API keys into constants and throw exception if no API key set 
* pull out copyToClipboard method for reuse

Fix "continue as random user" purchase tester button

---

integration-tests/build.gradle

Integration tests are failing, appears to be due to our downgrading the compileSdkVersion. We should eventually update everything to compileSdk 30, but that would require more testing

Fix integration tests

---

feature/amazon/src/main/java/com/revenuecat/purchases/amazon/AmazonBilling.kt
feature/amazon/src/main/java/com/revenuecat/purchases/amazon/AmazonStrings.kt
feature/amazon/src/test/java/com/revenuecat/purchases/amazon/AmazonBillingTest.kt
feature/amazon/src/test/java/com/revenuecat/purchases/amazon/BillingFactoryAmazonTest.kt
purchases/src/main/kotlin/com/revenuecat/purchases/BillingFactory.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/test/java/com/revenuecat/purchases/BillingFactoryTest.kt

same as https://github.com/RevenueCat/purchases-android/pull/469, but for billing-client-3

Skip registering listener in Amazon observer mode - billing client 3

---

examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/EntitlementInfoExtensions.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OfferingFragment.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/PackageCardAdapter.kt
examples/purchase-tester/src/main/res/layout/fragment_offering.xml
examples/purchase-tester/src/main/res/layout/package_card.xml
public/src/main/java/com/revenuecat/purchases/Package.kt

Add a purchaseProduct button under the purchasePackage button. 
Also: 
* fix parameter label
* print entitlement ID in active entitlements instead of productID -- was confused why i'd see 2 new active entitlements with the same ID after a single purchase
* fix crash if you navigate back before purchase success toast displays
* add progress bar for purchase in progress

Add purchaseProduct button to purchasetester

---

feature/amazon/src/main/java/com/revenuecat/purchases/amazon/AmazonBilling.kt
feature/amazon/src/main/java/com/revenuecat/purchases/amazon/AmazonStrings.kt

This updates the Amazon observer mode log to point customers to our new syncObserverModeAmazonPurchase. Also downgrades to a warning...since we skip registering the listener and making any calls into the App store anyway, it's not technically broken anymore.

Update Amazon observer mode log

---

.circleci/config.yml
CHANGELOG.latest.md
CHANGELOG.md
common/src/main/java/com/revenuecat/purchases/common/Config.kt
fastlane/Fastfile
fastlane/README.md
gradle.properties
library.gradle

- Skip registering listener in Amazon observer mode
https://github.com/RevenueCat/purchases-android/pull/478
- Add new function (`syncObserverModeAmazonPurchase`) to sync a single Amazon purchase with our backend
https://github.com/RevenueCat/purchases-android/pull/470
- Add DangerousSettings to configure function so automatic syncing of purchases can be disabled. 
Not recommended unless instructed by RevenueCat support.
https://github.com/RevenueCat/purchases-android/pull/451

Release fixing observer mode for Amazon + BillingClient 3 

---

api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt

We provide explicit types in closures to check them.

`PurchasesAPI`: silenced a couple of warnings

---

api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
common/src/main/java/com/revenuecat/purchases/common/logUtils.kt
common/src/main/java/com/revenuecat/purchases/common/logWrapper.kt
common/src/test/java/com/revenuecat/purchases/common/LogHandlerTest.kt
public/src/main/java/com/revenuecat/purchases/LogHandler.kt
purchases/src/main/java/com/revenuecat/purchases/util/AdvertisingIdClient.kt
purchases/src/main/kotlin/com/revenuecat/purchases/AttributionFetcherFactory.kt
purchases/src/main/kotlin/com/revenuecat/purchases/BillingFactory.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt

Fixes [sc-11102].
The default implementation is unchanged, using `android.util.Log`.
Users can provide their own implementation of `LogHandler`.
- `errorLog` can now provide an optional `throwable`, which will be forwarded if set
- Added tests to verify the handler is used
- Removed ad-hoc usage of `Log.e`
- Added API to `apitester`

Added `Purchases.logHandler`

---

purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

We found a small bug in our Amazon implementation.
The Amazon queryPurchases method doesn't return a Purchase State. When we call queryPurchases on app start, we were only posting those with state == PURCHASED to the backend. This means someone migrating to RevenueCat (or without identity after a re-install) won't get their purchases synced.
The fix is to just send all purchases that aren't in the PENDING state (Amazon will be in UNSPECIFIED_STATE). This shouldn't break anything for Play Store, since they properly return a state, which will either be pending or purchased.
[sc-13525]

Fix queryPurchases for Amazon

---

feature/amazon/src/main/java/com/revenuecat/purchases/amazon/handler/ProductDataHandler.kt
feature/amazon/src/main/java/com/revenuecat/purchases/amazon/handler/PurchaseHandler.kt
feature/amazon/src/main/java/com/revenuecat/purchases/amazon/handler/PurchaseUpdatesHandler.kt
feature/amazon/src/main/java/com/revenuecat/purchases/amazon/handler/UserDataHandler.kt
feature/amazon/src/test/java/com/revenuecat/purchases/amazon/handler/ProductDataHandlerTest.kt
feature/amazon/src/test/java/com/revenuecat/purchases/amazon/handler/PurchaseHandlerTest.kt
feature/amazon/src/test/java/com/revenuecat/purchases/amazon/handler/PurchaseUpdatesHandlerTest.kt
feature/amazon/src/test/java/com/revenuecat/purchases/amazon/handler/UserDataHandlerTest.kt

[CF-241]
[CF-241]: https://revenuecats.atlassian.net/browse/CF-241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
I noticed offerings were not loading. Products were failing to load. There was no exceptions or anything. But after a lot of debugging I found this little gem in Amazon's code:
```
try {
if (var1 instanceof ProductDataResponse) {
var3.onProductDataResponse((ProductDataResponse)var1);
} else if (var1 instanceof UserDataResponse) {
var3.onUserDataResponse((UserDataResponse)var1);
} else if (var1 instanceof PurchaseUpdatesResponse) {
var3.onPurchaseUpdatesResponse((PurchaseUpdatesResponse)var1);
} else if (var1 instanceof PurchaseResponse) {
var3.onPurchaseResponse((PurchaseResponse)var1);
} else {
e.b(c.a, "Unknown response type:" + …
```

CF-241  Amazon is swallowing all exceptions that happen in the listeners

---

common/src/main/java/com/revenuecat/purchases/common/logUtils.kt

We were missing some cases in a when statement. I noticed when upgrading Kotlin version in https://github.com/RevenueCat/purchases-android/pull/474 . More recent versions of Kotlin will fail when missing cases in a when statement.

Adds missing cases to when statement in errorLog mapping

---

examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OverviewViewModel.kt

I was getting a crash when customerinfo was null. Not sure why the compiler didn't catch that the CustomerInfo was nullable when we set the value to null explicitly... 🤷‍♀️  i suppose it's a livedata bug.

Fix purchasetester crash

---

.circleci/config.yml
.gitignore
build.gradle
docs/index.html
fastlane/Fastfile

updates the output directory for dokka to include the version number. 
This is the low-tech implementation. 
A high-tech implementation would be to use the [Versioning plugin](https://kotlin.github.io/dokka/1.4.30/user_guide/versioning/versioning/), but that might take a lot more effort to set up, so in the meantime, the idea is to manually update the docs in S3 for the first time, and use this to generate them in the correct subfolder until we get the high-tech implementation in place. 
Fixes [CF-99]
[CF-99]: https://revenuecats.atlassian.net/browse/CF-99?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CF-99: Separate docs per version

---

purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt

[CF-363]
Google made the following announcement:
- If you use an advertising ID, you must declare the [AD_ID Permission](https://notifications.google.com/g/p/AD-FnExFIeKajosxiqsy-MrtrabL2IRO46OkDhHL5JATpByWtiYnmwUkWjBU9SNEglAg1dTndpYpRdwFPTHngDRvAmID5fVENY2rokXEF4_unFfRfkopSis-08ixU-I2QV8hiAcCQlw71iOZ6PbMO7DevUQY) when your app targets Android 13 or above. Apps that don’t declare the permission will get a string of zeros. Note: You’ll be able to target Android 13 later this year.If your app’s [target audience](https://notifications.google.com/g/p/AD-FnEyCHyziYRF-dBi6BcDI0-9ibYDScV6buzW0DGqRw3WPuPCPEkyJPpq1Cmx1fPOUL1Adc5l3Piow1cAVT1hxRCanA8WE5zZjfSRqD50uTaWqAUKHQXLEgqWwEIGUGamlx2P3ZGFJcR_6SoEKhjlzJ0r4) includes children, you must not transmit Android Advertising ID (AAID) from children or …

Adds warnings for collecting Advertising ID

---

docs/index.html

I think this change got merged by mistake in https://github.com/RevenueCat/purchases-android/pull/504/files#diff-b04b38d4e36f7a7171aeb211bf933eaf36d41d9866ebbc3639f673f84dc350aeR4
It should match the current version, so when deploying 5.0.0 docs broke and trying to access https://sdk.revenuecat.com/android/index.html gives a broken website.

Fix docs version in redirect html

---

migrations/v5-MIGRATION.md

- Renamed `Amazon Store` to `Amazon Appstore`
- Add missing `with` prefix to kotlin helper `purchasePackageWith` functions

Updates migration guide

---

api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
common/src/main/java/com/revenuecat/purchases/common/subscriberattributes/SpecialSubscriberAttributes.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt

We added support for setting the [Mixpanel Distinct ID](https://docs.revenuecat.com/docs/mixpanel) as a subscriber attribute, so we should have a convenience setter.
- Adds new reserved attribute for Mixpanel
- Adds new SubscriberAttributeKey class: `IntegrationIds` (Mixpanel isn't an attribution network, and shouldn't be categorized into the `AttributionIds`)
- Adds new convenience setter for the Mixpanel attribute
- Adds new tests flow for IntegrationIds (`integrationIDTest`)

Adds Mixpanel method and adds structure for integration IDs

---

purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/listenerConversions.kt

We were missing docs in a couple functions. I also made more clear that product changes don't work in Amazon Appstore.

Adds missing purchaseProduct and purchasePackage docs

---

CHANGELOG.latest.md
CHANGELOG.md
common/src/main/java/com/revenuecat/purchases/common/Config.kt
common/src/main/java/com/revenuecat/purchases/common/ReceiptInfo.kt
gradle.properties
library.gradle
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

We need to add currency and price to the `syncObserverModeAmazonPurchase` so we can track it

[On top of billing-client-3-amazon branch] Fix for Amazon observer mode missing price and currency

---

common/src/main/java/com/revenuecat/purchases/common/subscriberattributes/SpecialSubscriberAttributes.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt

For [CF-473](https://revenuecats.atlassian.net/browse/CF-473?atlOrigin=eyJpIjoiYjMyMmE2ZTY3Y2M5NDUwMjllODFhYjIxNmJmMjNjMTQiLCJwIjoiaiJ9)
OneSignal and Airship aren't attribution providers, but we were treating them as such and setting attributes that are not necessary for the integrations to function correctly.
Migrates OneSignal and Airship attributes to be `IntegrationIds` instead of `AttributionIds`, and tweaks how we're setting the attributes from the `subscriberAttributesManager` to only set the single attributes needed for the integrations.

Migrate OneSignal and Airship to IntegrationIds instead of AttributionIds

---

api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
common/src/main/java/com/revenuecat/purchases/common/subscriberattributes/SpecialSubscriberAttributes.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt

For CF-566
We have convenience setter methods for reserved attributes, and `$firebaseAppInstanceID` is another reserved attribute that needs a setter.
Adds new public method to Purchases: `setFirebaseAppInstanceID`

New public convenience setter for Firebase app instance ID

---

feature/amazon/src/main/java/com/revenuecat/purchases/amazon/AmazonStrings.kt
feature/amazon/src/main/java/com/revenuecat/purchases/amazon/handler/ProductDataHandler.kt
feature/amazon/src/main/java/com/revenuecat/purchases/amazon/storeProductConversions.kt
feature/amazon/src/test/java/com/revenuecat/purchases/amazon/AmazonBillingTest.kt
feature/amazon/src/test/java/com/revenuecat/purchases/amazon/ProductConverterTest.kt
feature/amazon/src/test/java/com/revenuecat/purchases/amazon/handler/PurchaseHandlerTest.kt
feature/amazon/src/test/java/com/revenuecat/purchases/amazon/helpers/dummies.kt

If devs set the parent subscription instead of the term in the dashboard, Amazon will not provide a price (which makes sense since only terms have price) and we will crash when trying to get the product.
This PR prevents the crash and adds a nicer error message

Better error when Amazon price is missing

---

common/src/main/java/com/revenuecat/purchases/common/Backend.kt
common/src/main/java/com/revenuecat/purchases/common/HTTPClient.kt
common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
feature/amazon/src/main/java/com/revenuecat/purchases/amazon/AmazonBilling.kt
feature/amazon/src/main/java/com/revenuecat/purchases/amazon/paymentTransactionConversions.kt
feature/amazon/src/test/java/com/revenuecat/purchases/amazon/AmazonBackendTest.kt
feature/amazon/src/test/java/com/revenuecat/purchases/amazon/AmazonBillingTest.kt
feature/amazon/src/test/java/com/revenuecat/purchases/amazon/ReceiptToStoreTransactionTest.kt
feature/google/src/main/java/com/revenuecat/purchases/google/paymenTransactionConversions.kt
public/src/main/java/com/revenuecat/purchases/models/StoreTransaction.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt
purchases/src/testLatestDependencies/java/com/revenuecat/purchases/PostingTransactionsTestsBillingClient4.kt

We have been getting reports of wrong prices for Amazon transactions. This PR adds a header that would send whatever we get from the Amazon SDK as a header so we can do better debugging.

Adds price string header to post receipt call

---

purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt

Upgrading the Kotlin version triggers a compilation error. We were comparing a PurchasesError against error codes.

Fix log when failing to fetch offerings

---

feature/amazon/src/main/java/com/revenuecat/purchases/amazon/storeProductConversions.kt
feature/amazon/src/test/java/com/revenuecat/purchases/amazon/PriceExtractorTest.kt

We had a test that covered this, but the code behaves differently in an Android device and during unit testing.
I thought I was crazy, but https://stackoverflow.com/questions/27402616/how-to-get-plain-price-value-with-amazon-in-app-purchasing-api#comment43795089_27449971 this comment corroborates my theory.
We have to migrate this test to be instrumented but I encountered a bunch of issues doing that:
- Adding a simple instrumented test brings the number of methods above 64k, which means we need to enable multidex.
- After enabling multidex I started getting Java out of memory errors when compiling.
- I gave more memory allocation to the JVM and then Kotlin started to fail so I had to increase the Kotlin version
- I looked into some dependencies we have using a dependencies plugin and …

Fix price parsing of prices with "nbsp" characters

---

base-application.gradle
build.gradle
library.gradle
public/build.gradle
public/src/main/java/com/revenuecat/purchases/CustomerInfo.kt
public/src/main/java/com/revenuecat/purchases/EntitlementInfo.kt
public/src/main/java/com/revenuecat/purchases/EntitlementInfos.kt
public/src/main/java/com/revenuecat/purchases/Offering.kt
public/src/main/java/com/revenuecat/purchases/Offerings.kt
public/src/main/java/com/revenuecat/purchases/Package.kt
public/src/main/java/com/revenuecat/purchases/PurchaserInfo.kt
public/src/main/java/com/revenuecat/purchases/models/StoreProduct.kt
public/src/main/java/com/revenuecat/purchases/models/StoreTransaction.kt
public/src/main/java/com/revenuecat/purchases/models/Transaction.kt
public/src/main/java/com/revenuecat/purchases/parceler/JSONObjectParceler.kt
purchases/build.gradle

https://revenuecats.atlassian.net/browse/CSDK-123
`kotlin-android-extensions` was deprecated a while back. We only used the `parcelize` functionalities of that plugin, which were moved to the `kotlin-parcelize` plugin. With this PR we use that new plugin. In order to use the new plugin I had to update our kotlin version from 1.4.10 to 1.4.20. Didn't see any changes there that should cause problems 
The changes mostly involved changing the imports to the new package.

Migrate from kotlin-android-extensions to kotlin-parcelize

---

purchases/src/main/kotlin/com/revenuecat/purchases/BillingFactory.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesFactoryTest.kt

https://revenuecats.atlassian.net/browse/CSDK-101
This PR moves the creation of the `Purchases` object to a factory class. This allows us to test the validation logic that happens during this process. In the future, it might be good to test the whole process, but for that, we will need to create factories for the different objects that are created during this initialization process which might take a bit longer. I judged the value of that not to be that big considering there is no more logic on that part of the code aside from the validations which are already tested with these changes.

Extract Purchases creation logic to factory to improve testability

---

build.gradle
common/build.gradle
examples/purchase-tester/build.gradle
feature/amazon/build.gradle
feature/google/build.gradle
feature/identity/build.gradle
feature/subscriber-attributes/build.gradle
integration-tests/build.gradle
library.gradle
public/build.gradle
purchases/build.gradle
utils/build.gradle

We are adding a bunch of dependencies that are unused on each module. This PR removes some of the easier to remove dependencies. I also removed all the dependencies from `library.gradle` since those are imported on every module. I feel that dependencies belong to each module but lmk if you think otherwise.

Remove some of the unused dependencies for tests in each module

---

purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/deprecatedListenerConversions.kt
purchases/src/main/kotlin/com/revenuecat/purchases/listenerConversions.kt

https://revenuecats.atlassian.net/browse/CSDK-300
This removes all private typealiases from the public api so Dokka can generate the docs appropriately. 
This is an example of how it looks:

Remove private typealiases to fix generated documentation

---

purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
strings/src/main/java/com/revenuecat/purchases/strings/ConfigureStrings.kt

Android equivalent to https://github.com/RevenueCat/purchases-ios/pull/1749

added a log when `autoSyncPurchases` is disabled

---

feature/google/src/main/java/com/revenuecat/purchases/google/BillingWrapper.kt
feature/google/src/testLatestDependencies/java/com/revenuecat/purchases/google/BillingWrapperTestBillingClient4.kt

Checking our code against [Google's example](https://github.com/android/play-billing-samples/blob/8f8792fe23e343883984f361a5ecb56e70653911/TrivialDriveKotlin/app/src/main/java/com/sample/android/trivialdrivesample/billing/BillingDataSource.kt#L151), it strikes me that there are a couple of instances where we're not actively retrying the connection, but Google is (and it seems reasonable). 
So I added those cases. 
https://revenuecats.atlassian.net/browse/CSDK-302
Another attempt at solving https://github.com/RevenueCat/purchases-android/issues/553

[CSDK-302] Fix: attempt to reconnect when billing response is error

---

purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt

This should deal with https://github.com/RevenueCat/purchases-hybrid-common/issues/176
The issue was added here: https://github.com/RevenueCat/purchases-android/commit/2bed17a041994cedf7e370d0f186c1d7b0fce078#diff-e019410c58657f001e6ba8be4f066c84c928f4e017ae3b3b6366cebfd64b9716R1251
Basically, we use the `dispatch` method during the `init` function, which requires the `handler` to not be null. However, `init` will be called before `handler` has been initialized, according to https://stackoverflow.com/a/33689543. Now, we weren't able to repro this locally because we initialize `Purchases` in the main thread for all our tests, and this issue will only happen if we initialize the sdk on a different thread.

Fix issue with handler not being initialized on time on Purchases initialization

---

integration-tests/build.gradle

Followup to #566 
This fixes the integration tests so they run normally. With the change to `compileOnly`, we didn't have the billing client during integration tests for unity: https://app.circleci.com/pipelines/github/RevenueCat/purchases-android/2925/workflows/f31a6715-2198-4451-8e21-63b4e7ef9886/jobs/7226

Add missing dependency from integration tests

---

.circleci/config.yml
CHANGELOG.latest.md
CHANGELOG.md
common/src/main/java/com/revenuecat/purchases/common/Config.kt
docs/index.html
gradle.properties
library.gradle

* Updates the `unityIAP` build flavor so we don't include the billing client directly
* https://github.com/RevenueCat/purchases-android/pull/566
* Fixes issue where SDK could not be initialized on a thread other than the main thread
* https://github.com/RevenueCat/purchases-android/pull/568

Release: 5.3.0

---

feature/identity/src/main/java/com/revenuecat/purchases/identity/IdentityManager.kt
feature/identity/src/test/java/com/revenuecat/purchases/identity/IdentityManagerTests.kt
feature/subscriber-attributes/src/main/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesManager.kt
feature/subscriber-attributes/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesManagerTests.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

https://revenuecats.atlassian.net/browse/CSDK-76
In this PR we modify the behavior during login and logout so we sync all unsynced subscriber attributes with the backend before actually performing the login/logout. I inspired the implementation on the iOS implementation here: https://github.com/RevenueCat/purchases-ios/pull/1716

Sync subscriber attributes before login and logout

---

feature/google/src/main/java/com/revenuecat/purchases/google/BillingWrapper.kt
feature/google/src/test/java/BillingWrapperTest.kt

This is a step to prepare for the BillingClient 5 update. `queryPurchases` is obsoleted in BC5, replaced with an async version (deprecated in 5).
The deprecated async function will eventually be replaced with the new one, accepting a different parameter type. But migrating to the async version (and remaining on BC4) is a testable step. Once we feel the async code is clean, upgrading to the BC5 version will be easier.
This is definitely a little messy with all the nested callbacks and makes me wonder if we should start using coroutines internally..
Note: this is PR'ed into the `drop-bc3-support` branch, which I'll be using for BC5 work. We are waiting to merge that until Unity has updated their IAP plugin to BC4.

[CF-822] Use queryPurchaseAsync

---

purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt

After this change: https://github.com/RevenueCat/purchases-android/commit/2bed17a041994cedf7e370d0f186c1d7b0fce078#diff-e019410c58657f001e6ba8be4f066c84c928f4e017ae3b3b6366cebfd64b9716R1251 we run into a couple of issues. 
- First one happened during the `init` of `Purchases` and was fixed here: https://github.com/RevenueCat/purchases-android/pull/568. 
- We received another report (https://github.com/RevenueCat/purchases-flutter/issues/408) which seems related since it's also caused by a null `mainHandler`.
I couldn't find the cause for this second issue after trying a few things, so I'm reverting that change for now.

Revert handler nullability change

---

fastlane/Fastfile

Fixes: Could not find action, lane or variable 'release_version'. Check out the documentation for more details: https://docs.fastlane.tools/actions
resolves [SDKONCALL-83]
[SDKONCALL-83]: https://revenuecats.atlassian.net/browse/SDKONCALL-83?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Pass along release_version variable

---

.circleci/config.yml

resolves [SDKONCALL-84]
[SDKONCALL-84]: https://revenuecats.atlassian.net/browse/SDKONCALL-84?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
It seems that CircleCI is calling:
`prepare_next_version` with no options, so the check here:
```
lane :prepare_next_version do |options|
create_next_snapshot_version(
current_version: current_version_number,
repo_name: repo_name,
github_pr_token: ENV["GITHUB_PULL_REQUEST_API_TOKEN"],
files_to_update: files_with_version_number,
branch: options[:branch] || 'main'
)
end
```
`branch: options[:branch] || 'main'` is falling back to main. When we're deploying from a tag, we're not on main.

Pass $CIRCLE_BRANCH to prepare_next_version

---

.circleci/config.yml
Gemfile.lock
fastlane/Fastfile

Updates to latest fastlane plugin with this change: https://github.com/RevenueCat/fastlane-plugin-revenuecat_internal/pull/12. Now we won't validate the current branch when running the `prepare_next_version` lane.

Update latest fastlane plugin

---

README.md
examples/MagicWeather/README.md

- [ x ] If applicable, unit tests
- [ x ] If applicable, create follow-up issues for `purchases-ios` and hybrids
The main README was tweaked to be consistent with the purchases-ios README and to point to the MagicWeather example app. The MagicWeather README was written to be consistent with the iOS example app README (with Android instructions). 
The changes to the main README were mainly changes in the ordering of information or adding additional links to docs.revenuecat.com
The MagicWeather README was written using the purchases-ios README as a template. Screenshots of steps in Android Studio are included.
I pulled the most current repo and got MagicWeather working on a simulator using the instructions written.

Update README and add MagicWeather README

---

api-tester/src/main/java/com/revenuecat/apitester/java/TransactionAPI.java
api-tester/src/main/java/com/revenuecat/apitester/kotlin/TransactionAPI.kt
common/src/test/java/com/revenuecat/purchases/common/CustomerInfoTest.kt
public/src/main/java/com/revenuecat/purchases/CustomerInfo.kt
public/src/main/java/com/revenuecat/purchases/PurchaserInfo.kt
public/src/main/java/com/revenuecat/purchases/models/Transaction.kt
public/src/test/java/com/revenuecat/purchases/common/models/TransactionTest.kt

This is the first PR in https://revenuecats.atlassian.net/browse/CSDK-409. We want to rename `Transaction.revenueCatId` and `Transaction.productId` to `Transaction.transactionIdentifier` and `Transaction.productIdentifier` respectively. This adds those properties and deprecates the old properties to be removed in a future release.

Rename revenueCatId and productId to transactionIdentifier and productIdentifier. Deprecate old properties

---

.gitignore
Gemfile.lock
RELEASING.md

There was an issue during the `prepare_next_version` job: https://app.circleci.com/pipelines/github/RevenueCat/purchases-android/3021/workflows/dc01939b-d2b3-43d9-b0c9-1ab0df5bf070/jobs/7463. This was because there were some CircleCI only folders that caused git to be dirty and fail the process. We are adding those to `.gitignore` so it's not a problem anymore. 
Additionally, this PR updates the releasing documentation and the fastlane plugin to the lastest version.

Fix prepare next version

---

examples/purchase-tester/build.gradle
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/LoginFragment.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/MainActivity.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OfferingCardAdapter.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OfferingFragment.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OverviewFragment.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/PackageCardAdapter.kt

In order to test internally using the `purchase-tester` sample app, I was running into difficulties since we don't have a good setup for that app in the RC dashboard nor on the play console. This PR changes the package name of that app from `com.revenuecat.purchase_tester` to `com.revenuecat.purchases_sample` so we can reuse the existing setup we have in RC and the play console for that app.
Note that I didn't rename the actual code package name, since using an underscore in a package name is not recommended...
**Important Note:** this will cause apps with the same package name in other repos to overwrite each other. I think it's an acceptable compromise but lmk if you think otherwise

Rename package name of purchase tester app to com.revenuecat.purchases_sample

---

api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
build.gradle
feature/google/src/test/java/BillingWrapperTest.kt
public/src/main/java/com/revenuecat/purchases/BillingFeature.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

This is the first PR of the BillingClient 5 changes. It updates the version and fixes breaking changes, but does not yet take advantage of any of the new APIs.
Note that I'm going to keep BC5 stuff on the billing-client-5 branch for now.

BillingClient 5 Update

---

.circleci/config.yml
api-tester/build.gradle
base-application.gradle
build.gradle
common/build.gradle
docs/index.html
feature/amazon/build.gradle
feature/google/build.gradle
integration-tests/build.gradle
library.gradle
public/build.gradle
purchases/build.gradle
test-utils/build.gradle

This adds a new flavor to our setup, `bc5SupportDev`. This flavor will be used for all the work to support BC5. We won't be releasing this as a library, only work on it internally.
* Note 1: this will increase tests runtime by 50%... For devs, if you want to run tests on a single flavor/variant I suggest doing something like this: `./gradlew testLatestDependenciesReleaseUnitTest`
* Note 2: This is pointing to the `billing-client-5` branch. We can probably merge that branch soon and work off main.

Add bc5SupportDev flavor

---

feature/subscriber-attributes/src/main/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesManager.kt
feature/subscriber-attributes/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesManagerTests.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/test/java/com/revenuecat/purchases/PostingTransactionsTests.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt

Second attempt at dealing with https://revenuecats.atlassian.net/browse/CSDK-433
In this approach, we are adding an observable to know whether there is an ongoing operation to get device identifiers. Once all ongoing operations are done, we can get the unsubscribed attributes, which would include device identifiers.

Wait to obtain unsubscribed attributes until finishing getting device identifiers

---

common/src/main/java/com/revenuecat/purchases/common/AppConfig.kt
common/src/test/java/com/revenuecat/purchases/common/AppConfigTest.kt

`packageName` was added in #618 but we didn't add it to the `equals` and `toString` method. This adds it to those missing methods.

Add missing packageName to helper methods in AppConfig

---

fastlane/Fastfile

If the fastlane plugin indicates we should skip the release, we were not actually skipping and we were creating the PR, as we. noticed in #623. This should avoid creating unnecessary releases

Not create release if next version should be skipped

---

.circleci/config.yml
RELEASING.md

This change lets you run a pipeline manually from CircleCI using the Trigger Pipeline feature

Adds action parameter to CircleCI config to be able to trigger the automatic bump manually

---

feature/amazon/src/main/java/com/revenuecat/purchases/amazon/AmazonBilling.kt
feature/amazon/src/main/java/com/revenuecat/purchases/amazon/AmazonStrings.kt
feature/amazon/src/main/java/com/revenuecat/purchases/amazon/handler/ProductDataHandler.kt
feature/amazon/src/main/java/com/revenuecat/purchases/amazon/handler/UserDataHandler.kt
feature/amazon/src/test/java/com/revenuecat/purchases/amazon/handler/ProductDataHandlerTest.kt
feature/amazon/src/test/java/com/revenuecat/purchases/amazon/handler/UserDataHandlerTest.kt

https://revenuecats.atlassian.net/browse/CSDK-452
In certain situations, Amazon fails silently and doesn't return anything for the requests. For example, when enabling [sandbox mode ](https://developer.amazon.com/docs/in-app-purchasing/iap-app-tester-user-guide.html#installtester) and using the version from Live App testing. In those situations, we want to add a timeout to the requests so it doesn't get stuck and we show a meaningful error log. I added it to both the `getUserData` and `getProducts` requests.

Add timeout to Amazon's getProducts and getUserData requests

---

examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/ConfigureFragment.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/MainApplication.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/TesterLogHandler.kt
examples/purchase-tester/src/main/res/layout/fragment_configure.xml
examples/purchase-tester/src/main/res/navigation/nav_graph.xml
examples/purchase-tester/src/main/res/values/colors.xml
examples/purchase-tester/src/main/res/values/strings.xml

First PR for https://revenuecats.atlassian.net/browse/CSDK-483
In this PR we are adding a new screen at the start of purchase tester where we can configure the SDK before it's initialized. This will allow us to not need to build the SDK to test with different API keys and proxy URLs. The app will always start on this screen and it will move to the login fragment once it's configured. The SDK won't be automatically initialized on app open anymore. Instead, it will be initialized after completing this screen.
Additionally, this PR also makes error logs show as Toasts. Since we intend to use this app from the play store test tracks, being able to see logs without a computer would be useful. However, i thought all logs would need a different system so for now I'm just showing error logs as …

Add configuration fragment to purchase tester

---

examples/purchase-tester/build.gradle
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/ConfigureFragment.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/DataStoreUtils.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/SdkConfiguration.kt

https://revenuecats.atlassian.net/browse/CSDK-483
Followup to #632. In this PR we store the sdk configuration from the configuration screen in DataStore so it's prefilled next time the user opens the app. This PR uses coroutines and DataStore instead of using the old SharedPreferences system.

Store purchase tester sdk configuration in DataStore

---

.circleci/config.yml
base-application.gradle
common/build.gradle
feature/amazon/build.gradle
feature/google/build.gradle
library.gradle
public/build.gradle
purchases/build.gradle
test-utils/build.gradle

Part of https://revenuecats.atlassian.net/browse/CF-969
Removing `bc5DevSupport` flavor from `main`. The flavor will be moved to `latestDependencies` in a new branch
I didn't remove any code in this PR on purpose, those files will be moved to the `main` folder in the `bc5-support` branch. They have already been reviewed so I didn't want to remove them

Remove bc5DevSupport flavor from main

---

.circleci/config.yml

The `assemble-sample-app` job didn't work very well until it was fixed in https://github.com/RevenueCat/purchases-android/pull/639. This job builds the purchase tester app on every commit. Before this PR, we were only storing the latestDependencies release build as an artifact. This adds the debug version of latestDependencies since it can be useful while developing bc5. 
Note that this will increase our space usage a lot, since this happens on every commit to every branch. I thought about limiting it to run only on main (or at least, only store artifacts on main), but I thought I would leave it until it becomes a problem, and we can reevaluate then.

Store debug builds of purchase tester on each commit

---

fastlane/Fastfile

I accidentally broke creating the GitHub release during a deploy in https://github.com/RevenueCat/purchases-android/commit/1b1f647bf0e924bd24fa79f5311d5ccb8cd08b60#diff-dff4b99d4e651ab9d7597876ec8dbe92aa934e42c0fb55f4aadd6c106fc96688L152

Fix GitHub releases not being created 

---

.circleci/config.yml

To prevent deploying something that fails on integration tests, I think the deploy job should go after the integration tests are finished

Moves hold job after integration tests

---

feature/google/src/test/java/com/revenuecat/purchases/google/ParcelableTests.kt
feature/google/src/test/java/com/revenuecat/purchases/google/StoreProductTest.kt
test-utils/src/main/java/com/revenuecat/purchases/utils/billingClientStubs.kt

With BC5, classes like `ProductDetails`, `OneTimePurchaseOfferDetails`, `SubscriptionOfferDetails` don't have a public constructor. So unfortunately we are forced to mock those classes for our tests instead of relying on the original implementation :( 
This PR adds an initial version of these mocks and comments out some tests that won't work easily after changing to use mocks.

Use mocks for BC5 purchase classes since constructor is not public anymore

---

feature/google/src/main/java/com/revenuecat/purchases/google/BillingWrapper.kt
feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
test-utils/src/main/java/com/revenuecat/purchases/utils/billingClientStubs.kt

This fixes part of the existing tests that were broken in #662 , specifically those in `BillingWrapperTests`. I still need to fix tests in `PurchasesTests` and add the new tests, but I thought I would do this in several PRs so it doesn't end up with a huge PR

Fix existing BillingWrapper unit tests related to purchasing

---

api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/listenerConversions.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

This PR follows up on #662 to add the new API to the listener helper methods in Kotlin. This also moves the tests currently using those helper methods to use the new ones, though we have still added some to keep coverage on the deprecated methods.

Bc5 add new listener helper methods

---

api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
feature/google/src/main/java/com/revenuecat/purchases/google/BillingWrapper.kt
feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/listenerConversions.kt
purchases/src/test/java/com/revenuecat/purchases/PostingTransactionsTests.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
test-utils/src/main/java/com/revenuecat/purchases/utils/billingClientStubs.kt

In this PR we:
- Fix issue where we weren't calling the listener if we had errors when launching the billing flow.
- Fix tests in `PurchaseTests` related to the changes in #662 .
- Fix a couple of detekt issues.
- Add some new tests to `BillingWrapperTests`

BC5 Continue fixing purchase tests and add missing BillingWrapper tests

---

examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OfferingFragment.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/PackageCardAdapter.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/PurchaseOptionExtensions.kt
examples/purchase-tester/src/main/res/layout/package_card.xml
examples/purchase-tester/src/main/res/values/strings.xml

https://revenuecats.atlassian.net/browse/CF-971
Allows to visualize and choose different PurchaseOptions in purchase tester sample app.
https://user-images.githubusercontent.com/808417/200937963-38842dc1-78cc-479a-b168-eaee6248c1d1.mp4

[BC5] Support PurchaseOptions in purchase tester app

---

feature/subscriber-attributes/src/main/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesManager.kt
feature/subscriber-attributes/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesManagerTests.kt

https://revenuecats.atlassian.net/browse/CSDK-520
This issue could happen in any situation in which we try to get unsynced subscriber attributes before getting device identifiers. For example, if we called `collectDeviceIdentifiers` or one of the set attribution ID methods after calling  `logIn`. In those cases, the completion blocks from getting unsynced subscriber attributes could be called twice. This could also cause us to send these attributes multiple times to the backend among other side effects. This issue was introduced in #604.

Fix for calling getUnsyncedSubscriberAttributes callback twice

---

feature/identity/build.gradle
feature/subscriber-attributes/build.gradle

Remove unnecessary appcompat dependency from feature modules. This isn't needed there and only used in the apps (purchase-tester, MagicWeather and integration tests) which already include the dependency.

Remove unnecessary appcompat dependency

---

common/src/main/java/com/revenuecat/purchases/common/OfferingFactories.kt
common/src/test/java/com/revenuecat/purchases/common/OfferingsTest.kt
feature/google/src/main/java/com/revenuecat/purchases/google/purchaseOptionConversions.kt
public/src/main/java/com/revenuecat/purchases/Package.kt
public/src/main/java/com/revenuecat/purchases/models/GooglePurchaseOption.kt
public/src/main/java/com/revenuecat/purchases/models/PurchaseOption.kt
test-utils/src/main/java/com/revenuecat/purchases/utils/productStubs.kt

[CF-1020]
Use basePlanId and subscriptionId from the package definition to map subscriptionOfferDetails objects to a package instead of subscriptionId and duration
[CF-1020]: https://revenuecats.atlassian.net/browse/CF-1020?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BC5] Map packages to SubscriptionOfferDetails using basePlanId instead of duration

---

purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

We were still using the old `platform_product_group_identifier` when getting offerings

[BC5] Fix offerings

---

common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
test-utils/src/main/java/com/revenuecat/purchases/utils/productStubs.kt

This is some BackendTest cleanup work I did in the process of writing postReceipt tests. I will put the new postReceipt tests in a separate PR for easier review
It might be easiest to step through the commits, but this PR:
* rearranges BackendTest into regions based on call (perhaps in the future we should have separate files altogether)
* uses a `basicReceiptInfo` variable instead of re-creating everywhere
* utilizes the new stubStoreProduct method instead of the old mockStoreProduct
* updates stubStoreProduct to pass the duration through to downstream stub methods
* renames sku->productId in PurchasesTest
things still aren't building here, and there shouldn't really be functional changes besides a slightly different stubbed storeproduct now...

Backend test cleanup

---

purchases/src/main/kotlin/com/revenuecat/purchases/FeatureLockUtils.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt
test-utils/src/main/java/com/revenuecat/purchases/utils/billingClientStubs.kt

https://revenuecats.atlassian.net/browse/CF-989
For the first BC5 beta, not all features will be available. We will document this for our beta users but additionally, it's good to try to fail early if beta users try to use unsupported features. This PR adds some checks so we fail as early as possible when using any of these unsupported features.

Disable unsupported features for first BC5 beta

---

common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
test-utils/src/main/java/com/revenuecat/purchases/utils/productStubs.kt

We had a postReceipt() method called in `BackendTest` that I found a little confusing to work with. It calls both mockPostReceiptResponse and then posts to the backend. We had duplicate code mocking/posting for the tests using the asyncBackend.
This PR:
* renames postReceipt to make more clear that it is a test function
* update it to take a backend parameter so it can be reused for asyncBackend calls
* removes the fetchToken as a return value -- it was just hard-coded every time anyway
* update stubStoreProduct to not take in duration, since that's a pricingphase idea
tests for postReceipt will still be in a different PR, this was just some clean up to make those easier to add

Refactor postReceipt helper method

---

common/src/main/java/com/revenuecat/purchases/common/Backend.kt
common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
common/src/test/java/com/revenuecat/purchases/common/OfferingsTest.kt
feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
purchases/src/test/java/com/revenuecat/purchases/PostingTransactionsTests.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

* fix a couple build errors in unit tests
* updates `PostingTransactionTests` to use new stubStoreProduct method
* adds a couple missing tests to `PostingTransactionsTests`, including one for pricing phases being sent
* uses `stubStoreProduct` in a few leftover PurchasesTests

fix build errors and add postReceipt PostingTransactionsTests

---

purchases/consumer-rules.pro

Should prevent https://github.com/RevenueCat/purchases-flutter/pull/547 everywhere. Longer explanation in that other PR

Added androidx.lifecycle.DefaultLifecycleObserver to consumer-rules.pro

---

api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OfferingFragment.kt
migrations/v6-MIGRATION.md
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/listenerConversions.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

This PR is a first step towards the latest API we talked about in the last meeting.
- Undeprecate `purchaseProduct` and `purchasePackage` which meant to be used with INAPP products, and when used with subscriptions, it will choose a default `purchaseOption` (logic on this TBD).
- Removed old `purchaseProductOption` and `purchasePackageOption` in favor of `purchaseSubscriptionOption`. This is meant only for subscriptions so devs can choose their own subscription option. Currently it requires a `StoreProduct` + `PurchaseOption` but the intention is to remove the `StoreProduct` parameter which deserves it's own big PR.

[BC5] Change purchasing API with latest changes

---

purchases/src/test/java/com/revenuecat/purchases/PostingTransactionsTests.kt

Fixes failing tests in `PostingTransactionsTests`
One interesting find -- you cannot `capture` a nullable type. This was leading to some of the failures... 
we had
```
val postedStoreUserIdSlot = slot<String>()
every {
backendMock.postReceiptData(
...
storeAppUserID = capture(postedStoreUserIdSlot),
...
)
} answers { ... }
```
and when the storeUserId was null, it wasn't matching the calls. you can't make a `slot<String?>`, so the [recommendation](https://github.com/mockk/mockk/issues/293) for nullables is apparently to use a list, like i did here. idk if that's a well-known thing, but it definitely caught me..

Fix PostingTransactionsTests

---

common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt

Adds a few tests to cover the postReceipt updates
I think we could use better testing around the `cacheKey` calculation, but that is an existing issue for all calls and feels bigger than this PR

BackendTests and BillingWrapperTests for postReceipt

---

feature/google/src/main/java/com/revenuecat/purchases/google/storeProductConversions.kt
feature/google/src/test/java/com/revenuecat/purchases/google/StoreProductConversionsTest.kt
feature/google/src/test/java/com/revenuecat/purchases/google/StoreProductTest.kt

[CF-1065](https://revenuecats.atlassian.net/browse/CF-1065)
Part of [CF-1000](https://revenuecats.atlassian.net/browse/CF-1000) _(I think)_
Non-subscription products were mysteriously not showing in offerings and no tests were failing/catching this
- `List<ProductDetails>.toStoreProducts()` no longer early returns when no base plan is found
- Added tests for `List<ProductDetails>.toStoreProducts()`

[CF-1065] Fix and add tests for listing of INAPP StoreProducts

---

api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
api-tester/src/main/java/com/revenuecat/apitester/java/StoreTransactionAPI.java
api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
migrations/v6-MIGRATION.md
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/listenerConversions.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

[CF-1069](https://revenuecats.atlassian.net/browse/CF-1069)
[CSDK-484](https://revenuecats.atlassian.net/browse/CSDK-484)
This task was to verify that `getSubscriptionSkus` and `getNonSubscriptionSkus` still worked but realized this naming is using BC4/V5 style so renamed all things talking about SKUs to Products
- Added:
- `getProducts`
- `getProductsWith`
- Deprecated:
- `getSubscriptionSkus`
- `getNonSubscriptionSkus`
- `getSubscriptionSkusWith`
- `getNonSubscriptionSkusWith`
Also updated and cleaned up `v6-MIGRATION.md`
[CF-1069]: https://revenuecats.atlassian.net/browse/CF-1069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CSDK-484]: https://revenuecats.atlassian.net/browse/CSDK-484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5Y …

[CF-1069] [CSDK-484] Replace getSubscriptionSkus and getNonSubscriptionSkus with getProducts

---

api-tester/src/main/java/com/revenuecat/apitester/java/UpgradeInfoAPI.java
api-tester/src/main/java/com/revenuecat/apitester/kotlin/UpgradeInfoAPI.kt
common/src/main/java/com/revenuecat/purchases/common/BillingAbstract.kt
common/src/main/java/com/revenuecat/purchases/common/ReplaceProductInfo.kt
feature/amazon/src/main/java/com/revenuecat/purchases/amazon/AmazonBilling.kt
feature/google/src/main/java/com/revenuecat/purchases/google/BillingFlowParamsExtensions.kt
feature/google/src/main/java/com/revenuecat/purchases/google/BillingWrapper.kt
feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
migrations/v6-MIGRATION.md
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/UpgradeInfo.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
strings/src/main/java/com/revenuecat/purchases/strings/PurchaseStrings.kt

* Update the upgrade/downgrade purchase flow to use the new BC5 methods
* rename `ReplaceSkuInfo` -> `ReplaceProductInfo` (this is an internal class)
* deprecate `UpgradeInfo.oldSku` and replace with `UpgradeInfo.oldProductId`
* add `UpgradeInfo` purchase testers
Will open a different PR to merge some of my [POC](https://github.com/RevenueCat/purchases-android/pull/723/files) purchase tester code

[CF-997] Support upgrade/downgrade

---

common/src/main/java/com/revenuecat/purchases/common/logUtils.kt
purchases/src/main/kotlin/com/revenuecat/purchases/CustomerInfoHelper.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt

I've run into a number of situations now while testing where the `PurchasesError` `message (code.description)` is a little too vague, and we weren't printing the `underlyingErrorMessage` associated with the error.
I suggest updating the `errorLog` method to use `PurchasesError.toString()`, which prints both the `code.description` and `underlyingErrorMessage` for more detail while debugging. This only affects debug logs -- users can still switch on the higher-level code if they wish.
I then searched for where else we only print the message, and updated those usages to print the full error.
If people like this change, I'll get it into `main` as well.

Use toString in errorLog so that underlying message gets logged too

---

examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/MainApplication.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OfferingFragment.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/PackageCardAdapter.kt
examples/purchase-tester/src/main/res/layout/package_card.xml

Adds product change functionality to the purchase tester. See attached video for example.
When the `Is product change?` box is selected:
* prompts user for oldSubId (selecting from any current subs) -- debated having this be a text box so we could test invalid scenarios, open to thoughts there
* prompts user for proration mode
* creates `UpgradeInfo` with that data and passes to purchase flow
Other changes:
* make some interfering toasts short
* pull purchase callbacks out as members
* fix infinite loading indicator happening in some cases
* 
https://user-images.githubusercontent.com/2272924/211677644-bb279250-d671-47ed-bdd6-63d1264ac15b.mp4

[CF-1145] Upgrade/downgrade support in purchase tester

---

common/src/main/java/com/revenuecat/purchases/common/caching/DeviceCache.kt
common/src/test/java/com/revenuecat/purchases/common/DeviceCacheTest.kt

Deals with #737 
If devs store something in SharedPreferences with a null key, it can cause a crash the next time the SDK is configured. This PR just ignores that key when cleaning up SDK values from SharedPreferences.

Fix crash when cleaning old attribution data if SharedPreferences has a null key

---

api-tester/src/main/java/com/revenuecat/apitester/java/UpgradeInfoAPI.java
api-tester/src/main/java/com/revenuecat/apitester/kotlin/UpgradeInfoAPI.kt
common/src/main/java/com/revenuecat/purchases/common/ReplaceProductInfo.kt
purchases/src/main/kotlin/com/revenuecat/purchases/UpgradeInfo.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

BC4 used to default to `IMMEDIATE_WITH_TIME_PRORATION` when no `ProrationMode` was passed in, but BC5 will fail with no `ProrationMode`, so we now need a default.
Until we complete other ProrationMode logic, the best default is `IMMEDIATE_WITHOUT_PRORATION`. This will work for both base plan and sub switches.

Default ProrationMode to IMMEDIATE_WITHOUT_PRORATION

---

feature/subscriber-attributes/src/main/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesManager.kt
feature/subscriber-attributes/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesManagerTests.kt
strings/src/main/java/com/revenuecat/purchases/strings/AttributionStrings.kt

Attempt at dealing with [CSDK-531](https://revenuecats.atlassian.net/browse/CSDK-531)
Back in https://github.com/RevenueCat/purchases-android/pull/384, we added checks to make sure we don't allow blank user ids. However, before that was added, user ids could be empty and could have subscriber attributes. Those could remain in SharedPreferences unless users uninstall which could cause some issues when syncing user attributes.
This is an attempt of solving that issue by just ignoring those old user ids when syncing subscriber attributes.
[CSDK-531]: https://revenuecats.atlassian.net/browse/CSDK-531?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Avoid syncing attributes for users with blank user ids

---

api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
common/src/main/java/com/revenuecat/purchases/common/Config.kt
common/src/main/java/com/revenuecat/purchases/common/logUtils.kt
common/src/main/java/com/revenuecat/purchases/common/logWrapper.kt
common/src/test/java/com/revenuecat/purchases/common/LogHandlerTest.kt
common/src/test/java/com/revenuecat/purchases/common/LogUtilsTest.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/LogLevel.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/LogMessage.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/TesterLogHandler.kt
feature/amazon/src/test/java/com/revenuecat/purchases/amazon/handler/ProductDataHandlerTest.kt
feature/amazon/src/test/java/com/revenuecat/purchases/amazon/handler/PurchaseHandlerTest.kt
feature/amazon/src/test/java/com/revenuecat/purchases/amazon/handler/PurchaseUpdatesHandlerTest.kt
feature/amazon/src/test/java/com/revenuecat/purchases/amazon/handler/UserDataHandlerTest.kt
public/src/main/java/com/revenuecat/purchases/LogHandler.kt
public/src/main/java/com/revenuecat/purchases/LogLevel.kt
public/src/test/java/com/revenuecat/purchases/LogLevelTest.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesLoggerTest.kt

Fixes [CSDK-549].
[CSDK-549]: https://revenuecats.atlassian.net/browse/CSDK-549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add `Purchases.logLevel` and deprecate `Purchases.debugLogsEnabled`

---

migrations/v6-MIGRATION.md
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt

[CF-1120](https://revenuecats.atlassian.net/browse/CF-1120)
Adding some SDK doc about what default offer is
- Updated doc for the `purchasePackage` and `purchaseProduct` functions
- Updated V6 migration doc explaining new behavior
[CF-1120]: https://revenuecats.atlassian.net/browse/CF-1120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CF1120] - Update SDK docs for default offer logic

---

common/src/main/java/com/revenuecat/purchases/common/ReceiptInfo.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

I started to look info [CF-1191](https://revenuecats.atlassian.net/browse/CF-1191) and realized that there were missing testing logic around this.
Making this PR before looking if there are any fixes for [CF-1191](https://revenuecats.atlassian.net/browse/CF-1191)
- `ReceiptInfo` was missing an equality check on its `storeProduct` property
- This missing equality check prevented tests from testing everything they needed to... test? 🤔 
- Ex: `ReceiptInfo` objects in didn't need to have the same `storeProduct` to pass an assert
[CF-1191]: https://revenuecats.atlassian.net/browse/CF-1191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CF-1191]: https://revenuecats.atlassian.net/browse/CF-1191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YT …

[BC5]  Add `storeProduct` to `ReceiptInfo`'s equals method (and fix broken tests because of this)

---

Gemfile.lock
fastlane/Pluginfile

Reverts RevenueCat/purchases-android#765
Our CI (especially deploys) break because `octokit >= 5.x.x` requires Ruby >= 2.7 and we don't have that being used in our jobs
I tried adding them using CircleCi's Ruby Orb but it `rvm` fails to install newer Ruby versions due to `apt-get` issues 🤷‍♂️

Revert "Update gems"

---

common/src/main/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsEvent.kt
common/src/main/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsLogEventName.kt
common/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsEventTest.kt

This is the first PR in a series of PRs to support sending diagnostic data from our SDKs to our backend. In this PR, we are just adding the models that we can potentially send to the backend.
This work is based on #766 but I'm splitting it up to make it easier to review. It's pointing to the `diagnostics` branch so we don't merge to main until everything is ready.

Diagnostics: Add diagnostics event types

---

examples/MagicWeather/app/src/main/java/com/revenuecat/sample/data/Constants.kt
examples/MagicWeather/app/src/main/java/com/revenuecat/sample/ui/paywall/PaywallAdapter.kt
examples/MagicWeather/app/src/main/java/com/revenuecat/sample/ui/paywall/PaywallFragment.kt
examples/MagicWeather/app/src/main/res/layout/paywall_item.xml
examples/MagicWeather/build.gradle

[CF-1121](https://revenuecats.atlassian.net/browse/CF-1121)
- Migrated from SDK `5.0.0` to `6.0.0-alpha.2`
- Changes to `PaywallAdapter` to make paywall show more useful information to user
- Duration (gross code)
- Multiple offers (and "best offer" first)
- Pricing phases (gross looking now but will improve later)
- Works for both subscriptions and one-time purchases
The initial migration (with only necessary code changes to compile) made for a very confusing paywall 👇 
- The subscriptions relied on the product title (which is the same for each base plan)
- Did not include the duration so user had no idea what they were buying
-  This is because these were previously in the individual subscription titles for BC4
- It did use the default/best offer which was nice but didn't explain any …

[CF-1121] Update Magic Weather for BC5 / SDK V6

---

common/src/main/java/com/revenuecat/purchases/common/FileHelper.kt
common/src/main/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsFileHelper.kt
common/src/test/java/com/revenuecat/purchases/common/FileHelperTest.kt
common/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsFileHelperTest.kt

Based on #783, this PR adds the logic to store and read JSONL files with the events we want to send to the backend.
This has been extracted from #766 and #771

Diagnostics: Add jsonl file management for diagnostics

---

public/src/main/java/com/revenuecat/purchases/models/RecurrenceMode.kt
public/src/test/java/com/revenuecat/purchases/RecurrenceModeTest.kt

Noticed that was testing the recurring mode of a prepaid plan (because curious) that the value was `3` and our `RecurrenceMode` enum only had values for 0, 1, and 2.
- `NON_RECURRING(0)` to `NON_RECURRING(3)`
Docs here - https://developer.android.com/reference/com/android/billingclient/api/ProductDetails.RecurrenceMode
And screenshot incase this link or doc ever changes which would make this PR seem wrong 😝

[BC5] Fix value of NON_RECURRING from 0 to 3

---

common/src/main/java/com/revenuecat/purchases/common/Backend.kt
common/src/main/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsAnonymizer.kt
common/src/main/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsManager.kt
common/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsManagerTest.kt

This PR is based on #784. Here we are adding the `DiagnosticsManager` which is in charge of coordinating the diagnostics logic like calling the backend and handling the jsonl files. There are some WIPs to be addressed in future PRs.

Diagnostics Add diagnostics manager

---

common/src/main/java/com/revenuecat/purchases/common/Anonymizer.kt
common/src/main/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsAnonymizer.kt
common/src/test/java/com/revenuecat/purchases/common/AnonymizerTest.kt
common/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsAnonymizerTest.kt

Based on #785 
Deals with [CSDK-652](https://revenuecats.atlassian.net/browse/CSDK-652)
This PR introduces some basic anonymization guardrails for diagnostics events. Currently we remove emails, uuids and ips from exception error messages, the only arbitrary piece of data.
[CSDK-652]: https://revenuecats.atlassian.net/browse/CSDK-652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Diagnostics: Anonymize events

---

common/src/main/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsFileHelper.kt
common/src/main/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsLogEventName.kt
common/src/main/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsManager.kt
common/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsFileHelperTest.kt
common/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsManagerTest.kt

Based on #785 
Deals with [CSDK-648](https://revenuecats.atlassian.net/browse/CSDK-648)
In this PR we add a limit to the number of events that can be sent to the backend and we add a diagnostics event tracking when this happens.
[CSDK-648]: https://revenuecats.atlassian.net/browse/CSDK-648?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Diagnostics: limit events sent

---

api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesConfiguration.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
purchases/src/test/java/com/revenuecat/purchases/PostingTransactionsTests.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesConfigurationTest.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt

Based on #787 
This PR adds support to enable/disable diagnostics (disabled by default) and adds all the plumbing to sync diagnostics when configuring the SDK.

Diagnostics: Sync diagnostics when configuring SDK if needed

---

common/src/main/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizer.kt
common/src/main/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTracker.kt
common/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizerTest.kt
common/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerTest.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
purchases/src/test/java/com/revenuecat/purchases/PostingTransactionsTests.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt

Based on #793 
This PR refactors previous code to split the `DiagnosticsManager` into `DiagnosticsTracker` and `DiagnosticsSynchronizer`. This is a prerequisite to avoid circular dependencies when tracking request data. 
- Before: `DiagnosticsManager`->`Backend`->`HttpClient`->`DiagnosticsManager`.
- After: `DiagnosticsSynchronizer`->`Backend` for syncing and `HttpClient`->`DiagnosticsTracker` for tracking requests 
I could have tried to extract this logic from the HttpClient, but that would be a bigger refactor. This was the simplest solution I thought for this problem. Also, sorry I didn't see that issue before. I didn't modify the #785 PR directly to try to avoid some conflicts that would happen if I did it there directly.

Diagnostics: Diagnostics split manager into tracker and synchronizer

---

common/src/main/java/com/revenuecat/purchases/common/Backend.kt
common/src/main/java/com/revenuecat/purchases/common/HTTPClient.kt
common/src/main/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsEvent.kt
common/src/main/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsLogEventName.kt
common/src/main/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizer.kt
common/src/main/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTracker.kt
common/src/main/java/com/revenuecat/purchases/common/durationExtensions.kt
common/src/main/java/com/revenuecat/purchases/common/networking/ETagManager.kt
common/src/main/java/com/revenuecat/purchases/common/networking/Endpoint.kt
common/src/main/java/com/revenuecat/purchases/common/networking/HTTPResult.kt
common/src/main/java/com/revenuecat/purchases/common/networking/RCHTTPStatusCodes.kt
common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
common/src/test/java/com/revenuecat/purchases/common/DispatcherTest.kt
common/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
common/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsAnonymizerTest.kt
common/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsEventTest.kt
common/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsFileHelperTest.kt
common/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizerTest.kt
common/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerTest.kt
common/src/test/java/com/revenuecat/purchases/common/networking/ETagManagerTest.kt
common/src/test/java/com/revenuecat/purchases/common/networking/EndpointTest.kt
common/src/test/java/com/revenuecat/purchases/common/networking/HTTPResultTest.kt
feature/amazon/src/main/java/com/revenuecat/purchases/amazon/AmazonBackend.kt
feature/amazon/src/test/java/com/revenuecat/purchases/amazon/AmazonBackendTest.kt
feature/subscriber-attributes/src/main/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesPoster.kt
feature/subscriber-attributes/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesBackendTests.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt

Based on #795 
Deals with [CSDK-655](https://revenuecats.atlassian.net/browse/CSDK-655)
- Adds functionality to send an `endpoint_hit` event to the diagnostics endpoint on every request
- Adds the `Endpoint` class with the enpoints we support, instead of hardcoding the path on each method.
- Adds functionality to detect whether a response comes from the backend or the cache.
[CSDK-655]: https://revenuecats.atlassian.net/browse/CSDK-655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Diagnostics: Track endpoint hit

---

common/src/main/java/com/revenuecat/purchases/common/Backend.kt
common/src/main/java/com/revenuecat/purchases/common/Dispatcher.kt
common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
common/src/test/java/com/revenuecat/purchases/common/SyncDispatcher.kt
test-utils/src/main/java/com/revenuecat/purchases/utils/SyncDispatcher.kt

Deals with [SDK-2865](https://linear.app/revenuecat/issue/SDK-2865/add-random-jitter-to-diagnostics-requests)
This increases the jittering we add for diagnostics calls to make sure they don't cause any interference with the main SDK calls.

Diagnostics: Increase jittering for diagnostics backend calls

---

common/src/main/java/com/revenuecat/purchases/common/FileHelper.kt
common/src/main/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsAnonymizer.kt
common/src/main/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsEntry.kt
common/src/main/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsEventName.kt
common/src/main/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsFileHelper.kt
common/src/main/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTracker.kt
common/src/test/java/com/revenuecat/purchases/common/FileHelperTest.kt
common/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsAnonymizerTest.kt
common/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsEntryTest.kt
common/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsFileHelperTest.kt
common/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizerTest.kt
common/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerTest.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/ConfigureFragment.kt

This PR we are adapting the code to the latest changes in the backend. 
- We've removed `exceptions` as a type of diagnostic, those can be sent as a Log/Event
- We've renamed `DiagnosticsEvent` to `DiagnosticsEntry`
- We've renamed `DiagnosticsEvent.Log` to `DiagnosticsEntry.Event`
- Renamed "type" of `DiagnosticsEntry.Event` to `event`
- Enabled diagnostics and verbose logs in purchase tester.

Diagnostics: Adapt to latest backend changes

---

public/src/main/java/com/revenuecat/purchases/models/StoreProduct.kt

⚠️ Chained off of #814
[CF-1210](https://revenuecats.atlassian.net/browse/CF-1210)
The `StoreProduct`'s `title` is the same for every base plan and its kind of confusing.
This is a "simple" doc change but difficult to put into the proper words 😛 
The new doc explains that if you are using Google subscription with multiple base plans, the `title`  will be the same for every subscription duration (monthly, yearly, etc) ase base plans don't have their own titles.
[CF-1210]: https://revenuecats.atlassian.net/browse/CF-1210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BC5] update StoreProduct title doc for Google base plans not having a title

---

feature/google/src/main/java/com/revenuecat/purchases/google/storeProductConversions.kt
feature/google/src/test/java/com/revenuecat/purchases/google/StoreProductConversionsTest.kt
public/src/main/java/com/revenuecat/purchases/models/StoreProduct.kt

⚠️ Chained off of #813
[CF-1237](https://revenuecats.atlassian.net/browse/CF-1237)
Bug with having recurring subscription and prepaid subscription of the same duration. 
The subscriptions would get mapped into one `StoreProduct` because previous logic grouped by billing duration.
- `List<ProductDetails>.toStoreProducts()` now groups base plans by `basePlanId`
- Added new tests that verifies that a `StoreProduct` is created/grouped by base plan id
|---|---|
| Prepaid group as a purchase option in recurring subscription | Now its its own package / `StoreProduct` |
| ![Screenshot 2023-02-22 at 8 39 01 PM](https://user-images.githubusercontent.com/401294/220813974-a80c2f92-9e4a-4ad7-9851-90575f0acedf.png) | ![Screenshot 2023-02-22 at 9 09 33 …

[BC5] Maps StoreProducts on basePlanId and not duration (fixes issue with prepaid with same duration as recurring)

---

feature/google/src/main/java/com/revenuecat/purchases/google/storeProductConversions.kt
feature/google/src/test/java/com/revenuecat/purchases/google/StoreProductConversionsTest.kt
public/src/main/java/com/revenuecat/purchases/models/StoreProduct.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt

⚠️ Chained off of #810
Fixes an issue where `logMissingProducts` was never logging missing products
`logMissingProducts` takes 2 parameters. The first being an array of all product ids and the second being a map containing all product ids fetched from Billing Client.
🐛 There was a bug where the first parameter was getting an array of all product ids from `Offerings` but `Offerings` already removes all the products that were not found
🔨 The fix in this PR is to pass all the product ids from the raw API JSON response containing all the product ids that are being requested into Billing Client

[BC5] Fixes logMissingProducts never logging missing products

---

.sdkmanrc
api-tester/src/main/java/com/revenuecat/apitester/java/StoreProductAPI.java
api-tester/src/main/java/com/revenuecat/apitester/kotlin/StoreProductAPI.kt
common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
common/src/test/java/com/revenuecat/purchases/common/DeviceCacheTest.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/PackageCardAdapter.kt
examples/purchase-tester/src/main/res/layout/package_card.xml
feature/amazon/src/main/java/com/revenuecat/purchases/amazon/AmazonBilling.kt
feature/amazon/src/main/java/com/revenuecat/purchases/amazon/handler/PurchaseHandler.kt
feature/amazon/src/main/java/com/revenuecat/purchases/amazon/storeProductConversions.kt
feature/amazon/src/test/java/com/revenuecat/purchases/amazon/handler/ProductDataHandlerTest.kt
feature/google/src/main/java/com/revenuecat/purchases/google/storeProductConversions.kt
feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
feature/google/src/test/java/com/revenuecat/purchases/google/StoreProductConversionsTest.kt
feature/google/src/test/java/com/revenuecat/purchases/google/StoreProductTest.kt
public/src/main/java/com/revenuecat/purchases/models/GoogleStoreProduct.kt
public/src/main/java/com/revenuecat/purchases/models/StoreProduct.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
test-utils/src/main/java/com/revenuecat/purchases/utils/productStubs.kt

⚠️ Chained off of #806 
[CF-1218](https://revenuecats.atlassian.net/browse/CF-1218)
`StoreProduct`'s `productId` field was a bit confusing on what information it was holding with the introduction of Google's BC5.
In the current implementation, the `productId` field stored the "Subscription ID" which does not include the Base Plan ID. This meant if there was a list of `StoreProduct`s all on the on same subscription (where there were base plans for weekly, monthly, yearly, etc), all the `StoreProduct`s would have identical `productId`s which... could be confusing to the user 😖 
- Renames `productId` to `id`
- Changes what is stored in `id` for Google subscriptions and updates doc to explain
- Google INAPP: `"<productId>"`
- Google Sub: `"<productId:basePlanID>"`
- Amazon INAPP: `"<sku>"`
- …

[BC5] Improve uniqueness and clarity of StoreProduct product ids

---

common/src/main/java/com/revenuecat/purchases/common/Backend.kt
common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt

Serialize the iso8601 duration
This was causing pricingPhases to serialize a null value
Use iso8601 for serialization

Fix period serialization

---

fastlane/Fastfile
fastlane/README.md

I believe we are not using the `latest` tag for anything. We were using it to point to the latest version from the docs

Remove `tag_release_with_latest_if_needed` fastlane lane

---

README.md

I tested a project using Kotlin gradle plugin 1.4.31 and I had issues when adding purchases-android. I tested and 1.5.0 was the minimum version that let me compile the app

Update README.md to include minimum Kotlin version

---

.circleci/config.yml

- Updated to the latest version of https://circleci.com/developer/orbs/orb/circleci/android, which was long overdue. This removed a warning we were getting in CircleCI
- Updating to the latest version of the Android docker image also fixed issues we were seeing in main like https://app.circleci.com/pipelines/github/RevenueCat/purchases-android/4469/workflows/6a4748b9-c235-40c5-b057-83f37c3fefef/jobs/12176, which were due to using an old version of ruby
- Removed the usage of `android-wordpress-orb`

Fix bundle install on CircleCI

---

config/detekt/detekt-baseline.xml
feature/identity/src/main/java/com/revenuecat/purchases/identity/IdentityManager.kt
feature/identity/src/test/java/com/revenuecat/purchases/identity/IdentityManagerTests.kt
feature/subscriber-attributes/src/main/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesManager.kt
feature/subscriber-attributes/src/main/java/com/revenuecat/purchases/subscriberattributes/caching/SubscriberAttributesCache.kt
feature/subscriber-attributes/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesDeviceCacheTests.kt
feature/subscriber-attributes/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesManagerTests.kt
strings/src/main/java/com/revenuecat/purchases/strings/AttributionStrings.kt

Deals with [SDK-2816](https://linear.app/revenuecat/issue/SDK-2816/fix-issue-with-missing-subscriber-attributes-on-purchases-[android])
There was an issue where subscriber attributes could be delayed to be synced to the backend. This happened when setting a subscriber attribute AFTER the `logIn` call but BEFORE the `logIn` operation was completed.
This issue happens because we start syncing subscriber attributes immediately when calling `logIn`, but if we set any after that but before the login is complete, they will be assigned to the old user id. We would sync those the next time the app is backgrounded/foregrounded but might be missed if there is a purchase in between since when there is a purchase, we only sync the current user's unsynced attributes.
This PR copies all unsynced …

Fix issue with missing subscriber attributes if set after login but before login callback

---

.circleci/config.yml

After #827, looks like pip isn't installed in the machine anymore. I ssh'ed in the machine to finish docs deployment in #833. Python3 was already installed, so we only needed to install pip. I did this for that and deployment seems to have worked fine after that doing it manually.

Fix docs deployment

---

build.gradle
common/build.gradle
common/src/main/java/com/revenuecat/purchases/common/verification/SignatureVerifier.kt
common/src/test/java/com/revenuecat/purchases/common/verification/DefaultSignatureVerifierTest.kt
common/src/test/java/com/revenuecat/purchases/common/verification/SigningManagerTest.kt

This PR adds Tink as a dependency to perform signature verification. It also adds our production public key so we can verify responses from the backend.

Entitlement verification: Add Tink dependency to perform signature verification

---

common/src/main/java/com/revenuecat/purchases/common/HTTPClient.kt
common/src/main/java/com/revenuecat/purchases/common/verification/SignatureVerificationMode.kt
common/src/main/java/com/revenuecat/purchases/common/verification/SigningManager.kt
common/src/main/java/com/revenuecat/purchases/common/verification/entitlementVerificationModeExtensions.kt
common/src/test/java/com/revenuecat/purchases/common/BaseHTTPClientTest.kt
common/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
common/src/test/java/com/revenuecat/purchases/common/HTTPClientVerificationTest.kt
common/src/test/java/com/revenuecat/purchases/common/verification/SignatureVerificationModeTest.kt
common/src/test/java/com/revenuecat/purchases/common/verification/SigningManagerTest.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
strings/src/main/java/com/revenuecat/purchases/strings/NetworkStrings.kt

Depends on #820 
Changes:
- Make `SigningManager` not nullable, so an instance will be created even if verification mode is disabled. SignatureVerifier will still be only created when verification is enabled.
- Pass `responseCode` to verification, so we can use that to decide whether to use the body or the etag to sign.
- Move logic about whether signing is necessary to `SigningManager`.

Entitlement verification: Refactor SigningManager to make it not-nullable

---

examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/ConfigureFragment.kt
examples/purchase-tester/src/main/res/drawable/spinner_bg.xml
examples/purchase-tester/src/main/res/layout/fragment_configure.xml
examples/purchase-tester/src/main/res/values/dimens.xml
examples/purchase-tester/src/main/res/values/strings.xml

Depends on #826 
Deals with [SDK-2894](https://linear.app/revenuecat/issue/SDK-2894/add-verification-options-and-verification-values-to-purchasetester)
This PR adds a dropdown to the purchase tester sdk configuration screen to configure what entitlement verification mode to use.
| 1  | 2 |
| ------------- | ------------- |
| <img width="329" alt="image" src="https://user-images.githubusercontent.com/808417/222105299-6de74f63-d7d6-455b-aa3e-5e06e1f16e88.png"> | <img width="327" alt="image" src="https://user-images.githubusercontent.com/808417/222105131-03377db2-e8a8-4c27-99a2-08816b92b098.png"> |

Entitlement verification: Add entitlement verification options to purchase tester

---

common/src/main/java/com/revenuecat/purchases/common/networking/ETagManager.kt
common/src/test/java/com/revenuecat/purchases/common/HTTPResultMockFactory.kt
common/src/test/java/com/revenuecat/purchases/common/networking/ETagManagerTest.kt

Depends on #826 
We should not cache responses where we detect verification errors. This changes ETagManager to follow that behavior

Entitlement verification: Avoid caching responses with verification errors

---

examples/MagicWeather/app/src/main/java/com/revenuecat/sample/data/Constants.kt
examples/MagicWeather/app/src/main/java/com/revenuecat/sample/ui/paywall/PaywallAdapter.kt
examples/MagicWeather/build.gradle

[CF-1213](https://revenuecats.atlassian.net/browse/CF-1213)
Keep our test and example apps up to date with our latest APIs
**Magic Weather** got the most updates as **PurchaseTester** has been getting updates for each API improvement PR.
This PR updates **Magic Weather** to use new `Price` and `Period` classes to make the code quiet a bit cleaner. I think this is a good example from a code side of things but the paywall itself could use some love to make it look a little bit prettier (probably out of scope of this PR).
- Magic Weather
- Updated to `6.0.0-alpha.4`
- Uses new `Price` property on  `PricingPhase`
- Uses new `Period` and `Unit` class for showing billing periods
- PurchaseTester
- Fixed subscription option to show ISO 8601 (because more compact for our use case) instead of a …

[BC5] Update MagicWeather and Purchase Tester with 6.0.0-alpha.4 APIs

---

api-tester/src/main/java/com/revenuecat/apitester/java/VerificationResultAPI.java
api-tester/src/main/java/com/revenuecat/apitester/kotlin/VerificationResultAPI.kt
common/src/main/java/com/revenuecat/purchases/common/CustomerInfoFactory.kt
common/src/main/java/com/revenuecat/purchases/common/HTTPClient.kt
common/src/main/java/com/revenuecat/purchases/common/caching/DeviceCache.kt
common/src/main/java/com/revenuecat/purchases/common/networking/ETagManager.kt
common/src/main/java/com/revenuecat/purchases/common/networking/HTTPResult.kt
common/src/main/java/com/revenuecat/purchases/common/verification/SigningManager.kt
common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
common/src/test/java/com/revenuecat/purchases/common/BaseHTTPClientTest.kt
common/src/test/java/com/revenuecat/purchases/common/DeviceCacheTest.kt
common/src/test/java/com/revenuecat/purchases/common/EntitlementInfosTests.kt
common/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
common/src/test/java/com/revenuecat/purchases/common/HTTPClientVerificationTest.kt
common/src/test/java/com/revenuecat/purchases/common/HTTPResultMockFactory.kt
common/src/test/java/com/revenuecat/purchases/common/MockCustomerInfoFactory.kt
common/src/test/java/com/revenuecat/purchases/common/networking/ETagManagerTest.kt
common/src/test/java/com/revenuecat/purchases/common/networking/HTTPResultTest.kt
common/src/test/java/com/revenuecat/purchases/common/verification/SigningManagerTest.kt
feature/amazon/src/test/java/com/revenuecat/purchases/amazon/AmazonBackendTest.kt
feature/subscriber-attributes/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesBackendTests.kt
public/src/main/java/com/revenuecat/purchases/EntitlementInfo.kt
public/src/main/java/com/revenuecat/purchases/EntitlementInfos.kt
public/src/main/java/com/revenuecat/purchases/VerificationResult.kt
public/src/test/java/com/revenuecat/purchases/ParcelableTests.kt
purchases/src/test/java/com/revenuecat/purchases/PostingTransactionsTests.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt

Following the conversation in [SDK-2896](https://linear.app/revenuecat/issue/SDK-2896/invalidate-devicecache-cache-if-entitlement-verification-is-missing), we are renaming `NOT_VERIFIED` to `NOT_REQUESTED`. We're also renaming `ERROR` to `FAILED` to match iOS.

Entitlement verification: Rename not verified to not requested and error to failed

---

common/src/main/java/com/revenuecat/purchases/common/networking/ETagManager.kt
common/src/test/java/com/revenuecat/purchases/common/HTTPClientVerificationTest.kt
common/src/test/java/com/revenuecat/purchases/common/networking/ETagManagerTest.kt

This PR makes sure we expose the current call verification result over the cached version. We shouldn't be storing verification errors in the etag cache. Also, we plan to clear the cache when verification mode is enabled, so we shouldn't have `NOT_REQUESTED` values either, so the etag cache should only contain successful values

Entitlement verification: Return current call verification result over cached version

---

purchases/src/main/kotlin/com/revenuecat/purchases/PurchaseParams.kt

[CF-1165](https://revenuecats.atlassian.net/browse/CF-1165)
Logic to purchase a `PurchasingData` shouldn't have to check if a `defaultOption` exists. There should be a reusable helper to do this.
Turns out... I didn't realize the `purchaseData` on `GoogleStoreProduct` was already being overridden to choose the `defaultOption.purchasingData` for SUBS 😇 
See [here](https://github.com/RevenueCat/purchases-android/blob/bc5-support-cleanup-extra-use-of-purchasingData/public/src/main/java/com/revenuecat/purchases/models/GoogleStoreProduct.kt#L29-L37) in `GoogleStoreProduct`
So... this task was a lot shorter than planned because the implementation already existed but just needed to be used
[CF-1165]: https://revenuecats.atlassian.net/browse/CF-1165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2 …

[BC5] Always use purchasingData property directly on the StoreProduct when purchasing

---

common/src/main/java/com/revenuecat/purchases/common/HTTPClient.kt
common/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
common/src/test/java/com/revenuecat/purchases/common/HTTPClientVerificationTest.kt

We were performing signature verification when the request failed with 400/500 errors. We don't need to verify those requests since it will fail anyway. Network errors were already handled since they throw an exception that is catched later on.

Entitlement verification: Not perform verification if request returns error

---

common/src/main/java/com/revenuecat/purchases/common/Backend.kt
common/src/main/java/com/revenuecat/purchases/common/CustomerInfoFactory.kt
common/src/main/java/com/revenuecat/purchases/common/HTTPClient.kt
common/src/main/java/com/revenuecat/purchases/common/caching/DeviceCache.kt
common/src/main/java/com/revenuecat/purchases/common/networking/ETagManager.kt
common/src/main/java/com/revenuecat/purchases/common/networking/HTTPResult.kt
common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
common/src/test/java/com/revenuecat/purchases/common/BaseHTTPClientTest.kt
common/src/test/java/com/revenuecat/purchases/common/DeviceCacheTest.kt
common/src/test/java/com/revenuecat/purchases/common/EntitlementInfosTests.kt
common/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
common/src/test/java/com/revenuecat/purchases/common/HTTPClientVerificationTest.kt
common/src/test/java/com/revenuecat/purchases/common/HTTPResultMockFactory.kt
common/src/test/java/com/revenuecat/purchases/common/MockCustomerInfoFactory.kt
common/src/test/java/com/revenuecat/purchases/common/networking/ETagManagerTest.kt
common/src/test/java/com/revenuecat/purchases/common/networking/HTTPResultTest.kt
feature/amazon/src/test/java/com/revenuecat/purchases/amazon/AmazonBackendTest.kt
feature/identity/src/main/java/com/revenuecat/purchases/identity/IdentityManager.kt
feature/identity/src/test/java/com/revenuecat/purchases/identity/IdentityManagerTests.kt
feature/subscriber-attributes/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesBackendTests.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
purchases/src/test/java/com/revenuecat/purchases/PostingTransactionsTests.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt
strings/src/main/java/com/revenuecat/purchases/strings/IdentityStrings.kt

Completes [SDK-2897](https://linear.app/revenuecat/issue/SDK-2897/requestdate-not-returning-updated-value)
With this PR, we will update `CustomerInfo`'s `requestDate` with the latest value even when a 304 response is received.

Entitlement verification: Return updated request time from header in CustomerInfo in 304 responses

---

common/src/main/java/com/revenuecat/purchases/common/EntitlementInfoFactories.kt
common/src/test/java/com/revenuecat/purchases/common/CustomerInfoTest.kt
common/src/test/java/com/revenuecat/purchases/common/EntitlementInfosTests.kt
common/src/test/java/com/revenuecat/purchases/common/testDurationExtensions.kt
public/src/main/java/com/revenuecat/purchases/CustomerInfo.kt
strings/src/main/java/com/revenuecat/purchases/strings/PurchaseStrings.kt
test-utils/src/main/java/com/revenuecat/purchases/utils/Responses.kt
test-utils/src/main/java/com/revenuecat/purchases/utils/dateExtensions.kt
utils/src/main/java/com/revenuecat/purchases/utils/DateHelper.kt

Completes [SDK-2895](https://linear.app/revenuecat/issue/SDK-2895/create-a-grace-period-for-entitlements-when-the-backend-is-offline).
Android equivalent of: https://github.com/RevenueCat/purchases-ios/pull/2288
In this PR we are adding a 3 day grace period to entitlements expiration dates.

Grant grace period for entitlements when the backend is offline

---

common/src/main/java/com/revenuecat/purchases/common/HTTPClient.kt
common/src/main/java/com/revenuecat/purchases/common/verification/SigningManager.kt
common/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
common/src/test/java/com/revenuecat/purchases/common/verification/SigningManagerTest.kt

There was a mismatch in what body the signing expects and what the body we read from the response. We were missing an end of line at the end of the body when verifying the signature. This fixes that issue.

Entitlement verification: Fix request verification

---

api-tester/src/main/java/com/revenuecat/apitester/java/DeprecatedPurchasesAPI.java
api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
api-tester/src/main/java/com/revenuecat/apitester/kotlin/DeprecatedPurchasesAPI.kt
api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
common/src/main/java/com/revenuecat/purchases/common/ReplaceProductInfo.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/DeprecatedOfferingFragment.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/DeprecatedPackageCardAdapter.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OverviewFragment.kt
examples/purchase-tester/src/main/res/navigation/nav_graph.xml
feature/google/src/main/java/com/revenuecat/purchases/google/BillingFlowParamsExtensions.kt
migrations/v6-MIGRATION.md
purchases/src/main/kotlin/com/revenuecat/purchases/PurchaseParams.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesState.kt
purchases/src/main/kotlin/com/revenuecat/purchases/interfaces/ProductChangeCallback.kt
purchases/src/main/kotlin/com/revenuecat/purchases/interfaces/PurchaseCallback.kt
purchases/src/main/kotlin/com/revenuecat/purchases/listenerConversions.kt
purchases/src/test/java/com/revenuecat/purchases/PurchaseParamsTest.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
strings/src/main/java/com/revenuecat/purchases/strings/PurchaseStrings.kt
test-utils/src/main/java/com/revenuecat/purchases/utils/productStubs.kt

Follow-up PR addressing the following:
* have the  deprecated listenerConversions call into new listenerConversions to keep all retrofitting in purchases
* have the deprecated purchase methods in purchases directly call startPurchase without PurchaseParams (so no more breaking change on which prorationmodes can be used with the deprecated methods)
* remove all subscriptionOption purchase methods
* add PurchaseParamsTests
* make PurchaseParams a data class
* deprecate ProductChangeCallback, use PurchaseCallback everywhere else, split startProductChange methods between the two kinds of callbacks

Purchase.Builder Follow-up

---

CHANGELOG.latest.md
CHANGELOG.md

We deployed a backend fix so the instructions in the CHANGELOG were outdated. This PR updates those instructions.

Update CHANGELOG with improved notes about SDK issue

---

.circleci/config.yml

Followup to #836 
When changing the orbs, looks like we changed where the project is stored during the `checkout` step. That was causing the aws commands to fail. I missed updating those in the last PR so #853 failed docs deployment. This should fix it moving forward.

Fix docs deployment paths

---

common/src/test/java/com/revenuecat/purchases/common/EntitlementInfoTest.kt
common/src/test/java/com/revenuecat/purchases/common/EntitlementInfosTests.kt
public/src/main/java/com/revenuecat/purchases/EntitlementInfo.kt
public/src/main/java/com/revenuecat/purchases/EntitlementInfos.kt

We were not sending updated values in the listener when we only detected a change in the verification result. This fixes that by adding this new property to the equals calculation.

Entitlement verification: Send updated value in listener when verification result changes

---

feature/amazon/src/main/java/com/revenuecat/purchases/amazon/storeProductConversions.kt
feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
feature/google/src/test/java/com/revenuecat/purchases/google/ParcelableTests.kt
migrations/v6-MIGRATION.md
public/src/main/java/com/revenuecat/purchases/Offering.kt
public/src/main/java/com/revenuecat/purchases/Offerings.kt
public/src/main/java/com/revenuecat/purchases/Package.kt
public/src/main/java/com/revenuecat/purchases/models/GoogleStoreProduct.kt
public/src/main/java/com/revenuecat/purchases/models/GoogleSubscriptionOption.kt
public/src/main/java/com/revenuecat/purchases/models/StoreProduct.kt
public/src/main/java/com/revenuecat/purchases/models/StoreTransaction.kt
public/src/main/java/com/revenuecat/purchases/models/SubscriptionOption.kt
public/src/main/java/com/revenuecat/purchases/models/SubscriptionOptions.kt
public/src/test/java/com/revenuecat/purchases/ParcelableTests.kt
test-utils/src/main/java/com/revenuecat/purchases/utils/productStubs.kt

Because ProductDetails does not have a public constructor, `StoreProduct`, `Package`, `Offering`, `PurchasingData` and `Offerings` are no longer Parcelable.
This PR takes away the implementation/annotation for those classes and updates unit tests accordingly. It also adds a missing test for `StoreProduct`, which caught a failure in parcelization. This is now fixed with the inner `ComparableData` class, copying the pattern we use in `CustomerInfo` to exclude the JSONObject.

Remove Parcelable implementation for classes with ProductDetails as a member

---

purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
strings/src/main/java/com/revenuecat/purchases/strings/ConfigureStrings.kt

Completes [SDK-2916](https://linear.app/revenuecat/issue/SDK-2916/log-error-message-when-trying-to-configure-sdk-when-its-already-been)
When configuring the SDK multiple times, we will log a message indicating this fact. This log can be helpful to debug issues. This is based on the same log that we have in iOS.

Log message when trying configure the SDK multiple times

---

common/src/test/java/com/revenuecat/purchases/common/HTTPClientVerificationTest.kt
common/src/test/java/com/revenuecat/purchases/common/networking/ETagManagerTest.kt

This is improving our test coverage for the tests in the [spreadsheet](https://docs.google.com/spreadsheets/d/1kNcFNB8U47N5_vm8Ww57izMgdp60mdzUxZFK-cm46KU/edit#gid=0). 
Android equivalent of https://github.com/RevenueCat/purchases-ios/pull/2333

Improve tests on etag cache verification logic

---

api-tester/src/main/java/com/revenuecat/apitester/java/VerificationResultAPI.java
api-tester/src/main/java/com/revenuecat/apitester/kotlin/VerificationResultAPI.kt
common/src/main/java/com/revenuecat/purchases/common/verification/SigningManager.kt
common/src/test/java/com/revenuecat/purchases/common/DeviceCacheTest.kt
common/src/test/java/com/revenuecat/purchases/common/EntitlementInfoTest.kt
common/src/test/java/com/revenuecat/purchases/common/EntitlementInfosTests.kt
common/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
common/src/test/java/com/revenuecat/purchases/common/HTTPClientVerificationTest.kt
common/src/test/java/com/revenuecat/purchases/common/networking/ETagManagerTest.kt
common/src/test/java/com/revenuecat/purchases/common/networking/HTTPResultTest.kt
common/src/test/java/com/revenuecat/purchases/common/verification/SigningManagerTest.kt
feature/identity/src/test/java/com/revenuecat/purchases/identity/IdentityManagerTests.kt
public/src/main/java/com/revenuecat/purchases/VerificationResult.kt
public/src/test/java/com/revenuecat/purchases/ParcelableTests.kt

This PR renames `VerificationResult.SUCCESS` to `VerificationResult.VERIFIED`. This is to match iOS nomenclature.

Rename verification result SUCCESS to VERIFIED

---

common/src/main/java/com/revenuecat/purchases/common/Backend.kt
common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt

[CF-1198](https://revenuecats.atlassian.net/browse/CF-1198)
The `price_string` was removed but is needed for Amazon debugging.
- Adds `price_string` as an extra header on `postReceiptData`
[CF-1198]: https://revenuecats.atlassian.net/browse/CF-1198?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BC5] Re-add `price_string` header on postReceipt

---

api-tester/src/main/java/com/revenuecat/apitester/java/StoreProductAPI.java
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/DeprecatedOfferingFragment.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OfferingFragment.kt
public/src/main/java/com/revenuecat/purchases/models/StoreProduct.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt

Getting rid of TODOs in the code when this goes into production
- Added comment to splitting product ids by ":" in purchase tester because probably fine 🤷‍♂️ 
- Added javadoc to `purchasingData` on `StoreProduct`
- Removing comment about multi-line purchases because don't need to worry about that (yet)

[BC5] Cleaning up some TODOs in the code

---

api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
common/src/test/java/com/revenuecat/purchases/common/EntitlementInfoTest.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OfferingFragment.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchaseParams.kt
purchases/src/test/java/com/revenuecat/purchases/PurchaseParamsTest.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

[CF-1283](https://revenuecats.atlassian.net/browse/CF-1283)
Might be good to move the `Activity` param as the first param in `PurchaseParams` to make things Android consistent (see [comment here](https://github.com/RevenueCat/purchases-hybrid-common/pull/359#discussion_r1138224884))
- `Activity` is now first param
- Also fixed a flaky local test in `EntitlementInfoTest` that had nothing to do with this but I think was failing because of creating dates on my machine but weren't equal because milliseconds off? 🤷‍♂️ 
[CF-1283]: https://revenuecats.atlassian.net/browse/CF-1283?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BC5] Make Activity first param in PurchaseParams

---

common/src/test/java/com/revenuecat/purchases/common/EntitlementInfoTest.kt

This fixes a flaky test in `EntitlementInfoTest`. Copied fix in #882 
Basically, we were creating multiple `EntitlementInfoTest` and comparing them but the dates could be different which caused the test to fail.

Fix flaky test in EntitlementInfoTest

---

migrations/v6-MIGRATION.md
public/src/main/java/com/revenuecat/purchases/models/SubscriptionOptions.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchaseParams.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt

[CF-1291](https://revenuecats.atlassian.net/browse/CF-1291)
Turns out that `rc-ignore-default-offer` is too long for Google Play to handle 🙈 Max 20 characters so now using `rc-ignore-offer`
Giant find replace for `rc-ignore-default-offer` to `rc-ignore-offer`
[CF-1291]: https://revenuecats.atlassian.net/browse/CF-1291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BC5] Use `rc-ignore-offer` instead of `rc-ignore-befault-offer`

---

api-tester/src/main/java/com/revenuecat/apitester/java/SubscriptionOptionsAPI.java
api-tester/src/main/java/com/revenuecat/apitester/kotlin/SubscriptionOptionsAPI.kt
migrations/v6-MIGRATION.md
public/src/main/java/com/revenuecat/purchases/models/SubscriptionOptions.kt
public/src/test/java/com/revenuecat/purchases/common/models/SubscriptionOptionsTest.kt

[CF-1292](https://revenuecats.atlassian.net/browse/CF-1292)
Rename `introTrial` to `introOffer` since "trial" usually refers to free in most of other references
Rename `introTrial` to `introOffer` in `SubscriptionOptions`
[CF-1292]: https://revenuecats.atlassian.net/browse/CF-1292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BC5] Rename `introTrial` to `introOffer` on `SubscriptionOptions`

---

common/src/main/java/com/revenuecat/purchases/common/Backend.kt
common/src/main/java/com/revenuecat/purchases/common/networking/Endpoint.kt
common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
common/src/test/java/com/revenuecat/purchases/common/networking/EndpointTest.kt

Second part of SDK-2982
Based on #888 
This PR adds support to get product entitlement mappings from the backend.

Offline entitlements: Add support for fetching ProductEntitlement mappings

---

common/src/main/java/com/revenuecat/purchases/common/HTTPClient.kt
common/src/main/java/com/revenuecat/purchases/common/networking/Endpoint.kt
common/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
common/src/test/java/com/revenuecat/purchases/common/networking/EndpointTest.kt

3rd part of SDK-2982
This PR adds support for endpoints to not send an ETag header in requests. Currently only needed for the product entitlement mapping endpoint.

Support requests without ETags

---

common/src/main/java/com/revenuecat/purchases/common/HTTPClient.kt
common/src/main/java/com/revenuecat/purchases/common/networking/Endpoint.kt
common/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
common/src/test/java/com/revenuecat/purchases/common/networking/EndpointTest.kt

This PR reverts #894 since we don't need this functionality currently so we can just remove it and add it back if it becomes necessary in the future.

Revert "Support requests without ETags (#894)"

---

common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/OfflineEntitlementsManager.kt
common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/OfflineEntitlementsManagerTest.kt
strings/src/main/java/com/revenuecat/purchases/strings/OfflineEntitlementsStrings.kt

Second part of SDK-2986
Based on #892 
This PR adds `OfflineEntitlementsManager`. This class will be in charge of performing most of the logic to make sure the SDK can handle entitlements in the unlikely case the servers are down.
Currently, only has one method to update the cache with the product entitlement mappings from the servers.

Offline entitlements: Add `OfflineEntitlementsManager` and add operation to perform backend request and cache result in device

---

examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/ConfigureFragment.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/ObserverModeBillingClient.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OfferingFragment.kt
examples/purchase-tester/src/main/res/layout/fragment_configure.xml

Easily test observable mode in Purchase Tester with just a click of a toggle
I knew nothing about how our observer mode worked and never implemented BillingClient directly. My first attempt at this was as a separate app so that I didn't need to worry about any existing app complexities 🤷‍♂️ 
Once I had that new app working, I understand how observer mode and BillingClient worked so adding this into Purchase Tester seemed much easier than I originally thought 😅 
- Adds option at configuration screen want to enable observer mode
- When enabled...
1. Starts another instance of billing client to make purchases on
2. Purchasing package, product, or subscription offer will purchase on new billing client instance
3. After successful purchase, `syncPurchases()` will get called
⚠️ Only works for …

PurchaseTester gets observable mode for google

---

examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OfferingFragment.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/PackageCardAdapter.kt
examples/purchase-tester/src/main/res/layout/package_card.xml

The extra modal for setting isPersonalized price for each purchase was being a bit annoying.
Moved it to a checkbox.

Make personalized price checkbox

---

public/src/main/java/com/revenuecat/purchases/EntitlementInfo.kt

Noticed by @aboedo 
Make `productPlanIdentifier` in the `toString` use `productPlanIdentifier` instead of `productIdentifier` 🤦‍♂️

[BC5] Fix entitlment info to string plan identifier

---

common/src/main/java/com/revenuecat/purchases/common/Anonymizer.kt
common/src/main/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsAnonymizer.kt
common/src/main/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsCounterName.kt
common/src/main/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsEntry.kt
common/src/test/java/com/revenuecat/purchases/common/AnonymizerTest.kt
common/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsAnonymizerTest.kt
common/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsEntryTest.kt

This PR adds anonymization to diagnostics counters and converts the counters names to an enum.
This is in preparation of possibly sending some counters to get entitlement verification results as counters, instead of events for now.

Improve diagnostics counters system by adding anonymization and changing counter name to an enum

---

purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
purchases/src/test/java/com/revenuecat/purchases/PostingTransactionsTests.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt

3rd part of SDK-2986
Based on #893 
This PR glues previous code so we perform the backend request to get the product-entitlement mapping and store it in the device cache. This will happen if the cache is stale and: 
- When the SDK is first initialized
- When the app is foregrounded

Offline entitlements: Initialize OfflineEntitlementsManager and perform cache update on SDK configuration

---

examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/MainApplication.kt

This has already been removed in #657 , but both @aboedo and I got hit by it the other day while testing with purchase tester so I figured it should be removed from main too.
Strict mode was complaining about a leaked closeable violation. I've only seen it in certain emulators so I actually don't think it's related to our code.
I've created a task in Linear SDK-2988 to actually do research make sure this is not a real issue.

Removes strict mode from purchase tester

---

purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/test/java/com/revenuecat/purchases/PostingTransactionsTests.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt

After merging #896, tests in main started failing. This is because there was another change in a different PR modifying the name from `mappings` to `mapping` that was merged that modified existing methods. We don't run tests based on the merge commit, so we didn't catch this before.

Fix tests after PR merge changes

---

common/src/main/java/com/revenuecat/purchases/common/Backend.kt
common/src/main/java/com/revenuecat/purchases/common/BackendHelper.kt
common/src/main/java/com/revenuecat/purchases/common/HTTPClient.kt
common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
feature/amazon/src/main/java/com/revenuecat/purchases/amazon/AmazonBackend.kt
feature/amazon/src/main/java/com/revenuecat/purchases/amazon/AmazonBilling.kt
feature/amazon/src/test/java/com/revenuecat/purchases/amazon/AmazonBackendTest.kt
feature/amazon/src/test/java/com/revenuecat/purchases/amazon/BillingFactoryAmazonTest.kt
feature/subscriber-attributes/src/main/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesPoster.kt
feature/subscriber-attributes/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesBackendTests.kt
integration-tests/build.gradle
purchases/src/main/kotlin/com/revenuecat/purchases/BillingFactory.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
purchases/src/test/java/com/revenuecat/purchases/BillingFactoryTest.kt

When working on https://github.com/RevenueCat/purchases-android/pull/885 I had to refactor the AmazonBackend to not depend on Backend. 
The reason is that I was adding a dependency to `CustomerInfoResponseHandler(billing)` on Backend, which was creating a circular dependency between `BillingAbstract` and `Backend`.
I noticed the only reason why `BillingAbstract` had a dependency on `Backend` was for `AmazonBackend` to make some calls to the backend. So I removed that dependency in `BillingAbstract` by creating a new `BackendHelper`, that both `Backend` and `BillingAbstract` depend on

Refactors BillingAbstract to not depend on Backend

---

feature/amazon/src/main/java/com/revenuecat/purchases/amazon/AmazonBilling.kt
feature/amazon/src/test/java/com/revenuecat/purchases/amazon/AmazonBillingTest.kt
feature/amazon/src/test/java/com/revenuecat/purchases/amazon/helpers/dummies.kt

SDK-2993
Until now, Amazon returned the whole purchase history with `queryPurchases`. This modifies the behavior in the Amazon store so we mimick what we do for Google, where `queryPurchases` only returns active purchases. 
To do this, we use the `cancelDate` field in Amazon purchases, whose [documentation](https://developer.amazon.com/docs/in-app-purchasing/iap-rvs-for-android-apps.html#cancel-date-and-renewal-date) is:

Filter out expired purchases from queryPurchases in Amazon store

---

.circleci/config.yml
fastlane/Fastfile
fastlane/README.md
purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/PurchasesIntegrationTest.kt

First part of SDK-3005
This PR adds some automation to be able to run the integration tests against the load shedder servers. Note that this will run it only for the running branch.
Will work on those on different PRs

Automate integration tests for load shedder

---

feature/google/src/test/java/com/revenuecat/purchases/google/StoreProductTest.kt
public/src/main/java/com/revenuecat/purchases/models/GoogleStoreProduct.kt

There was an infinite loop when trying to access a Google's `StoreProduct.sku` property. This fixes that and adds a test for it.

Fix infinite loop when accesing deprecated property

---

api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

Use the `Purchases.shared.store` to limit functionality on hybrid.
Example: `purchaseSubscriptionOptions()` should not be run if Amazon
- Adds `store` getting property to `Purchases` instance

Add store getter to purchases instance

---

common/src/main/java/com/revenuecat/purchases/common/errors.kt

Made `toPurchasesError` back to internal because it's not needed. It was made public in #885 and forgot to make internal before merging

`toPurchasesError` back to internal

---

.circleci/config.yml
fastlane/Fastfile
fastlane/README.md

This PR adds reporting to slack for load shedder integration tests on V5. This is pointing to the latest changes before v6 was merged.

Report load shedder integration tests results in slack for V5

---

.circleci/config.yml
fastlane/Fastfile
purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/Constants.kt
purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/PurchasesIntegrationTest.kt

Add verifications to integration tests to check that expected entitlements are active after purchasing and readd check to make sure purchases have the correct identifier after load shedder has been fixed.

Add verification for entitlement granting to integration tests

---

base-application.gradle
feature/amazon/build.gradle
gradle.properties
library.gradle
purchases/build.gradle

We found an issue in 6.1.0 that made the listener functions in the `listenerConversions.kt` file not accessible when being deployed in Maven. We tracked it down to the flavors that were added to run integration tests. We are removing these temporarily.

Remove flavors temporarily to fix deployment

---

api-tester/src/main/java/com/revenuecat/apitester/java/VerificationResultAPI.java
api-tester/src/main/java/com/revenuecat/apitester/kotlin/VerificationResultAPI.kt
common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/OfflineCustomerInfoCalculator.kt
common/src/test/java/com/revenuecat/purchases/common/EntitlementInfoTest.kt
common/src/test/java/com/revenuecat/purchases/common/EntitlementInfosTests.kt
utils/src/main/java/com/revenuecat/purchases/VerificationResult.kt

Used for entitlements computed directly with data from BillingClient
The name of the enum is open to feedback and it's being discussed [here](https://github.com/RevenueCat/purchases-ios/pull/2379#discussion_r1149784192)

Added ENTITLEMENTS_COMPUTED_ON_DEVICE

---

.circleci/config.yml

`store_test_results` wasn't working because the modules render the test results in their own folders. This change fixes the issue by moving all test results into another folder and storing that folder instead

Fix storing test results

---

common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/OfflineCustomerInfoCalculator.kt
common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/OfflineCustomerInfoCalculatorTest.kt
test-utils/src/main/java/com/revenuecat/purchases/utils/billingClientStubs.kt

Since we don't have the RevenueCat ID and we are doing this mainly for entitlement granting purposes, I mimicked what the backend does, which is add the non-subscriptions to the subscriptions array.

Add non-subscriptions support to offline customer info

---

base-application.gradle
feature/amazon/build.gradle
gradle.properties
library.gradle
purchases/build.gradle

We detected that the chnages to support the new integration tests caused compilation issues for top-level kotlin functions. After debugging the issue, we tracked the issue down to this block of code:
```
productFlavors {
integrationTest {
.....
packagingOptions {
resources.excludes.add("META-INF/*")
}
}
}
```
We assumed that the `packagingOptions` there would only affect the `integrationTest` flavor, but it actually affects other flavors as well. This was causing a `kotlin_module` file to not be included in the published `aar` file, which caused top level functions to not be accessible by library consumers.
In this PR we change the exclusion to only exclude the files that were duplicated during instrumentation tests: `META-INF/LICENSE.md` and `META-INF/LICENSE-notice.md`. 
Comparing the …

Add back integration test flavors

---

common/src/main/java/com/revenuecat/purchases/common/Backend.kt
common/src/main/java/com/revenuecat/purchases/common/networking/RCHTTPStatusCodes.kt
common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
feature/subscriber-attributes/src/main/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesPoster.kt
feature/subscriber-attributes/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesBackendTests.kt
purchases/src/main/kotlin/com/revenuecat/purchases/CustomerInfoHelper.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/test/java/com/revenuecat/purchases/CustomerInfoHelperTest.kt
purchases/src/test/java/com/revenuecat/purchases/PostingTransactionsTests.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt

First PR for SDK-2992
In this PR, we add a `isServerError` parameter to the error callback for the `postReceipt` and `getCustomerInfo` backend requests. This will be true if we get a 5xx error code, false otherwise.
This is currently unused but will be used to detect whether we need to compute offline entitlements

Add isServerDown to error callback for postReceipt and getCustomerInfo requests

---

.sdkmanrc
base-application.gradle
build.gradle
common/build.gradle
common/consumer-rules.pro
examples/MagicWeather/app/build.gradle
examples/MagicWeather/app/src/main/AndroidManifest.xml
examples/MagicWeather/app/src/main/java/com/revenuecat/sample/ui/paywall/PaywallFragment.kt
examples/MagicWeather/build.gradle
examples/MagicWeather/gradle.properties
examples/MagicWeather/gradle/wrapper/gradle-wrapper.properties
examples/purchase-tester/build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties

Android Studio Flamingo 8.0 was released a few days ago. As part of the upgrade, it's recommended to upgrade to AGP 8.0 and Gradle 8.0. This PR performs that upgrade. 
AGP Upgrade assistant steps run:
In our case:
- For R8, we currently keep everything, which is not the best practice but protects us from most issues from running R8 in full mode. These are the changes we should be aware of for R8 full mode: https://r8.googlesource.com/r8/+/refs/heads/master/compatibility-faq.md#r8-full-mode. We do have issues with external dependencies though, being the Tink library.
- The `BuildConfig` files are used in a couple places so I enabled them only in the modules that use them (`common`, `purchase-tester` and `MagicWeather`).
- The `R` file related steps don't affect us much since we don't …

Upgrade to AGP 8.0

---

.circleci/config.yml

We added the integration tests flavor back in #962, but we didn't bring back the CircleCI automations. Also, since unit tests are taking twice as long after adding this flavor, we are making CircleCI unit tests run only on the `defaults` flavor.

Add back integration tests automation

---

.circleci/config.yml
common/build.gradle
common/src/test/java/com/revenuecat/purchases/backend_integration_tests/BackendIntegrationTest.kt
common/src/test/java/com/revenuecat/purchases/backend_integration_tests/BaseBackendIntegrationTest.kt
common/src/test/java/com/revenuecat/purchases/backend_integration_tests/Constants.kt
common/src/test/java/com/revenuecat/purchases/backend_integration_tests/LoadShedderBackendIntegrationTest.kt
common/src/test/java/com/revenuecat/purchases/backend_integration_tests/ProductionBackendIntegrationTest.kt
fastlane/Fastfile
fastlane/README.md

SDK-3015
This PR adds backend integration tests. These are setup as unit tests in the `common` module.
I thought about adding these as instrumentation tests, but that increases the complexity and runtime of these tests, and we can relatively simply run them as unit tests in the JVM.

Add backend integration tests and test product entitlement mapping endpoint

---

common/src/main/java/com/revenuecat/purchases/common/HTTPClient.kt
common/src/main/java/com/revenuecat/purchases/common/networking/ETagManager.kt
common/src/main/java/com/revenuecat/purchases/common/networking/HTTPRequest.kt
common/src/test/java/com/revenuecat/purchases/common/BaseHTTPClientTest.kt
common/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
common/src/test/java/com/revenuecat/purchases/common/networking/ETagManagerTest.kt

SDK-3025
Now, when we store a backend result in the cache, we will also store the time it was stored. When we perform the same request with a stored time, we will add a `X-RC-Last-Refresh-Time` header to the request.
- Nothing saved for that request: We only send an empty `X-RevenueCat-ETag` header
- Saved ETag for a request but no last refresh time saved: We send the `X-RevenueCat-ETag` header only
- Saved ETag and last refresh time for a request: We send both the `X-RevenueCat-ETag` and `X-RC-Last-Refresh-Time` headers.

Store and return ETag last refresh time header

---

.idea/codeStyles/Project.xml
api-tester/src/main/java/com/revenuecat/apitester/java/GoogleProrationModeAPI.java
api-tester/src/main/java/com/revenuecat/apitester/java/StoreTransactionAPI.java
api-tester/src/main/java/com/revenuecat/apitester/kotlin/GoogleProrationModeAPI.kt
api-tester/src/main/java/com/revenuecat/apitester/kotlin/StoreTransactionAPI.kt
common/src/main/java/com/revenuecat/purchases/common/Backend.kt
common/src/main/java/com/revenuecat/purchases/common/ReceiptInfo.kt
common/src/main/java/com/revenuecat/purchases/common/ReplaceProductInfo.kt
common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
common/src/test/java/com/revenuecat/purchases/common/ReceiptInfoTest.kt
feature/amazon/src/main/java/com/revenuecat/purchases/amazon/storeTransactionConversions.kt
feature/google/src/main/java/com/revenuecat/purchases/google/BillingFlowParamsExtensions.kt
feature/google/src/main/java/com/revenuecat/purchases/google/BillingWrapper.kt
feature/google/src/main/java/com/revenuecat/purchases/google/PurchaseContext.kt
feature/google/src/main/java/com/revenuecat/purchases/google/storeTransactionConversions.kt
feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
public/src/main/java/com/revenuecat/purchases/ProrationMode.kt
public/src/main/java/com/revenuecat/purchases/models/GoogleProrationMode.kt
public/src/main/java/com/revenuecat/purchases/models/StoreTransaction.kt
public/src/test/java/com/revenuecat/purchases/ParcelableTests.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PostReceiptHelper.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/test/java/com/revenuecat/purchases/PostReceiptHelperTest.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
test-utils/src/main/java/com/revenuecat/purchases/utils/ParcelizationTestHelper.kt

Add missing proration modes and forward them to the Backend when posting receipts
For supporting proration modes we need to send them to the Backend. Added extra parameter in POST receipt.
Added all proration modes in GoogleProrationModes
* Use GoogleProrationMode internally instead of an enum
* Add an interface that Amazon could potentially implement in the future

Add proration modes to post to backend

---

common/src/main/java/com/revenuecat/purchases/common/AppConfig.kt
common/src/main/java/com/revenuecat/purchases/common/Backend.kt
common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/OfflineEntitlementsManager.kt
common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/OfflineEntitlementsManagerTest.kt
feature/identity/src/main/java/com/revenuecat/purchases/identity/IdentityManager.kt
feature/identity/src/test/java/com/revenuecat/purchases/identity/IdentityManagerTests.kt
feature/subscriber-attributes/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesBackendTests.kt
purchases/src/main/kotlin/com/revenuecat/purchases/CustomerInfoHelper.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PostReceiptHelper.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
purchases/src/test/java/com/revenuecat/purchases/CustomerInfoHelperTest.kt
purchases/src/test/java/com/revenuecat/purchases/PostReceiptHelperTest.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
strings/src/main/java/com/revenuecat/purchases/strings/CustomerInfoStrings.kt
strings/src/main/java/com/revenuecat/purchases/strings/OfflineEntitlementsStrings.kt

This PR enables offline entitlements automatically when we receive 5xx response codes in the `postReceipt` requests or on `getCustomerInfo` if there isn't a cached version already. It also disables offline entitlements when we receive a successful response in one of the above requests or logIn/logout.
We went with a stateful approach since we need to return the offline computed customer info from `getCustomerInfo` after a `postReceipt` fails. 
All this is also behind a flag right now that is hardcoded so we don't enter offline entitlements mode yet.

Support enabling/disabling offline entitlements

---

common/src/main/java/com/revenuecat/purchases/common/caching/DeviceCache.kt
common/src/main/java/com/revenuecat/purchases/common/networking/Endpoint.kt
common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/ProductEntitlementMapping.kt
common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/PurchasedProduct.kt
common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/PurchasedProductsFetcher.kt
common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
common/src/test/java/com/revenuecat/purchases/common/DeviceCacheTest.kt
common/src/test/java/com/revenuecat/purchases/common/networking/EndpointTest.kt
common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/OfflineCustomerInfoCalculatorTest.kt
common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/ProductEntitlementMappingTest.kt
common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/PurchasedProductsFetcherTest.kt
common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/productEntitlementMappingFactory.kt
strings/src/main/java/com/revenuecat/purchases/strings/OfflineEntitlementsStrings.kt

We are changing the format of the request to get the product entitlement mapping. This is safe to change since this is still not being used in production.

Update product entitlement mapping request to new format

---

common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/OfflineEntitlementsManager.kt
common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/OfflineEntitlementsManagerTest.kt

SDK-3095
Offline entitlements mode caches the computed customer info in memory. That means it will be lost upon a restart. So if users restart, they would temporarily go back to the cached customer info until we either get a new value from the backend or it fails again and we enter offline entitlement mode again. This can make it so developers see a strange change in customer infos upon a restart after entering offline customer info.
In order to solve this, we are clearing the cached customer info upon entering offline entitlements mode in this PR. This way, next time the user restarts the app, it will have to first try to get the value from the backend, waiting to return a value, avoiding the changes in customer info.

Clear cached customer info upon entering offline entitlements mode

---

common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/OfflineCustomerInfoCalculatorTest.kt

- Fixes `OfflineCustomerInfoCalculatorTest` `Unresolved reference: ProductType` caused by a merge conflict between #983 and #959
CI `test` job in `main` is currently ❌ https://app.circleci.com/pipelines/github/RevenueCat/purchases-android/5568/workflows/43815025-8dbf-4b47-a476-f619f7d9065f/jobs/15887
- Fixes `OfflineCustomerInfoCalculatorTest` `Unresolved reference: ProductType` caused by a merge conflict between #983 and #959
This was due to `auto-merge` https://github.com/RevenueCat/purchases-android/pull/959 without updating from https://github.com/RevenueCat/purchases-android/pull/983 which landed first
*Please describe in detail how you tested your changes*
Run …

Fix `OfflineCustomerInfoCalculatorTest` `Unresolved reference: ProductType`

---

purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/factories/StoreTransactionFactory.kt

- Fixes `PurchasesIntegrationTest` building issue caused by missing `prorationMode` in `StoreTransactionFactory#createStoreTransaction` - regression from https://github.com/RevenueCat/purchases-android/pull/977
CI `run-firebase-tests-purchases-load-shedder-integration-test` job in `main` is currently ❌ https://app.circleci.com/pipelines/github/RevenueCat/purchases-android/5569/workflows/a55166e6-0930-4086-ad32-5328d0a109d8/jobs/15888
```
> Task :purchases:compileIntegrationTestReleaseAndroidTestKotlin
e: /home/circleci/project/purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/factories/StoreTransactionFactory.kt: (43, 9): No value passed for parameter 'prorationMode'
```
Regression from #977 
*Describe your …

Fix `PurchasesIntegrationTest` building issue

---

purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/PurchasesIntegrationTest.kt

There was one test failing due to the change in https://github.com/RevenueCat/purchases-android/pull/952. This fixes the verification so the test passes.

Fix purchases integration tests

---

examples/MagicWeather/app/build.gradle
examples/MagicWeather/gradle.properties
fastlane/Fastfile

Looks like our previous solution to inject versionCode and versionName using `android.injected.version.code` and `android.injected.version.name` is broken and the lane fails to set version code and name https://issuetracker.google.com/issues/242730594?pli=1
This PR replaces that injection with just replacing two gradle properties

Fix  build_magic_weather lane

---

common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/PurchasedProductsFetcher.kt
common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/PurchasedProductsFetcherTest.kt
strings/src/main/java/com/revenuecat/purchases/strings/OfflineEntitlementsStrings.kt

If the product-entitlement mapping is not stored, we shouldn't try to calculate an offline customer info.

Fail offline entitlements computation if product entitlement mapping not available

---

common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/OfflineCustomerInfoCalculator.kt
common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/PurchasedProduct.kt
common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/PurchasedProductsFetcher.kt
common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/OfflineCustomerInfoCalculatorTest.kt
common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/PurchasedProductsFetcherTest.kt
test-utils/src/main/java/com/revenuecat/purchases/utils/billingClientStubs.kt

We were querying for the whole history of purchases when generating the offline entitlements customer info. This was done to get more accurate data in that situation. However, it adds complexity for a non-critical use case. This PR removes that functionality, simplifying the use cases for offline entitlements.

Query only active purchases when generating offline entitlements customer info

---

api-tester/src/main/java/com/revenuecat/apitester/java/SubscriptionOptionAPI.java
api-tester/src/main/java/com/revenuecat/apitester/kotlin/SubscriptionOptionAPI.kt
feature/google/src/test/java/com/revenuecat/purchases/google/SubscriptionOptionTest.kt
public/src/main/java/com/revenuecat/purchases/models/SubscriptionOption.kt

Ticket https://linear.app/revenuecat/issue/CAT-859/%5Bsdk%5D-expose-in-the-store-product-if-the-product-is-a-pre-piad-plan-or
We need to support prepaid subscriptions that were introduced starting BC 5. The SDK can check if a pricing phase's recurrence mode is NON_RECURRING to determine prepaid status.
Tested with unit tests.

CAT-859 Expose whether or not a SubscriptionOption is Prepaid in the SDK

---

build.gradle

Dokka failed to generate the docs after the gradle plugin 8 update: https://app.circleci.com/pipelines/github/RevenueCat/purchases-android/5693/workflows/aedc539a-ddc4-4478-b99b-45894517aaca/jobs/16381.
```
org.gradle.api.internal.tasks.AbstractTaskDependency: method 'void <init>()' not found
```
Updating to the latest dokka version seems to fix the issue

Bump dokka to 1.8.10 to support Gradle 8

---

common/src/main/java/com/revenuecat/purchases/common/AppConfig.kt
common/src/main/java/com/revenuecat/purchases/common/HTTPClient.kt
common/src/test/java/com/revenuecat/purchases/backend_integration_tests/BaseBackendIntegrationTest.kt
common/src/test/java/com/revenuecat/purchases/common/BaseHTTPClientTest.kt
common/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/purchasesExtensions.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt

In iOS, this flag lives within `DangerousSettings`. In Android, that's not possible due to our module setup, so I moved this flag to `AppConfig`, which is internal, so there won't be a public API.

Support forcing server errors for tests

---

common/src/main/java/com/revenuecat/purchases/common/HTTPClient.kt
common/src/main/java/com/revenuecat/purchases/common/networking/MapConverter.kt
common/src/test/java/com/revenuecat/purchases/common/networking/MapConverterTest.kt

Fixes https://linear.app/revenuecat/issue/SDK-3052/400-from-post-receipts-because-product-did-not-have-quotes
https://revenuecats.atlassian.net/browse/CSDK-681
Works around the following bug in android 4:
https://stackoverflow.com/q/37317669
http://fupeg.blogspot.com/2011/07/android-json-bug.html
Essentially, this bug means that when you get a list of product_ids, instead of sending a list of strings, it sends a list with a string in it. 
| :-: | :-: |
| "product_ids": "[item1, item2]" | "product_ids": ["item1, "item2"] |

Workaround bug in android 4 for JSON objects with List<String>

---

api-tester/build.gradle
build.gradle
examples/purchase-tester/build.gradle
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OverviewFragment.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OverviewViewModel.kt
purchases/build.gradle
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

Continuing with my exploration thought that I could kick-off https://github.com/RevenueCat/purchases-android/issues/434 work so opening this PR as a `Draft` to start the Coroutine support discussion 😊 
Some initial questions:
- What's your "policy" around adding new dependencies to the SDK?
https://github.com/RevenueCat/purchases-android/blob/04c818915a94a21fd560674cc2d90a9b5f8f6226/purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt#L736-L737
- Do you include / test all the variants of an API in `purchase-tester` app?
https://github.com/RevenueCat/purchases-android/blob/04c818915a94a21fd560674cc2d90a9b5f8f6226/examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OverviewFragment.kt#L68-L75
For now, I …

Add Coroutine support to `Purchases#getCustomerInfo(callback: ReceiveCustomerInfoCallback)` API

---

purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

Extracted `setup` and `tearDown` from `PurchasesTest.kt` so it's easier not only to split `Purchases.kt` into different test files, but also it's easier to create new tests that depend on creation of a `Purchases` object.

Extracts setup and teardown to BasePurchasesTest

---

common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/OfflineEntitlementsManager.kt
common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/OfflineEntitlementsManagerTest.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt

SDK-3139
This PR will disable offline entitlements entirely in observer mode. We won't update the product-entitlement cache either. This feature doesn't provide any value for users in observer mode so can disable it for them without consequences.

Disable offline entitlements in observer mode

---

.circleci/config.yml
purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/offlineentitlements/BaseOfflineEntitlementsIntegrationTest.kt

After adding the integration tests for offline entitlements in #1006, I was testing running each set of tests separately. However, I was changing the parameters we use to run integration tests between normal integration tests and the offline entitlement tests in order to make them pass. In order to make them compatible, I'm just hardcoding the entitlements we verify are granted after purchases during offline entitlements integration tests.

Fix integration tests in CI

---

api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
purchases/src/main/java/com/revenuecat/purchases/interfaces/SyncPurchasesCallback.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PostReceiptHelper.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
purchases/src/main/kotlin/com/revenuecat/purchases/SyncPurchasesHelper.kt
purchases/src/main/kotlin/com/revenuecat/purchases/listenerConversions.kt
purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
purchases/src/test/java/com/revenuecat/purchases/PostReceiptHelperTest.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
purchases/src/test/java/com/revenuecat/purchases/SyncPurchasesHelperTest.kt
purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt
strings/src/main/java/com/revenuecat/purchases/strings/PurchaseStrings.kt

This PR adds a new optional parameter to the `syncPurchases` function containing a success and error callbacks for that operation. Also added a new Kotlin-only version `syncPurchasesWith` to provide an easier Kotlin API.
Additionally, while doing this, I decided to move the logic from `syncPurchases` to a new `SyncPurchasesHelper`, so it can be better tested in isolation.

Add completion callback to syncPurchases API

---

.idea/codeStyles/Project.xml
api-tester/src/main/java/com/revenuecat/apitester/java/GoogleProrationModeAPI.java
api-tester/src/main/java/com/revenuecat/apitester/kotlin/GoogleProrationModeAPI.kt
feature/google/src/main/java/com/revenuecat/purchases/google/BillingWrapper.kt
feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
public/src/main/java/com/revenuecat/purchases/models/GoogleProrationMode.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/interfaces/ProductChangeCallback.kt
purchases/src/test/java/com/revenuecat/purchases/PostReceiptHelperTest.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
strings/src/main/java/com/revenuecat/purchases/strings/PurchaseStrings.kt

Support DEFERRED Proration mode.
One problem is that the returned purchase is for the old product, not the new one, so all the callback need to use the replaced productId.
Use old productId in callbacks for when proration mode is deferred.

Support DEFERRED mode

---

common/src/main/java/com/revenuecat/purchases/common/GoogleOfferingParser.kt
common/src/main/java/com/revenuecat/purchases/common/offerings/OfferingsFactory.kt
common/src/main/java/com/revenuecat/purchases/common/offerings/OfferingsManager.kt
common/src/test/java/com/revenuecat/purchases/common/offerings/OfferingsFactoryTest.kt
common/src/test/java/com/revenuecat/purchases/common/offerings/OfferingsManagerTest.kt
purchases/src/main/kotlin/com/revenuecat/purchases/OfferingParserFactory.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt
test-utils/src/main/java/com/revenuecat/purchases/utils/productStubs.kt

This is a first PR in preparation of persisting offerings in cache (SDK-3094). There are no behavior changes in this PR. This just extracts most of the code related to offerings from `Purchases` to the new classes `OfferingsManager` and `OfferingsFactory`.
- Created `OfferingsManager` that will be the entry point for all offerings-related logic
- Created `OfferingsFactory` that allows to create the `Offerings` object from a JSON response. It will query the store to get the necessary products and create the final object.
- Moved `GoogleOfferingParser` from the `feature/google` module to the `common` module. This is to be able to use the actual code in the unit tests more easily.

Refactor offerings code out of Purchases

---

common/src/defaults/kotlin/com/revenuecat/purchases/common/DispatcherConstants.kt
common/src/integrationTest/kotlin/com/revenuecat/purchases/common/DispatcherConstants.kt
common/src/main/java/com/revenuecat/purchases/common/Backend.kt
common/src/main/java/com/revenuecat/purchases/common/Dispatcher.kt
common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/BasePurchasesIntegrationTest.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

The product entitlement mapping info is not critical most times, so we can perform it as the last step when initializing the SDK as a small optimization.

Perform product entitlement mapping request after more critical requests

---

common/src/main/java/com/revenuecat/purchases/common/caching/DateExtensions.kt
common/src/main/java/com/revenuecat/purchases/common/caching/DeviceCache.kt
common/src/main/java/com/revenuecat/purchases/common/offerings/OfferingsCache.kt
common/src/main/java/com/revenuecat/purchases/common/offerings/OfferingsManager.kt
common/src/test/java/com/revenuecat/purchases/common/DeviceCacheTest.kt
common/src/test/java/com/revenuecat/purchases/common/caching/DateExtensionsTest.kt
common/src/test/java/com/revenuecat/purchases/common/offerings/OfferingsCacheTest.kt
common/src/test/java/com/revenuecat/purchases/common/offerings/OfferingsManagerTest.kt
feature/identity/src/main/java/com/revenuecat/purchases/identity/IdentityManager.kt
feature/identity/src/test/java/com/revenuecat/purchases/identity/IdentityManagerTests.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt

This is the second PR in preparation of persisting offerings (SDK-3094). In this PR, we persist the backend response for offerings, but we aren't using it yet.
- Created `OfferingsCache` to abstract the caching logic for offerings and the offerings response
- Extracted `isStale` helpers to extension functions so they can be used in the new offerings cache.

Store offerings response in SharedPreferences

---

common/src/main/java/com/revenuecat/purchases/common/Backend.kt
common/src/main/java/com/revenuecat/purchases/common/offerings/OfferingsManager.kt
common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
common/src/test/java/com/revenuecat/purchases/common/offerings/OfferingsManagerTest.kt
purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/BasePurchasesIntegrationTest.kt
purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/PurchasesIntegrationTest.kt
strings/src/main/java/com/revenuecat/purchases/strings/OfferingStrings.kt

Third and final part of persisting offerings in disk to make the system more robust. In this final PR, we use the offerings response cached in #1028 so, in case of a backend error getting offerings, we can calculate the offerings (as long as Play store/Amazon store still give us the product information) as long as we have cached the value before.

Get offerings response from disk cache if available

---

README.md
migrations/v5-MIGRATION.md

Want to make migrations guide more discoverable, so adding links to the main Readme

Updated readme to include links to migration guides

---

README.md

Follow-up from https://github.com/RevenueCat/purchases-android/pull/984#pullrequestreview-1449271470
Quick PR adding a quick `README` fix that I found while exploring `purchases-android`'s repo / learning how RevenueCat's Purchases SDK works.
- Fixes `README` `CONTRIBUTING` guide broken link
*Please describe in detail how you tested your changes*
- Easy test 😅
`CONTRIBUTING.md` lives now in the repo's root (`Contributing` folder doesn't exist anymore) so checked that clicking the link redirects me to `CONTRIBUTING`
cc @tonidero

[EXTERNAL] Fix `README` `CONTRIBUTING` guide broken link

---

.circleci/config.yml
build.gradle
library.gradle
purchases/build.gradle

~Resolves #356 by adding test coverage back.~ Code coverage was added back in a while ago! This PR updates Kover to 0.7.0 and makes the changes necessary to merge reports.
Kover has recently updated to 0.7.0, so the update was also performed as part of this PR.
It required some changes to how Kover is set up and how the reports are merged. I followed the advice in the [migration
guide](https://github.com/Kotlin/kotlinx-kover/blob/v0.7.0/docs/gradle-plugin/migrations/migration-to-0.7.0.md) and the [android multiproject
example](https://github.com/Kotlin/kotlinx-kover/tree/v0.7.0/examples/android/multiproject).
I also updated the CircleCI script and added the test coverage badge back to the readme.
Obviously, I don't have access to your CI to test this completely, but I have run everything …

[EXTERNAL] Update Kover to 0.7.0 (#1031) via @mikescamell

---

examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/MainApplication.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OverviewFragment.kt

Changed PurchaseTester to update the customer info in the overview fragment from the customer info listener instead of the initial result from getting the customer info. This way, we always display the most up to date information.

[PurchaseTester] Update CustomerInfo from listener in overview screen

---

README.md

Follow-up from https://github.com/RevenueCat/purchases-android/pull/984#discussion_r1209172348
- Adds `MagicWeather` app note to the main `README` as discussed in https://github.com/RevenueCat/purchases-android/pull/984#discussion_r1209172348
- Fixes a typo: ~Migrating~ > Migration
cc @tonidero

[EXTERNAL] Add `MagicWeather` app note to the main `README` and fix a typo

---

common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/PurchasedProductsFetcher.kt
common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/PurchasedProductsFetcherTest.kt

As I continue my journey exploring `purchases-android`'s repo / learning how RevenueCat's Purchases SDK works (refs. https://github.com/RevenueCat/purchases-android/pull/984) noticed that `PurchasedProductsFetcher` was relying on `@Deprecated` usage of `skus` so this is mostly a quick refactoring that addresses that tech debt replacing `skus` occurrences by `productIds`.
- Replace `@Deprecated` usage of `skus` by `productIds` from `PurchasedProductsFetcher`
- Refactor `getExpirationDate` `if else` chain by `when`
- When checking that the changes made in `PurchasedProductsFetcher` were working as expected, I landed at `PurchasedProductsFetcherTest` and took a quick pass and refactored the tests to …

[EXTERNAL] Replace `@Deprecated` usage of `skus` by `productIds` from `PurchasedProductsFetcher`

---

README.md

Follow-up from
https://github.com/RevenueCat/purchases-android/pull/984#discussion_r1209172348
- Adds `MagicWeather` app note to the main `README` as discussed in https://github.com/RevenueCat/purchases-android/pull/984#discussion_r1209172348
- Fixes a typo: ~Migrating~ > Migration
Contributed by @pablo-guardiola

[EXTERNAL] Add `MagicWeather` app note to the main `README` and fix a typo (#1041)

---

build.gradle
examples/MagicWeather/build.gradle

This PR updates the Gradle plugin from 8.0.0 to 8.0.2

Update gradle plugin to 8.0.2

---

fastlane/Fastfile

I noticed a lot of flakiness around the backend integration tests. Looks like it's because those were using the long jittering durations for the requests, which can delay the request up to 10s. I changed to execute the backend integration tests only in the integration test flavor which reduces that amount to a maximum of 1s.

Fix backend integration test flakiness

---

api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OverviewViewModel.kt
public/src/main/java/com/revenuecat/purchases/ExperimentalPreviewRevenueCatPurchasesAPI.kt
purchases/src/main/kotlin/com/revenuecat/purchases/coroutinesExtensions.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesCoroutinesTest.kt

**Why is this change required? What problem does it solve?**
Follow up from
https://github.com/RevenueCat/purchases-android/pull/1012/files#r1223917692
Instead of only noting that `Purchases.awaitCustomerInfo()` is experimental in the docs (which are often overlooked 😬), we can be more explicit and add an opt-in requirement annotation
`ExperimentalPreviewRevenueCatPurchasesAPI`.
Capturing from the [Kotlin Opt-in requirements
docs](https://kotlinlang.org/docs/opt-in-requirements.html):
> The Kotlin standard library provides a mechanism for requiring and
giving explicit consent for using certain elements of APIs. This mechanism lets library developers inform users of their APIs about specific conditions that require opt-in, for example, if an API is in the experimental state and is likely …

[EXTERNAL] Add `ExperimentalPreviewRevenueCatPurchasesAPI` opt-in requirement to `Purchases.awaitCustomerInfo()` (#1060)

---

api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/ConfigureFragment.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesConfiguration.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesConfigurationTest.kt

SDK-3186
This makes it so enabling entitlement verification informational mode also requires enabling diagnostics. This is meant to be used for the beta.

Make enabling entitlement verification also enabled diagnostics

---

api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
api-tester/src/main/java/com/revenuecat/apitester/kotlin/EntitlementInfoAPI.kt
api-tester/src/main/java/com/revenuecat/apitester/kotlin/EntitlementInfosAPI.kt
common/src/main/java/com/revenuecat/purchases/common/caching/DeviceCache.kt
common/src/test/java/com/revenuecat/purchases/common/DeviceCacheTest.kt
common/src/test/java/com/revenuecat/purchases/common/EntitlementInfosTests.kt
config/detekt/detekt-baseline.xml
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/ConfigureFragment.kt
feature/identity/src/main/java/com/revenuecat/purchases/identity/IdentityManager.kt
feature/identity/src/test/java/com/revenuecat/purchases/identity/IdentityManagerTests.kt
public/src/main/java/com/revenuecat/purchases/EntitlementInfo.kt
public/src/main/java/com/revenuecat/purchases/EntitlementInfos.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesConfiguration.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesConfigurationTest.kt

This PR has changes from #1060 and is based on #1061 
This adds a require opt in requirement to use the trusted entitlements API.

Require experimental annotation for trusted entitlements API

---

feature/google/src/main/java/com/revenuecat/purchases/google/BillingWrapper.kt
feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt

I noticed Google's `queryPurchases` method would never end if we got a connection error to the billing client (either a `FEATURE_NOT_SUPPORTED` or `BILLING_UNAVAILABLE` error).
This makes it so the method returns the error in the error callback.

Return error in queryPurchases if error connecting to billing client

---

common/src/main/java/com/revenuecat/purchases/common/AppConfig.kt
common/src/main/java/com/revenuecat/purchases/common/verification/SigningManager.kt
common/src/test/java/com/revenuecat/purchases/backend_integration_tests/BaseBackendIntegrationTest.kt
common/src/test/java/com/revenuecat/purchases/common/AppConfigTest.kt
common/src/test/java/com/revenuecat/purchases/common/BaseHTTPClientTest.kt
common/src/test/java/com/revenuecat/purchases/common/verification/SigningManagerTest.kt
purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/BasePurchasesIntegrationTest.kt
purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/purchasesExtensions.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt

SDK-3182
This allows to force signing errors during tests so we can better test the trusted entitlements feature automatically.

Trusted entitlements: Add internal mechanism to force signing errors for tests

---

purchases/src/main/kotlin/com/revenuecat/purchases/CustomerInfoHelper.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PostPendingTransactionsHelper.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
purchases/src/main/kotlin/com/revenuecat/purchases/SyncPurchasesHelper.kt
purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
purchases/src/test/java/com/revenuecat/purchases/CustomerInfoHelperTest.kt
purchases/src/test/java/com/revenuecat/purchases/PostPendingTransactionsHelperTest.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesCoroutinesTest.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
purchases/src/test/java/com/revenuecat/purchases/SyncPurchasesHelperTest.kt
strings/src/main/java/com/revenuecat/purchases/strings/CustomerInfoStrings.kt

Followup to #1052 and #1058 
This changes the behavior of fetching customer info. Now, when fetching customer info, we will first try to sync any pending purchases if any. If there are pending purchases, we will return the customer info from the last request sent. If there aren't, we will then hit the current customer info endpoint to get the latest customer info.

Sync pending purchases before getting customer info

---

common/src/main/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizer.kt
common/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizerTest.kt

We got reports of some crashes for users using diagnostics https://community.revenuecat.com/questions/2388. I haven't been able to repro the issues, but we shouldn't let the SDK crash due to this. This makes our catch for reading diagnostics events more generic so we handle those more gracefully

Handle other diagnostics-related exceptions

---

api-tester/build.gradle
base-application.gradle
build.gradle
common/build.gradle
examples/MagicWeather/app/build.gradle
examples/MagicWeather/build.gradle
examples/MagicWeather/gradle/libs.versions.toml
examples/MagicWeather/settings.gradle
examples/purchase-tester/build.gradle
feature/amazon/build.gradle
feature/google/build.gradle
feature/identity/build.gradle
feature/subscriber-attributes/build.gradle
gradle/libs.versions.toml
integration-tests/build.gradle
library.gradle
public/build.gradle
purchases/build.gradle
settings.gradle
strings/build.gradle
test-utils/build.gradle
utils/build.gradle

Migrate to Gradle version catalog

---

common/src/main/java/com/revenuecat/purchases/common/CustomerInfoFactory.kt
common/src/test/java/com/revenuecat/purchases/common/CustomerInfoFactoryTest.kt

An integration test started failing due to #1073. The error was that the schemaVersion field in the customer info didn't match between the fetched and cached customer info. It was actually luck that made it work before 😬 .
Before that change, this test tried to get customer info twice: On sdk configuration and the first part of the test. Since both of these happen pretty quickly, we only made the request once and called both callbacks with the same response. However, the first request actually modified the JSONObject, adding the schema version and some other fields in order to cache it in the device. This made it so the JSONObject actually had those fields in the second callback, causing the schemaVersion to have a value. Then, the value returned from cache already has the schemaVersion …

Default customer info schema version to latest known by SDK

---

.run/Debug tests.run.xml
.run/Release tests.run.xml
.run/Tests in defaultsRelease variant.run.xml

This adds 2 new run configuration in Android studio to run the tests only in the `defaultsDebug` or `defaultsRelease` variant
The `All tests` run configuration run the same tests multiple times:
- defaultsDebug
- defaultsRelease
- integrationTestDebug
- integrationTestRelease
Many times, we don't really need to run the tests in all variants, this provides a way so tests are a bit faster to run locally when it's not needed to run in all variants.

Add defaultsRelease variant tests run configuration

---

api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
purchases/src/main/kotlin/com/revenuecat/purchases/coroutinesExtensions.kt

**Why is this change required? What problem does it solve?**
Follow up from https://github.com/RevenueCat/purchases-android/pull/1077#discussion_r1238268219
**Describe your changes in detail**
- Add missing `fetchPolicy` parameter to `awaitCustomerInfo` API
**Please describe in detail how you tested your changes**
- Run `purchases` tests
- Run `examples.purchase-test` app
cc @vegaro @tonidero

[EXTERNAL] Add missing `fetchPolicy` parameter to `awaitCustomerInfo` API

---

CHANGELOG.md

Follow up on https://github.com/RevenueCat/purchases-android/pull/1059#issuecomment-1608037836
It looks like the changelog didn't include @mikescamell name as a contributor

Update CHANGELOG.md to include external contribution

---

gradle/libs.versions.toml
purchases/build.gradle
purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/BasePurchasesIntegrationTest.kt
purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/trustedentitlements/TrustedEntitlementsInformationalModeIntegrationTest.kt

**Why is this change required? What problem does it solve?**
Follow up from https://github.com/RevenueCat/purchases-android/pull/1071#discussion_r1232485138
**Describe your changes in detail**
- Adds `awaitCustomerInfo` / coroutines tests to `TrustedEntitlementsInformationalModeIntegrationTest`
**Please describe in detail how you tested your changes**
- Run integration tests locally ✅ 
cc @tonidero @vegaro @NachoSoto

[EXTERNAL] Add `awaitCustomerInfo` / coroutines tests to `TrustedEntitlementsInformationalModeIntegrationTest`

---

gradle/libs.versions.toml
purchases/build.gradle
purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/BasePurchasesIntegrationTest.kt
purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/trustedentitlements/TrustedEntitlementsInformationalModeIntegrationTest.kt

**Why is this change required? What problem does it solve?**
Follow up from
https://github.com/RevenueCat/purchases-android/pull/1071#discussion_r1232485138
**Describe your changes in detail**
- Adds `awaitCustomerInfo` / coroutines tests to `TrustedEntitlementsInformationalModeIntegrationTest`
**Please describe in detail how you tested your changes**
- Run integration tests locally ✅ 
Contributed by @pablo-guardiola

[EXTERNAL] Add `awaitCustomerInfo` / coroutines tests to `TrustedEntitlementsInformationalModeIntegrationTest` (#1077) via @pablo-guardiola

---

common/src/main/java/com/revenuecat/purchases/common/verification/Signature.kt
common/src/test/java/com/revenuecat/purchases/common/verification/SignatureTest.kt

First PR for SDK-3200
This adds the new `Signature` type which will encode the different fields that are part of the new signature format. This is currently unused and will be used in future PRs.

Trusted entitlements: Add Signature type to process new signature response format

---

common/src/main/java/com/revenuecat/purchases/common/IntExtensions.kt
common/src/main/java/com/revenuecat/purchases/common/verification/IntermediateSignatureHelper.kt
common/src/main/java/com/revenuecat/purchases/common/verification/SignatureVerifier.kt
common/src/test/java/com/revenuecat/purchases/common/verification/IntermediateSignatureHelperTest.kt

Second PR to implement SDK-3200
This PR creates the new `IntermediateSignatureHelper` class to handle the logic related to verifying intermediate keys. This is not currently used and will be used in future PRs

Trusted entitlements: Add IntermediateSignatureHelper to handle intermediate signature verification process

---

examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OverviewFragment.kt
examples/purchase-tester/src/main/res/layout/fragment_overview.xml
examples/purchase-tester/src/main/res/values/strings.xml

Current limitation: only supports purchasing OTP products and the first baseplan of a subscription
https://github.com/RevenueCat/purchases-android/assets/1014118/ebb91409-3afe-4f8d-b4a2-fa229995e8f2

[PurchaseTester] Add option to purchase an arbitrary product id

---

common/src/main/java/com/revenuecat/purchases/common/HTTPClient.kt
common/src/main/java/com/revenuecat/purchases/common/verification/SignatureVerificationMode.kt
common/src/main/java/com/revenuecat/purchases/common/verification/SigningManager.kt
common/src/main/java/com/revenuecat/purchases/strings/NetworkStrings.kt
common/src/test/java/com/revenuecat/purchases/common/HTTPClientVerificationTest.kt
common/src/test/java/com/revenuecat/purchases/common/verification/SignatureVerificationModeTest.kt
common/src/test/java/com/revenuecat/purchases/common/verification/SigningManagerTest.kt

Third PR for SDK-3200
- Adds support to the new signature format (salt + nonce + TS + etag + content)
- Adds support for intermediate signatures verification
- Makes nonce optional in preparation of static endpoint signing.
Based on #1109 and #1110.

Trusted entitlements: Use new signature verification format

---

common/src/main/java/com/revenuecat/purchases/common/HTTPClient.kt
common/src/main/java/com/revenuecat/purchases/common/networking/ETagManager.kt
common/src/main/java/com/revenuecat/purchases/common/verification/SignatureVerificationMode.kt
common/src/main/java/com/revenuecat/purchases/common/verification/SigningManager.kt
common/src/main/java/com/revenuecat/purchases/strings/NetworkStrings.kt
common/src/test/java/com/revenuecat/purchases/common/BaseHTTPClientTest.kt
common/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
common/src/test/java/com/revenuecat/purchases/common/HTTPClientVerificationTest.kt
common/src/test/java/com/revenuecat/purchases/common/networking/ETagManagerTest.kt
common/src/test/java/com/revenuecat/purchases/common/verification/SignatureVerificationModeTest.kt
common/src/test/java/com/revenuecat/purchases/common/verification/SigningManagerTest.kt

Added additional checks to not use cached etags when cached result is NOT_REQUESTED and verification is enabled. This will be used for other signed requests aside from the customer info/post receipt/login endpoints.

Trusted entitlements: Do not use etags if cache version not requested and verification enabled

---

.circleci/config.yml
purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/BasePurchasesIntegrationTest.kt

Looks like our new coroutine test infrastructure added in #1077 / #1107 wasn't waiting for the code to be executed before continuing. In some cases the `@After` code was actually executed before the test, in those cases, the test was failing. In this PR I change it to a blocking method so the test finishes before continuing.

Fix flaky integration tests: Wait for coroutines to finish before continuing

---

purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/BasePurchasesIntegrationTest.kt
purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/PurchasesIntegrationTest.kt
purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/helpers/BillingAbstractMockHelper.kt
purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/offlineentitlements/BaseOfflineEntitlementsIntegrationTest.kt
purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/purchasesExtensions.kt
purchases/src/test/java/com/revenuecat/purchases/backend_integration_tests/ProductionBackendIntegrationTest.kt

This fixes a couple of things:
- Fixes integration tests after the changes in #1106. There were some compiler issues
- Changes the project used by production integration tests and production backend integration tests to make it more stable (We were using a shared project before 😬 )

Fix integration tests and change to a different project

---

purchases/src/main/kotlin/com/revenuecat/purchases/common/verification/SigningManager.kt
purchases/src/test/java/com/revenuecat/purchases/common/verification/SigningManagerTest.kt

We made one more change to the signature verification. Now we don't need to decode the url in order to verify the signature.

Trusted entitlements: Remove decoding of url to verify signatures

---

purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
purchases/src/main/kotlin/com/revenuecat/purchases/common/HTTPClient.kt
purchases/src/main/kotlin/com/revenuecat/purchases/common/networking/ETagManager.kt
purchases/src/main/kotlin/com/revenuecat/purchases/common/verification/SignatureVerificationMode.kt
purchases/src/main/kotlin/com/revenuecat/purchases/common/verification/SigningManager.kt
purchases/src/main/kotlin/com/revenuecat/purchases/strings/NetworkStrings.kt
purchases/src/test/java/com/revenuecat/purchases/backend_integration_tests/BaseBackendIntegrationTest.kt
purchases/src/test/java/com/revenuecat/purchases/common/BaseHTTPClientTest.kt
purchases/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
purchases/src/test/java/com/revenuecat/purchases/common/HTTPClientVerificationTest.kt
purchases/src/test/java/com/revenuecat/purchases/common/networking/ETagManagerTest.kt
purchases/src/test/java/com/revenuecat/purchases/common/verification/SignatureVerificationModeTest.kt
purchases/src/test/java/com/revenuecat/purchases/common/verification/SigningManagerTest.kt

Integration branch for the changes in trusted entitlements. Includes changes from:
- #1111 
- #1114 
- #1118 
- #1119 
- #1124

Trusted entitlements: New trusted entitlements signature format

---

api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
api-tester/src/main/java/com/revenuecat/apitester/kotlin/EntitlementInfoAPI.kt
api-tester/src/main/java/com/revenuecat/apitester/kotlin/EntitlementInfosAPI.kt
api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
config/detekt/detekt-baseline.xml
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/ConfigureFragment.kt
purchases/src/main/kotlin/com/revenuecat/purchases/EntitlementInfo.kt
purchases/src/main/kotlin/com/revenuecat/purchases/EntitlementInfos.kt
purchases/src/main/kotlin/com/revenuecat/purchases/EntitlementVerificationMode.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesConfiguration.kt
purchases/src/main/kotlin/com/revenuecat/purchases/common/caching/DeviceCache.kt
purchases/src/main/kotlin/com/revenuecat/purchases/identity/IdentityManager.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesConfigurationTest.kt
purchases/src/test/java/com/revenuecat/purchases/common/CustomerInfoFactoryTest.kt
purchases/src/test/java/com/revenuecat/purchases/common/DeviceCacheTest.kt
purchases/src/test/java/com/revenuecat/purchases/common/EntitlementInfosTests.kt
purchases/src/test/java/com/revenuecat/purchases/identity/IdentityManagerTests.kt

This PR brings Trusted entitlements to stable and to java. 
This new feature prevents MitM attacks between the SDK and the RevenueCat server.
With verification enabled, the SDK ensures that the response created by the server was not modified by a third-party, and the entitlements received are exactly what was sent.
This is 100% opt-in. EntitlementInfos have a new VerificationResult property, which will indicate the validity of the responses when this feature is enabled.
```
fun configureRevenueCat() {
val configuration = PurchasesConfiguration.Builder(context, apiKey)
.entitlementVerificationMode(EntitlementVerificationMode.INFORMATIONAL)
.build()
Purchases.configure(configuration)
}
```

`Trusted Entitlements`: stable

---

purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/PurchasesIntegrationTest.kt

After #1123, we fixed the production integration tests but we broke the load shedder integration tests (since the load shedder is using monthly skus and the production app is using annual skus)... This fixes it so it works for both.

Fix load shedder integration tests

---

purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
purchases/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt

In some situations, we weren't refreshing the customer info on app open. This was caused by #1073. In that PR we changed to fetch current purchases before getting customer info, so we would sync purchases before getting customer info. However, when we fetch customer info during the app open's `onAppForeground` callback, the `billing.purchasesUpdatedListener` was not set. Currently, if that listener isn't set, we would just [skip the query](https://github.com/RevenueCat/purchases-android/blob/ef34062996a17aa6a47d6eb2ca0903d66a51ab5e/purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt#L142) altogether so we would never get a response. 
Thanks @joshdholtz  for bringing it up!

Fix issue updating customer info on app open

---

purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesConfiguration.kt
purchases/src/main/kotlin/com/revenuecat/purchases/errors.kt

This adds a link to the trusted entitlements page in the docs when there is a signature verification error. This will help users get more data about the issue immediately without having to contact support.

Trusted entitlements: Improve signature verification error log

---

.circleci/config.yml
purchases/consumer-rules.pro

Looks like integration tests from the integration tests module failed to build after the module refactor https://circleci.com/gh/RevenueCat/purchases-android/20341. 
After investigating, looks like it's complaining when minifying the purchases module since it can't find the amazon classes. This makes sense since we don't have the amazon sdk there (it's compile only). The solution is to make those classes not warn. If people use the amazon dependency, they would get its own set of rules which keeps the amazon classes

R8: Do not warn about amazon classes in purchases module

---

api-tester/src/main/java/com/revenuecat/apitester/java/VerificationResultAPI.java
api-tester/src/main/java/com/revenuecat/apitester/kotlin/VerificationResultAPI.kt
purchases/src/main/kotlin/com/revenuecat/purchases/VerificationResult.kt
purchases/src/test/java/com/revenuecat/purchases/VerificationResultTest.kt

This adds a `isVerified` property to the `VerificationResult` enum for convenience when dealing with the verification results. Android version of: https://github.com/RevenueCat/purchases-ios/pull/2788

Trusted entitlements: Add isVerified propety to VerificationResult enum

---

purchases/src/main/kotlin/com/revenuecat/purchases/amazon/AmazonBackend.kt
purchases/src/main/kotlin/com/revenuecat/purchases/common/Backend.kt
purchases/src/main/kotlin/com/revenuecat/purchases/common/BackendHelper.kt
purchases/src/main/kotlin/com/revenuecat/purchases/common/HTTPClient.kt
purchases/src/main/kotlin/com/revenuecat/purchases/common/networking/HTTPRequest.kt
purchases/src/main/kotlin/com/revenuecat/purchases/common/verification/SigningManager.kt
purchases/src/main/kotlin/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesPoster.kt
purchases/src/test/java/com/revenuecat/purchases/amazon/AmazonBackendTest.kt
purchases/src/test/java/com/revenuecat/purchases/backend_integration_tests/BaseBackendIntegrationTest.kt
purchases/src/test/java/com/revenuecat/purchases/backend_integration_tests/LoadShedderBackendIntegrationTest.kt
purchases/src/test/java/com/revenuecat/purchases/backend_integration_tests/ProductionBackendIntegrationTest.kt
purchases/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
purchases/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
purchases/src/test/java/com/revenuecat/purchases/common/HTTPClientVerificationTest.kt
purchases/src/test/java/com/revenuecat/purchases/common/verification/SigningManagerTest.kt
purchases/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesBackendTests.kt

As an additional security measure we will add a new header to the request that will be part of the data to verify as part of the signature.
Depends on https://github.com/RevenueCat/khepri/pull/6246

Trusted entitlements: Support post params hash header

---

purchases/src/main/kotlin/com/revenuecat/purchases/DangerousSettings.kt
purchases/src/main/kotlin/com/revenuecat/purchases/common/AppConfig.kt
purchases/src/test/java/com/revenuecat/purchases/DangerousSettingsTest.kt
purchases/src/test/java/com/revenuecat/purchases/common/AppConfigTest.kt

This PR adds an internal `customEntitlementsComputation` property to `DangerousSettings` and `AppConfig` so it can be used in the following PRs

Add internal customEntitlementsComputation mode to app config

---

purchases/src/main/kotlin/com/revenuecat/purchases/common/HTTPClient.kt
purchases/src/test/java/com/revenuecat/purchases/backend_integration_tests/BaseBackendIntegrationTest.kt
purchases/src/test/java/com/revenuecat/purchases/common/BaseHTTPClientTest.kt
purchases/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt

This PR adds a new header `X-Custom-Entitlements-Computation` to all requests when custom entitlement computation is enabled.

Add header to requests when in custom entitlement computation mode

---

purchases/src/main/kotlin/com/revenuecat/purchases/DangerousSettings.kt
purchases/src/main/kotlin/com/revenuecat/purchases/common/AppConfig.kt
purchases/src/main/kotlin/com/revenuecat/purchases/common/HTTPClient.kt
purchases/src/main/kotlin/com/revenuecat/purchases/common/offlineentitlements/OfflineEntitlementsManager.kt
purchases/src/test/java/com/revenuecat/purchases/DangerousSettingsTest.kt
purchases/src/test/java/com/revenuecat/purchases/backend_integration_tests/BaseBackendIntegrationTest.kt
purchases/src/test/java/com/revenuecat/purchases/common/AppConfigTest.kt
purchases/src/test/java/com/revenuecat/purchases/common/BaseHTTPClientTest.kt
purchases/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
purchases/src/test/java/com/revenuecat/purchases/common/offlineentitlements/OfflineEntitlementsManagerTest.kt

In iOS, we are using `customEntitlementComputation` instead of `customEntitlementsComputation`. This makes it consistent in android

Make customEntitlementComputation singular

---

config/detekt/detekt-baseline.xml
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt

We need to separate the public interface from the class itself, so we can reuse the logic in custom entitlements. 
To do that, we're going to rename the Purchases class to something private, then create a new Purchases class that only has the public interface. The public interface will redirect all calls and properties to the internal class.

Creates PurchasesOrchestrator

---

purchases/src/main/kotlin/com/revenuecat/purchases/CustomerInfoUpdateHandler.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
purchases/src/test/java/com/revenuecat/purchases/CustomerInfoUpdateHandlerTest.kt

Disables the first fire of the Customer Info listener when it's set initially.

CustomEntitlementsComputation: disable first listener callback when set

---

purchases/build.gradle

After #1153, docs were generated with multiple `Purchases` classes and it was very confusing. For the public docs, we only need the defaults flavor, so we can remove docs for the customEntitlementComputation package

CustomEntitlementComputation: Generate dokka docs only for defaults flavor

---

api-tester/src/customEntitlementComputation/kotlin/com/revenuecat/apitester/java/PurchasesAPI.java
api-tester/src/customEntitlementComputation/kotlin/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
purchases/src/customEntitlementComputation/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
purchases/src/main/kotlin/com/revenuecat/purchases/identity/IdentityManager.kt
purchases/src/main/kotlin/com/revenuecat/purchases/strings/IdentityStrings.kt
purchases/src/test/java/com/revenuecat/purchases/identity/IdentityManagerTests.kt
purchases/src/testCustomEntitlementComputation/kotlin/com/revenuecat/purchases/PurchasesLoginTests.kt
purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesTest.kt

This method allows you to change the cached app user id, but it doesn't fetch the customer info afterwards. It does fetch offerings though. 
Here's the iOS equivalent
https://github.com/RevenueCat/purchases-ios/blob/598a76f18d4836573381ebd6a90140e5e24e07c1/Sources/Identity/IdentityManager.swift#L94

Add switchUser

---

api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesTransactionExceptionAPI.java
api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesCommonAPI.kt
api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesTransactionExceptionAPI.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OfferingFragment.kt
purchases/src/main/kotlin/com/revenuecat/purchases/CoroutinesExtensionsCommon.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchaseResult.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesException.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesTransactionException.kt
purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesCommonTest.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesCoroutinesCommonTest.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTransactionExceptionTest.kt
purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesCoroutinesTest.kt
purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesTest.kt

Adds a coroutine alternative to `purchase()`

purchase coroutine
