RevenueCat/purchases-android

purchases-sample/src/main/java/com/revenuecat/purchases_sample/MainActivity.java
purchases/build.gradle
purchases/src/androidTest/java/com/revenuecat/purchases/PurchasesBuilderTest.java
purchases/src/main/java/com/revenuecat/purchases/Backend.java
purchases/src/main/java/com/revenuecat/purchases/Dispatcher.java
purchases/src/main/java/com/revenuecat/purchases/Purchases.java
purchases/src/test/java/com/revenuecat/purchases/BackendTest.java
purchases/src/test/java/com/revenuecat/purchases/BillingWrapperTest.java
purchases/src/test/java/com/revenuecat/purchases/DispatcherTest.java
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.java

[FINAL] Some Small Tweaks

---

purchases/src/main/java/com/revenuecat/purchases/Purchases.java
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.java

- Emits the cached user info every time the activity resumes
- Caches purchaser info for all cases

[FINAL] Better Caching

---

CHANGELOG.md
README.md
gradle.properties
purchases/build.gradle
purchases/src/main/java/com/revenuecat/purchases/Purchases.java

- Entitlements support
- Caching of purchaser info
- RevenueCat is coming out of beta! Sign up at https://www.revenuecat.com/

[RELEASE] 1.0.0

---

CHANGELOG.md
gradle.properties
purchases/build.gradle
purchases/src/main/java/com/revenuecat/purchases/Purchases.java

- Add restore transactions listener methods

[FINAL] 1.1.0

---

purchases/src/main/java/com/revenuecat/purchases/Backend.java
purchases/src/test/java/com/revenuecat/purchases/BackendTest.java

Encodes the app user id if someone uses an appUserID with non url friendly characters

[FINAL] Encode appUserId

---

CHANGELOG.md
gradle.properties
purchases/build.gradle
purchases/src/main/java/com/revenuecat/purchases/Purchases.java

Just fixes visibility of addAttribution methods.

[RELEASE] 1.3.1

---

build.gradle
purchases-sample/src/main/java/com/revenuecat/purchases_sample/MainActivity.java
purchases-sample/src/main/res/layout/activity_main.xml
purchases/src/main/java/com/revenuecat/purchases/BillingWrapper.java
purchases/src/main/java/com/revenuecat/purchases/Purchases.java
purchases/src/test/java/com/revenuecat/purchases/BillingWrapperTest.java
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.java

Add support for "finishing" non-subscription purchases.

[FINAL] Basic Consumables Support

---

purchases-sample/src/main/java/com/revenuecat/purchases_sample/MainActivity.java
purchases-sample/src/main/res/layout/activity_main.xml
purchases/src/main/java/com/revenuecat/purchases/Backend.java
purchases/src/main/java/com/revenuecat/purchases/BillingWrapper.java
purchases/src/main/java/com/revenuecat/purchases/Dispatcher.java
purchases/src/main/java/com/revenuecat/purchases/Purchases.java
purchases/src/test/java/com/revenuecat/purchases/BillingWrapperTest.java
purchases/src/test/java/com/revenuecat/purchases/DispatcherTest.java
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.java

Add a close method to Purchases. This provides a way to clean up the framework when switching users.

[FINAL] Add Close Method

---

purchases/src/main/java/com/revenuecat/purchases/Purchases.java
purchases/src/test/java/com/revenuecat/purchases/PurchasesBuilderTest.java

There was a UnitTest inside the `androidTest` folder. I moved it to `test` to be able to run it as a Unit Test. It was actually broken so I fixed it.
Also I removed the field `context` from `Purchases::Builder` since you can actually access the application context from `Application`.

Fix missing test

---

purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

On 1.4.0 we removed sending whatever is in the cache because it would be done after refreshing the caches. It turns out, if the app doesn't have network connectivity, it will never send anything since the backend call would never complete. 
I reverted this change and now it matches what we do in iOS too, which is send whatever is in the cache when the delegate is set.
So now, if online, the listener will be called twice (first with whatever is in the cache if anything, and second with whatever the backend returns), if offline, the listener will be called with whatever is in the cache after setting it. 
When coming back from background, it will also send whatever is in the cache if it is not stale.
I realized there's another "bug" related to this. If offline, when coming back from …

Fix offline: emits whatever is in the cache after setting the listener

---

purchases-sample/src/main/java/com/revenuecat/sample/MainApplication.kt
purchases/src/main/java/com/revenuecat/purchases/interfaces/Callback.java
purchases/src/main/java/com/revenuecat/purchases/interfaces/IsSupportedListener.java
purchases/src/main/kotlin/com/revenuecat/purchases/BillingWrapper.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/listenerConversions.kt
purchases/src/test/java/com/revenuecat/purchases/BillingWrapperTest.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

- `isBillingSupported` as a way to check if Play Billing is available on the device and IAPs are available
- `isFeatureSupported` as a way to check if Subscriptions are available on device

Creates two methods: isBillingSupported and isFeatureSupported.

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
purchases-sample/src/main/java/com/revenuecat/sample/UpsellActivity.kt
purchases/build.gradle
purchases/src/main/kotlin/com/revenuecat/purchases/BillingWrapper.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/listenerConversions.kt
purchases/src/test/java/com/revenuecat/purchases/BillingWrapperTest.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

Updates BillingClient to 1.2 and adds a `syncPurchases` method to be called on observerMode

BillingClient 1.2

---

purchases/src/main/kotlin/com/revenuecat/purchases/HTTPClient.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/utils.kt
purchases/src/test/java/com/revenuecat/purchases/HTTPClientTest.kt

Had to add a backup for Android versions below Lollipop since `toLanguageTag` is not available

Adds locale and version name to headers

---

purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

Fixes https://github.com/RevenueCat/purchases-android/issues/68

Avoids cache being deleted if there is an error when fetching purchaser info

---

build.gradle
gradle.properties
purchases-sample/build.gradle
purchases/build.gradle
purchases/consumer-proguard-rules.pro
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt

Related to https://youtrack.jetbrains.com/issue/KT-16084
Also added consumer proguard rules

Fixes pro guard

---

purchases/src/main/kotlin/com/revenuecat/purchases/Backend.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/test/java/com/revenuecat/purchases/BackendTest.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

Added observer_mode parameter to the post token calls. This will help us identify which apps are using us on observer mode.

Adds observer_mode parameter

---

purchases/src/main/kotlin/com/revenuecat/purchases/Backend.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/utils.kt
purchases/src/test/java/com/revenuecat/purchases/BackendTest.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

We need to start posting prices and currencies for consumables when purchasing.
https://trello.com/b/IfcFWN4U/backlog

[final] Adds price and currency to the post receipt

---

build.gradle
purchases/build.gradle

The maven publish plugin was adding a more recent version of dokka to our project and they have changed the way the plugin is configured. I have updated the configuration and the dokka version we include

Fixes build by updating dokka

---

.circleci/config.yml

For some reason, the docs deployment job wasn't added to any workflow

Adds docs job

---

CHANGELOG.md
gradle.properties
purchases/build.gradle
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt

- Fixes NoSuchElementException #115

Version 3.0.7

---

build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties
purchases-sample/src/main/java/com/revenuecat/sample/MainApplication.kt
purchases/build.gradle
purchases/src/main/kotlin/com/revenuecat/purchases/Backend.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Factories.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/attributes/SpecialSubscriberAttributes.kt
purchases/src/main/kotlin/com/revenuecat/purchases/attributes/SubscriberAttribute.kt
purchases/src/main/kotlin/com/revenuecat/purchases/attributes/SubscriberAttributesManager.kt
purchases/src/main/kotlin/com/revenuecat/purchases/caching/DeviceCache.kt
purchases/src/main/kotlin/com/revenuecat/purchases/caching/InMemoryCachedObject.kt
purchases/src/main/kotlin/com/revenuecat/purchases/errors.kt
purchases/src/main/kotlin/com/revenuecat/purchases/utils/DateProvider.kt
purchases/src/test/java/com/revenuecat/purchases/BackendTest.kt
purchases/src/test/java/com/revenuecat/purchases/DeviceCacheTest.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
purchases/src/test/java/com/revenuecat/purchases/SyncDispatcher.kt
purchases/src/test/java/com/revenuecat/purchases/attributes/SpecialSubscriberAttributesTests.kt
purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributeTests.kt
purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesBackendTests.kt
purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesDeviceCacheTests.kt
purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesManagerTests.kt
purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt
purchases/src/test/java/com/revenuecat/purchases/caching/InMemoryCachedObjectTest.kt
purchases/src/test/java/com/revenuecat/purchases/responses.kt
purchases/src/test/resources/responses/attribute_errors_post_receipt_response.json

Integrates the following
https://github.com/RevenueCat/purchases-android/pull/116
https://github.com/RevenueCat/purchases-android/pull/117
https://github.com/RevenueCat/purchases-android/pull/118
https://github.com/RevenueCat/purchases-android/pull/119
https://github.com/RevenueCat/purchases-android/pull/122

[FINAL] Subscriber Attributes

---

.buildscripts/deploy_snapshot.sh
build.gradle
detekt.gradle
gradle.properties
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

Brings this fix https://github.com/RevenueCat/purchases-android/pull/97/ to 2.x.x

AppsFlyer fix for 2.4.2

---

CHANGELOG.md
gradle.properties
purchases/build.gradle
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt

- Fixes compatibility with AppsFlyer SDK https://github.com/RevenueCat/purchases-android/pull/127

Prepare for release 2.4.3

---

.buildscripts/jacoco.gradle
.circleci/config.yml
README.md
build.gradle
purchases/build.gradle

- Adds Jacoco as code coverage tool
- Adds Coveralls as reporting system
- Other smaller CircleCI tweaks

[FINAL] Add test coverage support

---

purchases-sample-java/src/main/java/com/revenuecat/purchases/purchases_sample_java/MainApplication.java
purchases-sample/src/main/java/com/revenuecat/sample/MainApplication.kt
purchases-sample/src/main/java/com/revenuecat/sample/UpsellActivity.kt

The annual and unlimited purchase button weren't being purchased correctly

Fixes purchase buttons in sample app

---

purchases/src/main/kotlin/com/revenuecat/purchases/PurchaserInfo.kt

I merged the other PR without updating the docs

Docs fixes for management url

---

gradle.properties
purchases/build.gradle
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt

bump version number to 3.3.0-SNAPSHOT

Prepare for next version: 3.3.0

---

purchases/src/main/kotlin/com/revenuecat/purchases/ProductInfo.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/test/java/com/revenuecat/purchases/BackendTest.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

This was tech debt from this comment https://github.com/RevenueCat/purchases-android/pull/148/files/045c3d37f42a8ae3e9d5ba48334645eddc394ca8#r436937299

Moves SkuDetails inside the ProductInfo to simplify the constructor

---

.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md

Bug Report template:
There are certain project specific issues that are commonly misinterpreted as bugs.
- [Offerings, products, or available packages are empty](https://support.revenuecat.com/hc/en-us/articles/360041793174)
- [Invalid Play Store credentials errors](https://support.revenuecat.com/hc/en-us/articles/360046398913)
- [Unable to connect to the App Store (STORE_PROBLEM) errors](https://support.revenuecat.com/hc/en-us/articles/360046399333)
For support I'd recommend our [online community](https://spectrum.chat/revenuecat), [StackOverflow](https://stackoverflow.com/tags/revenuecat/) and/or [Help Center](https://support.revenuecat.com/hc/en-us) 👍
If you have a clearly defined bug (with a [Minimal, Complete, and Reproducible …

Adds issue templates

---

CHANGELOG.md
fastlane/README.md
gradle.properties
purchases/build.gradle
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt

- New properties added to the PurchaserInfo to better manage non-subscriptions.
https://github.com/RevenueCat/purchases-android/pull/172

Version 3.4.0

---

purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt

Adds missing attribution v2 docs

Adds missing Attribution v2 docs

---

.circleci/config.yml

The deploy job was missing the import of the signing key

Adds signing key to deploy job

---

common/src/main/java/com/revenuecat/purchases/common/Config.kt
gradle.properties
library.gradle

Preparing for next version 3.6.0-SNAPSHOT

---

.circleci/config.yml

We are starting to have OOM errors, so we increased the size

Increases circleci instance to large

---

.circleci/config.yml
fastlane/Fastfile

https://github.com/RevenueCat/purchases-android/pull/205 didn't fix the deploys

Fixes deploys

---

CHANGELOG.md
RELEASING.md
common/src/main/java/com/revenuecat/purchases/common/Config.kt
gradle.properties
library.gradle

More aggressive caches and jittering for apps in background 
https://github.com/RevenueCat/purchases-android/pull/201

Version 3.5.3

---

strings/src/main/java/com/revenuecat/purchases/strings/Emojis.kt

Adds Emojis file for other PRs

adds emojis file

---

common/src/main/java/com/revenuecat/purchases/common/logWrapper.kt

Forgot to change the flag back to false before merging the first PR.

flips V2_LOGS_ENABLED to false

---

common/src/main/java/com/revenuecat/purchases/common/AppConfig.kt
common/src/main/java/com/revenuecat/purchases/common/BillingWrapper.kt
feature/subscriber-attributes/src/main/java/com/revenuecat/purchases/subscriberattributes/AttributionFetcher.kt
strings/src/main/java/com/revenuecat/purchases/strings/AttributionStrings.kt
strings/src/main/java/com/revenuecat/purchases/strings/ConfigureStrings.kt

Found some logging methods that did not get replaced by Logging v2.

replaces left over logging methods

---

common/src/main/java/com/revenuecat/purchases/common/Config.kt
gradle.properties
library.gradle

Preparing for next version

---

common/src/main/java/com/revenuecat/purchases/common/caching/DeviceCache.kt

We still haven't decided how to take care of the spikes, but I figured changing this to 25 asap would have some benefits

Changes cache refresh period to 25

---

public/src/main/java/com/revenuecat/purchases/errors.kt

This should be helpful to keep parity between the iOS and Android error codes

Added code to PurchasesErrorCode

---

.circleci/config.yml
.gitignore
CHANGELOG.latest.md
fastlane/Fastfile
fastlane/README.md

Moves the following to CI:
- Making a GitHub release
- Opening PR with SNAPSHOT version

Moves more steps of the release process to CI

---

common/src/test/java/com/revenuecat/purchases/common/DeviceCacheTest.kt

Adds missing test for https://github.com/RevenueCat/purchases-android/pull/280

Adds test for ClassCastException when calling getStringSet

---

CHANGELOG.latest.md
CHANGELOG.md

Updates changelog in develop to include hotfix 4.0.5

Updates changelog to 4.0.5

---

purchases-sample/proguard-rules.pro
purchases-sample/src/main/java/com/revenuecat/sample/LoginFragment.kt
purchases-sample/src/main/java/com/revenuecat/sample/MainApplication.kt
purchases-sample/src/main/java/com/revenuecat/sample/OfferingCardAdapter.kt
purchases-sample/src/main/java/com/revenuecat/sample/OfferingFragment.kt
purchases-sample/src/main/java/com/revenuecat/sample/OverviewFragment.kt
purchases-sample/src/main/java/com/revenuecat/sample/PackageCardAdapter.kt
purchases-sample/src/main/res/drawable/ic_copy.xml
purchases-sample/src/main/res/layout/fragment_login.xml
purchases-sample/src/main/res/layout/fragment_overview.xml
purchases-sample/src/main/res/layout/offering_card.xml
purchases-sample/src/main/res/layout/package_card.xml
purchases-sample/src/main/res/layout/row_view.xml
purchases-sample/src/main/res/navigation/nav_graph.xml
purchases-sample/src/main/res/values/dimens.xml

Adds login/reset functionality.
Also:
* cleans up PurchaserInfo card to display less
* adds button to manage subscriptions
* ability to copy user ID (for logging back in)
* add labels to current offering and active subscription cards
The test build is now active in the Play Store. Let me know if you want me to add you to the testers list.

Purchases Sample: Login

---

common/src/main/java/com/revenuecat/purchases/common/Factories.kt
common/src/test/java/com/revenuecat/purchases/common/DeviceCacheTest.kt
common/src/test/java/com/revenuecat/purchases/common/OfferingsTest.kt
examples/purchase-tester-java/src/main/java/com/revenuecat/purchasetester/java/UpsellActivity.java
feature/google/src/test/java/com/revenuecat/purchases/google/ParcelableTests.kt
public/src/main/java/com/revenuecat/purchases/Package.kt
public/src/main/java/com/revenuecat/purchases/parceler/SkuDetailsParceler.kt
purchases/src/main/java/com/revenuecat/purchases/interfaces/GetSkusResponseListener.java
purchases/src/main/java/com/revenuecat/purchases/interfaces/MakePurchaseListener.java
purchases/src/main/java/com/revenuecat/purchases/interfaces/ProductChangeListener.java
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/listenerConversions.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

Revert public changes introduced by #275 so we can release from develop without having to cherry pick commits.

Revert public changes introduced by #275

---

purchases/src/main/kotlin/com/revenuecat/purchases/listenerConversions.kt

Adds missing change from https://github.com/RevenueCat/purchases-android/pull/306

Hides purchasePackageWith

---

purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt

Add JvmOverloads to expose version of function without BillingFeature list to java users

add jvm overloads annotation

---

.circleci/config.yml
fastlane/Fastfile

* ignore latest tag for releases
* fix commitish branch to develop
* separate the upload and release tasks to avoid releasing before publish finishes

Fix fastlane

---

.circleci/config.yml
.github/ISSUE_TEMPLATE/bug_report.md
CONTRIBUTING.md
README.md
RELEASING.md
fastlane/Fastfile
purchases/build.gradle

Updates `develop` with `main` and removes some old references to `master`.

Changes develop with main

---

README.md

We are not calculating coverage anymore so I think we should remove it from the README.md

Removes coverage from README.md

---

.github/ISSUE_TEMPLATE/config.yml
CONTRIBUTING.md

Update community links

---

.circleci/config.yml

Counterpart of https://github.com/RevenueCat/purchases-ios/pull/841

Fix deployment of docs

---

.sdkmanrc

The previous version is not available in M1 computers

Update Java version

---

purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/deprecatedListenerConversions.kt
purchases/src/main/kotlin/com/revenuecat/purchases/listenerConversions.kt

Moves around deprecated functions and cleans up some annotations

Organize Amazon release deprecations

---

feature/amazon/src/main/AndroidManifest.xml

Hopefully the final PR around this...there was definitely a cleaner way to accomplish this, my bad...

add exported tag in main

---

common/src/main/java/com/revenuecat/purchases/common/HTTPClient.kt
strings/src/main/java/com/revenuecat/purchases/strings/NetworkStrings.kt

[sc-12011]
Prevents a user-reported crash when there is an exception setting up the network connection (see shortcut ticket for more details)

Catch IllegalArgumentException in getInputStream

---

common/src/main/java/com/revenuecat/purchases/common/EntitlementInfoFactories.kt
public/src/main/java/com/revenuecat/purchases/CustomerInfo.kt
public/src/main/java/com/revenuecat/purchases/EntitlementInfo.kt
public/src/main/java/com/revenuecat/purchases/models/RawDataContainer.kt
public/src/test/java/com/revenuecat/purchases/ParcelableTests.kt

[sc-11079]
Equivalent to https://github.com/RevenueCat/purchases-ios/pull/956.

Created `RawDataContainer`

---

common/src/main/java/com/revenuecat/purchases/common/errors.kt

Fixes [sc-10692].
iOS equivalent: https://github.com/RevenueCat/purchases-ios/pull/916

`BackendErrorCode`: changed to `private`

---

common/src/main/java/com/revenuecat/purchases/common/CustomerInfoFactories.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
strings/src/main/java/com/revenuecat/purchases/strings/OfferingStrings.kt

Purchases: added configuration errors for missing products

---

purchases/src/main/java/com/revenuecat/purchases/interfaces/GetSkusResponseListener.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/interfaces/GetStoreProductsCallback.kt
purchases/src/main/kotlin/com/revenuecat/purchases/listenerConversions.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
v5-MIGRATION.md

Simple rename from `getStoreProductCallback` to `getStoreProductsCallback`

Rename getStoreProductCallback to getStoreProductsCallback

---

api-tester/src/main/java/com/revenuecat/apitester/java/DeprecatedPurchasesAPI.java
api-tester/src/main/java/com/revenuecat/apitester/java/PackageAPI.java
api-tester/src/main/java/com/revenuecat/apitester/java/PaymentTransactionAPI.java
api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
api-tester/src/main/java/com/revenuecat/apitester/kotlin/DeprecatedPurchasesAPI.kt
api-tester/src/main/java/com/revenuecat/apitester/kotlin/PackageAPI.kt
api-tester/src/main/java/com/revenuecat/apitester/kotlin/PaymentTransactionAPI.kt
api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt

Fixes API tester in amazon-release branch

Fix api tester for Amazon branch

---

purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesConfiguration.kt

There were some internal kotlin properties that needed to be hidden from Java code

Adds missing JvmSynthetic

---

examples/purchase-tester-java/src/main/java/com/revenuecat/purchasetester/java/CatsActivity.java
examples/purchase-tester-java/src/main/java/com/revenuecat/purchasetester/java/MainApplication.java
examples/purchase-tester-java/src/main/java/com/revenuecat/purchasetester/java/UpsellActivity.java
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/MainApplication.kt

- [n/a ] If applicable, unit tests
- [n/a ] If applicable, create follow-up issues for `purchases-ios` and hybrids
Updates our internal testing apps to use the latest configuration method, and to use lambdas now that our library is on Java 8.

Update purchase testers

---

AMAZON-INSTRUCTIONS.md

Forgot to update the version number in the instructions

Update version in AMAZON-INSTRUCTIONS.md 

---

examples/MagicWeather/app/build.gradle
examples/MagicWeather/build.gradle

Pulling purchases version into a variable now that we re-use it for two dependencies

MagicWeather purchases_version variable

---

examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/PackageCardAdapter.kt
examples/purchase-tester/src/main/res/layout/package_card.xml

Depends on: https://github.com/RevenueCat/purchases-android/pull/481
[sc-12864]

Add product JSON to package card in purchasetester

---

common/src/main/java/com/revenuecat/purchases/common/Backend.kt
common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt

Android equivalent to https://github.com/RevenueCat/purchases-ios/pull/1249 and https://github.com/RevenueCat/purchases-ios/pull/1292.
Finishes [sc-12802].
Before this change, the sequence illustrated by the new test `"gets updated customer after posting receipt data"` would fail:
- GET /subscribers/
- POST /receipts
- GET /subscribers/
When the first GET request finishes, the second one shares the cache key, so it receives the (soon to be) outdated `CustomerInfo`.
Unfortunately this fix is isolated for this specific issue, and not a generalized one.
I came up with several other alternatives, but what I ended up going with here involves the least amount of moving pieces.
If a `getCustomerInfo` request is enqueued with `postReceiptData` in the queue, then a new unique cache key is created …

`Backend#getCustomerInfo`: improve logic for caching responses

---

examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/MainApplication.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OfferingFragment.kt

Add UpdatedCustomerInfoListener to purchase tester and display a toast and log whenever it receives an update
[sc-12866]

Add UpdatedCustomerInfoListener to purchase-tester

---

build.gradle

Simple update to BillingClient 4.1 (https://developer.android.com/google/play/billing/release-notes#4-1)
Ran some tests via purchase tester, and everything looked normal. Opened a ticket to implement the new method showInAppMessages() separately

Update to billing client 4.1

---

library.gradle

From https://github.com/RevenueCat/purchases-android/pull/444/files#r807266435 comment

Remove unwanted println printing artifact id

---

feature/amazon/src/main/java/com/revenuecat/purchases/amazon/AmazonStrings.kt

Just adds a better error message for folks that forget to enable sandbox mode

Better error message when trying to load Amazon user data fails

---

.circleci/config.yml
CHANGELOG.latest.md
CHANGELOG.md
common/src/main/java/com/revenuecat/purchases/common/Config.kt
docs/index.html
gradle.properties
library.gradle

* Upgrade compile sdk and target sdk versions and Android Gradle Plugin, Kotlin and a few other versions
* https://github.com/RevenueCat/purchases-android/pull/474

Release 5.4.0

---

RELEASING.md

Resolves https://revenuecats.atlassian.net/browse/CSDK-440
The documentation wasn't updated after recent changes to the release process.

Update releasing documentation

---

common/src/main/java/com/revenuecat/purchases/common/AppConfig.kt
common/src/main/java/com/revenuecat/purchases/common/HTTPClient.kt
common/src/test/java/com/revenuecat/purchases/common/AppConfigTest.kt
common/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
strings/src/main/java/com/revenuecat/purchases/strings/ConfigureStrings.kt

https://revenuecats.atlassian.net/browse/CSDK-462
This PR adds a new header to all requests with the package name of the app running the SDK.

Add package name to all requests headers

---

common/src/main/java/com/revenuecat/purchases/common/BillingAbstract.kt
feature/amazon/src/main/java/com/revenuecat/purchases/amazon/AmazonBilling.kt
feature/google/src/bc5SupportDev/java/com/revenuecat/purchases/google/BillingWrapper.kt
feature/google/src/unityIAP/java/com/revenuecat/purchases/google/BillingWrapper.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt

[DRAFT] Bc5 code split 

---

examples/purchase-tester/src/main/AndroidManifest.xml

https://revenuecats.atlassian.net/browse/CSDK-482
This PR enables HTTP traffic for the purchase tester app. This will be used to test the app with local environments.

Enable HTTP traffic in purchase tester

---

feature/google/src/test/java/com/revenuecat/purchases/google/StoreProductTest.kt
purchases/src/main/java/com/revenuecat/purchases/interfaces/GetSkusResponseListener.kt
purchases/src/main/kotlin/com/revenuecat/purchases/interfaces/GetStoreProductsCallback.kt

Minor fixes on comments from a prev. PR.
Fix incorrect package name
Use JvmSuppressWildcards

Fix comments from PR

---

api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
common/src/main/java/com/revenuecat/purchases/common/BillingAbstract.kt
feature/amazon/src/main/java/com/revenuecat/purchases/amazon/AmazonBilling.kt
feature/google/src/latestDependencies/java/com/revenuecat/purchases/google/BillingWrapper.kt
feature/google/src/unityIAP/java/com/revenuecat/purchases/google/BillingWrapper.kt
public/src/latestDependencies/java/com/revenuecat/purchases/models/GoogleStoreProduct.kt
public/src/main/java/com/revenuecat/purchases/models/StoreProduct.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/StoreProductExtensions.kt

https://revenuecats.atlassian.net/browse/CF-874
This PR works on implementing the new BC5 purchase flow using the new models added in #658. This is pointing to `bc5-support` as a WIP branch.

BC5 purchase flow new API

---

common/src/test/java/com/revenuecat/purchases/common/OfferingsTest.kt
test-utils/src/main/java/com/revenuecat/purchases/utils/productStubs.kt

[BC5] Fix OfferingsTests

---

api-tester/src/main/java/com/revenuecat/apitester/java/StoreProductAPI.java
api-tester/src/main/java/com/revenuecat/apitester/kotlin/StoreProductAPI.kt
common/src/test/java/com/revenuecat/purchases/common/DeviceCacheTest.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/PackageCardAdapter.kt
examples/purchase-tester/src/main/res/layout/package_card.xml
feature/amazon/src/main/java/com/revenuecat/purchases/amazon/AmazonBilling.kt
feature/amazon/src/main/java/com/revenuecat/purchases/amazon/handler/PurchaseHandler.kt
feature/amazon/src/main/java/com/revenuecat/purchases/amazon/storeProductConversions.kt
feature/amazon/src/test/java/com/revenuecat/purchases/amazon/ProductConverterTest.kt
feature/amazon/src/test/java/com/revenuecat/purchases/amazon/handler/ProductDataHandlerTest.kt
feature/google/src/main/java/com/revenuecat/purchases/google/BillingWrapper.kt
feature/google/src/main/java/com/revenuecat/purchases/google/storeTransactionConversions.kt
feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
public/src/main/java/com/revenuecat/purchases/models/GoogleStoreProduct.kt
public/src/main/java/com/revenuecat/purchases/models/StoreProduct.kt
public/src/main/java/com/revenuecat/purchases/models/StoreTransaction.kt
purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
test-utils/src/main/java/com/revenuecat/purchases/utils/productStubs.kt

* deprecates StoreProduct.sku
* adds StoreProduct.productId
* updates api testers
* adds api tester for GoogleStoreProduct

Replace StoreProduct.sku with productId

---

migrations/v6-MIGRATION.md

Ideally we update this doc in every PR

[BC5] Creates v6-MIGRATION.md 

---

common/src/main/java/com/revenuecat/purchases/common/Config.kt

Bump version

---

api-tester/src/main/java/com/revenuecat/apitester/java/StoreTransactionAPI.java
api-tester/src/main/java/com/revenuecat/apitester/kotlin/StoreTransactionAPI.kt

I forgot to update the StoreTransaction api testers with `purchaseOptionId`

Fix API Testers

---

migrations/v6-MIGRATION.md

Small updates on the v6-MIGRATION doc

[BC5] Update v6-MIGRATION.md

---

purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

PurchasesTest is a massive file, so I split it into regions to provide some organization. In the future perhaps we can split these into separate files
This also updates a few test names for clarity. There are no functionality updates here

Clean up PurchasesTest

---

common/src/main/java/com/revenuecat/purchases/common/ReceiptInfo.kt
feature/amazon/src/test/java/com/revenuecat/purchases/amazon/AmazonBillingTest.kt
feature/amazon/src/test/java/com/revenuecat/purchases/amazon/ProductConverterTest.kt
feature/amazon/src/test/java/com/revenuecat/purchases/amazon/handler/ProductDataHandlerTest.kt
feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
feature/google/src/test/java/com/revenuecat/purchases/google/ParcelableTests.kt
feature/google/src/test/java/com/revenuecat/purchases/google/StoreProductTest.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

- I commented out all Amazon tests that were failing
- Fixed PurchasesTest and BillingWrapperTest

Fix PurchasesTest, BillingWrapperTest and comments out Amazon tests

---

public/src/main/java/com/revenuecat/purchases/models/StoreTransaction.kt

Add comment making it clear we don't support multiline

Add clarifying comment for multiline

---

api-tester/src/main/java/com/revenuecat/apitester/java/CustomerInfoAPI.java
api-tester/src/main/java/com/revenuecat/apitester/kotlin/CustomerInfoAPI.kt
common/src/test/java/com/revenuecat/purchases/common/CustomerInfoTest.kt
migrations/v6-MIGRATION.md
public/src/main/java/com/revenuecat/purchases/CustomerInfo.kt

still need to update the migration guide

Deprecate CustomerInfo sku references, update to product Id

---

.circleci/config.yml
.version
CHANGELOG.latest.md
CHANGELOG.md
common/src/main/java/com/revenuecat/purchases/common/Config.kt
docs/index.html
gradle.properties
library.gradle

Alpha!!
Preparing alpha release

Release 6.0.0 alpha.1

---

.circleci/config.yml

Configured codecov to report on differences on code coverage

Add codecov

---

examples/MagicWeather/README.md

Sample Project Location from Configuring the *Purchases* SDK was wrong

Fixed Readme.MD

---

api-tester/src/main/java/com/revenuecat/apitester/java/PackageAPI.java
api-tester/src/main/java/com/revenuecat/apitester/java/StoreProductAPI.java
api-tester/src/main/java/com/revenuecat/apitester/kotlin/PackageAPI.kt
api-tester/src/main/java/com/revenuecat/apitester/kotlin/StoreProductAPI.kt
common/src/main/java/com/revenuecat/purchases/common/ReceiptInfo.kt
common/src/test/java/com/revenuecat/purchases/common/OfferingsTest.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OfferingFragment.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/PackageCardAdapter.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/SubscriptionOptionExtensions.kt
examples/purchase-tester/src/main/res/layout/package_card.xml
feature/amazon/src/main/java/com/revenuecat/purchases/amazon/storeProductConversions.kt
feature/google/src/main/java/com/revenuecat/purchases/google/billingClientParamBuilders.kt
feature/google/src/main/java/com/revenuecat/purchases/google/subscriptionOptionConversions.kt
feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
feature/google/src/test/java/com/revenuecat/purchases/google/ParcelableTests.kt
public/src/main/java/com/revenuecat/purchases/CustomerInfo.kt
public/src/main/java/com/revenuecat/purchases/EntitlementInfo.kt
public/src/main/java/com/revenuecat/purchases/Package.kt
public/src/main/java/com/revenuecat/purchases/models/GoogleStoreProduct.kt
public/src/main/java/com/revenuecat/purchases/models/PricingPhase.kt
public/src/main/java/com/revenuecat/purchases/models/RecurrenceMode.kt
public/src/main/java/com/revenuecat/purchases/models/StoreProduct.kt
public/src/main/java/com/revenuecat/purchases/models/StoreTransaction.kt
public/src/test/java/com/revenuecat/purchases/ParcelableTests.kt
purchases/src/main/kotlin/com/revenuecat/purchases/listenerConversions.kt
utils/src/main/java/com/revenuecat/purchases/utils/JSONObjectParceler.kt

Was going through the TODOs in the codebase, fixing the quick ones and making sure we have tickets for the rest.

Clean up Google-related TODOs

---

purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt

Updating comment for syncPurchases as there was some confusion with previous version stating that it could be called after each purchase. 
- [ x ] If applicable, create follow-up issues for `purchases-ios` and hybrids
Confusion with usage of syncPurchases, such as [here](https://community.revenuecat.com/sdks-51/when-should-i-call-syncpurchases-2502?postid=7942#post7942)
Updated comment

Updating comment for syncPurchases

---

examples/purchase-tester/src/main/AndroidManifest.xml

This was needed to make the purchases_sample work with the AmazonAppTester on my Fire device

Add queries

---

common/src/main/java/com/revenuecat/purchases/common/AppConfig.kt
common/src/main/java/com/revenuecat/purchases/common/Backend.kt
common/src/main/java/com/revenuecat/purchases/common/HTTPClient.kt
common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
common/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
feature/amazon/src/test/java/com/revenuecat/purchases/amazon/AmazonBackendTest.kt
feature/subscriber-attributes/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesBackendTests.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt

Based on #785 
This PR adds the logic to send diagnostics data to our backend.

Diagnostics: Backend support

---

migrations/v6-MIGRATION.md
public/src/main/java/com/revenuecat/purchases/models/StoreProduct.kt

I forgot to add some things after all of my API improvement PRs to the V6 migration guide
N/A

[BC5] Migration guide updates for API improvements

---

.circleci/config.yml

This PR fixes the issues with SDKMAN outages on CI systems.

Fix SDKMAN issues

---

common/src/main/java/com/revenuecat/purchases/common/networking/Endpoint.kt
common/src/test/java/com/revenuecat/purchases/common/networking/EndpointTest.kt

We broke posting receipts to the backend in #803 
This fixes it so we post to the correct URL

Fix issue posting receipts to backend

---

api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
migrations/v6-MIGRATION.md
purchases/src/main/kotlin/com/revenuecat/purchases/PurchaseParams.kt

hiding this from purchaseparams for now, since we don't actually set it on the purchase yet and we want to get a beta out

Hide isPersonalizedPrice

---

public/src/main/java/com/revenuecat/purchases/VerificationResult.kt

Android equivalent of https://github.com/RevenueCat/purchases-ios/pull/2337
Update documentation to new behavior of `VerificationResult.NOT_REQUESTED`.

Update VerificationResult NOT_REQUESTED docs to new behavior

---

purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesConfiguration.kt

Improves the documentation for the Entitlement verification feature. Adding a note about the behavior when enabling entitlement verification.

Improve entitlement verification documentation

---

examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OverviewViewModel.kt
examples/purchase-tester/src/main/res/layout/fragment_overview.xml

This PR adds the verification result to purchase tester's overview page so it's easier to visualize. This will be specially useful during the bug bash

Add verification result to purchase tester overview page

---

common/src/main/java/com/revenuecat/purchases/common/Backend.kt
common/src/main/java/com/revenuecat/purchases/common/caching/DeviceCache.kt
common/src/main/java/com/revenuecat/purchases/common/networking/Endpoint.kt
common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/OfflineEntitlementsManager.kt
common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/ProductEntitlementMapping.kt
common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
common/src/test/java/com/revenuecat/purchases/common/DeviceCacheTest.kt
common/src/test/java/com/revenuecat/purchases/common/networking/EndpointTest.kt
common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/OfflineEntitlementsManagerTest.kt
common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/ProductEntitlementMappingTest.kt
common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/productEntitlementMappingFactory.kt
strings/src/main/java/com/revenuecat/purchases/strings/OfflineEntitlementsStrings.kt

This renames `ProductEntitlementMappings` to `ProductEntitlementMapping`

Offline entitlements: Rename `ProductEntitlementMappings` -> `ProductEntitlementMapping`

---

migrations/v6-MIGRATION.md

Making sure this `v6-MIGRATION.md` is as good as it can be for release 💪 
- Some reorganization
- More descriptions
- Small fixes

[BC5] Small improvements to v6-MIGRATION.md

---

.circleci/config.yml
fastlane/Fastfile
fastlane/README.md
purchases/.gitignore
purchases/build.gradle
purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/Constants.kt
purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/PurchasesIntegrationTest.kt
purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/factories/StoreProductFactory.kt
purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/factories/StoreTransactionFactory.kt
purchases/src/integrationTest/AndroidManifest.xml

Followup to #899 
This PR automates running integration test in CircleCI and Firebase test labs. They will run on release branches currently, same as our existing integration tests.

Automate purchases module integration tests

---

integration-tests/build.gradle
integration-tests/src/main/AndroidManifest.xml

I started getting single dex file errors on integration-tests when working on #885 
This PR adds multidex to integration-tests

Adds multidex to integration tests

---

gradle.properties

I was getting OOM errors, I increased the Gradle and Kotlin's daemon max heap size and I stopped getting the errors.

Increase heap size

---

common/src/main/java/com/revenuecat/purchases/common/Constants.kt
common/src/main/java/com/revenuecat/purchases/common/CustomerInfoFactory.kt
common/src/main/java/com/revenuecat/purchases/common/EntitlementInfoFactories.kt
common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/OfflineCustomerInfoCalculator.kt
common/src/main/java/com/revenuecat/purchases/common/responses/CustomerInfoResponseJsonKeys.kt

Followup on #885 extracting all JSON keys into their own file so they can be reused

Extract all customer info json strings

---

.circleci/config.yml
fastlane/Fastfile
fastlane/README.md
purchases/.gitignore
purchases/build.gradle

This PR adds some automation so we run the load shedder integration tests for the V4 version daily from CircleCI scheduled jobs.

Automate load shedder integration tests for V4

---

.circleci/config.yml
fastlane/Fastfile
fastlane/README.md

This will report the results of load shedder integration tests V4 in Slack.

Report load shedder integration tests results in slack for V4

---

.circleci/config.yml

Inspired by https://github.com/RevenueCat/purchases-android/pull/942#issuecomment-1505244860

Extract detekt job from test job

---

.circleci/config.yml
fastlane/Fastfile
purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/Constants.kt
purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/PurchasesIntegrationTest.kt

This PR adds some extra checks to the integration tests in V4 to verify that entitlements are being granted as expected.

Add entitlement verification checks to load shedder integration tests v4

---

common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/OfflineCustomerInfoCalculatorTest.kt

Merging #994 into `main` and running all tests

Fix `OfflineCustomerInfoCalculatorTest` `Unresolved reference: ProducType`

---

common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/OfflineCustomerInfoCalculatorTest.kt

Brought up in https://github.com/RevenueCat/purchases-android/pull/994#issuecomment-1535415272
There were two issues, one that requestDate was being mocked to the wrong value (a date in the past instead of now), and also that we were checking if an entitlement should be active, when it shouldn't be

Fix flaky test in OfflineCustomerInfoCalculatorTest

---

.circleci/config.yml
integration-tests/build.gradle
integration-tests/src/androidTest/java/com/revenuecat/purchases/integrationtests/IntegrationTest.kt
purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/factories/StoreTransactionFactory.kt

Fix `PurchasesIntegrationTest` building issue (#996 into main)

---

api-tester/src/main/java/com/revenuecat/apitester/java/OfferingAPI.java
api-tester/src/main/java/com/revenuecat/apitester/kotlin/OfferingAPI.kt
common/src/main/java/com/revenuecat/purchases/common/OfferingParser.kt
common/src/test/java/com/revenuecat/purchases/common/DeviceCacheTest.kt
public/src/main/java/com/revenuecat/purchases/Offering.kt
purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/PurchasesIntegrationTest.kt
purchases/src/test/java/com/revenuecat/purchases/OfferingsTest.kt
test-utils/src/main/java/com/revenuecat/purchases/utils/productStubs.kt
utils/build.gradle
utils/src/main/java/com/revenuecat/purchases/utils/JSONArrayExtensions.kt
utils/src/main/java/com/revenuecat/purchases/utils/JSONObjectExtensions.kt
utils/src/test/java/com/revenuecat/purchases/utils/JSONArrayExtensionsTest.kt
utils/src/test/java/com/revenuecat/purchases/utils/JSONObjectExtensionsTest.kt

Added `metadata` to `Offering` 😊 
- Added `metadata` to `Offering`
- Updated `JSONObject.toMap()` to have a new `deep: Boolean` parameter to fully expand out all `JSONObject`s and `JSONArray`s
- Added a new `JSONArray.toList()` method
- Updated unit tests
- Updated backend integration tests
- Updated load shedder tests

`Offering` metadata

---

common/src/main/java/com/revenuecat/purchases/common/AppConfig.kt
common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/OfflineEntitlementsManager.kt
common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/OfflineEntitlementsManagerTest.kt
strings/src/main/java/com/revenuecat/purchases/strings/OfflineEntitlementsStrings.kt

We want to do some more testing on the offline entitlements feature. To not block other releases, this PR temporarily disables the feature entirely.

Disable offline entitlements temporarily

---

.circleci/config.yml
common/src/main/java/com/revenuecat/purchases/common/AppConfig.kt
purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/offlineentitlements/OfflineEntitlementsWithInitialRequestsCompletedIntegrationTest.kt

This PR reenables offline entitlements and brings back the related integration tests.

Reenable offline entitlements

---

feature/google/src/main/java/com/revenuecat/purchases/google/BillingWrapper.kt
feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt

With the addition of offline entitlements, we query active purchases early in the process lifetime. This sometimes resulted in the billing client connection not being established at that point in time and not calculating offline entitlements (returning an error).
This PR fixes those errors by making the queryPurchases method execute AFTER the billing client connection has been established. We already do this in all other methods that interact with the billing client except this one, so it seemed like a bug.

Fix billing connection error when querying purchases early in the process lifetime

---

common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/OfflineEntitlementsManager.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PostReceiptHelper.kt
strings/src/main/java/com/revenuecat/purchases/strings/OfflineEntitlementsStrings.kt

From our bug bash, we found that there are some situations that may be confusing to our users. This tries to improve the logs so some of the limitations of offline entitlements are clearer.

Improve offline entitlements logs to mention limitations of this mode

---

build.gradle
examples/MagicWeather/build.gradle
examples/purchase-tester/src/main/AndroidManifest.xml
feature/google/src/main/java/com/revenuecat/purchases/google/attribution/GoogleDeviceIdentifiersFetcher.kt
feature/google/src/test/java/com/revenuecat/purchases/google/attribution/GoogleDeviceIdentifiersFetcherTests.kt
strings/src/main/java/com/revenuecat/purchases/strings/AttributionStrings.kt

SDK-3017
This PR:
- Updates target SDK version to 33
- Updates build tools version to 33.0.2
- Updates robolectric to latest version 4.10.3
- Handles new requirements around advertising id for apps targeting version 33. https://developer.android.com/about/versions/13/behavior-changes-13
Documentation for API changes:
- https://developer.android.com/google/play/requirements/target-sdk#pre12
- https://developer.android.com/about/versions/13/behavior-changes-13

Update targetSDK version to 33

---

.circleci/config.yml

This will update our CI to use the latest android executor image.

Update to latest android executor image

---

purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
strings/src/main/java/com/revenuecat/purchases/strings/ConfigureStrings.kt

Added logs with selected verification mode during sdk initialization.

Trusted entitlements: Add logs with verification mode

---

.circleci/config.yml
fastlane/Fastfile

This adds a simple compilation job to CircleCI to make sure MagicWeatherCompose builds fine on each commit. We can iterate on this and add some UI tests or something like that to make sure it also loads data correctly

Compose sample app: automate builds

---

purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/PurchasesIntegrationTest.kt
purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/helpers/BillingAbstractMockHelper.kt
purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/offlineentitlements/OfflineEntitlementsFreshInstallIntegrationTest.kt
purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/offlineentitlements/OfflineEntitlementsWithInitialRequestsCompletedIntegrationTest.kt

#1073 broke some more integration tests. I fixed one in #1080, but didn't run the offline entitlements integration tests 🤦‍♂️ .
Most of these make sense after that functionality was added

Fix offline entitlements integration tests

---

gradle/libs.versions.toml

This updates the billing library to 5.2.1. This includes a fix to support android 14 devices in apps targeting android 14.

Update billing library to 5.2.1

---

api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
purchases/src/main/kotlin/com/revenuecat/purchases/coroutinesExtensions.kt
purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesCoroutinesTest.kt
purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt

Added experimental `awaitOfferings` to the API

Add await offerings

---

common/src/main/java/com/revenuecat/purchases/common/HTTPClient.kt
common/src/main/java/com/revenuecat/purchases/common/verification/SigningManager.kt
common/src/test/java/com/revenuecat/purchases/backend_integration_tests/BaseBackendIntegrationTest.kt
common/src/test/java/com/revenuecat/purchases/common/HTTPClientVerificationTest.kt
common/src/test/java/com/revenuecat/purchases/common/verification/SigningManagerTest.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt

This will support the newer form of signature that includes the API key and url

Trusted entitlements: Support API key and url in signature

---

fastlane/Fastfile

We forgot to update the paths to update versions in #1106. This fixes it so we can make a new release

Fix release path after module refactor

---

examples/MagicWeather/gradle/libs.versions.toml

I was testing MagicWeather using Kotlin 1.9.0 and took the chance to update the versions of all dependencies. Didn't run into any issues, neither building nor purchasing nor some of the most common use cases.

Update MagicWeather dependencies to latest versions

---

codecov.yml

Equivalent of https://github.com/RevenueCat/purchases-ios/pull/2828 and https://github.com/RevenueCat/purchases-ios/pull/2670

CI: make all Codecov jobs informational

---

purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesTest.kt

Fix tests after merges of #1142 and #1156 caused issue in main

Fix tests in customEntitlementComputation after merges

---

examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/main/MainViewModel.kt

Follow up on #1160 using `awaitPurchase`

Use purchase coroutine in CustomEntitlementComputationSample

---

fastlane/Fastfile

Adds a step to the deploy lane to deploy the new artifact

Add publish system for customEntitlementComputation package

---

.circleci/config.yml
fastlane/Fastfile
fastlane/README.md
purchases/src/androidTest/kotlin/com/revenuecat/purchases/BasePurchasesIntegrationTest.kt
purchases/src/androidTestCustomEntitlementComputation/kotlin/com/revenuecat/purchases/PurchasesIntegrationTest.kt
purchases/src/androidTestCustomEntitlementComputation/kotlin/com/revenuecat/purchases/PurchasesTestConfigurationExtensions.kt
purchases/src/androidTestDefaults/kotlin/com/revenuecat/purchases/PurchasesTestConfigurationExtensions.kt

This PR adds integration tests for the custom entitlement computation feature

CustomEntitlementComputation: Integration tests

---

build.gradle
examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/MainApplication.kt
examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/data/CustomerInfoEvent.kt
examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/main/CustomerInfoDetailScreen.kt
examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/main/CustomerInfoEventList.kt
examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/main/ExplanationScreen.kt
examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/main/MainScreen.kt
examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/main/MainState.kt
examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/main/MainViewModel.kt

We want to run the linter in the `CustomEntitlementComputation` sample app. This PR makes sure of that.

Run linter in CustomEntitlementComputation sample app

---

examples/CustomEntitlementComputationSample/gradle/libs.versions.toml
examples/MagicWeather/gradle/libs.versions.toml
examples/MagicWeatherCompose/gradle/libs.versions.toml
gradle/libs.versions.toml

Update Android gradle plugin to 8.1.0
Release notes: https://developer.android.com/build/releases/gradle-plugin#8-1-0

Update AGP to 8.1.0

---

CONTRIBUTING.md
fastlane/Fastfile
fastlane/README.md
scripts/pre-commit.sh

Added a `setup_dev` lane to fastlane that setups the pre-commit hook that will run detekt before commiting.

Add setup_dev

---

fastlane/Fastfile

This broke in #1192. We were missing some fixes for the refactor to deploy the debug view

Fix deploying extra packages

---

.circleci/config.yml
examples/paywall-tester/build.gradle
fastlane/Fastfile
gradle.properties

Submits paywall tester to Google Play nightly

Nightly deploy of paywall tester

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/Logger.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallDataExtensions.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallViewModel.kt

Added `Logger` class with some static methods to be able to unify the behavior for logs in the RevenueCatUI sdk.

Paywalls: Add logger class to unify logging behavior

---

purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/PaywallData.kt
purchases/src/test/java/com/revenuecat/purchases/paywalls/PaywallDataTest.kt
purchases/src/test/resources/paywalldata-sample1.json

We were missing tests for PaywallData deserialization

Add PaywallDataTest

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/TestData.kt
ui/revenuecatui/src/test/java/com/revenuecat/purchases/ui/revenuecatui/data/processed/TemplateConfigurationFactoryTest.kt

This adds some basic tests to the previous logic added in #1242, so we make sure the mapping make sense.

Paywalls: Add template configuration factory tests

---

purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/PaywallData.kt
purchases/src/test/java/com/revenuecat/purchases/paywalls/PaywallDataTest.kt
purchases/src/test/resources/paywalldata-missing_current_locale.json

I forgot to add this property that's available in iOS. I noticed when using iOS tests as a base

Adds localizedConfiguration

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/Footer.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModel.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/TestData.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template2.kt
ui/revenuecatui/src/main/res/values/strings.xml

Created `Footer`

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/UIConstant.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/RemoteImage.kt

This makes async loading a bit smoother and consistent with iOS.

`Paywalls`: added transition when loading images

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/TestData.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/TemplateConfigurationFactory.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template2.kt
ui/revenuecatui/src/main/res/values-es/strings.xml

This PR adds the spanish version of the existing hardcoded strings and adds a preview for spanish locale

Paywalls: Adds some initial spanish strings and some initial preview

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableDataProvider.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableProcessor.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/PeriodExtensions.kt
ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableProcessorTest.kt

Adds support for the `sub_duration` variable in paywalls.

Paywalls: Add support for SUB_DURATION variable in paywalls

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableProcessor.kt

Extracted variable names to an enum

Created enum with variable names

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/TestData.kt
ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableProcessorTest.kt

Added some more tests to cover different time periods in variable processor.

Paywalls: Add tests for additional periods in variable processor

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/TestData.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableDataProvider.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableProcessor.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/PackageExtensions.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/PeriodExtensions.kt
ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/TemplateConfigurationFactoryTest.kt
ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableProcessorTest.kt

This adds support for the `total_price_and_per_month` variable in paywalls

Paywalls: Add support for `total_price_and_per_month` variable in paywalls

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableProcessor.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/OfferingToStateMapper.kt

Validate icons

---

README.md
build.gradle
integration-tests/build.gradle

To be merged alongside https://github.com/RevenueCat/purchases-android/pull/1209

Bump minimum sdk version to Android 4.4 (API level 19)

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/InternalPaywallView.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallViewMode.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/IconImage.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/PurchaseButton.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/TestData.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template2.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template3.kt

Preview with a lot of features
Preview with three features
Screenshot from emulator

Template 3

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/IntroEligibilityStateView.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/PackageExtensions.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template2.kt

This PR improves the select button to make it more similar to iOS and include the same information

Paywalls: Template2 improve select button

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallDialog.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallDialogOptions.kt

Reverse logic discovered during testing.

`Paywalls`: fixed `PaywallDialog.setRequiredEntitlementIdentifier`

---

purchases/src/test/java/com/revenuecat/purchases/paywalls/PaywallDataTest.kt
purchases/src/test/resources/paywalldata-sample1.json
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableDataProvider.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableProcessor.kt
ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableProcessorTest.kt

Add support for `{{ sub_offer_price_2 }}` and `{{ sub_offer_duration_2 }}`

Parse `{{ sub_offer_price_2 }}` and `{{ sub_offer_duration_2 }}` variables

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/UIConstant.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/ConsistentPackageContentView.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/IntroEligibilityStateView.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/PurchaseButton.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModel.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewState.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template1.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template2.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template3.kt

https://github.com/RevenueCat/purchases-android/assets/685609/f7d337bb-613f-47c1-8429-13a270171236

`Paywalls`: animate package selection transitions

---

examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/SamplePaywalls.kt
examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/main/MainScreen.kt

`Paywalls`: display default template in paywalls tester

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/PaywallBackground.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/PaywallDataExtensions.kt
ui/revenuecatui/src/test/resources/default_template.json

- Added background image
- Improved colors

`Paywalls`: improved default paywall

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/Markdown.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/testdata/templates/Template3TestData.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template3.kt

`Paywalls`: polish template 3

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template1.kt

`Paywalls`: polish template 1

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/AdaptiveComposable.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/Footer.kt
ui/revenuecatui/src/main/res/values-es/strings.xml
ui/revenuecatui/src/main/res/values/strings.xml

`Paywalls`: `ViewThatFits` equivalent to improve `Footer`

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModel.kt

We were not calling the restore callbacks. This fixes that.

Paywalls: Add restore paywall callbacks

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/LoadingPaywallView.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModel.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/testdata/TestData.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/OfferingToStateMapper.kt
ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/TemplateConfigurationFactoryTest.kt

In the future we'll need to also update the UI for this (https://linear.app/revenuecat/issue/PWL-243/sdk-update-templates-to-reflect-currently-subscribed-products)

`Paywalls`: disallow purchasing currently subscribed products

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/LoadingPaywallView.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/UIConstant.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/PurchaseButton.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModel.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/testdata/TestData.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/Animations.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template2.kt

https://github.com/RevenueCat/purchases-android/assets/685609/1c13a65e-a630-477c-b82e-b00a98b9fdc6

`Paywalls`: handle "action in progress" state

---

gradle/libs.versions.toml
purchases/src/main/kotlin/com/revenuecat/purchases/PurchaseParams.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModel.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModelFactory.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PurchasesType.kt
ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModelTest.kt

There's more things we could test, but this is a start.

`Paywalls`: `PaywallViewModel` tests

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/PackageConfigurationFactory.kt
ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/TemplateConfigurationFactoryTest.kt

Depends on #1369.
This is needed for template 4 (#1349).

`Paywalls`: calculate `discountRelativeToMostExpensivePerMonth`

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/UIConstant.kt

`Paywalls`: improve `FooterDialog` corner radius

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/PurchaseButton.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/ColorsFactory.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/TemplateConfiguration.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/testdata/templates/Template2TestData.kt

See also https://github.com/RevenueCat/purchases-ios/pull/3121

`Paywalls`: `PurchaseButton` supports gradients

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template2.kt

`Paywalls`: polish template 2 spacing

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template2.kt

`Paywalls`: improve template 2 layout

---

.circleci/config.yml

Allow triggering paywall tester upload to play console manually.

Paywalls: Allow trigger manual paywall tester release

---

ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/TemplateConfigurationFactoryTest.kt
ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableProcessorTest.kt
ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/PackageInfoForTest.kt

Followup from #1349 adding a test for packageInfo.localizedDiscount

Add test for packageInfo.localizedDiscount

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/PurchaseButton.kt

Fix button padding in Loading paywall

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/InternalPaywall.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModel.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template2.kt

Adds a fade in/out transition between Loading and Loaded paywalls

Animate transition between loading and loaded paywall

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableDataProvider.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template4.kt

The main improvement is that the package buttons are now a single accessibility element, including the discount percentage.

`Paywalls`: improve template 4 A11y support

---

purchases/src/main/kotlin/com/revenuecat/purchases/common/OfferingParser.kt
purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/PaywallData.kt
purchases/src/test/java/com/revenuecat/purchases/common/offerings/OfferingsFactoryTest.kt
purchases/src/test/java/com/revenuecat/purchases/paywalls/PaywallDataTest.kt
purchases/src/test/resources/paywalldata-sample1.json
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/ColorsFactory.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/TemplateConfiguration.kt
ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallDataValidationTest.kt

These are needed for template 4 and 5.

`Paywalls`: support `text3` and `accent3` colors

---

examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/SamplePaywalls.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/testdata/templates/Template4TestData.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template4.kt

`Paywalls`: update template 4 colors

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/PackageConfigurationFactory.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/ProcessedLocalizedConfiguration.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableDataProvider.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableProcessor.kt
ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableProcessorTest.kt

Equivalent to https://github.com/RevenueCat/purchases-ios/pull/3131

`Paywalls`: new `{{ sub_relative_discount }}` variable

---

ui/revenuecatui/src/main/res/values-ja/strings.xml

Equivalent of https://github.com/RevenueCat/purchases-ios/pull/3364

`Paywalls`: improve Japanese localization

---

.circleci/config.yml

Fixes https://app.circleci.com/pipelines/github/RevenueCat/purchases-android/8727/workflows/464934c1-124f-4b92-9851-c4b909954d4c/jobs/31494

`CircleCI`: fix `record-revenuecatui-snapshots`

---

gradle/libs.versions.toml

Updating to the latest version of the gradle plugin.

Update gradle plugin to version 8.1.1

---

fastlane/Fastfile

`fastlane update_snapshots_commit` was failing without this

`Snapshots`: fix Fastlane job

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/RemoteImage.kt

We currently only had disk cache. This should improve image loading performance. Note that `CoilImageDownloader` is untouched because it would have its own memory cache.
Currently if you end up with a corrupted image in the cache, it would continue failing to load forever.
Ideally Coil handles this, but with this implementation we'll attempt to load them again with a write-only cache policy. If that succeeds, the cache will get updated with the correct image.

`Paywalls`: improve image loading

---

examples/CustomEntitlementComputationSample/gradle/libs.versions.toml
examples/MagicWeather/gradle/libs.versions.toml
examples/MagicWeatherCompose/gradle/libs.versions.toml
gradle/libs.versions.toml

This will update the android gradle plugin to the latest version 8.1.3

Update AGP to 8.1.3

---

gradle/libs.versions.toml
purchases/src/test/java/com/revenuecat/purchases/google/attribution/GoogleDeviceIdentifiersFetcherTests.kt

I run some basic tests to make sure common use cases work (subscribe, unsubscribe and upgrade). Everything seems to work fine. We can add support for the new APIs in future PRs.

Update Billing client to 6.1.0

---

config/detekt/detekt-baseline.xml
purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
purchases/src/main/kotlin/com/revenuecat/purchases/common/HTTPClient.kt
purchases/src/main/kotlin/com/revenuecat/purchases/common/caching/DeviceCache.kt
purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
purchases/src/main/kotlin/com/revenuecat/purchases/google/usecase/GetBillingConfigUseCase.kt
purchases/src/main/kotlin/com/revenuecat/purchases/interfaces/StorefrontProvider.kt
purchases/src/main/kotlin/com/revenuecat/purchases/strings/BillingStrings.kt
purchases/src/test/java/com/revenuecat/purchases/backend_integration_tests/BaseBackendIntegrationTest.kt
purchases/src/test/java/com/revenuecat/purchases/common/BaseHTTPClientTest.kt
purchases/src/test/java/com/revenuecat/purchases/common/DeviceCacheTest.kt
purchases/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
purchases/src/test/java/com/revenuecat/purchases/google/usecase/GetBillingConfigUseCaseTest.kt

This adds a new `X-Storefront` header to all backend requests.  This will allow the backend to know the store country for users.

Add `X-Storefront` header to requests

---

purchases/src/androidTestDefaults/kotlin/com/revenuecat/purchases/offlineentitlements/BaseOfflineEntitlementsIntegrationTest.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PostReceiptHelper.kt
purchases/src/main/kotlin/com/revenuecat/purchases/amazon/AmazonBilling.kt
purchases/src/main/kotlin/com/revenuecat/purchases/common/BillingAbstract.kt
purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
purchases/src/main/kotlin/com/revenuecat/purchases/google/usecase/ConsumePurchaseUseCase.kt
purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
purchases/src/test/java/com/revenuecat/purchases/PostReceiptHelperTest.kt
purchases/src/test/java/com/revenuecat/purchases/amazon/AmazonBillingTest.kt
purchases/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
purchases/src/test/java/com/revenuecat/purchases/google/usecase/ConsumePurchaseUseCaseTest.kt

Created ConsumePurchaseUseCase with retries
Based off #1490

ConsumePurchaseUseCase

---

purchases/src/test/java/com/revenuecat/purchases/google/usecase/AcknowledgePurchaseUseCaseTest.kt

Removed some warnings in AcknowledgePurchaseUseCaseTest

Cleanup warnings in AcknowledgePurchaseUseCaseTest

---

api-tester/src/defaults/java/com/revenuecat/apitester/java/revenuecatui/PaywallViewAPI.java
api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/revenuecatui/PaywallViewAPI.kt
api-tester/src/defaults/res/layout/paywall_view_api.xml
examples/paywall-tester/src/main/AndroidManifest.xml
examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/MainActivity.kt
examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/PaywallViewActivity.kt
examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/main/offerings/OfferingsScreen.kt
examples/paywall-tester/src/main/res/layout/activity_paywall_view.xml
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/views/PaywallFooterView.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/views/PaywallView.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/views/PaywallViewAttributesReader.kt
ui/revenuecatui/src/main/res/values/paywall_view_attrs.xml

Full screen counterpart to #1509. This adds a new view `PaywallView` which wraps the `Paywall` composable so it's usable in the view system. 
The view will be used in the hybrids.

Paywalls: Add `PaywallView`

---

ui/revenuecatui/src/main/res/values-zh-rHK/strings.xml

See https://github.com/RevenueCat/purchases-ios/pull/3512

`Paywalls`: fix traditional chinese string

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/views/PaywallFooterView.kt

This is needed for https://github.com/RevenueCat/react-native-purchases/pull/799/files#diff-8eaf252c074773fc7f002e444b255a9c2c60b23a2c75448799b85abb2f509bf9R20

Opens PaywallFooterView

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template2.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template5.kt

This is equivalent in LTR languages, but more correct for RTL.

`Paywalls`: replace `TextAlign.Left` with `TextAlign.Start` to better support RTL

---

ui/revenuecatui/src/main/res/values-kk/strings.xml
ui/revenuecatui/src/main/res/values-ru/strings.xml

Updated Kazakh and Russian translations

Update russian and kazakh translations

---

ui/revenuecatui/src/main/res/values-kk/strings.xml
ui/revenuecatui/src/main/res/values-ru/strings.xml

contributed by @janbolat in #1577 
Updated Kazakh and Russian translations

[External] Update russian and kazakh translations (#1577 by @janbolat)

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/views/PaywallView.kt

WIP while I take a look at safe area issues

Add setDisplayDismissButton to PaywallView

---

purchases/src/androidTestCustomEntitlementComputation/kotlin/com/revenuecat/purchases/PurchasesIntegrationTest.kt
purchases/src/androidTestDefaults/kotlin/com/revenuecat/purchases/PurchasesIntegrationTest.kt

Fix compilation in load shedder integration tests

Fix load shedder integration tests

---

purchases/src/main/kotlin/com/revenuecat/purchases/PostTransactionWithProductDetailsHelper.kt

[v6 HOTFIX] Fix amazon zero price (#1634)

---

CHANGELOG.md

Adding #1638 to changelog in main

Add 6.9.7 to changelog

---

api-tester/src/main/java/com/revenuecat/apitester/java/EntitlementInfoAPI.java
api-tester/src/main/java/com/revenuecat/apitester/kotlin/EntitlementInfoAPI.kt
purchases/src/main/kotlin/com/revenuecat/purchases/EntitlementInfo.kt
purchases/src/main/kotlin/com/revenuecat/purchases/common/EntitlementInfoFactories.kt
purchases/src/test/java/com/revenuecat/purchases/common/EntitlementInfosTests.kt

Android part of adding `RC_BILLING` store to the mobile SDKs

Add `RC_BILLING` store 

---

examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/SamplePaywalls.kt
purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/PaywallData.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/InternalPaywall.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/LoadingPaywall.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/CloseButton.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/ColorsFactory.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/TemplateConfiguration.kt

Allow dialog paywall view to have a custom close button color from the dashboard
- New `close_button` color

Paywalls: Allow closed button color to be configured

---

gradle/libs.versions.toml

Looking at the AndroidManifest.xml I see something new:
```
<activity
android:name="com.android.billingclient.api.ProxyBillingActivityV2"
android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"
android:exported="false"
android:theme="@android:style/Theme.Translucent.NoTitleBar" />
</application>
```
But after looking at the contents of the `ProxyBillingActivityV2` and `ProxyBillingActivity` I see they've removed some stuff from `ProxyBillingActivity` related to Alternative Billing, so I think this new activity is being used for alternative billing
Ran some tests, like purchasing and getting products and seems to be working fine.

Update BillingClient version to 6.2.1

---

fastlane/Fastfile
fastlane/README.md

Add trigger_bump lane

---

Gemfile.lock
docs/index.html

This gets the latest version of the plugin with some fixes for the index.html automation update and makes the index.html point to the latest stable version.

Update fastlane plugin and fix docs index path

---

purchases/src/main/kotlin/com/revenuecat/purchases/strings/ConfigureStrings.kt

Fix a small copy error in a log message

Fix bad copy in log message

---

purchases/src/androidTestDefaults/kotlin/com/revenuecat/purchases/offlineentitlements/BaseOfflineEntitlementsIntegrationTest.kt

Integration tests are failing on main due to the changes in #1697. This fixes those

Fix offline integration tests

---

gradle/libs.versions.toml

Bump amazon SDK version to 3.0.5

---

CHANGELOG.md

Adds 6.9.8 to the changelog.

---

README.md
migrations/v8-MIGRATION.md

This adds the migration guide for V8 of the SDK.

Add V8 Migration guide

---

examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/ConfigureFragment.kt
migrations/v8-MIGRATION.md

- Address comments in #1738 
- Enable pending prepaid plans in purchase tester

Improve migration guide for V8

---

CHANGELOG.md

Add 7.12.0 to CHANGELOG

---

migrations/v7-MIGRATION.md

Update migration docs adding back support for `DEFERRED` upgrades

---

test-apps/testpurchasesuiandroidcompatibility/build.gradle.kts
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallFooter.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/Markdown.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/PaywallDataExtensions.kt

This fixes the broken previews we had so snapshots work as expected in the emerge snapshots PR #1831

[Paywalls] Fix previews emerge snapshots

---

api-tester/src/defaults/java/com/revenuecat/apitester/java/PurchasesAPI.java
api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
purchases/src/defaults/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
purchases/src/main/kotlin/com/revenuecat/purchases/common/subscriberattributes/SpecialSubscriberAttributes.kt
purchases/src/testDefaults/kotlin/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt

This reverts #1829 until the full implementation in the backend + client is done

Revert "Add `$kochavaDeviceId` attribution convencience method (#1829)"

---

examples/MagicWeatherCompose/app/src/main/java/com/revenuecat/sample/data/SampleWeatherData.kt
examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/ConfigureFragment.kt
purchases/src/main/kotlin/com/revenuecat/purchases/CustomerInfoHelper.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
purchases/src/main/kotlin/com/revenuecat/purchases/common/caching/DeviceCache.kt
purchases/src/main/kotlin/com/revenuecat/purchases/common/offerings/OfferingsManager.kt
purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
purchases/src/main/kotlin/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesManager.kt

Detekt is applying these fixes for me, not sure why it's not applying them remotely... They seemed to make sense so I just applied them for now.

Detekt auto-fixes

---

.circleci/config.yml

Add new workflow to deploy snapshots from branches manually
Plan to use this to deploy some preview versions of some features, allowing people to test them before actually making a stable release.

[CI] Allow publishing snapshot releases manually from branches

---

api-tester/src/defaults/java/com/revenuecat/apitester/java/PurchasesAPI.java
api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
purchases/src/defaults/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
purchases/src/main/kotlin/com/revenuecat/purchases/common/subscriberattributes/SpecialSubscriberAttributes.kt
purchases/src/testDefaults/kotlin/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt

This adds a new reserved attribute `$tenjinId` and adds a new `setTenjinAnalyticsInstallationID` API to the SDK to set it.

Add `tenjinAnalyticsInstallationId` setter property

---

purchases/src/main/kotlin/com/revenuecat/purchases/common/Backend.kt
purchases/src/main/kotlin/com/revenuecat/purchases/common/networking/Endpoint.kt
purchases/src/test/java/com/revenuecat/purchases/common/backend/BackendRedeemWebPurchaseTest.kt
purchases/src/test/java/com/revenuecat/purchases/common/networking/EndpointTest.kt

Change to use new web redemption endpoint that passes the user id as part of the body

Use new web redemption endpoint

---

purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/ColorUtils.kt
purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/PaywallColor.kt
purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/ColorInfo.kt
purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/ImageUrls.kt
purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/ColorInfoTests.kt
purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/ImageUrlsTests.kt

As the title says. This adds: 
- `ImageUrls` and `ThemeImageUrls`
- `ColorInfo` and `ColorScheme`
and ensures they are deserialized correctly.

[Paywalls V2] Adds `ImageUrls` and `ColorInfo` properties

---

ui/revenuecatui/src/main/res/values-fi/strings.xml

Better translations provided by a customer. Internal ticket 48413.
"Restore" > Palauta 
"Restore Purchases" > Palauta ostot

Paywalls: Update Finnish "restore" localization

---

ui/revenuecatui/src/main/res/values-pl/strings.xml

Similar change to https://github.com/RevenueCat/purchases-ios/pull/4496
Improving Polish translations.

[EXTERNAL] fix: update polish translations

---

ui/revenuecatui/src/main/res/values-pl/strings.xml

Similar change to https://github.com/RevenueCat/purchases-ios/pull/4496
Improving Polish translations.
Original PR https://github.com/RevenueCat/purchases-android/pull/1919 by @radko93

[EXTERNAL] fix: update polish translations (#1919) via @radko93

---

purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/StackComponent.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/PaywallAction.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/button/ButtonComponentView.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/StackComponentView.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/ButtonComponentStyle.kt

This PR adds `ButtonComponentView` to our components

[Paywalls V2] Add `ButtonComponentView`

---

api-tester/src/defaults/java/com/revenuecat/apitester/java/PurchasesAPI.java
api-tester/src/defaults/java/com/revenuecat/apitester/java/RedeemWebPurchaseListenerAPI.java
api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/IntentExtensionsAPI.kt
api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/RedeemWebPurchaseListenerAPI.kt
purchases/src/defaults/kotlin/com/revenuecat/purchases/IntentExtensions.kt
purchases/src/defaults/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
purchases/src/main/kotlin/com/revenuecat/purchases/WebPurchaseRedemption.kt
purchases/src/main/kotlin/com/revenuecat/purchases/deeplinks/WebPurchaseRedemptionHelper.kt
purchases/src/main/kotlin/com/revenuecat/purchases/interfaces/RedeemWebPurchaseListener.kt

This removes the experimental annotations of the new APIs to redeem Redemption Links.

Make web redemption link APIs stable

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/button/ButtonComponentView.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/StackComponentView.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/text/TextComponentView.kt

[Paywalls V2] Fixes previews of `ButtonComponentView`, `StackComponentView` and `TextComponentView`

---

ui/revenuecatui/src/main/res/values-fr/strings.xml

adds a couple of improvements for the fr translations. Equivalent to https://github.com/RevenueCat/purchases-ios/pull/4624

improvements for fr translations

---

gradle/libs.versions.toml
gradle/wrapper/gradle-wrapper.properties

After updating to the latest AS, I was getting this update suggested, and we haven't updated in a while.

Update `agp` to 8.8.0

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/StackComponentView.kt

As the title says. Will put more details in comments below.

[Paywalls V2] Uses `SubcomposeLayout` to support pill-shaped edge-to-edge badges.

---

purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/ImageComponent.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/image/ImageComponentState.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/image/ImageComponentView.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/ImageComponentStyle.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/StyleFactory.kt

Added the following properties to the `ImageComponent`
- Padding
- Margin
- Border
- Shadow

[Paywalls V2] Add new `ImageComponent` properties

---

purchases/src/main/kotlin/com/revenuecat/purchases/EntitlementInfo.kt
purchases/src/test/java/com/revenuecat/purchases/utils/Responses.kt

It looks like the backend is actually returning this in uppercase

Fix `OwnershipType` enum serialization

---

purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/IconComponent.kt
purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/PaywallComponent.kt
purchases/src/test/java/com/revenuecat/purchases/paywalls/components/IconComponentTests.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/ComponentView.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/PresentedIconPartial.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/iconcomponent/IconComponentState.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/iconcomponent/IconComponentView.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/IconComponentStyle.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/StyleFactory.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/RemoteImage.kt

This adds a new `IconComponent`

[Paywalls V2] Add `IconComponent`

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/iconcomponent/IconComponentView.kt

As the title says. We're going too fast 🚀

Fixes compilation of `IconComponentView`.

---

purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/PaywallComponent.kt
purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/TimelineComponent.kt
purchases/src/test/java/com/revenuecat/purchases/paywalls/components/TimelineComponentTests.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/StyleFactory.kt

This adds the parsing of the `TimelineComponent` to the SDK (it still won't display any UI)

[Paywalls V2] Add `TimelineComponent` network parsing

---

purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/TimelineComponent.kt
purchases/src/test/java/com/revenuecat/purchases/paywalls/components/TimelineComponentTests.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/ComponentView.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/PresentedTimelinePartial.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/PreviewHelpers.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/button/ButtonComponentView.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/iconcomponent/IconComponentView.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/image/ImageComponentView.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/StackComponentView.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/StyleFactory.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/TimelineComponentStyle.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/text/TextComponentView.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/timeline/TimelineComponentState.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/timeline/TimelineComponentView.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/Result.kt

Based on #2047 
This performs the processing for the `TimelineComponent` overrides and its items. It also changes a couple of small things in the network parsing. This does not include the actual view implementation, just an skeleton. The actual implementation will come in a follow-up PR.

[Paywalls V2] Process `TimelineComponent` overrides and state

---

gradle/libs.versions.toml
purchases/src/test/java/com/revenuecat/purchases/paywalls/components/TimelineComponentTests.kt
ui/revenuecatui/build.gradle
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/PresentedTimelinePartial.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/PreviewHelpers.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/iconcomponent/IconComponentView.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/StackComponentView.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/StyleFactory.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/TimelineComponentStyle.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/text/TextComponentView.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/timeline/TimelineComponentState.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/timeline/TimelineComponentView.kt

Based on #2047  and #2082 
This adds the `TimelineComponentView` with the actual view for displaying the timeline component.

[Paywalls V2] Add `TimelineComponentView`

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/PreviewHelpers.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/button/ButtonComponentView.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/StackComponentView.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/StyleFactory.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/TextComponentStyle.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/OfferingToStateMapper.kt
ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallComponentDataValidationTests.kt
ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/LoadedPaywallComponentsLocaleTests.kt
ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/PaywallActionTests.kt
ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/button/ButtonComponentViewTests.kt
ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/pkg/PackageComponentViewTests.kt
ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/StackComponentViewTests.kt
ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/StackComponentViewWindowTests.kt
ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/StyleFactoryTests.kt
ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/text/TextComponentViewTests.kt
ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/text/TextComponentViewWindowTests.kt
ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModelTest.kt
ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/FakePaywallState.kt
ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/StyleFactory.kt
ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/UiConfig.kt

This is the first preparation PR for Variables V2. No actual implementation yet. 
- Adds `variableLocalizations` to `TextComponentStyle` and `StyleFactory`. This will be used in follow-up PRs. 
- Adds convenience constructors for `StyleFactory` and `UiConfig` to decrease the number of ripple effect changes needed in the future. (Not yet in this PR unfortunately.)
- Uses `previewTextComponentStyle()` in more places for the same reason.

[Paywalls V2] Preparation for Variables V2

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/ComponentView.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/PreviewHelpers.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/carousel/CarouselComponentState.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/carousel/CarouselComponentView.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/modifier/Padding.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/StackComponentView.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/CarouselComponentStyle.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/StyleFactory.kt

This adds the `CarouselComponentView` that actually displays the carousel
Second part of Android equivalent of https://github.com/RevenueCat/purchases-ios/pull/4722
https://github.com/user-attachments/assets/9649e370-d207-4b81-9119-7c60dc9cff13

[Paywalls V2] Add `CarouselComponentView`

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/carousel/CarouselComponentView.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/SizeConstraintExtensions.kt

This adds a transition animation to the page indicator when switching pages 
https://github.com/user-attachments/assets/3392510d-74b9-4ac2-9fef-6b5c7c191956

[Paywalls V2] Add CarouselComponent page indicator animation

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/image/ImageComponentView.kt

This adds some extra previews for the ImageComponent to make sure we handle correctly the cases of an image size constraint being `Fill` and the other `Fit`, while using `FitMode.Fill`

[Paywalls V2] Add more `ImageComponentView` preview tests

---

purchases/src/main/kotlin/com/revenuecat/purchases/customercenter/CustomerCenterConfigData.kt
purchases/src/test/java/com/revenuecat/purchases/common/backend/BackendGetCustomerCenterConfigTest.kt
purchases/src/test/java/com/revenuecat/purchases/customercenter/CustomerCenterConfigDataTest.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/InternalPaywall.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/InternalCustomerCenter.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/actions/CustomerCenterAction.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/viewmodel/CustomerCenterViewModel.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/views/ManageSubscriptionsView.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/utils/URLOpener.kt

Add Custom URLs support, reusing the way Paywalls opens URLs

Support for opening custom urls in Customer Center

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/viewmodel/CustomerCenterViewModel.kt

Fix title not being reset after closing Feedback Survey

---

purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/CarouselComponent.kt
purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/StackComponent.kt
purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/TabsComponent.kt
purchases/src/test/java/com/revenuecat/purchases/paywalls/components/CarouselComponentTests.kt
purchases/src/test/java/com/revenuecat/purchases/paywalls/components/StackComponentTests.kt
purchases/src/test/java/com/revenuecat/purchases/paywalls/components/TabsComponentTests.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/PresentedCarouselPartial.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/PresentedStackPartial.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/PresentedTabsPartial.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/PreviewHelpers.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/button/ButtonComponentView.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/carousel/CarouselComponentState.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/carousel/CarouselComponentView.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/properties/BackgroundStyle.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/StackComponentState.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/StackComponentView.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/CarouselComponentStyle.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/StackComponentStyle.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/StyleFactory.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/TabsComponentStyle.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/tabs/TabsComponentState.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/tabs/TabsComponentView.kt
ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/PresentedCarouselPartialTests.kt
ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/PresentedStackPartialTests.kt
ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/PresentedTabsPartialTests.kt
ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/button/ButtonComponentViewTests.kt
ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/StyleFactoryTests.kt

This adds support for the existing `Background` property to some extra component so we can add images as backgrounds for them.

[Paywalls V2] Support background images in StackComponent, CarouselComponent, TabsComponent

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/InternalPaywall.kt

Despite what we say in the updated docs, I noticed that the font provider wasn't ignored at all for V2 paywalls. If there's no custom font set on the dashboard, the font provider still sets the font. This PR corrects that.

[Paywalls V2] Actually ignores the font provider for V2.

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/StackComponentView.kt

I broke main after merging a couple recent PRs that had some conflicting definitions. This fixes that.

[Paywalls V2] Fix merge conflict

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/StyleFactory.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/errors/PaywallValidationError.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/strings/PaywallValidationErrorStrings.kt

Avoids a crash and returns a validation error instead if a package is missing. Also uses the correct error message 😅

[Paywalls V2] Avoids a crash if a package is missing

---

purchases/src/main/kotlin/com/revenuecat/purchases/customercenter/CustomerCenterConfigData.kt
purchases/src/test/java/com/revenuecat/purchases/common/backend/BackendGetCustomerCenterConfigTest.kt
purchases/src/test/resources/get_customer_center_config_success.json
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/InternalCustomerCenter.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/dialogs/RestorePurchasesDialog.kt

This PR adds localization support for the Restore Dialog in Customer Center.

fix: Localize Restore Purchases Dialog

---

purchases/src/main/kotlin/com/revenuecat/purchases/Offerings.kt
purchases/src/main/kotlin/com/revenuecat/purchases/utils/OfferingImagePreDownloader.kt
purchases/src/test/java/com/revenuecat/purchases/utils/OfferingImagePreDownloaderTest.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/properties/BackgroundStyle.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/RemoteImage.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/CoilImageLoader.kt
ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/tabs/TabsComponentViewTests.kt

This prefetches the images for paywalls V2 for the `current` offering. It includes background images, icon images and ImageComponent images.

[Paywalls V2] Predownload paywall low res images

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/ktx/Shape.kt

[Paywalls V2] Adjusts the convex/concave offset to 10% of the image height

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/StackComponentView.kt

This fixes an issue with the stack shadow overlaying the edgeToEdge Top/Bottom badges.

[Paywalls V2] Fix issue with shadows overlapping long edgeToEdge badges

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/properties/ColorStyle.kt

A follow-up to https://github.com/RevenueCat/purchases-android/pull/2142, as there were some scenarios still incorrect. This adds a bunch of previews too, and I verified it against our template 014 button:
| purchases-android | dashboard |
|------------------|-----------|
|  <img src="https://github.com/user-attachments/assets/3ff7c9d7-b0e2-4cc7-9720-5754a993e2da" width="400" /> | <img src="https://github.com/user-attachments/assets/b52cdf46-2de0-4a17-882e-65bbdb38ec71" width="400" />  |

[Paywalls V2] Gradients Reloaded: Makes linear gradients match CSS even more closely

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/image/ImageComponentView.kt

This makes the border draw on top of the image overlay

[Paywalls V2] Make border draw on top of the image overlay

---

ui/revenuecatui/build.gradle
ui/revenuecatui/consumer-rules.pro

This was actually causing compilation issues in release with minification enabled.

Fix issue with release minification with Emerge's annotation 

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/carousel/CarouselComponentView.kt

This enables manual scrolling in carousels if auto-advance is enabled, same as in iOS.

[Paywalls V2] Allow manual scrolling if auto-advance is enabled

---

purchases/src/main/kotlin/com/revenuecat/purchases/common/HTTPClient.kt
purchases/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt

This will allow us to make informed decisions on when to update the Kotlin language version, both in purchases-android and purchases-kmp.

Adds X-Kotlin-Version header.

---

ui/revenuecatui/src/debug/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/TemplatePreviews.kt

Previously, we'd read every Offering into memory (one at a time), and would discard Offerings we'd already seen. That puts pressure on the garbage collector. In this PR, we only instantiate an Offering if we're actually going to return it. 
We do that by first identifying the indices at which each Offering appears in the JSON, and then only reading the characters between those indices when we need a particular Offering. This is an attempt to decrease the rendering errors on Emerge Snapshots.

[Paywalls V2] Some more template previews optimizations

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/InternalCustomerCenter.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/actions/CustomerCenterAction.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/dialogs/RestorePurchasesDialog.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/viewmodel/CustomerCenterViewModel.kt
ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/CustomerCenterViewModelTests.kt

Reload the Customer Center after a successful restore

Reload Customer Center after a successful restore

---

gradle/libs.versions.toml

Original PR https://github.com/RevenueCat/purchases-android/pull/2211 by @runningcode

[EXTERNAL] Bump Emerge Gradle Plugin and Snaphsots version (#2211) via @runningcode

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/PresentedStackPartial.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/StackComponentState.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/BadgeStyle.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/StyleFactory.kt
ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/PresentedStackPartialTests.kt

Addresses [MON-927](https://linear.app/revenuecat/issue/MON-927) for Android. iOS PR is here: https://github.com/RevenueCat/purchases-ios/pull/4900.

[Paywalls V2] Fixes badges not being overriden

---

fastlane/README.md
purchases/src/test/java/com/revenuecat/purchases/backend_integration_tests/LoadShedderBackendIntegrationTest.kt

These broke with some changes to the load shedder integration tests project. The proper integration tests are still broken, but this fixes the immediate tests so we don't block things for everyone

Fix load shedder backend integration tests

---

examples/MagicWeatherCompose/app/src/main/java/com/revenuecat/sample/paywall/PaywallViewModel.kt
ui/revenuecatui/src/main/res/values-ko/strings.xml

Improve inaccurate Korean translations to make them more natural and fluent for native speakers.

Improve Korean translation

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/StackComponentView.kt

The paywall was still applying window insets that were already consumed, e.g. by a `Scaffold` or `AppBar`. 
I was under the impression that the `WindowInsets.systemBars` (and equivalent) properties would only return not-yet-consumed insets, as these are Composable properties. This turned out not to be the case. 
The fix is to use the `windowInsetsPadding` modifier instead. This modifier will internally keep track of the consumed insets, and will avoid applying them again.

[Paywalls v2] Ignores already-consumed window insets.

---

examples/CustomEntitlementComputationSample/app/build.gradle.kts
examples/CustomEntitlementComputationSample/gradle/libs.versions.toml
examples/MagicWeatherCompose/app/build.gradle.kts
examples/MagicWeatherCompose/gradle/libs.versions.toml
gradle/libs.versions.toml
test-apps/testpurchasesandroidcompatibility/build.gradle.kts
test-apps/testpurchasesuiandroidcompatibility/build.gradle.kts
ui/debugview/build.gradle

Remove redundant Kotlin bom dependencies.

Remove redundant Kotlin bom dependencies

---

config/detekt/detekt-baseline.xml
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/Markdown.kt

Before this, if using markdown to make text Bold on a Text composable that had a FontWeight > Bold, that text would actually lower weight to Bold. This makes it so we use the Text composable weight in case FontWeight > Bold.

[Paywalls] Fix Bold text in Markdown on higher Weights Text composables

---

.github/workflows/issue-notifications.yml

Get notified of important issue
Add workflow

Add GitHub Issue Action Ack

---

purchases/src/customEntitlementComputation/kotlin/com/revenuecat/purchases/Purchases.kt

CEC Mode Purchases Constructor w/ VCManager

---

purchases/src/customEntitlementComputation/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/defaults/kotlin/com/revenuecat/purchases/Purchases.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
purchases/src/testDefaults/kotlin/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt

Move VirtualCurrencyManager to PurchasesOrchestrator

---

README.md

1. [RevenueCat Google Play Integration](https://revenuecat.github.io/codelab/google-play/codelab-1-google-play-integration/index.html#0): In this codelab, you'll learn how to:
- Properly configure products on Google Play.
- Set up the RevenueCat dashboard and connect it to your Google Play products.
- Understanding Product, Offering, Package, and Entitlement.
- Create paywalls using the [Paywall Editor](https://www.revenuecat.com/docs/tools/paywalls/creating-paywalls#using-the-editor).
2. [Android In-App Purchases & Paywalls](https://revenuecat.github.io/codelab/android/codelab-2-android-sdk/index.html#0): In this codelab, you will:
- Integrate the Android RevenueCat SDK into your project
- Implement in-app purchases in your Android application
- Learn how to distinguish between paying …

Add codelab instructions on README file

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/CustomerCenterUIConstants.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/theme/CustomerCenterPreviewTheme.kt
ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/views/NoActiveUserManagementView.kt

| Old | New |
|--------|--------|
| <img width="347" height="704" alt="Screenshot 2025-07-22 at 16 38 15" src="https://github.com/user-attachments/assets/31530ae9-9cf0-4f87-9c13-3eecf4450b91" /> | <img width="344" height="707" alt="Screenshot 2025-07-22 at 16 37 21" src="https://github.com/user-attachments/assets/a4dc612d-18ef-4093-aede-34aa27ea1b80" /> |

Update design of No Active subscriptions screen in Customer Center

---

ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/viewmodel/CustomerCenterViewModel.kt
ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/CustomerCenterViewModelTests.kt

Display the latest expired subscription in the customer center, if there are no active subscriptions

Display latest expired subscription if no active subscriptions

---

purchases/src/main/kotlin/com/revenuecat/purchases/common/Backend.kt
purchases/src/main/kotlin/com/revenuecat/purchases/common/networking/Endpoint.kt
purchases/src/test/java/com/revenuecat/purchases/common/backend/BackendTest.kt
purchases/src/test/java/com/revenuecat/purchases/common/networking/EndpointTest.kt

This adds the alias endpoint call. Currently unused but will be used in follow-up PRs

Add alias users backend call

---

purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
purchases/src/main/kotlin/com/revenuecat/purchases/strings/RestoreStrings.kt

Add log when restoring purchases finds no purchases with some troubleshooting

---

api-tester/build.gradle.kts
baselineprofile/build.gradle.kts
dokka-hide-internal/build.gradle.kts
examples/CustomEntitlementComputationSample/app/build.gradle.kts
examples/MagicWeather/app/build.gradle.kts
examples/MagicWeatherCompose/app/build.gradle.kts
examples/paywall-tester/build.gradle.kts
examples/web-purchase-redemption-sample/build.gradle.kts
test-apps/testpurchasesandroidcompatibility/build.gradle.kts
test-apps/testpurchasesuiandroidcompatibility/build.gradle.kts
ui/revenuecatui/build.gradle.kts

Migrate deprecated kotlinOptions to compilerOptions.

Migrate deprecated kotlinOptions to compilerOptions

---

purchases/src/androidTest/kotlin/com/revenuecat/purchases/BasePurchasesIntegrationTest.kt

We migrated to a new shared preferences file in #2621, but we didn't update the integration tests to use the new file. This fixes those integration tests.

Fix integration tests shared preferences file

---

config/detekt/detekt-baseline.xml
purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/VideoComponent.kt
purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/VideoUrls.kt
purchases/src/test/java/com/revenuecat/purchases/paywalls/components/VideoComponentTests.kt

Creating a new paywall component can be a VERY large amount of code, I'm breaking things apart to make the PR's easier to review. This PR is just the creation of the VideoComponent model.
Add a video component model and serialization tests
> [!Note]
> I did not make it a member of the PaywallComponent sealed interface. I intentionally left that part out so I wouldn't have to have a style factory function setup and all of the other stuff that would domino into the PR.
> This is just the json -> model

Video Component Models (dark code)
